### ISSUE TITLE
Faraday::ConnectionFailed: Connection refused - connect(2)

### ISSUE THREAD

**Issue by edipofederle** [toptal/chewy#108]
I really dont know whats happen here. Yesterday everything works great, and today i got: Faraday::ConnectionFailed: Connection refused - connect(2) when I try ran rake tasks like:

bundle exec rake chewy:reset:all

This is some kind of bug or I messed up something?

Thanks

**Comment by blueror815** [comment]
Hi all!
I have got this error, and I can not find solution.
Who can help me?
The error message is following.
"Faraday::ConnectionFailed: Connection refused - connect(2) for "localhost" port 9200"
Cheers

**Comment by pyromaniac** [comment]
Did you start ES?

**Comment by blueror815** [comment]
Thank you for reply.
I have not start ES.
How can I start ES?
Please help me

**Comment by pyromaniac** [comment]
It depends on your OS. In OS X use `brew info elasticsearch`, on linux something like `sudo service elasticsearch start`

**Comment by blueror815** [comment]
Thank you. I will try

**Comment by blueror815** [comment]
When I type out  " brew info elasticsearch ", I can find out following error message
elasticsearch: stable 1.7.3, HEAD
Distributed real-time search & analytics engine for the cloud
https://www.elastic.co/products/elasticsearch
Not installed

**Comment by blueror815** [comment]
How can I solve this?

**Comment by pyromaniac** [comment]
You probably have to find answers using google, it is your own way you have to pass

**Comment by pyromaniac** [comment]
Or you can try to read the output carefully, maybe there are some clues there.

**Comment by blueror815** [comment]
Thanks I found out.
Thanks again.

**Comment by blueror815** [comment]
And could you help me with my opentok API using for video conference in rails app?
I can not use it in Ruby 2.2.3
I have used opentok gem in ruby 2.2.0
But when I use it in 2.2.3, issue occurs.
I can not find out solution by googling.
Please help me

**Comment by pyromaniac** [comment]
Sorry, but I've never used opentok unfortunately

**Comment by aditidhus** [comment]
1. OS => Ubuntu 14.04
2. ruby -v => ruby 2.0.0p353 (2013-11-22 revision 43784) [i686-linux]
3. rails -v => Rails 4.0.5
4. sudo /etc/init.d/elasticsearch restart
 * Stopping Elasticsearch Server                                                                                                    [ OK ] 
 * Starting Elasticsearch Server       
5. sudo /etc/init.d/elasticsearch status
 * elasticsearch is running                     
6. When ever I try to run rake tasks getting error
**Faraday::ConnectionFailed: Connection refused - connect(2)**

My ElasticSearch is running still I am getting this issue. Any help How can this issue be resolved ?

**Comment by pyromaniac** [comment]
`ps ax | grep elastic`, check out port there, make sure you have the same port in chewy.yml for development env.

**Comment by aditidhus** [comment]
ps ax | grep elastic

13463 ?        Sl     0:17 /usr/lib/jvm/java-8-oracle//bin/java -Xms256m -Xmx256m -Djava.awt.headless=true -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+HeapDumpOnOutOfMemoryError -XX:+DisableExplicitGC -Dfile.encoding=UTF-8 -Delasticsearch -Des.pidfile=/var/run/elasticsearch/elasticsearch.pid -Des.path.home=/usr/share/elasticsearch -cp :/usr/share/elasticsearch/lib/elasticsearch-1.7.0.jar:/usr/share/elasticsearch/lib/*:/usr/share/elasticsearch/lib/sigar/* -Des.default.config=/etc/elasticsearch/elasticsearch.yml -Des.default.path.home=/usr/share/elasticsearch -Des.default.path.logs=/var/log/elasticsearch -Des.default.path.data=/var/lib/elasticsearch -Des.default.path.work=/tmp/elasticsearch -Des.default.path.conf=/etc/elasticsearch org.elasticsearch.bootstrap.Elasticsearch


I don't have any chewy.yml in my code base ?

my rake tasks is : rake roles:seed_roles_and_permissions RAILS_ENV=development

**Comment by pyromaniac** [comment]
is localhost:9200 reachable for you?

**Comment by aditidhus** [comment]
Yes it is, I am able to get the below output :
{
  "status" : 200,
  "name" : "Night Thrasher",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "1.7.0",
    "build_hash" : "929b9739cae115e73c346cb5f9a6f24ba735a743",
    "build_timestamp" : "2015-07-16T14:31:07Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}

**Comment by pyromaniac** [comment]
try to run ruby console then and check out `Chewy.configuration`

**Comment by aditidhus** [comment]
I dont have any Chewy model below is what I get :

2.0.0-p353 :001 > Chewy.configuration
NameError: uninitialized constant Chewy
	from (irb):1
	from /home/aditi/.rvm/gems/ruby-2.0.0-p353@canopy/gems/railties-4.0.5/lib/rails/commands/console.rb:90:in `start'
	from /home/aditi/.rvm/gems/ruby-2.0.0-p353@canopy/gems/railties-4.0.5/lib/rails/commands/console.rb:9:in `start'
	from /home/aditi/.rvm/gems/ruby-2.0.0-p353@canopy/gems/railties-4.0.5/lib/rails/commands.rb:62:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'

**Comment by pyromaniac** [comment]
Are you using chewy gem at all?

**Comment by aditidhus** [comment]
No I am not is it required ?

**Comment by pyromaniac** [comment]
Well, then you don't have to address this question here, I have no idea what causes the problem in your code

**Comment by pyromaniac** [comment]
Faraday is just a library which is used buy a lot of other libraries

**Comment by inska** [comment]
@aditidhus, Do you use Puma?

**Comment by aditidhus** [comment]
No I was stuck due to Lapis server issue but not its resolved.

**Comment by magedmakled** [comment]
I have a similar problem but recently I switched Elasticsearch server to a new one but for some reason redis/reque job is still trying to use the old one. I only have the elasticsearch configuration in one spot and regular elasticsearch operation is working fine

Error: 
```
Faraday::ConnectionFailed
Error
Failed to open TCP connection to    the old elasticsearch URL
```
