### ISSUE TITLE
Cannot configure middleware RequestStrategy

### ISSUE THREAD

**Issue by eproulx-petalmd** [toptal/chewy#117]
Would it be possible to configure the middleware strategy? When running capybara tests, middleware RequestStrategy is loaded which is fine, but I would prefer the bypass strategy instead of the atomic one. Right now, my only option is to delete it and replace it with my own.

Thanks

**Comment by pyromaniac** [comment]
Great point, actually I was going to create such a configuration for every case, but was not sure if it is necessary. Now I'm pretty sure :). Just wait a little bit.

**Comment by pyromaniac** [comment]
Check out master please

**Comment by eproulx-petalmd** [comment]
+1 thanks :)
