### ISSUE TITLE
order doesn't working

### ISSUE THREAD

**Issue by kalashnikovisme** [toptal/chewy#124]
I have this code ```@users = @filter.find(params, disable_wildcard_prefix: true)``` which gives such query ```SELECT "users".* FROM "users"  WHERE "users"."id" IN ('8', '6', '1')```

After adding ```order(id: :desc)``` -  ```@users = @filter.find(params, disable_wildcard_prefix: true).order(id: :desc)``` query didn't changes.

What I do wrong?

**Comment by pyromaniac** [comment]
I'm confused a little bit. If you are talking about chewy, so where is this SQL from? I don't remember disable_wildcard_prefix option anywhere as well. Could you specify a little bit more?

**Comment by kalashnikovisme** [comment]
I'll explane.

```@filter.find(params, disable_wildcard_prefix: true)``` gives me instance of Chewy::Query. This instance has method ```order```. But it doesn't working.
I guess that I should add ```order: :desc``` option in ```filter``` class, but I still don't understand why method ```order``` doesn't working.

**Comment by pyromaniac** [comment]
Was this `find` method defined in your application? Could I see the implementation? Which version of chewy you are using?

**Comment by cuppincake** [comment]
Order isn't working for me either. Using chewy v0.7.0:

> KidsIndex.query(term: {school_id: section.school_id}).to_a

returns first names in this order:

> Edward
> Charlene
> Helen
> Amanda
> Marcie
> Hector
> Aaron
> Dennis
> Jennifer
> Georgia

and then when I add an order clause: 

> KidsIndex.query(term: {school_id: section.school_id}).order(first_name: :asc).to_a

it returns:

> Aaron
> Rachel
> Horacio
> Tracy
> Tracy
> Michael
> Michael
> Elaine
> Donald
> Alice

So, the results are **different** but not ordered by first name.

**Comment by pyromaniac** [comment]
Actually this is ES feature, order depends on your field analyzer. ES doesn't store your values passed to index, instead it stores already analyzed fields, do to make ordering by string values possible you have to define additional field with correct analyzer. It might be even nested field.

```
field :full_name, type: 'string', value: -> { full_name.try(:strip) } do
  field :sorted, analyzer: 'sorted'
end
```

Where sorted analyzer defined as keyword or lowercased keyword analyzer.

**Comment by cuppincake** [comment]
Thanks for your response and explanation.

**Comment by rtcoms** [comment]
I am also having same issue, and I didn't exactly understood your explanation.

So here is my Index class

    class ProjectsIndex < Chewy::Index
    settings analysis: {
      analyzer: {
        lowercase: {
          tokenizer: 'keyword',
          filter: ['lowercase']
        }
      }
    }

    if ActiveRecord::Base.connection.table_exists?('projects') && Project.count > 0
      define_type Project.includes(:causes, :fundraiser_campaigns) do
        field :id
        field :name, analyzer: 'lowercase'
        field :short_description, analyzer: 'lowercase'
        field :long_description, analyzer: 'lowercase'
        field :active
        field :impact_text
        field :project_type
        field :visible
        field :location, analyzer: 'lowercase'
        field :organisation_name, analyzer: 'lowercase'
        field :causes,  value: ->(prj) { prj.causes.map(&:name) if(prj.causes.present?)}
        field :category, type: 'object' do
          field :name, analyzer: 'category_name'
        end
        field :partner, type: 'object' do
          field :name, analyzer: 'partner_name'
        end
      end
    end
    end


But for me 

    ProjectsIndex.filter{ visible == true }.filter{ active == true }.query(match: {_all: "udaipur"}).order(name: :asc)

and

    ProjectsIndex.filter{ visible == true }.filter{ active == true }.query(match: {_all: "udaipur"}).order(name: :desc)

gives the same result.

**Comment by pyromaniac** [comment]
Well it seems like it is ordered by relevance, could you examine generated request? and responce to understand how is it really ordered. Actually such a request supposed to be working

**Comment by rtcoms** [comment]
Well, I deleted my Index and did an import again .It's working fine now .  Thanks for your time.

**Comment by pyromaniac** [comment]
Welcome, seems like there was an old mapping or somrthing
