### ISSUE TITLE
How to filter on nested field?

### ISSUE THREAD

**Issue by jimmybaker** [toptal/chewy#125]
Here is my index definition:

```
class ProductVariantsIndex < Chewy::Index
  define_type ProductVariant do

    field :sku, :upc, :barcode
    field :product, type: 'object' do
      field :name, :page_title, :page_description, :page_keywords, :additional_search_terms, :state
      field :tenant_id, :company_id

      field :brand do
        field :name
      end

      field :product_options do
        field :name
        field :values
      end
    end

  end
end
```

I would like to filter my results by the products tenant_id and company_ids but I cannot see how to do this? I've tried several methods like this:

```
ProductVariantsIndex::ProductVariant.query({ query_string: { query: 't-shirt' } }).filter{ product.name == 'T-Shirt' }.to_a
```

```
ProductVariantsIndex::ProductVariant.query({ query_string: { query: 't-shirt' } }).filter{ product["name"] == 'T-Shirt' }.to_a
```

How do I access the product name in the filter?

**Comment by pyromaniac** [comment]
Ah, got it. I'm pretty sure the cause is in analyzer. You don't have the `T-Shirt` term in you index, you have just `t` and `shirt` - 2 terms instead, pointing on this document and generated during the analysis process. That is how ES works and you have to read about it somewhere.

**Comment by mitani** [comment]
You may just want the white space analyzer for name http://www.elasticsearch.org/guide/en/elasticsearch/reference/current/analysis-whitespace-analyzer.html

**Comment by Neodelf** [comment]
How search with this? When `has_many association?
```ruby
define_type BusinessCenter.includes(:offices), name: 'bc' do
    field :offices, type: 'string' do
        field :published, type: 'boolean'
    end
end
```
