### ISSUE TITLE
Does chewy work with elastic search 1.4 w/Groovy?

### ISSUE THREAD

**Issue by tomfbiz** [toptal/chewy#126]
I recently went live with chewy and searchbox elastic search heroku addon vendor (aka searchly), 

I just got an [email] (http://us3.campaign-archive2.com/?u=542f79102a1caf25426ab788c&id=2a197766a9&e=e16adfad67) that seachly is switching from elastic search 1.3 to 1.4, with associated change from Mvel to Groovy.

Will will my app with chewy work with out changes? Do I need to do something to explicitly set the language to Mvel?

**Comment by pyromaniac** [comment]
Actually this is a ES internal scripting language changes. It would affect the `script` filters and queries only. Such as `script` or `function_score`, so this is not related to chewy at all. Also, I've got ES 1.4.2 in developments and it seems to be quite compatible with previous ones, so it works awesome.
