### ISSUE TITLE
Filtering Confusion

### ISSUE THREAD

**Issue by eliduke** [toptal/chewy#128]
I am new to ElasticSearch and Chewy, so please excuse me if this is a simple question with a simple answer, but I can't get filtering to work at all.

You have examples in your README like this:

`UsersIndex.filter{ first_name == 'Dan' }`

I can't get that to work. It seems like that is the most basic filter and so that's where I started, but I get nothing. I have tried all variations on that and still it returns nothing. I have confirmed that I have a UsersIndex that is full of users. I can query that index all day long (and return users with the first name of Dan!), but filtering does not seem to be working properly. The only filter that works is a filter on id.

I can run:

`UsersIndex.filter{ id == 1 }`

and 

`UsersIndex.filter{ id != 1 }`

Both of those work great! Why would that matter? Is there something I'm missing here.

I feel like I'm taking crazy pills!!

**Comment by pyromaniac** [comment]
Try `UsersIndex.filter{ first_name == 'dan' }`

**Comment by eliduke** [comment]
Ok. That worked, but why? The examples in the README are capitalized...

`UsersIndex.filter{ name == 'Fred' }`

Am I missing some sort of setting?

**Comment by pyromaniac** [comment]
Check this out: https://github.com/toptal/chewy/issues/125#issuecomment-72691587

**Comment by eliduke** [comment]
Hmmm... That's interesting. So, by default ElasticSearch lowercases everything? One of the fields in my index is `first_name` and there are multiple people in there with an explicit first name of "Dan" with a capital D. I understand the t-shirt example because there is a dash in there, but if I'm searching for "Dan" and it can't find anyone then it feels like something is broken. I'm new to search and sometimes it seems backwards, but I'm learning. Thanks for your help! Either way it's working now, and that's what's important.

**Comment by pyromaniac** [comment]
ES uses inverted index as main data structure. So for every test passed to be indexed it applies some analyzer to this text (basically, this is words splitter with lowercasing by default) and gets terms which are pointing to this document. http://www.toptal.com/ruby-on-rails/elasticsearch-for-ruby-on-rails-an-introduction-to-chewy

**Comment by eliduke** [comment]
Search and indexing has always been sort of like magic for me. Thanks for helping to simplify and demystify the process.
