### ISSUE TITLE
delete_from_index? access to current index

### ISSUE THREAD

**Issue by fpbouchard** [toptal/chewy#129]
Hi,

we are indexing content in different types (with different analyzers) and we want to switch to different types if the content changes. I'm trying to implement delete_from_index, but since I don't know which index/type is asking, I don't know. Would it make sense to either pass the type name (index#type) or type itself to delete_from_index?

**Comment by pyromaniac** [comment]
Actually, not so long ago, I've came to idea that delete_from_index should be deprecated and there should be a method in type itself. And I was just going to implement this as the next feature :) Will do it asap.

**Comment by fpbouchard** [comment]
Makes a lot more sense and is more in line with Chewy's philosophy. Thanks!

**Comment by pyromaniac** [comment]
Try master

**Comment by fpbouchard** [comment]
Works perfectly, problem solved, thanks @pyromaniac!
