### ISSUE TITLE
Limit number of indexed documents?

### ISSUE THREAD

**Issue by jshultz** [toptal/chewy#130]
I'm setting up my elasticsearch index and right now I only want to index a certain limited amount of documents before deploying. I've got about 200k records in my mysql table and I'd like to only import a couple hundred. Currently, it takes about 2 hours to index all the records and their associations so you can see why i'd like to keep the number down. :)

If i do this from the rails console: 
```
MaterialsIndex::Material.import Material.where('id < 10')
```
I can see it do the queries but then it ends with "false" without any explanation. Any suggestions?

**Comment by pyromaniac** [comment]
try MaterialsIndex::Material.import! Material.where('id < 10')

**Comment by jshultz** [comment]
Ok, I tried that and received this error:

```
Import failed for `MaterialsIndex::Material` with:
    Index errors:
      `MapperParsingException[object mapping for [material] tried to parse as object, but got EOF, has a concrete value been provided to it?]`
        on 8 documents: ["2", "3", "4", "5", "6", "7", "8", "9"]
/Users/jasonshultz/Projects/work/mc/vendor/bundle/ruby/2.1.0/gems/chewy-0.6.2/lib/chewy/type/import.rb:60:in `import!'
(pry):5:in `<main>'
/Users/jasonshultz/Projects/work/mc/vendor/bundle/ruby/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:355:in `eval'
/Users/jasonshultz/Projects/work/mc/vendor/bundle/ruby/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
/Users/jasonshultz/Projects/work/mc/vendor/bundle/ruby/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:323:in `handle_line'
/Users/jasonshultz/Projects/work/mc/vendor/bundle/ruby/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
/Users/jasonshultz/Projects/work/mc/vendor/bundle/ruby/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:242:in `catch'
/Users/jasonshultz/Projects/work/mc/vendor/bundle/ruby/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:242:in `block in eval'
/Users/jasonshultz/Projects/work/mc/vendor/bundle/ruby/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:241:in `catch'
/Users/jasonshultz/Projects/work/mc/vendor/bundle/ruby/2.1.0/gems/pry-0.10.1/lib/pry/pry_instance.rb:241:in `eval'
```

**Comment by pyromaniac** [comment]
Yeah, that is the exact error you have to fix.

**Comment by jshultz** [comment]
what does it mean? :/

**Comment by pyromaniac** [comment]
http://bit.ly/16XFh7w

**Comment by jshultz** [comment]
lol. yeah, I found one when I googled the error: http://blog.endpoint.com/2013/04/elasticsearch-object-mapping-eof-400.html

**Comment by jshultz** [comment]
ok, well at least I'm on the right track, thanks for your help. :)

**Comment by pyromaniac** [comment]
Always welcome ;)

**Comment by jshultz** [comment]
if I change from a type of object to leaving the value blank, I'll have to delete and recreate my schema again, right? I believe so.

**Comment by pyromaniac** [comment]
Yep, you have, use #purge method.

**Comment by jshultz** [comment]
if I delete and/or purge everything. when I go back to create, the fields I had previously defined and then delete from my definition return. I had reverted back to early yesterday morning so I could step through to see which field is causing the problem. Unfortunately, all those fields reappear when I go look it up in the browser.

**Comment by jshultz** [comment]
So if use

```
MaterialsIndex.delete!
```

to delete the index and then

```
MaterialsIndex.create!
```

to recreate it, it recreates the indices with the old schema even though I deleted all those fields from app/chewy/materials_index.rb

But, I can run the rake task

```
bin/rake chewy:reset[materials]
```

to create it and will do it correctly. 

On a side note, by doing this, it will start importing data without any problems, but if I were to run:

```
MaterialsIndex::Material.import! Material.where('id < 10')
``` 

it ends with an error like before saying:

```
MapperParsingException[object mapping for [material] tried to parse as object, but got EOF, has a concrete value been provided to it?]`
        on 8 documents: ["2", "3", "4", "5", "6", "7", "8", "9"]
```

**Comment by pyromaniac** [comment]
Have you restart console after changes and before MaterialsIndex.create! ? Could you post your index definition?

**Comment by jshultz** [comment]
I've shift/refreshed it and stuff. I can see the Indices disappear and reappear if that's what your asking.

Here's what I would like for my definition to be: https://gist.github.com/jshultz/5cbe1ce93f130da4c33d

and here's what I'm using right now for testing from back when I originally created it before getting all crazy: https://gist.github.com/jshultz/934b6e6fa7326e40fd66

**Comment by pyromaniac** [comment]
It seems like you misunderstood object type.

`field :objectives, type: 'object', value: ->(material) { }`

In case of objectives it seems to be used correctly, but I'm scared a little bit of value proc lol.

`field :class, type: 'object', value: ->(material) { material.class_objective_id.blank? ? material.get_unique_class_objectives_names.join(', ') : material.class_objective.name`

In cases such as `:class` you are trying to index arrays, so you have to set type the same as every array value has. It would be string in current case. In its turn, ES doesn't distinct array of strings and just string. So return array of strings or just a string from your value proc and set type to string or whatever necessary.

And object in ES literally means hash and nothing else.
Read ES docs a little bit more please.

**Comment by jshultz** [comment]
Ok, thanks. This has been an interesting project. Between converting from ERB/HTML to Angular, and then integrating Chewy and ES into it as well. It's been a journey of figuring out what I don't know about what that is causing the problem. Was it my lack of knowledge regarding Chewy or ES that is causing this issue? Dig into docs. Oh, and don't forget, there's a timeline for the project so don't take forever. lol. It's fun, though. Lots of learning going on with this story.
