### ISSUE TITLE
rake task for specific environment?

### ISSUE THREAD

**Issue by eliduke** [toptal/chewy#131]
Is it possible to tack on a RAILS_ENV at the end of the chewy rake tasks?

**Comment by pyromaniac** [comment]
Yeah, it is possible, but makes sense for production or development only.

**Comment by eliduke** [comment]
Thanks for the response. I'm wondering specifically about "staging". We have a remote staging server that we push to first, reset our indexes, test searching functionality, and then eventually go to production. I'm just now actually looking at chewy.rake and I think I just answered my own question.

`
namespace :chewy do
  desc 'Destroy, recreate and import data to specified index'
  task :reset, [:index] => :environment do |task, args|
    subscribe_task_stats!
    args[:index].present? ? reset_index(args[:index]) : reset_all
  end

  namespace :reset do
    desc 'Destroy, recreate and import data for all found indexes'
    task all: :environment do
      subscribe_task_stats!
      reset_all
    end
  end

  desc 'Updates data specified index'
  task :update, [:index] => :environment do |task, args|
    subscribe_task_stats!
    args[:index].present? ? update_index(args[:index]) : update_all
  end

  namespace :update do
    desc 'Updates data for all found indexes'
    task all: :environment do
      subscribe_task_stats!
      update_all
    end
  end
end
`

Thanks!
