### ISSUE TITLE
Index Update Strategies

### ISSUE THREAD

**Issue by eliduke** [toptal/chewy#132]
The documentation for update strategies is somewhat confusing. Here is my `update_index` method.

`update_index('users#user') { self if self.user_profile? }`

But that does NOT update the index when I save a user. If I specify 'urgent: true' in there it does, but then I get a depreciation warning. So, I checked the documentation, where you have examples like this:

```
Chewy.strategy(:atomic) do
  City.popular.map(&:do_some_update_action!)
end
```
That makes sense for a specific action, but what about a default? In looking at your elasticsearch / chewy blog post on toptal.com, I found this little bit about update strategies:

`around_action { |&block| Chewy.atomic(&block) }`

But that doesn't work either.

When I try `Chewy.strategy(:urgent)` in the console I get an undefined method error for 'strategy'. I ran `Chewy.methods` and found `urgent_update` and then added this to my application.rb.

`Chewy.urgent_update = true`

And that finally is what did the trick.

Am I missing something here?

**Comment by pyromaniac** [comment]
Yeah, the current README is for current master, there was a lot of changes and I recommend to use it, it will be released really soon.

**Comment by eliduke** [comment]
I'm confused. So, the current README is not the most current information? How did the README get updated before the actual code? You said you recommend that I "use it." What is "it" in that situation? And what will be released really soon? A new README?

**Comment by pyromaniac** [comment]
Current README is the most current information. Usually README updates in accordance with implemented features. If you want the latest released version README you could just use corresponding git tag (https://github.com/toptal/chewy/tree/v0.6.2)

But I recommend to use master branch. Just set it up in your Gemfile and enjoy the latest features of Chewy. Also I was talking about new version of gem which would be released soon. And all the features form master branch would be included in this release.

Was it more clear?

**Comment by eliduke** [comment]
Thank you, thank you, thank you. That clears things up a BUNCH. It all makes sense now. I don't think it would hurt to add a little something to the README about what we are talking about here.

Because, in my experience, this is how things unfolded. I added chewy to my gemfile as such:

`gem 'chewy'`

I didn't specify a version, I just wanted the latest from rubygems. When I went looking for information about the gem and how it works, I came upon the github repo and the corresponding README. Nowhere in there does it say anything about what version that it relates to or where the documentation for the current rubygems.org version can be found.

Maybe you could add a little note at the top of the README that says

"This is the master branch of this gem, and the corresponding README. If you'd like the documentation for the most recent version on rubygems.org, use the following link:"

http://www.rubydoc.info/gems/chewy/0.6.2

Just a thought. Maybe I'm just a newbie and all of this is obvious, but that would have been very helpful and could have saved me some time. I'm only hoping to help out other future developers that might run into the same problem.

Thanks again for your time. I hope I wasn't too annoying. :)

**Comment by pyromaniac** [comment]
It is quite a usual case for ruby gems on github btw. And welcome if you have more questions.
