### ISSUE TITLE
Change index prefix on-the-fly for request

### ISSUE THREAD

**Issue by AvaelKross** [toptal/chewy#133]
Can I somehow change prefix of indexes on-the-fly ? It would be perfect if I can do it just for current request. I need to build integration with Apartment - multi-tenancy gem; So when I'm switching to tenant 'account1' I want to switch also to account1_products index..

**Comment by pyromaniac** [comment]
Currently This is not possible. But why do you need separate indexes? ES doing sharding automatically, so you don't need to split this manually. Just try to use one index.

**Comment by AvaelKross** [comment]
I need separated indexes because I store user's data in separated postgresql schemas and don't want to search objects across all schemas...
Temporary I've done this code: 

```ruby
Apartment::Tenant.class_eval do
  def switch_tenant_and_select_index(tenant_name)
    switch(tenant_name)
    Chewy::Index.descendants.each do |index|
      default_name = index.build_index_name(
        index.name.gsub(/Index\Z/, '').demodulize.underscore,
        prefix: Chewy.configuration[:prefix]
      )
      index.index_name("#{tenant_name}_#{default_name}")
    end
  end
end
```

This code switches both schema and index. Some problems: 
1) I'm not sure if it will correctly work on multi-threaded server like puma.. Index may be switched while other request does some queries with another index.. Don't really know.
2) Sometimes search gives me wrong result - 1 object instead of 2 for example. Rarely, but happens.
3) Chewy::Index.descendants returns only indexes that have been already somehow used in code - so I need to use additional initializer with copy of "eager_load_chewy!" function from rake tasks.. Doesn't smells well too..

And, finally, rake task to be used with Apartment(maybe somebody needs this functionality too and knows how to make it better):
```ruby
def reset_tenants
  Apartment.tenant_names.each do |tenant_name|
    Apartment::Tenant.switch_tenant_and_select_index(tenant_name)
    ProductsIndex.reset!
  end
end

namespace :chewy do
  desc "Reset chewy indexes for all tenants"
  task :reset_tenants => :environment do
    reset_tenants
  end
end
```

**Comment by AvaelKross** [comment]
about 1st problem:
"1) I'm not sure if it will correctly work on multi-threaded server like puma.. Index may be switched while other request does some queries with another index.. Don't really know."

Yes, I've tried simple code in two accounts concurrently:
```ruby
def test_index_name
    sleep(10)
    render json: {index_name: ProductsIndex.index_name}
end
```
and it returns same index_name - for the second request :( 
So I need some way to change index_name only for one request..

**Comment by pyromaniac** [comment]
Have you tried to generate classes? And create an abstract method to access current class?

**Comment by AvaelKross** [comment]
Hm.. Not really sure how can it help and how to implement it.. Can you help&explain please ?

**Comment by pyromaniac** [comment]
I'm here :) Sorry for delay. I mean you have to `10.times.map { |i| klass = Class.new(Chewy::Index); const_set("ProductsIndex#{i}", klass) }` And get current index via `def current_product_index; "ProductsIndex#{some_value}".constantize; end`. The code might be broken, but I think you've got the idea.

**Comment by vchynarov** [comment]
Hi, I think I've run into a similar issue and would think it would be a cool feature - switching indicies on the fly. 

Use case: We have a somewhat large dataset that takes 4-6 hours to import fully from Postgresql and we keep playing around with changing mappings. It would be nice to change prefix/index_names on the fly so we can easily see what works without deleting and reimporting the same data set each time.
