### ISSUE TITLE
Can't Update Index on Many-to-Many Relationship Changes

### ISSUE THREAD

**Issue by waltaskew** [toptal/chewy#137]
I've got a pretty standard many-to-many relationship between users and groups with searchable users:

```ruby
class User < ActiveRecord::Base
  has_and_belongs_to_many :groups, join_table: :groups_users
  update_index('index#user') { self }
end
  
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users, join_table: :groups_users, class_name: 'User'
end
```

I'd like to re-index users when their group membership changes to keep their current group membership up-to-date in the elastic search index.  I tried adding the update_index bits on the join table model, but it's update_index calls don't seem to be happening:

```ruby
class GroupsUser < ActiveRecord::Base
  self.primary_keys = :user_id, :group_id
  belongs_to :user
  belongs_to :group
  update_index('index#user') { user } 
```

Things like
```
user.groups.delete(group)
```
Do not result in those update_index calls occurring -- I've tried dropping debug stuff in into the update_index blocks and they just don't seem to be getting called when something like the above expression to modify group membership is evaluated.

Am I doing something wrong, or does Chewy not support re-indexing on changes to a many-to-many relationship?

**Comment by pyromaniac** [comment]
You have to define mediator table explicitly and apply update_index in it.
Also explicitly defined mediator table is a kind of a best practice in rails, so avoid has_and_belongs_to_many associations and using of id-less tables.

**Comment by pyromaniac** [comment]
Yeah, didn't realize you've defined it, but recreate is with id (just for the future) and use has_many :through instead of has_and_belongs_to_many and this would work.

**Comment by waltaskew** [comment]
Cool -- using a has_many :through results in those update_index calls happening on something like:
```ruby
user.groups << some_group
```
but does not result in the index being updated for something like
```ruby
user.groups.delete(another_group) 
```
That is, it looks like I can update the index when a many-to-many model is saved, but not when one is deleted.  Is this by design?  I'd like a chance to update the index on both creation and deletion events to keep my users' group membership up-to-date in the index.

**Comment by pyromaniac** [comment]
Actually, deletion should work as well, could you try to debug or post your models here? And which chewy version are you using?

**Comment by waltaskew** [comment]
It's chewy-0.5.2

I'll try upgrading and see if I can't debug anything up.

**Comment by waltaskew** [comment]
Ah -- the difference is calling 'delete' vs 'destroy', the former apparently being un-catchable by Chewy because it skips active record.

Sorry for the trouble -- it looks like the problem is with me and active record rather than between Chewy and anything.  Thanks for the quick and helpful responses!
