### ISSUE TITLE
Revert "use_after_commit_callbacks configuration option"

### ISSUE THREAD

**Issue by eproulx-petalmd** [toptal/chewy#139]
Could you put back the commit named 'use_after_commit_callbacks configuration option' that you reverted few days ago? Since it's has been removed, my rspec tests fails because all examples are based on a transaction with saved single points. Thus, the after_commit is never called back. Putting it as a chewy settings was a great idea because I could switch easily depending of the rails env. For now, I'm pulling on the commit before you revert it.
Thanks and keep on the good work :)

**Comment by pyromaniac** [comment]
Wow, It just didn't work for me, that's why I have reverted it. Could you please tell me how do you use  it?

**Comment by eproulx-petalmd** [comment]
Well, it works when chewy his hooked on after_save & destroy callbacks. It never worked for me when it's hooked on after_commit callback. Why ? After_commit callback is never fired db_savepoints. If RSpec examples aren't wrapped by a db transaction, it works fine with after commit since ActiveRecord's save and destroy are automatically wrapped by a db transaction.

**Comment by pyromaniac** [comment]
Yeah, I know what I did the option for. It just didn't start to work in my application lol. But seems it was because of spring and you have to put this option before models are loaded. After revert it works for me as well :)

**Comment by eproulx-petalmd** [comment]
Alright, thanks a lot :)

**Comment by pyromaniac** [comment]
Thanks to you for opening my eyes :)
