### ISSUE TITLE
Performing Update of Index when Related Models are updated

### ISSUE THREAD

**Issue by jshultz** [toptal/chewy#140]
I have an Index that includes several related models, for example:

define_type Document.includes(:subject, :objectives, :teacher)

When I update Teacher I would like for the Document to be updated with that new information, such as if they change their name.

Based on the documentation, I should be able to, in the Teacher model add the following:

update_index('documents#document') { self }

or, if I'm using ChewyKiqqer:

async_update_index index: 'documents#document'

I've tried it both ways, but I don't see the index update. In the latter case, I see Sidekiq fire off a job, but the index doesn't update. 

What am I doing wrong?

**Comment by pyromaniac** [comment]
You have to `update_index('documents#document', :documents)` in Teacher model

**Comment by jshultz** [comment]
How quickly would I see results in the index?

For example, I updated my Teacher profile, and in another window, I'm looking at search results that contain her name, and it's not updated? What is a realistic turn around? I have 180,000 documents in the index and a handful of them are documents that would have her name on them.

**Comment by pyromaniac** [comment]
It should be updated immediately, index update occurs in AR callback

**Comment by jshultz** [comment]
I must be missing something then. Something "seems" to be happening.

So, in my teacher model I have, like you instructed:

`update_index('documents#document', :documents)`

in my documents model I have:

`include ChewyKiqqer::Mixin
async_update_index index: 'documents#document'`

I also setup logging for Chewy and ChewyKiqqer and nothing ever get's logged in the Chewy log.

If I use Chewy Kiqqer to update from the Teachers model it does show:

`D, [2015-03-21T12:00:33.821780 #24641] DEBUG -- : ChewyKiqqer queued jobs from Teacher 182901`

But, in either case, Documents doesn't update and so the name doesn't update in the Index. :/

**Comment by pyromaniac** [comment]
Didn't you miss Chewy.atomic block in your controller?

**Comment by pyromaniac** [comment]
And I recommend to use master branch, a lot of things were changed since the last release.

**Comment by jshultz** [comment]
No I don't have that anywhere. :(

How would I use that in the Teachers model?

**Comment by pyromaniac** [comment]
Check this out https://github.com/toptal/chewy/tree/v0.6.2#observing-strategies
And compare with the modern way: https://github.com/toptal/chewy#index-update-strategies

**Comment by jshultz** [comment]
So, in the Teachers model would I do something like this?

`Chewy.strategy(:atomic) do
  Teacher.map(&:update_index('materials#material', :materials))
end`

**Comment by pyromaniac** [comment]
Nope. This is completely incorrect.

```ruby
class Teacher < ActiveRecord::Base
  # This is dsl which is just defining callbacks for index updates.
  update_index('materials#material', :materials)
end

Chewy.strategy(:atomic) do
  # Here we have particular objects updates which are wrapped with strategy to perform actual update
  teachers.map(&:save!)
end
```

**Comment by jshultz** [comment]
Oh wow, that was not clear to me at all.

So, `teachers` would be the teacher that was just updated. Does that go in the controller or the model?

**Comment by jshultz** [comment]
oh, and i'm using chewy 0.6.2 if that makes a difference?

**Comment by pyromaniac** [comment]
Strategy should wrap every action in controller or even every block of code where AR objects saving happens. In 0.6.2 you have to wrap controller actions manually as specified in corresponding readme, in master there is already a rack middleware which is wrapping controller actions.

**Comment by jshultz** [comment]
ok, so if I understand correctly, and I hope I am now.

In the model, I just need to be sure to have this line:

`    update_index('materials#material', :materials)`

And then, in the controller, where ever I may be saving updates to the Teacher, I need to wrap that update like this:

`  Chewy.strategy(:atomic) do
    # Here we have particular objects updates which are wrapped with strategy to perform actual update
    teachers.map(&:save!)
  end`

Obviously, I'm not wrapping the WHOLE controller, just the update itself, correct?

**Comment by pyromaniac** [comment]
Almost. Seems like you still don't understand how rails controllers work.

Basically it is like `TeachersController.new.update` so every time rails processes your request, it uses an instance of controller to call action method. So you have to wrap this action method with strategy. I repeat that you have to do nothing with master branch because actions are already wrapped. In other cases it will be a good idea to wrap updates only, but it depends. If you are using `urgent` strategy, every object saving or destroying inside strategy block would update index immediately, contrariwise atomic strategy would just accumulate updated objects ids and perform index update only once at the end of the block. In case of controller action it is quite ok for us.

**Comment by jshultz** [comment]
you keep bringing up Master, I didn't specify to not use Master. in the Gemfile I simply have: 

`gem 'chewy'`

So shouldn't it be pulling in Master whatever version that is?

Finally, if I did, would that make all of this much simpler?

**Comment by pyromaniac** [comment]
`gem 'chewy', github: 'toptal/chewy'`

The concept of strategies block is quite simple and really convenient, just read the docs carefully please. Also yes, if you would use master - you would not have to think about strategies at all.

**Comment by jshultz** [comment]
so I updated the gemfile as you instructed and it is still 0.6.2:

`Using chewy 0.6.2 from git://github.com/toptal/chewy.git (at master)`

So I guess I am on Master?

**Comment by pyromaniac** [comment]
Yep

**Comment by jshultz** [comment]
so, if i'm on master then I don't have to wrap anything in the controller. But if that's the case, then why doesn't the document update?

**Comment by pyromaniac** [comment]
If you have update_index in models then it should be updated

**Comment by jshultz** [comment]
I do, but it's not, which is how we ended up here I guess. :/

**Comment by jshultz** [comment]
Ok, so here's what I found out. even if I'm in Master, then I still need to use the strategy.

so, in my case, when I update the teacher I need to have this in the controller:

`
Chewy.strategy(:atomic) do
          # Here we have particular objects updates which are wrapped with strategy to perform actual update
          @teacher.update_attributes(params[:teacher])
       end
`

**Comment by pyromaniac** [comment]
This is really strange. Could you show `rake middleware` result here?

**Comment by jshultz** [comment]
sure thing!

`
use Honeybadger::Rack::UserInformer
use Honeybadger::Rack::UserFeedback
use Honeybadger::Rack::ErrorNotifier
use Rack::Sendfile
use ActionDispatch::Static
use Rack::Lock
use #<ActiveSupport::Cache::Strategy::LocalCache::Middleware:0x007feb9e9fa768>
use Rack::Runtime
use Chewy::Railtie::RequestStrategy
use Rack::MethodOverride
use ActionDispatch::RequestId
use Rails::Rack::Logger
use ActionDispatch::ShowExceptions
use ActionDispatch::DebugExceptions
use MetaRequest::Middlewares::Headers
use ActionDispatch::RemoteIp
use ActionDispatch::Reloader
use ActionDispatch::Callbacks
use ActiveRecord::ConnectionAdapters::ConnectionManagement
use ActiveRecord::QueryCache
use ActionDispatch::Cookies
use ActionDispatch::Session::CookieStore
use ActionDispatch::Flash
use ExapiContentFix
use ActionDispatch::ParamsParser
use Rack::Head
use Rack::ConditionalGet
use Rack::ETag
use OAuth::Rack::OAuthFilter
use MetaRequest::Middlewares::MetaRequestHandler
use MetaRequest::Middlewares::AppRequestHandler
use Bullet::Rack
run MasteryConnect::Application.routes
`

**Comment by pyromaniac** [comment]
`Chewy::Railtie::RequestStrategy` this is exactly the thing which wraps every controller action. You have to debug this. Try to print `Chewy.strategy.current.name` at first

**Comment by jshultz** [comment]
print it how? I'm not sure what you are wanting?

**Comment by jshultz** [comment]
MasteryConnect (main):0 > Chewy.strategy.current.name
:urgent
MasteryConnect (main):0 >

**Comment by pyromaniac** [comment]
Nope, it is console strategy. And seems like controller actions are wrapped, otherwise you would mention  strategy exception. So index is not updated just because you are doing something wrong. Or maybe something is broken in master, but I'm currently in the process of master checking, tomorrow this ambiguity will be resolved I hope.

**Comment by jshultz** [comment]
yep, it seems to be showing :urgent as the strategy instead of atomic. Is that something I can override?

**Comment by jshultz** [comment]
if it makes a difference, I had wrapped three update functions in different models with that strategy you showed me. But that was only after you had told me about it. Up until that point it wasn't updating anything. Once I wrapped the teacher update like you instructed me, then the teacher name started updating. Which was definite progress. :)

**Comment by pyromaniac** [comment]
Yeah, but this is wrong. All the things had to be wrapped are already wrapped.

**Comment by jshultz** [comment]
Interesting. So, it does seem that I have to wrap the related models in the strategy in order for the update to work. The down side to this is that I can't do asynchronous updates using sidekiq that way which may be a deal breaker for us. 

Oddly, enough, in the main materials model which is what is what we're indexing in Elastic Search, I have:

`
  include ChewyKiqqer::Mixin

  async_update_index index: 'materials#material'
`
And it works fine, no need to wrap anything in a strategy. So why the related models are not working the same way is a mystery.

**Comment by pyromaniac** [comment]
ChewyKiqqer btw is not supposed to work with master.
Tha correct way is here: https://github.com/toptal/chewy/pull/119 but it is not finished yet

**Comment by jshultz** [comment]
Is it something we need at this time?

**Comment by pyromaniac** [comment]
You have to decide.

**Comment by jshultz** [comment]
Are race conditions an issue currently?

OK so I guess the only question left to uncover is why using a strategy
necessary in master and why updating the index doesn't work unless I use a
strategy in the associated models.

If there is anything I can do to help you with that I'm glad to do so. It's
12:30 in the morning here so I may not get back to you right away but I'm
glad to still do what I can.

**Comment by pyromaniac** [comment]
So have you solved this problem?

**Comment by jshultz** [comment]
Nope, I sure haven't. our team is trying to decide the next course of
action. :(

**Comment by pyromaniac** [comment]
I've checked the latest master, it is used in our applications as well and it works just fine, so I can offer two things here: to read docs and replay it carefully or try to debug the current state.

**Comment by jshultz** [comment]
Based on what you have previously said, it should work in the current
state. We've already confirmed in a prior email that we are on the master
branch which you said we need to be on.

Each model has the appropriate line at the top, in this case:

update_index('materials#material', :materials)

You said, if we are on master, then there is no reason to wrap anything
inside a strategy inside the controller, that it should "just work"

Is there anything else that needs to be done besides that?

**Comment by pyromaniac** [comment]
As far as I remember - no. There is still a little chance I forgot something :) But so far - no.

**Comment by jshultz** [comment]
Well then it doesn't work unless I wrap the update in the controller inside
a strategy irregardless of whether I have the correct line at the top of
the model.
