### ISSUE TITLE
Deploying index changes

### ISSUE THREAD

**Issue by dnd** [toptal/chewy#145]
What is the recommended way of deploying index changes with chewy? When there are changes that require reindexing we don't want to be down the entire time the reindexing occurs. I would assume it somehow involves using different index names/versions and aliasing, but how is it recommended to represent that in our codebase?

**Comment by pyromaniac** [comment]
`rake chewy:reset` performs zero-time reindexing automatically, it just creates new suffixed index and aliases it at the end. So use it after restart on every deploy.

**Comment by sharkzp** [comment]
@pyromaniac oh! I thought it will drop my index first.
This is brilliant. So I could change(add new fields, analyzers etc) my Chewy document and call this rake?

**Comment by pyromaniac** [comment]
Indeed

**Comment by sharkzp** [comment]
@pyromaniac thanks :)
