### ISSUE TITLE
Rubygems vs. Github

### ISSUE THREAD

**Issue by billy22g** [toptal/chewy#147]
When I updated the gem via rubygems, I got deprecation warnings regarding the 'urgent: true' syntax. Using the new syntax on the README documentation, I got undefined method errors for the block syntax. When I specified github as the source in my gemfile, it worked.  Might be worth versioning up the gem so the rubygems version has the latest commits from the past few months, in line with the README documentation. Or, placing a note in the readme that indicates using the github repo to bundle. Thanks so much!

**Comment by pyromaniac** [comment]
I'm going to release master really soon. It is almost ready. Sorry for the delay, there was a lot of thing to be reworked. And there is no any notes in readme just because I'm thinking about release for tha lst two month lol

**Comment by pyromaniac** [comment]
Released btw :)
