### ISSUE TITLE
What about search_type?

### ISSUE THREAD

**Issue by marshall-lee** [toptal/chewy#148]
Sometimes i need to fetch only aggregations(sum aggs, term aggs, etc).
It could be done with `search_type: 'count'` but there's no option in Chewy to do it.

Now i use this workaround:

```ruby
query.send(:_request).merge!(search_type: 'count')
```

It really works but need a native support for this.

**Comment by pyromaniac** [comment]
Good point, will add this some day, but actually you can send a small PR and this would be much better and faster.

**Comment by marshall-lee** [comment]
I thought about it but I didn't find a good place in code for this. Okay I will look for this soon.
