### ISSUE TITLE
Allow multi_field to index/analyze the main field

### ISSUE THREAD

**Issue by dnd** [toptal/chewy#151]
Is there a way to index the main field when using `type: :multi_field`? Right now chewy sets the first field definition to `index: no`. 

The following is a valid ES mapping taken from their docs, but I can't seem to recreate it with chewy. 

```json
"tweet": { 
    "type":     "string",
    "analyzer": "english",
    "fields": {
        "raw": { 
            "type":  "string",
            "index": "not_analyzed"
        }
    }
}
```

If it's not possible currently, would you accept a patch that changes to use a `multi_field: true` option instead, and allow type to be used again and index the main field? The user could still control whether a field is indexed or not by passing `index: false`.

**Comment by pyromaniac** [comment]
```ruby
field : tweet, analyzer: 'english', value: -> { tweet.try(:strip) } do
  field : raw, index: 'not_analyzed'
end
```

This should work actually

**Comment by pyromaniac** [comment]
The main thing here is to specify type for the multi_field and this type should not be `object`

**Comment by dnd** [comment]
You are correct, your syntax does work. It wasn't working for me because I hadn't explicitly declared a type. I was just letting chewy implicitly determine it. Once I set `type: 'string'` it worked perfectly. Maybe the docs could make mention of that to help people in the future?

**Comment by pyromaniac** [comment]
Sure, it should be mentioned in readme
