### ISSUE TITLE
Search with white space and with multiple field in database 

### ISSUE THREAD

**Issue by shefaleeComplitech** [toptal/chewy#152]
I want to search full name of User. But I have two fields in database first name and last name . So, It searches either first name or last name but not a full name at a time.

class PassengersIndex < Chewy::Index
	settings analysis: {
    analyzer: {
      email: {
        tokenizer: 'keyword',
        filter: ['lowercase']
      }
    }
  }
 define_type Passenger do
  field :phone_number
  field :email,analyzer: 'email'
  field :fullname, type: 'string', value: :fullname
end
end

**Comment by pyromaniac** [comment]
This seems to be a correct index definition, what the question exactly is?

**Comment by shefaleeComplitech** [comment]
Search is not working as per my need . Example - If I search 'Smith gail' then it return nothing in result.  But when I search only 'smith' or 'gail' I got the result. Also for 'Smith' - (Capital letter initial) it returns nothing. I want to make my search something like it can search all these case.

**Comment by pyromaniac** [comment]
Are you using filters for search?

**Comment by shefaleeComplitech** [comment]
No, I am using only email filter as I mentioned on my first comment. Nothing else.

**Comment by pyromaniac** [comment]
I mean there are 2 kinds of search: filters and queries, could you post your request btw?

**Comment by shefaleeComplitech** [comment]
if params[:search].present?
      conditions =  params[:search].delete_if { |_, v| v.blank? }
      @admin_passengers = PassengersIndex.filter(term: conditions).only(:id).load(
       passenger: {scope: Admin::Passenger.all })
    else
      @admin_passengers = Admin::Passenger.all
    end



I have used this and here 'full name' is instance method not a field in database.

**Comment by pyromaniac** [comment]
https://github.com/toptal/chewy/issues/112
https://github.com/toptal/chewy/issues/128

Check this 2 out and read about how do Lucene work.

**Comment by shefaleeComplitech** [comment]
I have converted my parameter to lowercase so It's working for 'smith' as well as 'Smith' and also for 'gail'  or 'Gail' . But I can't get any result for 'smith gail' or 'Smith Gail' . Please help me to solve out this.

**Comment by pyromaniac** [comment]
Have you read those issues carefully? There are all the answers. This is about how lucene works, long story short you don't have to lowercase your input, you have to use queries instead of filters.
