### ISSUE TITLE
Error while using Pry

### ISSUE THREAD

**Issue by AHaymond** [toptal/chewy#153]
Chewy is loaded in my apps gem file and now when I load my Rails environment into pry I am seeing the following error message:

`Chewy strategies stack: [2] <- urgent @ /Users/xyz/app_name/vendor/bundle/ruby/2.1.0/gems/chewy-0.7.0/lib/chewy/railtie.rb:42`

What is the purpose of this block?

```
    console do |app|
      Chewy.logger = ActiveRecord::Base.logger if defined?(ActiveRecord)

      if app.sandbox?
        Chewy.strategy(:bypass)
      else
        Chewy.strategy(:urgent)
      end
    end
```

**Comment by pyromaniac** [comment]
This is not an error actually, this means that `urgent` strategy is on top of the strategies stack. Just a debug message. But maybe you are right, I'll add something like `INFO:` at the beginning of the message

**Comment by npearson72** [comment]
:+1:
