### ISSUE TITLE
Search in nested objects

### ISSUE THREAD

**Issue by Neodelf** [toptal/chewy#155]
Hi, Arkadiy)
In my case BusinessCenter has_many offices
I try this:
```ruby
  define_type BusinessCenter.includes(:offices), name: 'bc' do
    field :id, type: 'integer'
    field :offices, type: 'string' do
        field :id, type: 'integer'
        field :published, type: 'boolean'
    end
  end
```
```ruby
BusinessCenterIndex.query(query_string: {fields: [:address], query: "*abc*"}).first
```
result above command is BusinessCenterIndex::Bc object with arrays of hashes offices:
```ruby
..."offices"=>[{"id"=>51, "published"=>true}, {"id"=>72, "published"=>true},...] ...
```
How i make filter this nested office?
I want get result as BusinessCenter objects, adding 
```ruby
.load(scope: -> {includes(:offices})
```
and get theirs **filtered** offices, how i do it?

**Comment by pyromaniac** [comment]
Hi! There is no way to do such a thing, you have to filter your offices additionally on AR objects load. additionally. It is possible only to filter business centers by some of offices properties. Say, to get centers having more then 3 published offices from ES.

**Comment by Neodelf** [comment]
Its impossible with chewy or with all ES?
And why? I think its not difficult.

**Comment by pyromaniac** [comment]
It is not possible in chewy by design, you are trying to do something strange actually
