### ISSUE TITLE
Arel errors in latest commit 

### ISSUE THREAD

**Issue by mkcode** [toptal/chewy#156]
I'm working off of chewy master. Letting you know that commit https://github.com/toptal/chewy/commit/6b02cef1493ea25bc545b80462c30b38f5ed5715
breaks at least the rake tasks. It works in the previous commit: https://github.com/toptal/chewy/commit/02422f0188a4d27daa805723ddcb7057681c6726

Running rails 4.2.0.

Exerpt from `rake chewy:reset` in https://github.com/toptal/chewy/commit/6b02cef1493ea25bc545b80462c30b38f5ed5715
```
** Execute chewy:reset
Resetting SchoolsIndex
  Imported SchoolsIndex::School for 0.01s, documents total: 0
rake aborted!
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "::"
LINE 1: SELECT  #<struct Arel::Attributes::Attribute relation=#<Arel...
                             ^
: SELECT  #<struct Arel::Attributes::Attribute relation=#<Arel::Table:0x007fee98bb52b8 @name="schools", @engine=School(id: integer, name: string, web_url: string, created_at: datetime, updated_at: datetime, trust_level: integer), @columns=nil, @aliases=[], @table_alias=nil, @primary_key=nil>, name="id"> FROM "schools"  ORDER BY "schools"."id" ASC LIMIT 1000
```

**Comment by pyromaniac** [comment]
Is was force-pushed, so you can check it out again, currently it should be just fine

**Comment by pyromaniac** [comment]
Thanks for the report, man!

**Comment by mkcode** [comment]
Excellent. Master works for me now. Thanks for this great gem!
