### ISSUE TITLE
Native transformation of Arel to ES AST

### ISSUE THREAD

**Issue by caldwecr** [toptal/chewy#157]
So I've nearly fallen in love with the approach you're taking with Chewy.

One piece I'm still hung up about is first class transformation between Arel and ES AST.

I'd like to do something similar to ...
```
foo = Foo.arel_table.(some long chain of arel)
es_foo = foo.as_es_ast chewy_type: ESFoo
es_foo.filter
```

Is this (1) already a feature that I just haven't discovered in Chewy, (2) feasible but not implemented or on the roadmap, (3) infeasible?

Kindest regards. 

Great work.

**Comment by pyromaniac** [comment]
Actually, this seems to be a good idea, it would be better to implement it like:

```ruby
UsersIndex.filter(...).merge(User.some_scope_or_arel)
UsersIndex::User.filter(...).merge(User.some_scope_or_arel)
# User is an AR model here
```

But since ES and AR functionality is quite different, the implementation would be really limited, I suppose. So, this is partially feasible and it was not on the roadmap, feel free to try.
