### ISSUE TITLE
acts_as_paranoid scopes

### ISSUE THREAD

**Issue by caldwecr** [toptal/chewy#159]
Is there a recommended way to integrate Chewy with acts_as_paranoid? The index I am currently trying to create has three types, one of which currently acts paranoid. (I did a quick search in this repo for acts_as_paranoid and paranoid and nothing came up). The results from google were not too helpful either.

This doesn't work (Models::Bar is acting paranoid) it produces the stack trace below it (I've replaced the real model names with foo and bar)
```
class FoosIndex < Chewy::Index
  define_type Models::Foo do
    field :some_field, ...
  end
  define_type Models::Bar do
    field :some_field_in_bar
  end
end
```

This does work
```
class FoosIndex < Chewy::Index
  define_type Models::Foo do
    field :some_field, ...
  end
  define_type Models::Bar.unscoped.where(deleted_at: nil) do
    field :some_field_in_bar
  end
end
```

This also does NOT work
```
class FoosIndex < Chewy::Index
  define_type Models::Foo do
    field :some_field, ...
  end
  define_type Models::Bar.with_deleted do
    field :some_field_in_bar
  end
end
```

Trace...
/usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.7/lib/active_record/connection_adapters/abstract/connection_pool.rb:541:in `retrieve_connection': ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)
	from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.7/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.7/lib/active_record/connection_handling.rb:87:in `connection'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.7/lib/active_record/relation/merger.rb:121:in `merge_multi_values'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.7/lib/active_record/relation/merger.rb:76:in `merge'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.7/lib/active_record/relation/spawn_methods.rb:44:in `merge!'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.7/lib/active_record/relation/spawn_methods.rb:33:in `merge'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.7/lib/active_record/scoping/default.rb:103:in `block (2 levels) in build_default_scope'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.7/lib/active_record/scoping/default.rb:102:in `each'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.7/lib/active_record/scoping/default.rb:102:in `inject'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.7/lib/active_record/scoping/default.rb:102:in `block in build_default_scope'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.7/lib/active_record/scoping/default.rb:125:in `evaluate_default_scope'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.7/lib/active_record/scoping/default.rb:101:in `build_default_scope'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.7/lib/active_record/scoping/named.rb:33:in `default_scoped'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.7/lib/active_record/scoping/named.rb:28:in `all'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/activerecord-4.1.7/lib/active_record/querying.rb:10:in `where'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/chewy-0.7.0/lib/chewy/type/adapter/active_record.rb:42:in `all_scope'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/chewy-0.7.0/lib/chewy/type/adapter/orm.rb:17:in `initialize'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/chewy-0.7.0/lib/chewy.rb:95:in `new'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/chewy-0.7.0/lib/chewy.rb:95:in `create_type'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/chewy-0.7.0/lib/chewy/index.rb:80:in `define_type'
	from /home/vagrant/mattermark/current/dwapi/lib/chewy/foos_index.rb:50:in `<class:FoosIndex>'
	from /home/vagrant/mattermark/current/dwapi/lib/chewy/foos_index.rb:2:in `<top (required)>'
	from /home/vagrant/mattermark/current/dwapi/app.rb:54:in `require_relative'
	from /home/vagrant/mattermark/current/dwapi/app.rb:54:in `<top (required)>'
	from /home/vagrant/mattermark/current/dwapi/config.ru:1:in `require'
	from /home/vagrant/mattermark/current/dwapi/config.ru:1:in `block in <main>'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `instance_eval'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/rack-1.5.2/lib/rack/builder.rb:55:in `initialize'
	from /home/vagrant/mattermark/current/dwapi/config.ru:1:in `new'
	from /home/vagrant/mattermark/current/dwapi/config.ru:1:in `<main>'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `eval'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/thin-1.6.3/lib/rack/adapter/loader.rb:33:in `load'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/thin-1.6.3/lib/rack/adapter/loader.rb:42:in `for'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/thin-1.6.3/lib/thin/controllers/controller.rb:170:in `load_adapter'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/thin-1.6.3/lib/thin/controllers/controller.rb:74:in `start'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/thin-1.6.3/lib/thin/runner.rb:200:in `run_command'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/thin-1.6.3/lib/thin/runner.rb:156:in `run!'
	from /usr/local/rvm/gems/ruby-2.1.1/gems/thin-1.6.3/bin/thin:6:in `<top (required)>'
	from /usr/local/rvm/gems/ruby-2.1.1/bin/thin:23:in `load'
	from /usr/local/rvm/gems/ruby-2.1.1/bin/thin:23:in `<main>'
	from /usr/local/rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `eval'
	from /usr/local/rvm/gems/ruby-2.1.1/bin/ruby_executable_hooks:15:in `<main>'

**Comment by pyromaniac** [comment]
Haven't faced with this yet, but are you sure Models::Bar.with_deleted returns scope? You definitely have to debug it to find out what's happening, can't help you here right now. Or can you maybe create a repo with the sample code so I could just check it out and try to debug as well?

**Comment by caldwecr** [comment]
Yes. I'll create a new repo tomorrow to enable you to repro the situation repeatedly.

**Comment by caldwecr** [comment]
Going to close this for now. We've decided to proceed with using Chewy. If this continues to be an issue when we get to this portion of our project I'll reopen.
