### ISSUE TITLE
detach model from association not updates the index

### ISSUE THREAD

**Issue by stefanosx** [toptal/chewy#160]
```ruby
class User
  belongs_to :mobile
  has_many :numbers, through: :mobile
  update_index(:numbers) {self.numbers}
end

class Mobile
  has_many :users
  has_many :numbers
  update_index(:numbers) {self.numbers}
end

class Numbers
  belongs_to :mobile
  has_many :users, through: :users

  update_index(:numbers) {self}
end
```

i have this models and i am saving an index called numbers, on the index i have an array of user' ids, 
but if i have an association between user and mobile and then i delete this association the index is not updating.

for example if i do this: 
```ruby
User.last.mobile_id = nil
User.last.save
```
on the index i still have the id of this user on the number index.
What should i do to update the index numbers when this happens?

**Comment by pyromaniac** [comment]
Looks like a bug, actually, I have to check it, but actually since user don't have mobile anymore, so `user.numbers` would be empty on save, so none of the numbers would be reindexed, and we should invent a way to bypass this.

**Comment by stefanosx** [comment]
Yes, that true there is no numbers to reindex.
Maybe a callback that keeps the instance of mobile before the user is saved, and after the users is saved then saves the mobile too, but is kind of tricky.

**Comment by pyromaniac** [comment]
This happens in belongs_to association case only, so maybe I should implement a workaround, or even you may try because I'm not sure I'll do this sooner

**Comment by pyromaniac** [comment]
I've just tried to figure out some magic to support your case and came to conclusion, that screw all the magic, you simply have to do something like:

```ruby
class User
  belongs_to :mobile
  has_many :numbers, through: :mobile
  update_index(:numbers) do
    if mobile_id_changed?
      mobile_id_now = mobile_id
      self.mobile_id = mobile_id_was
      numbers_was = numbers.pluck(:id)
      self.mobile_id = mobile_id_now
      numbers_now = numbers.pluck(:id)
      (numbers_was + numbers_now)
    else
      numbers
    end
  end
end
```

There is actually a heuristic way to automate this and it will be looking exactly like this solution, but inside chewy and with huge overhead on backreferences checks, so pleas try this solution and let's try to make it more beautiful maybe, so I could place it inside the readme.

**Comment by pyromaniac** [comment]
I've just found out that dirty attributes are not working here, so we can use previous_changes hash the same way, at least, for simple belongs_to update this works:

```ruby
class City < ActiveRecord::Base
  belongs_to :country
  update_index('cities#city') { self }
  update_index 'countries#country' do
    previous_changes['country_id'] || country
  end
```

In case of country_id change, it will simply reindex both of the countries - previous and current.
