### ISSUE TITLE
bin/rake chewy:update a specific range of ids?

### ISSUE THREAD

**Issue by jshultz** [toptal/chewy#162]
Is it possible, and if so, how can I do this:

I would like to update my elastic search index with a specific range of id's from the mysql table i'm indexing.

So, for example: I have a table with 100k id's. for whatever reason, the index stops at 90k. Instead of doing an update on the whole range of ids, i'd like to do from 90k on up. 

Can I do that? How would I got about doing that?

thank you in advance, I appreciate it.

**Comment by pyromaniac** [comment]
It would be much better to do such a things from the rails console manually and passing whatever conditions you need

**Comment by jshultz** [comment]
Ok thanks.
