### ISSUE TITLE
Updates during zero-downtime reindexing

### ISSUE THREAD

**Issue by fpbouchard** [toptal/chewy#163]
Hi,

I'm wondering how to manage the following situation: some of our indexes take a lot of time to reindex (hours), and while this is not really a downtime issue (thanks to zero-downtime reindexing), the issue is that our app is indeed not down during the reindexation, so we have some updates that are not being applied to the index being reindexed (for objects already reindexed). So once the app is back online, I still have to call a global `update` on the index so any updates that I've missed will be applied. That doubles the deployment time and load of reindexing.

I've thought of a few tricks we could do, one using an additional sidekiq queue that I could pause during the reindexation and in which I'd only queue if a reindexation is ongoing. Then, once the data has been reindexed, and sidekiq is restarted, I would unpause this queue which would replay all updates that were queued during the reindexation. I would need to keep the index status _somewhere_ (I'm thinking of doing this in Redis).

Do you have other ideas?

**Comment by fpbouchard** [comment]
I think I need to add some details on our current deployment strategy. When we deloy, we start by reindexing using the new code, while the app is running using the old code. We do this so everything still works for our customers, there is indeed no downtime. Then, as soon as the reindexation is over, we restart the apps with the new code.

**Comment by pyromaniac** [comment]
At first, the idea to run reindexing before the restart sounds strange for me, are you doing this before or after migrations? If before - then index is outdated at this point in data migrations or similar cases, if after - then the whole application is tried to use new schema with old codebase, which will cause exceptions often.

I'm offering to use ES for the search only (and load the real-world objects) and this will bring us to a couple benefits:
* ES index would be as small as possible, no excess data would be in it
* Loading real objects by id gives us a little bit overhead, but gives us an ability to ignore current ES mapping outdate, simply if you are trying to search by absent yet field, ES would just ignore this and gives slightly irrelevant results, but trying to access absent field of chewy document wrapper in ruby would cause an exception. At the meantime, AR schema is already updated and app is restarted, so all will be just fine.

The next thing here is: actually, using sidekiq for keeping updates while all the stuff is updated is a brilliant idea and it will simply work out of the box, you have just set default controller strategy to sidekiq in chewy config and don't forget to stop-start worker when necessary.
