### ISSUE TITLE
Expose the mapped model class to the block passed to define_type

### ISSUE THREAD

**Issue by caldwecr** [toptal/chewy#164]
Consider ...

```
module CustomTypeExtension
  def extended_field(*args, &block)
    # I want to be able to know that the Index document type is mapped to the class Models::Foo
    self.underlying_model.do_something #this method doesn't really exist
    field *args, &block
  end
end

class FooIndex < Chewy::Index
  define_type Models::Foo do
    extend CustomTypeExtension
    extended_field :cat, :dog
  end
end
```

I'd like to be able to access the associated Model's class inside of the block passed to define_type in general, and inside of mixed in modules specifically. I went trolling through the methods but I couldn't find anything appropriate. Advice?

**Comment by caldwecr** [comment]
I'm happy to submit a PR that accomplishes this if you let me know where you'd like to see the method which exposes the model class added and what you think it should be named.

**Comment by pyromaniac** [comment]
`adapter.target` actually

**Comment by caldwecr** [comment]
Thank you.
