### ISSUE TITLE
Can someone help with this filter?

### ISSUE THREAD

**Issue by npearson72** [toptal/chewy#166]
First of all, thank you for the amazing gem! Just great stuff.

So I'm trying to build a faceted navigation like zappos.com or amazon.com where a user can filter products based on key/value pairs.

Ex: color: red, size: large

Below is the filter I'm using and the output it gives. I'm not sure how to get the values (ex: blue, red) to be nested under the key (ex: color)

`ProductsIndex.filter { match_all }.aggs(key: {terms: {field: "features.key"}}, value: { terms: { field: "features.value"}}).aggs`

Here's the output:

````
{
    "value" => {
        "doc_count_error_upper_bound" => 0,
                "sum_other_doc_count" => 0,
                            "buckets" => [
            [0] {
                      "key" => "blue",
                "doc_count" => 1
            },
            [1] {
                      "key" => "red",
                "doc_count" => 1
            }
        ]
    },
      "key" => {
        "doc_count_error_upper_bound" => 0,
                "sum_other_doc_count" => 0,
                            "buckets" => [
            [0] {
                      "key" => "color",
                "doc_count" => 2
            }
        ]
    }
}
````

**Comment by pyromaniac** [comment]
Hey, sorry didn't aswer for this because have no idea how to help in this case since I've never used aggs :) So have you solved this?
