### ISSUE TITLE
Canonically import child documents

### ISSUE THREAD

**Issue by caldwecr** [toptal/chewy#169]
Is there a best practice for coordinated importing of parent documents and their associated children?

```
class UsersIndex < Chewy::Index

    define_type User do
      field :name
    end

    define_type UserInterest do
      root parent: 'user', parent_id: -> { user_id } do
        field :user_id
        field :interest_id
        field :description
      end
    end

end

# right now I do something like ... (no it's not really this ugly)
user_ids = [4, 5, 6]
UsersIndex::User.import user_ids
users = User.where(id: user_ids)
UsersIndex::UserInterest.import users.inject([]) do |interest_ids, user|
  interest_ids.concat user.interests.collect { |interest| interest.id }
end

# I'd like to do something like
user_ids = [4, 5, 6]
UsersIndex::User.deep_import user_ids

# or even
user_ids = [4, 5, 6]
UsersIndex::User.deep_import(user_ids, include: [:user_interests])

```

I'm pretty sure you've solved this already and I just need pointed in the right direction. Thank you.

**Comment by pyromaniac** [comment]
Actually you can do just

```
UsersIndex::User.import user_ids
UsersIndex:: UserInterest.import UserInterest.where(user_id: user_ids)
```

It seems like it should be enough. Unfortunately, there is no such a `deep_import` method, but you can just add it locally for you case because I don't think there is a way to implement it commonly

**Comment by caldwecr** [comment]
Yeah. The example above was just a watered down version of an actual scenario. It's actually not such a big deal for production data, but for testing it can be a real challenge. In our case the actual scenario is more like ..

Tree < 1 - many > Apple < many - 1 > Pie < many - 1 > PieTin

and then

```
define_type Tree do

end

# We create an index document type called pies that's based on the Apple model with pie
# specific methods set using the value syntax or via def_delegators
define_type Apple, name: 'pies' do
  root parent: 'tree', parent_id: -> { tree_id } do
    field :recipe, value: -> { pie.recipe }
  end
end

# We create another index document type called pie_tins that's also based on the Apple model with
# pie tin specific methods set using the value syntax or via def_delegators
define_type Apple, name: 'pie_tins' do
  root parent: 'tree', parent_id: -> { tree_id } do
    field :tin_size, value: -> { pie.pie_tin.tin_size }
  end
end
```

The above is complex, but manageable. But figuring out what to import when writing tests gets really confusing. Especially since we don't want to import duplicate PieTins for a given Tree. As in..

```
tree = FactoryGirl.create :tree, apples: [apple1, apple2]

```

**Comment by pyromaniac** [comment]
Got it, but still don't see any common way to do it automatically, so you have to do it manually for now unfortunately

**Comment by caldwecr** [comment]
Thanks @pyromaniac I'll continue as I have.

**Comment by pyromaniac** [comment]
Welcome
