### ISSUE TITLE
Trouble with polymorphic associations

### ISSUE THREAD

**Issue by npearson72** [toptal/chewy#170]
I have a polymorphic image class, and when I try to update my product when the image changes, I run into problems.

Is this a known issue... or is a there trick to it?

Here's a snippet of the stack trace:

````
2015-05-12 23:07:56 +0000: Rack app error: #<NoMethodError: undefined method `name' for nil:NilClass>
/vagrant/app/chewy/products_index.rb:23:in `block (3 levels) in <class:ProductsIndex>'
/usr/local/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `map'
/usr/local/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/activerecord-4.2.1/lib/active_record/relation/delegation.rb:46:in `map'
/vagrant/app/chewy/products_index.rb:23:in `block (2 levels) in <class:ProductsIndex>'
/usr/local/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/chewy-0.7.0/lib/chewy/fields/base.rb:25:in `instance_exec'
/usr/local/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/chewy-0.7.0/lib/chewy/fields/base.rb:25:in `compose'
/usr/local/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/chewy-0.7.0/lib/chewy/fields/base.rb:62:in `block in nested_compose'
/usr/local/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/chewy-0.7.0/lib/chewy/fields/base.rb:62:in `map'
/usr/local/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/chewy-0.7.0/lib/chewy/fields/base.rb:62:in `nested_compose'
/usr/local/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/chewy-0.7.0/lib/chewy/fields/base.rb:36:in `compose'
````

**Comment by pyromaniac** [comment]
Could you provide sources please?

**Comment by npearson72** [comment]
Hi,

I think I discovered the cause, but don't know how to solve it.

So my app is a multi-tenant app and each model has a `default_scope` to the `tenant_id`.

So in my indexes, something like this does not work:

` field :categories, analyzer: "keyword", value: -> { categories.pluck(:name) if categories.any? }`

But if I do something like this it works:

` field :categories, analyzer: "keyword", value: -> { Tenant.current_id =1; categories.pluck(:name) if categories.any? }`

The problem is that outside of the `value` lambda, `Tenant.current_id` is accessible by the scope. But inside it is not unless I explicitly hard code it.

Is there a way for me to pass a value into that lambda? Does the `field` method accept an optional argument for this?

**Comment by pyromaniac** [comment]
I still don't understand how `Tenant.current_id` is set. Is is happens before import? Could you please provide some pseudo-code?

**Comment by npearson72** [comment]
`Tenant.current_id` is set per request. Think of it as `current_user` or something like this. My app uses token authentication so each request re-authenticates and the Tenant.current_id is set.

Does that make sense?

So if I was to go to council and run `ProductsIndex.reset!` I would need to first assign the tenant. This is ok, because I'm in council. But when a user is interacting with the system and they make updates, the `Tenant.current_id` is set based on their authentication, so the index must import using their tenant id.

Does this help?

I'm not sure what code you would like me to provide?

**Comment by pyromaniac** [comment]
If `Tenant.current_id` is set right before import in every case, then I'm pretty sure it is available in `value` lambda

**Comment by npearson72** [comment]
It's strange, I was able to get it to work like this:

````
tenant_id = Tenant.current_id
field :categories, analyzer: "keyword", value: -> { Tenant.current_id = tenant_id; reload; categories.map(&:name) }

````

But why? Why is the current resource object loaded without the Tenant.current_id scope? It's available outside of the value proc.

**Comment by pyromaniac** [comment]
Nope, you are doing closure here, `tenant_id` in lambda will stay always the same as it was in definition time. But `Tenant.current_id` will be the same as it was set before import. So you don't have to set it up, you just have to access it.

**Comment by npearson72** [comment]
That's how I understand things too... but am seeing strange behavior.

I've attached two screen shots. The first is when I pry'd outside of the lambda, the second inside.

https://www.dropbox.com/s/6egda7ketnjgumd/2015-05-15%20at%2012.13%20AM.png?dl=0

https://www.dropbox.com/s/kzk46ydmipz3pbt/2015-05-15%20at%2012.16%20AM.png?dl=0

Is there something that chewy is doing to the current thread in the call stack?

**Comment by pyromaniac** [comment]
`define_type` method block is evaluated in type class context, so there is no any reason to do anything with `Tenant.current_id` in this context

**Comment by npearson72** [comment]
I'm not sure what to say. I've pry'd it in different scopes, and tried with
and without the explicit assignment as I now have, and nothing worked. For
some reason it only works when I assign the value of Tenant.current_id to a
variable and access that variable in the lambda.

I can give you access to my code if you like?

**Comment by pyromaniac** [comment]
Not sure I need this.

The main thing here you should use `Tenant.current_id` in value lambdas only. You can't set it or use anywhere inside index or type definition except value lambdas.

Try simple experiment: in definition try to value: -> { p Tenant.current_id }
After try: `Tenant.current_id = 1; YourIndex.import; Tenant.current_id = 2; YourIndex.import`
You will see that inside value lambda current_id is the same as was set before import.

Also chewy does nothing with thread variables except adding own ones.

**Comment by npearson72** [comment]
I'll investigate tomorrow -- it's late here now. Thanks for all the help. I really appreciate your concern.
