### ISSUE TITLE
How/where do I configure update strategy to use sidekiq?

### ISSUE THREAD

**Issue by npearson72** [toptal/chewy#171]
I saw a reference to it in the readme, but wasn't clear where I put that code and how exactly to do it.

Is there an example of this or does anyone have any info on it?

Thanks

**Comment by pyromaniac** [comment]
You have to wrap your code blocks with `Chewy.strategy(:sidekiq) { ... }` block everywhere you need. Since controller actions are already wrapped with `:atomic` strategy by default, you need to do `Chewy.request_strategy = :sidekiq` to change this.

**Comment by npearson72** [comment]
So just so I'm clear, do I first call `Chewy.request_strategy = :sidekiq` then wrap the action in `Chewy.strategy(:sidekiq) { ... }`?

Also, for some reason the sidekiq class isn't loading in rails on its own. Is that normal? I'm having copy it in to a lib dir and setup a load path.

**Comment by pyromaniac** [comment]
In controllers `Chewy.request_strategy = :sidekiq` only, in other places, such as rake tasks, where you have undefined strategy exception - `Chewy.strategy(:sidekiq) { ... }` only.

Try to place sidekiq before chewy in your Gemfile, this will fix loading, I hope
