### ISSUE TITLE
How do you set '_routing'?

### ISSUE THREAD

**Issue by hadees** [toptal/chewy#173]
I'm trying to figure out how I'd set the [_routing](http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-routing-field.html) inside of an index class.  The documentation seems kind of light on the various [underscore fields](http://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-fields.html).

**Comment by pyromaniac** [comment]
Actually, this is a kind of root object field, so unfortunately it is not supported now, because every such a field should be defined in root explicitly, take a look on Fields::Root class, there is already defined _parent field, so you can do a patch and submit a PR
