### ISSUE TITLE
How can you index dynamically created fields?

### ISSUE THREAD

**Issue by hadees** [toptal/chewy#174]
Our application is multi tenant based on a company model and every company can set custom fields for their users.  Can chewy handle these custom fields?  From the docs all I can tell is that you can set it once but looking in the code I kind of feel what I need would be possible i'm just not 100% sure how to do it.

**Comment by pyromaniac** [comment]
I have not try to define this stuff like this, but the very first thought would be to use just an object field, passing custom fields and values as a hash.

```
field :custom_fields, type: 'object', value: -> { custom_fields_hash }
```

If you have to define custom analyzers or types or other options for every custom field - you can use templates, which are supported in chewy.
