### ISSUE TITLE
Is there anyway to access the additional options on the Elasticsearch search method?

### ISSUE THREAD

**Issue by hadees** [toptal/chewy#176]
Does the query class expose all the options for [Elasticsearch::API#search](http://www.rubydoc.info/gems/elasticsearch-api/Elasticsearch/API/Actions#search-instance_method) anywhere?  I'm working on a pull request for #173 and need to add `routing` to the query.

I noticed in #149 `search_type` was added, would you be alright if I added a special key to the `query` method called `options` that just lets you set any of the options that the Elasticsearch gem allows?

**Comment by pyromaniac** [comment]
Not a key, but `search_options` chainable method would be just fine

**Comment by marshall-lee** [comment]
There is a small gotcha: when I was implementing `search_type` I found out that `Chewy::Query#options` accessor is not actually used for anything. Most of settings are passed to `criteria.options` that is used only for constructing `body` part of a query but nothing is merged to `query.options`.

I implemented `search_type` simply putting it in that `Query#options` hash (that was unused before). But now we reached the point where we should come up with the exact purpose of that `Query#options` hash. Where it will contain arbitrary search-api params or maybe something more? Treat this `Query#options` as `search_options` described by you or nest `search_options` in `Query#options`?

**Comment by marshall-lee** [comment]
It's also worth to add some convenient methods for known API params such as `routing` and `search_type`.
I personally prefer chainable methods rather than hash params because if I make a typo it'll  appear soon as `NoMethodError` but typos in hash params are more difficult to find.

**Comment by hadees** [comment]
We've actually added in a search_options method, just haven't gotten around to making a pull request for it yet.

**Comment by pyromaniac** [comment]
C'mon, don't hesitate to do such a great PR
