### ISSUE TITLE
Scenario that requires setting scope.criteria.sort directly

### ISSUE THREAD

**Issue by caldwecr** [toptal/chewy#177]
@pyromaniac kind of confused why this happens.

Was it your intent that in order to control the sorting behavior of an elasticsearch query that I would have to set scope.criteria.sort?

Based on the docs I was under the impression that this was the purpose of the #order method.

**Comment by pyromaniac** [comment]
Didn't get, there is `order` method, you don't have to modify criteria manually.

**Comment by caldwecr** [comment]
I must have run into a bug situation. I'll collect my notes tomorrow, but in situation I'm currently in the `order` method has no effect (the actual criteria's sort attribute is not changed). I'm using .aggs if that sheds any immediate light on what the issue might be.

**Comment by pyromaniac** [comment]
Probably, I think you have to try to debug this or post your essential code so I could debug it and fix.

**Comment by caldwecr** [comment]
User error.
