### ISSUE TITLE
Rspec config for Chewy.use_after_commit_callbacks

### ISSUE THREAD

**Issue by ka8725** [toptal/chewy#179]
Using RSpec 3.
Figured out that independently on the `Chewy.use_after_commit_callbacks` variable change in `before` callbacks and even before `RSpec.configure` the value is not updated in callbacks context to update index. So I got the following head of `spec_helper.rb` file:

```ruby
ENV['RAILS_ENV'] ||= 'test'

require 'chewy'
require 'chewy/rspec'
Chewy.use_after_commit_callbacks = false

require File.expand_path('../../config/environment', __FILE__)
require 'rspec/rails'
```

The `Chewy.use_after_commit_callbacks` must be set before all models' classes are initialized. May be add this to README or post to some wiki page?

**Comment by pyromaniac** [comment]
Feel free to do this. Moreover, if you are using spring models are loaded even before spec_helper.rb, so you have to create an initializer with `Chewy.use_after_commit_callbacks = false if Rails.env.test?`

**Comment by ka8725** [comment]
`Chewy.use_after_commit_callbacks = false if Rails.env.test?` doesn't work for me. Using spring, models' classes are already initialized in an initializer.

**Comment by pyromaniac** [comment]
Something wrong with your application, you are calling models in initializers or something like this. Normally models are loaded after initializers

**Comment by ka8725** [comment]
@pyromaniac , done - https://github.com/toptal/chewy/pull/184
