### ISSUE TITLE
Utilize Update API

### ISSUE THREAD

**Issue by marshall-lee** [toptal/chewy#186]
I see the _update_all support_ entry in TODO list.

What you mean by that? Does it mean that Chewy will be able to generate `{ "update" : {"_id" : "1", "_type" : "type1", "_index" : "index1"} }` entries in Elastic's [Bulk API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html) ?

Would it be possible to also do a partial updates on particular documents?

I'd like to see what new methods will be added to Chewy.

**Comment by pyromaniac** [comment]
Nope, this just means that `User.active.update_all(admin: true)` would update index with all the users affected by update. But this is a highly complex problem.

Talking about `update` requests: chewy already does `index` requests which is turned to `create` or `update` in ES internally depending on documents existence.

What do you mean by partial updates? Why do you need this?

**Comment by marshall-lee** [comment]
I know that Elastic doesn't have real in-place updates. Internally it's just a remove + create.

Nevertheless, utilizing Update API still has some benefits:

1. Network. Suppose we have *many* fields and writing to Elastic intensively. When just one field is updated I don't want to send all other document fields to Elastic. I just don't want to see them on the wire.
2. Also suppose this case:

```ruby
class SomeIndex < Chewy::Index
  define_type SomeType do
    field :x
    field :y, value: -> (s) { s.call_some_query }
  end
end
```

When I want to update just `x` (that is simply a db column value), i don't want to call the recalculation of `y` that involves additional query to the database.

For example, in our project we realized that some field is written to Elastic incorrectly. We need to do *mass update* against just one that field. And also we have 24 millions of documents so calling bulk import of **everything** is slow. We solved that problem by calling `Chewy.client.update`. But it would be very helpful to us if Chewy had `SomeIndex::SomeType.recalc_x!` or something.

**Comment by pyromaniac** [comment]
Honestly I have to think about it, there was a kind of partial updates idea, but it is still an idea only. If you are ready to offer your solution of this problem - welcome

**Comment by jorisvh** [comment]
Any news regarding the update_all support?

**Comment by pyromaniac** [comment]
Unfortunately, not. This is quite complicated thing. But you are able to use import explicitly as a workaround:

```ruby
scope = Model.scope
scope.update_all(column: value)
ModelIndex::Model.import(scope)
```

**Comment by pyromaniac** [comment]
It is kinda done in the latest version, you can import only specified fields you want.
