### ISSUE TITLE
Using a custom id for active record models

### ISSUE THREAD

**Issue by jwaldrip** [toptal/chewy#189]
How can I use a custom id for the active record models? Right now it is trying to access the id field on the model. I would like it to use something like "guid".

**Comment by marshall-lee** [comment]
Does your `guid` acts as primary key in the table or just `UNIQUE`?

**Comment by jwaldrip** [comment]
well the guid is something that I compose. The problem really stems from having 2 of the same records with different data due to a join query. For example:

```json
{
  "id": 55,
  "name": "foo",
  "section_id": 123,
}
```
and 

```json
{
  "id": 55,
  "name": "foo",
  "section_id": 456,
}
```

Both items have the same underlying attributes, but when joined with sections I have different section keys that need to be indexed independently. If I use the ID from the database, one record always overrides the other.

**Comment by pyromaniac** [comment]
Sorry, didn't answer in time, did you solve this? You may simply do

```ruby
define_type Model.scope do
  root id: -> { guid } do
    field ....
  end
end
```
