### ISSUE TITLE
How can I pass authentication header with elastic search connection request when using http basic auth for elasticsearch.

### ISSUE THREAD

**Issue by mayank-singh** [toptal/chewy#190]
How can I pass authentication header with elastic search connection request when using http basic auth for elasticsearch.

**Comment by pyromaniac** [comment]
Good question actually. There is no way currently, this need to be patched in chewy

**Comment by pyromaniac** [comment]
Have you find a way?

**Comment by timoshenkoav** [comment]
you can use this syntax to set http user/password in chewy.yml
```
development:
  host: 'http://<username>:<password>@<host>'
```

**Comment by mayank-singh** [comment]
development:
  host: 'localhost:9200'
  prefix: 'dev'
  user: 'user'
  password: 'pass'

I used the above config @pyromaniac

**Comment by Ryan-Berry** [comment]
Is there now a set way to do this? I've tried both solutions offered by @mayank-singh and @timoshenkoav but neither are working for me. Security was just applied to my cluster using Elastic Shield.

**Comment by pyromaniac** [comment]
As far as I get, you need to setup basic http auth, this means that you need to send an auth request with the transport, or send your credentials with every request. Anyway, seems like you have to customize the transport. Som you can try this: https://github.com/toptal/chewy/blob/master/lib/chewy.rb#L137

**Comment by davidrf** [comment]
If you are able to authenticate with `http://username:password@localhost:9200` in `cURL` requests, you can achieve the same by updating to your `chewy.yml` as follows:

```
production:
  host: "localhost"
  scheme: "http"
  port: "9200"
  user: "username"
  password: "password"
```

**Comment by brauliobo** [comment]
this should be on the readme
