### ISSUE TITLE
Proposed interface for deep actions, like import

### ISSUE THREAD

**Issue by caldwecr** [toptal/chewy#196]
The proposed method signature
```
#
# Execute the lambda in the scope of the type and invoke
# the action on the result (the result might be an array of ids, an AR scope, ... other options?)
# Simple usage:  `cascade :import, to: -> { }`
#    
def cascade action, options = {}

end
```

Some hypothetical examples
```
class User < ActiveRecord::Base
  has_many :posts
end

class Post < ActiveRecord::Base
  belongs_to :user
end

class UsersIndex < Chewy::Index
  define_type User do
    cascade :import, to: -> { posts }
  end

  define_type Post do
  end
end

class Person < ActiveRecord::Base
  has_many :pets
end

class Pet < ActiveRecord::Base
  belongs_to :person
  has_many :toys
end

class Toy < ActiveRecord::Base
  belongs_to :pet
end

class PetIndex < Chewy::Index
  define_type Pet do
    # does it make sense to support all of the various action types? 
    # some of the action types?
    # or would a more acute solution like a method called `cascade_import` be your preference?
    cascade [:import, :import!, :reset, :delete_all], to: :person
  end

  define_type Person do
  end
end

class PetIndex < Chewy::Index
  define_type Pet do
    # Causes :import, :update and :delete to be forwarded to all associations of the Pet
    # (in this case to #person and each Toy in #toys)
    #
    # Let me know if any of these actions are already able to be forwarded along associations
    cascade [:import, :update, :delete]
  end

  define_type Person do
  end

  define_type Toy do
  end
end
```

I kept this really loose, because I wanted to get your feedback before becoming committed to any approach.

As a side note, at Mattermark we actually have implemented a method .deep_import on specific document types, but a .deep_import method that must traverse every association and each of those associated objects' associations presents some challenges, and it turns out that we normally only wanted to traverse deeply over one or two associations, even between our most complex entities.

**Comment by pyromaniac** [comment]
I'm confused a little bit since I don't understand the purpose of this.

```ruby
class User < ActiveRecord::Base
  has_many :posts
  update_index 'posts#post', :posts
end

class Post < ActiveRecord::Base
  belongs_to :user
end

class UsersIndex < Chewy::Index
  define_type User do
  end

  define_type Post do
  end
end
```

If you will do `user.save` in such a setup all the user posts would be imported as well. Does it solve the problem?

**Comment by caldwecr** [comment]
It might. I'll take a day to think about it.

My suspicion is that I actually want to be able to have a different association traversal strategy for importing than I do for on going updates.

We do use the update_index syntax and we are generally quite liberal in updating records. Our strategy for 'create' indexing (indexing big chunks of new records fairly infrequently) tries to perform the minimum amount of work. 

I'm not too enthusiastic about having to invoke #save on each entity that I want to index.

I really want to do

``` 
UsersIndex::User.import [500000..550000]
```
And to be able to specify exactly how to determine which posts (and which associations of posts) should be imported.

Although it's an ugly syntax, section 13.1 of [AR Eager Loading](http://guides.rubyonrails.org/active_record_querying.html#eager-loading-associations) will give you some idea of the level of control I need to specify.

`Category.includes(articles: [{ comments: :guest }, :tags])`

might become

`Index::Category.import(articles: [{ comments: :guest }, :tags])`

**Comment by pyromaniac** [comment]
Got it. I'm calling this `update_all` support in readme and it is planned, I've event started to do it, but didn't succeed yet.

The first statement here: this feature have to reuse existing `update_index` already set up in models.
But this become a tough task since `update_index` support blocks, so we are not able to determine associations for preloading in several cases, this would still work actually, but not so efficient

**Comment by caldwecr** [comment]
@pyromaniac Is there an open branch or fork that has your rspec examples / partial implementation for update_all? Just curious to see how you envision it working.

**Comment by pyromaniac** [comment]
Unfortunately not, but I'll try to submit something as soon as it will be ready

**Comment by caldwecr** [comment]
Ok. I think this is fine for now. Not a huge priority for me. I'll move on to aggregates and look forward to see the update_all direction when it becomes available.
