### ISSUE TITLE
Sidekiq strategy and batching

### ISSUE THREAD

**Issue by fpbouchard** [toptal/chewy#197]
Hi,

we foresee some issues with the current sidekiq strategy as it instanciates only one worker instance for all models to re-index. In our case, it sometimes queue a single worker that has to re-index thousands of models. It still splits in batches in the worker itself, but the worker has too much to do and we can't control how much it should process.

What we'd like is just to call perform_async in batches, lets say a thousand at a time. This allows for parallel processing, so it scales better horizontally.

Does this make sense?

**Comment by caldwecr** [comment]
Just to clarify, you want to control the number of _instances_ of a model that should be tasked to a single sidekiq worker?

**Comment by fpbouchard** [comment]
Instances of any model in fact, but you get the idea yes.

Simplified example: 

```ruby
class User < ActiveRecord::Base
  has_many :tweets
  update_index 'users#tweets', :tweets
end

class Tweet < ActiveRecord::Base
  belongs_to :user
  update_index 'users#tweets', :self
end

class UsersIndex < Chewy::Index
  define_type Tweet do
    field :user_name, value: ->(tweet) { tweet.user.full_name }
  end
end
```

I want to index the user name in its posts so it is searchable. But if the user changes its name I then update all its posts, but a user could have many many posts, which are then queued in only _one_ worker instance. I'd like to split them in multiple workers so I can maximize my I/O on multiple sidekiq instances, work on the queues and tweak at the sidekiq level, instead of having one humongous worker working for a very long time to reindex everything.

**Comment by pyromaniac** [comment]
I think writing your custom strategy with [this](https://github.com/toptal/chewy/blob/master/lib/chewy/strategy/sidekiq.rb#L22) line fixed would be just enough for you

Also, if your solution would be common enough, don't hesitate to submit a PR :)
