### ISSUE TITLE
Timeout?

### ISSUE THREAD

**Issue by robly** [toptal/chewy#199]
Is there a way to change the default timeout of a Query/Index?

Here is the error we get randomly during the day:

Thanks

Faraday::Error::TimeoutError: Resolving timed out after 1511 milliseconds
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/patron-0.4.18/lib/patron/session.rb:223:in `handle_request'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/patron-0.4.18/lib/patron/session.rb:223:in `request'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/faraday-0.8.9/lib/faraday/adapter/patron.rb:33:in `call'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/faraday-0.8.9/lib/faraday/connection.rb:253:in `run_request'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/faraday.rb:21:in `block in perform_request'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:190:in `call'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/base.rb:190:in `perform_request'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/elasticsearch-transport-1.0.12/lib/elasticsearch/transport/client.rb:119:in `perform_request'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/namespace/common.rb:21:in `perform_request'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/actions/indices/exists.rb:46:in `block in exists'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/utils.rb:189:in `__rescue_from_not_found'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/elasticsearch-api-1.0.12/lib/elasticsearch/api/actions/indices/exists.rb:45:in `exists'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/chewy-0.8.1/lib/chewy/index/actions.rb:15:in `exists?'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/chewy-0.8.1/lib/chewy/type/import.rb:24:in `import'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/chewy-0.8.1/lib/chewy/type/import.rb:59:in `import!'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/chewy-0.8.1/lib/chewy/strategy/sidekiq.rb:17:in `perform'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/processor.rb:49:in `block (3 levels) in process'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/middleware/chain.rb:122:in `call'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/middleware/chain.rb:122:in `block in invoke'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-status-0.5.1/lib/sidekiq-status/server_middleware.rb:37:in `call'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/newrelic_rpm-3.10.0.279/lib/new_relic/agent/instrumentation/sidekiq.rb:33:in `block in call'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/newrelic_rpm-3.10.0.279/lib/new_relic/agent/instrumentation/controller_instrumentation.rb:353:in `perform_action_with_newrelic_trace'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/newrelic_rpm-3.10.0.279/lib/new_relic/agent/instrumentation/sidekiq.rb:29:in `call'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-failures-0.3.0/lib/sidekiq/failures/middleware.rb:10:in `call'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/middleware/server/active_record.rb:6:in `call'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/middleware/server/retry_jobs.rb:62:in `call'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/middleware/server/logging.rb:11:in `block in call'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/logging.rb:22:in `with_context'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/middleware/server/logging.rb:7:in `call'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/middleware/chain.rb:124:in `block in invoke'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/middleware/chain.rb:127:in `call'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/middleware/chain.rb:127:in `invoke'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/processor.rb:48:in `block (2 levels) in process'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/processor.rb:105:in `stats'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/processor.rb:47:in `block in process'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/processor.rb:86:in `do_defer'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/sidekiq-2.17.6/lib/sidekiq/processor.rb:37:in `process'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `public_send'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/celluloid-0.15.2/lib/celluloid/calls.rb:25:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/celluloid-0.15.2/lib/celluloid/calls.rb:122:in `dispatch'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/celluloid-0.15.2/lib/celluloid/actor.rb:322:in `block in handle_message'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/celluloid-0.15.2/lib/celluloid/actor.rb:416:in `block in task'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/celluloid-0.15.2/lib/celluloid/tasks.rb:55:in `block in initialize'
/home/ubuntu/.rvm/gems/ruby-2.1.3@robly/gems/celluloid-0.15.2/lib/celluloid/tasks/task_fiber.rb:13:in `block in create'=

**Comment by pyromaniac** [comment]
Seems like client supports timeouts: https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-transport/lib/elasticsearch/transport/client.rb#L62, you are able to pass it from `chewy.yml` or with `Chewy.settings =` accessor.

**Comment by robly** [comment]
Thanks, we will try that. We had been trying to set timeout since database adapters always use that.
