### ISSUE TITLE
ActiveRecord scope with `select` breaks migrations

### ISSUE THREAD

**Issue by gkaemmer** [toptal/chewy#200]
I have an index defined as follows (in real life its more complicated, but this code recreates the error):
```
class ControlIndex < Chewy::Index
  define_type Control.select('controls.*') do
    field :field
    # etc
  end
end
```
When I run `rake db:drop db:create db:schema:load` (which my CI server runs for tests), I get the following error:
```
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "controls" does not exist
LINE 5:                WHERE a.attrelid = '"controls"'::regcl...
                                          ^
:               SELECT a.attname, format_type(a.atttypid, a.atttypmod),
                     pg_get_expr(d.adbin, d.adrelid), a.attnotnull, a.atttypid, a.atttypmod
                FROM pg_attribute a LEFT JOIN pg_attrdef d
                  ON a.attrelid = d.adrelid AND a.attnum = d.adnum
               WHERE a.attrelid = '"controls"'::regclass
                 AND a.attnum > 0 AND NOT a.attisdropped
               ORDER BY a.attnum
```
It looks like the `arel` call in line 10 of `type/adapter/active_record.rb` doesn't like it when the table doesn't exist and a `select` scope is used. It works when I remove the `select`.

I've temporarily fixed the error by adding `if Control.table_exists?` after the `define_type`:
```
class ControlIndex < Chewy::Index
  define_type Control.select('controls.*') do
    field :field
    # etc
  end if Control.table_exists?
end
```
But that's real ugly. I wonder if there might be a way to address this in chewy's source.

**Comment by caldwecr** [comment]
Just curious, but what happends if you use `Control.arel_table.select('controls.*')` instead?

**Comment by gkaemmer** [comment]
Hmm, almost. Getting a `NoMethodError: private method `select' called for #<Arel::Table:0x007fa9e1680d70>`.

**Comment by pyromaniac** [comment]
The main question here is: how do you cause ControlIndex class loading while migrations? This should not happen actually

**Comment by gkaemmer** [comment]
@pyromaniac Yeah, this happens due to lazy loading in my models. I reference `ControlsIndex` from the inside the class definition of `Control`, which triggers loading of the index file.

**Comment by pyromaniac** [comment]
Do you really need such a reference? How is it implemented?

**Comment by pyromaniac** [comment]
Maybe it is possible to reference as a string and then simply constantize it when used?

**Comment by gkaemmer** [comment]
Good call on using a string -- I'll do that.
