### ISSUE TITLE
Potential data integrity fault by ensuring invocation of Chewy::Strategy#leave

### ISSUE THREAD

**Issue by inbeom** [toptal/chewy#201]
Hi,

We found an issue while using atomic strategy, as inside `Chewy::Strategy#wrap` it is `ensure`d `Chewy::Strategy#leave` is invoked regardless of exception inside the passed block.

https://github.com/toptal/chewy/blob/master/lib/chewy/strategy.rb#L56

Were there any reasons for the `ensure` block? With `:atomic` strategy, if some models are stashed before catching exception, they are indexed on ES regardless of their status after block execution. In our case, `INSERT`-rollbacked records are being indexed to ES, as `Post#save` (in a database transaction) raised an exception from a database error after some new `Tag` records are stashed in `:atomic` strategy.

```ruby
class Tag < ActiveRecord::Base
  update_index("posts_index#tag") { self }

  def self.find_or_create_with_content(content)
    extract_tags(content).each do |tag|
      create(name: tag)
    end
  end
end

class Post < ActiveRecord::Base
  has_many :tags

  before_save do
    self.tags = Tag.find_or_create_with_content(content)
  end
end
```

In our case, it would be best to create/update `Tag` records in `after_save` callback rather than `before_save` callback. Asserting `:use_after_commit_callbacks` can be another solution. But ensuring to index all stashed records could be problematic in other normal situations.

I'd like to discuss it thoroughly before making any changes as modifying it can affect many users.

Thanks!

**Comment by pyromaniac** [comment]
Actually, chewy stashes all the records in after_commit callback. https://github.com/toptal/chewy/blob/master/lib/chewy/type/observe.rb#L40-L41 did you turn it off?

**Comment by inbeom** [comment]
It was turned off apparently, and I think we should reconsider using ensure block. Unhandled exceptions are out of our expectations and preventing further operations seems like more viable option for this situation.

**Comment by pyromaniac** [comment]
Actually there is no other way except using ensure block to pop strategy from stack, all the gems using such an approach. We can consider to use `else` branch here to call `leave` on strategy and call only pop without leave in `ensure` branch, try to experiment with, but I don't think I'm going to implement it here since it may cause unpredictable results and current approach with `after_commit` works as it should. Have no idea why did you turn it off.

**Comment by inbeom** [comment]
Okay, I guess there some historical reasons (which I don't follow well) on that decision of turning the option off and we'll try to fix it by refining the scope of our transaction block or tweaking configurations and so forth.

Thanks for sharing your opinion!

**Comment by pyromaniac** [comment]
If you have anymore questions - always welcome.
