### ISSUE TITLE
Chewy::UndefinedUpdateStrategy raised in migrations even if specified

### ISSUE THREAD

**Issue by davekapp** [toptal/chewy#202]
In a migration, we're attempting to dynamically set some default values for a new column added to a table and Chewy::UndefinedUpdateStrategy is being raised even though we have a default strategy set. Attempting to explicitly set a strategy does not work either and results in the same error.

Versions:
chewy 0.7.0
Rails 4.21
pg 0.18.1

Example: 

class AddNewFieldToThings < ActiveRecord::Migration
  def up
    Chewy.strategy(:bypass) do
      add_column :things, :important_value, :string, default: ""

      Thing.find_each do |t|
        t.important_value = <whatever>
        t.save
      end
    end
  end
...

The result is the same whether using def change or def up/down. Putting the add_column line before or after the Chewy.strategy does not make a difference either.

We also have Chewy.root_strategy = :bypass set elsewhere, but it does not prevent the exception from being raised (whether Chewy.strategy is present in the migration or not, the exception is raised).

:bypass would be fine since this field does not matter in our index for the time being.

**Comment by davekapp** [comment]
And now I feel silly, this was fixed by Chewy 0.8.1 and I forgot to check for a new version first :(

So no problem here. :)

**Comment by pyromaniac** [comment]
Yeah, this was a bug with rails 4.2 unfortunately :(
