### ISSUE TITLE
How to use geo_point type?

### ISSUE THREAD

**Issue by andreimc** [toptal/chewy#206]
Hello, 

Can you show an example where I can use the geo point type in an index

```
field :coordinates, type: 'geo_point' do
   field :lat, :long
end
```

This doesn't work for me can you point me in the right direction ?

Regards

**Comment by pyromaniac** [comment]
simply `field :coordinates, type: 'geo_point'`, where object.coordinates returns hash {lat:, lon:}

**Comment by andreimc** [comment]
thanks pyro will give that a go :+1:

**Comment by joonty** [comment]
Could this be added as an example in the README? I can't find anywhere obvious where it's mentioned that it should be in the hash format with those particular fields, and it took a couple of targeted google searches to finally arrive at this issue. Might be worth stating it in the existing section showing the geo search example?

Thanks

**Comment by joonty** [comment]
Also, the answer given isn't quite right: the hash should use the keys `lat` and *`lon`*, not `long`.  Important difference, as the import silently fails if you use the wrong key!

So, a working example is:

```ruby
field :coordinates, type: "geo_point", value: ->(object) { { lat: object.latitude, lon: object.longitude } }
```

**Comment by pyromaniac** [comment]
Since you did this already, could you create a PR with readme fixed please?

**Comment by joonty** [comment]
Yep, done!

**Comment by davideghz** [comment]
Hey there, can you add to the doc some more information about the syntax to filter an index by coordinates? I'm trying something like the following, w/o any luck:

`ProductsIndex.filter{geo_distance:{ distance:'100km', location:{ lat: 60.0951482712848, lon: -86.4810766234584 }}}`

**Comment by pyromaniac** [comment]
Try `ProductsIndex.filter(geo_distance: {distance:'100km', location: {lat: 60.0951482712848, lon: -86.4810766234584}})`

**Comment by davideghz** [comment]
@pyromaniac yes, it works :) also, I defined the field type with :coordinates and in the query I was calling location. These two errors caused me quite a headache. Thanks for your input

**Comment by morgler** [comment]
How would I define the value of the `coordinates` field, if some of my objects don't have latitude and longitude? Later in a search I want to simply ignore the location for objects that don't have an address (and thus longitude and latitude).

Right now, I get a `mapper_parsing_exception' with reason `latitude must be a number` when trying to index my field with the code above.

**Comment by rosalinekarr** [comment]
Did anyone ever find a solution to @morgler's problem? I have the same issue.

**Comment by pyromaniac** [comment]
Try to pass an empty hash if no coordinates exist.
