### ISSUE TITLE
Wrong behavior when importing ids using Mongoid

### ISSUE THREAD

**Issue by comogo** [toptal/chewy#213]
I'm getting some wrong behavior on my indexes when updating some model. I debugged the chewy code for awhile and I think I found how the bug happens.

The problem happens right here https://github.com/toptal/chewy/blob/master/lib/chewy/type/adapter/orm.rb#L110-L130

When I call `MyIndex.import '5488aa814661623f655f0200'`:

1. the `collection` argument is something like `['5488aa814661623f655f0200']`

2. the `hash` variable is `{ '5488aa814661623f655f0200' => '5488aa814661623f655f0200' }`

3. so here https://github.com/toptal/chewy/blob/master/lib/chewy/type/adapter/orm.rb#L120 the `object.id` it is an bson object instead a string, so the key is not deleted from `hash`.

As the key `indexed` is not deleted from the `hash` it is also marked to delete from elasticsearch here https://github.com/toptal/chewy/blob/master/lib/chewy/type/adapter/orm.rb#L125-L127 so it indexes and deletes the index.

I get this behavior only when using `:atomic` strategy, because it identifies the objects here https://github.com/toptal/chewy/blob/master/lib/chewy/strategy/atomic.rb#L23, as `:resque` and `:sidekiq` strategies inherit from `Atomic` I think that it happens in those strategies too.

Can anyone check this behavior?

Sorry for my english.

**Comment by pyromaniac** [comment]
I'll take a look on this, but probably it would be better if you will simply submit a patch where every possible id in `import_objects` is type casted to_s (since I've got no idea now when I'll be able to patch this)

**Comment by comogo** [comment]
I'll do that, thanks.

**Comment by ciihla** [comment]
I can confirm that this fixes the issue with mongoid. I had to do similar monkey patch in our project.
The main important fix is line 120: where should be: 

    batch.each { |object| hash.delete(object.id.to_s) }

 Could you please send a MR?
