### ISSUE TITLE
Import more than 1000 records at a time

### ISSUE THREAD

**Issue by yang-rifiniti** [toptal/chewy#216]
I am using rails 4.2.2 and latest chewy gem 0.8.1 to index records from MySQL to Elasticsearch 1.4.4. When I index I notice that it imports 1000 records at a time until all records are exhausted. I wonder if there is a way to change the limit so that it could import say 5000 records at a time so the indexing time could be faster?

(More of a question than an issue; new to ES and GitHub issues. If not using right please point out and will correct. Thanks)

**Comment by pyromaniac** [comment]
Actually indexing time would not be faster, but it is possible to pass batch_size: 5000 to the `import method`

**Comment by yang-rifiniti** [comment]
Thanks a lot! Exactly what we are looking for!
