### ISSUE TITLE
Apply filter to query not produce correct result

### ISSUE THREAD

**Issue by edipofederle** [toptal/chewy#217]
I am facing a problem and do not know what might be happening. I do not know if it's a issue or misunderstanding my. 

I have this query:

```all = index.query(query_string: {fields: [:company_id],
              query: current_user_company_id}
            ).limit(get_limit)```
Considere get_limit equal 2.

When I execute it, I always get corrects results, lets say:

```Test 1
Test 2```
Then I apply some filter on all:

```all.filter { name == 'ana'}```
And the result contains ana record, but this is not present on all

The generated query is:

```{:body=>{:query=>{:filtered=>{:query=>{:query_string=>{:fields=>[:company_id], :query=>2364}}, :filter=>{:term=>{"name"=>"ana"}}}}, :sort=>[{:created_at=>:desc}], :size=>2}, :index=>"client", :type=>["person_client"]}```
It seems that the limit is not being properly used here.

Any idea here? Thanks in advance

**Comment by pyromaniac** [comment]
Are this two records returned with filter only?

**Comment by edipofederle** [comment]
The first code return the two records (```Test1 ```and ```Test2```). Then I apply the filter (second code), and I get the record ```ana```. 

The all dont contains ``àna``` records, but the filter return it.

**Comment by edipofederle** [comment]
this gist can maybe help explain the `problem`:

https://gist.github.com/edipofederle/8deb9b8781f9db6fc599

**Comment by pyromaniac** [comment]
And what does `ClientIndex.filter {name == "ana"}` return?

**Comment by edipofederle** [comment]
All records that contains ```ana``` (correct in this case). I want apply the filter only on records  returned on ``all```

**Comment by pyromaniac** [comment]
This is really strange, the query should work as expected, limit was applied correctly, I really don't see any issue with this query now. Probably, it's something with your data, you have to debug it carefully setp by step probably

**Comment by edipofederle** [comment]
It looks like the limit has been applied to the 'final query'. And not on the first query. I will continue investigating. Thanks for now.

**Comment by pyromaniac** [comment]
Actually there is no another way. Limit definitely applied to the whole query

**Comment by edipofederle** [comment]
Right. Is there any way that I can apply a filter only a set of records? That would help.

**Comment by pyromaniac** [comment]
Have no idea actually why do you need this. Seems like you want something strange. Could you please describe the final goal?

**Comment by edipofederle** [comment]
Yes of course. There are some cases where I need to limit the access of users to data. (matter of changing plans in a service).

So, lets say the user has 1000 registered clients, in some cases, I need only working with, 100, for example.

I made myself clear?

**Comment by pyromaniac** [comment]
Probably, it is possible to do in 2 queries. The first one plucks ids of this 100 users and the second one uses this ids for filtering

**Comment by edipofederle** [comment]
Sorry for late reply.
As you said at last comment, I did something like this:

```ClientIndex.filter{ id(execution: :or) == ids }.filter {name == "ana"}```

I will close it.

Thanks.
