### ISSUE TITLE
Typhoeus error / The option: disable_ssl_peer_verification is invalid

### ISSUE THREAD

**Issue by skwp** [toptal/chewy#22]
Anyone seeing this? During index create, chewy is complaining:
Ethon::Errors::InvalidOption: The option: disable_ssl_peer_verification is invalid.
Please try ssl_verifypeer instead of disable_ssl_peer_verification. 

```
from /Users/yan/.rvm/gems/ruby-2.1.1@reverb/gems/typhoeus-0.6.8/lib/typhoeus/hydra/runnable.rb:17:in `block in run'
    from /Users/yan/.rvm/gems/ruby-2.1.1@reverb/gems/chewy-0.4.1/lib/chewy/index/actions.rb:61:in `create!'
```

Seems like some option it's passing to typhoeus? Maybe I have a different version than it expects?

**Comment by darkness51** [comment]
@skwp Could you explain where you import the typhoeus faraday adapter please?

**Comment by skwp** [comment]
I required it in my index file, but I assume it should work if required in an initializer. That would probably be cleaner
