### ISSUE TITLE
Generating JSON without import

### ISSUE THREAD

**Issue by codezomb** [toptal/chewy#221]
I'm using ES (via chewy) to serve up our JSON in a few places without hitting the database. For us, this works really well as it gives us consistency between search and non-search queries, as well as being extremely fast. However, there's a few places I want to convert an AR object to the same JSON format, without actually having to maintain a different JSON mapping vs the ES mapping. I've been digging around a bit, but I've been unable to figure this out.

Is this possible? For example:

``` ruby
# GET /articles
render json: ArticleIndex.filter { category == 'foo' }
  .map { |a| a._data["_source"] }.to_json

# POST /articles (I want to match the ES mapping here)
render Article.create(article_params).to_json
```

**Comment by pyromaniac** [comment]
There is no direct way to do it currently, but you are able to use something like https://github.com/toptal/chewy/blob/master/lib/chewy/type/import.rb#L153 - i.e. take ArticleIndex::Article.root_object and call compose on it with newly created article.

**Comment by pyromaniac** [comment]
But actually this is great direction for refactoring, probably I'll ad such an ability, not sure when though :)

**Comment by codezomb** [comment]
Thanks, I think this is a pretty nice (albeit buried) approach. The main issue I was trying to avoid was having to either a) maintain a second serialization method, or b) hit ES to query the JSON after also hitting the database.

**Comment by pyromaniac** [comment]
Try out the new version please, there should be a way to do it now
