### ISSUE TITLE
Exclude fields in results

### ISSUE THREAD

**Issue by codezomb** [toptal/chewy#222]
Is it possible, without ruby processing to exclude fields from the ES results? For example, I have a policy file (via Pundit) that handles my query objects based on a role. This role could determine which columns I'll return the user. For example, admin has access to more columns than a guest.

https://www.elastic.co/guide/en/elasticsearch/reference/1.6/search-request-source-filtering.html

**Comment by pyromaniac** [comment]
https://github.com/toptal/chewy/blob/master/lib/chewy/query.rb#L771

**Comment by codezomb** [comment]
Thanks, I did see that, but a blacklist can be much better than a whitelist in scenarios where there's a lot of possible fields.

**Comment by pyromaniac** [comment]
I don't think ES supports blacklists itself, but if it is - you probably can add such a functionality

**Comment by codezomb** [comment]
For anyone else looking for this type of functionality, this is what I did... 

```ruby
original_fields =  mappings_hash[:mappings][:article][:properties].keys
exclusions      = [:comments, :revisions]

new_fields = original_fields - exclusions
```
