### ISSUE TITLE
complex index query with variables

### ISSUE THREAD

**Issue by aarongowatch** [toptal/chewy#223]
I'm looking for a way to construct some more complex queries.  I need something that basically looks like this:

```ruby
index.filter{ must(foo_ids == foo_list).must(key == variable) | must(bar_ids == bar_list) }
```

pseudo:

```
if (foo_ids in foo_list and key == variable) || (bar_ids in bar_list)
```

the issue I'm running into is that when using the block form of filter we have no reference to the calling class that I could use to interpolate the filter values.  I haven't been able to figure out how to make the same query without using the block form of filter, but maybe thats the part I'm missing.

any help would be appreciated!

**Comment by pyromaniac** [comment]
Could you please create your query without DSL at first? In plain hashes?

**Comment by pyromaniac** [comment]
Also `index.filter { ((foo_ids == foo_list) & (key == variable)) | (bar_ids == bar_list) }` probably could work if I understood you correctly

**Comment by aarongowatch** [comment]
the latter worked great.  the only catch was this doesn't work if `foo_list` and `bar_list` are instance methods or when using something like `foo_ids == object.list_method`.  creating local variables to hold these values worked great.

**Comment by pyromaniac** [comment]
Try `index.filter { ((foo_ids == o{foo_list}) & (key == variable)) | (bar_ids == o{bar_list}) }` then. `o{}` block uses outer scope

**Comment by aarongowatch** [comment]
that worked perfectly, thank you!
