### ISSUE TITLE
How to create cross model search index

### ISSUE THREAD

**Issue by rtcoms** [toptal/chewy#226]
I have two models (Story and Project), and both of them respond to title and description method, There is no association between these 2 models . 

How can I create a single search index which cover both these models ? I want the search query to return any story or project which matches the criteria ?

I see that I can have multiple define_type blocks in search index class , but could not find any method like 'import' which create whole index again considering stories and projects both.

**Comment by pyromaniac** [comment]
Use 2 types and 2 define_type statements. You will be able to query across the whole index

**Comment by rtcoms** [comment]
thanks . closing the issue .
