### ISSUE TITLE
Index multiple documents for one database record

### ISSUE THREAD

**Issue by maleblond** [toptal/chewy#230]
Is it possible with chewy to index multiple documents for one database records without creating multiple index types?

For example, we want to index calendar events, but some informations needs to be masked for some users (e.g. event's description). There is no table in the database containing the informations of who can see what (it's based on account groups and event owner). We would like to index two documents, one totally unmasked, and one with some informations unavailable. Would it be possible to do that without creating two index types (event and masked_event)?

**Comment by pyromaniac** [comment]
You may probably create one document with both events objects

**Comment by maleblond** [comment]
Actually, I want to create two documents with one event object

**Comment by pyromaniac** [comment]
It is probably possible if you will pass query to type definition which doubles records, but with an additional flag.

**Comment by maleblond** [comment]
I just figured out we could do something like :

Account.select(:id, "'true'").all.union(Account.select(:id, "'false'").all)

Is it possible to use auto-generated elastic search id instead of active_record id?

**Comment by pyromaniac** [comment]
Probably yes, you have to pass:

```
define_type ... do
  rood id: -> { nil (or probably it would be better to return uniq identifier like "s#{id}") } do
    field ...
  end
end
```

But you will have problems with such a solution in future with updates and so on. Chewy is built to use one particular approach. So maybe there are another way to do what you want and you picked no the best approach ever. Actually I would use one document per record but with 2 subdocuments or even use 2 different types since you are able to pick one or both to search on.

**Comment by maleblond** [comment]
I guess using multiple types for the same active record object is the best solution for us.

Thanks for your support and your amazing gem!
