### ISSUE TITLE
Search "+" crash

### ISSUE THREAD

**Issue by biow0lf** [toptal/chewy#232]
Hello,

There are some queries which raise errrors.

Simple "+" in ```query`` raise Elasticsearch::Transport::Transport::Errors::BadRequest

Is there needed any additional data escaping before sending query to ES via chewy?

Exception log:
```
 [400] {"error":"SearchPhaseExecutionException[Failed to execute phase [query], all shards failed; shardFailures {[QVDWwCDhQg-Vknw4NZQb2g][tours][0]: SearchParseException[[tours][0]: from[-1],size[-1]: Parse Failure [Failed to parse source [{\"query\":{\"filtered\":{\"query\":{\"query_string\":{\"fields\":[\"title.autocomplete\"],\"query\":\"+\", ....
```

**Comment by pyromaniac** [comment]
Actually the last part of exception is the most significant.

**Comment by biow0lf** [comment]
Ok

https://gist.github.com/biow0lf/c74ac65c672163b4d414

**Comment by biow0lf** [comment]
If needed, I can create minimal rails app with chewy to reproduce this behavior.

**Comment by pyromaniac** [comment]
So you are doing `query_string` query. Hence you have to read https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html completely and carefully. If you don't need all the `query_string` features, you have to use another query type then.

**Comment by pyromaniac** [comment]
Especially https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html#_reserved_characters section

**Comment by biow0lf** [comment]
Thank you, @pyromaniac! This is extractly what I am looking for. I will fix this in my working project and update README.md for ```chewy```. So, don't close this issue for now.

**Comment by biow0lf** [comment]
BTW, I have this same issue with thinking-sphinx and mostly the same answer. :smile:
