### ISSUE TITLE
Search Across Indices

### ISSUE THREAD

**Issue by joshuamcginnis** [toptal/chewy#236]
We want to include a global search which searches across indices and types.

How do I search across indices with chewy? It looks like the search interface is only available on the index class and I'd rather not perform multiple searches and merge the results.

Any thoughts on this approach?

**Comment by pyromaniac** [comment]
Just take a look on https://github.com/toptal/chewy/blob/master/lib/chewy/query.rb#L36. There is no public interface, but you are always able to initialize query for multiple indexes.

**Comment by joshuamcginnis** [comment]
Thanks!
