### ISSUE TITLE
Reset All and Update All rake tasks fail if rails engine doesn't include app/chewy folder

### ISSUE THREAD

**Issue by mattmenefee** [toptal/chewy#237]
When running `rake chewy:reset` or `rake chewy:update` while also having a Rails engine installed that doesn't pull in the `app/chewy` folder (in my case, [exception_notification](https://github.com/smartinez87/exception_notification)), the rake task fails with the backtrace:
```
rake aborted!
NoMethodError: undefined method `existent' for nil:NilClass
/home/deploy/apps/alice/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/tasks/chewy.rake:16:in `block in eager_load_chewy!'
/home/deploy/apps/alice/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/tasks/chewy.rake:16:in `map'
/home/deploy/apps/alice/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/tasks/chewy.rake:16:in `eager_load_chewy!'
/home/deploy/apps/alice/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/tasks/chewy.rake:51:in `update_all'
/home/deploy/apps/alice/shared/bundle/ruby/2.2.0/gems/chewy-0.8.1/lib/tasks/chewy.rake:80:in `block (3 levels) in <top (required)>'
```

The line that's causing the failure is in the [rake_helper file](https://github.com/toptal/chewy/blob/master/lib/chewy/rake_helper.rb#L20):

    dirs = Chewy::Railtie.all_engines.map { |engine| engine.paths['app/chewy'].existent }.flatten.uniq

**Comment by pyromaniac** [comment]
Yeah, looks like a bug, there should be probably `Chewy::Railtie.all_engines.map { |engine| engine.paths['app/chewy'] }.compact.map(&:existent).flatten`

Could you do a PR please?

**Comment by mattmenefee** [comment]
Sure! Thanks for the quick response!
