### ISSUE TITLE
Method for passing Active Record Relation to Chewy query

### ISSUE THREAD

**Issue by pfletch1023** [toptal/chewy#239]
In my API, I'd like to use Chewy for filtering objects in an index, but I would like to use Active Record to filter results for the current user (i.e. `User.accessible_to(@current_user)`). So at a high level I would like to merge Chewy results with Active Record results.

At the moment, I have written a wrapper around Chewy that takes as argument an Active Record Relation (or array) and adds a filter to the chewy query to the objects included. Here's an example:
```
# Example: initialize_query(UsersIndex, User.accessible_to(@current_user))
def initialize_query(index, scope = nil)
  q = index.query(nil)
  return q unless scope
  if scope.respond_to? :pluck
    ids = scope.pluck :id
  else
    ids = scope.map &:id
  end
  q.filter(terms: { id: ids })
end
```

Is there a better way of doing something like this? Are there built-in methods for scoping Chewy queries to an Active Record Relation?

**Comment by pyromaniac** [comment]
https://github.com/toptal/chewy/blob/master/lib/chewy/query/loading.rb#L46

**Comment by pfletch1023** [comment]
Thanks for the quick response, @pyromaniac. I tried something like that: `UsersIndex.query(nil).load(scope: User.accessible_to(@current_user))`. However, when I call `to_a` or render it as json, it doesn't seem to remove values that were excluded (it render `nil` results in addition to the actual objects).

**Comment by pyromaniac** [comment]
Yeah, this is desired behavior, you have to do `.compact` if you need by yourself. Also pagination will be broken with your approach. Maybe it would be better to apply cancan conditions to the ES query already?
