### ISSUE TITLE
Share settings between indexes

### ISSUE THREAD

**Issue by renatolond** [toptal/chewy#240]
Hello!

Sorry for the rookie question, but I couldn't find anything about this in the documentation.
I've got two indexes that share basically the same settings, but index different models, goes something like this:

```
    settings analysis: {
        filter: {
            my_synonym_filter: {
                type: "synonym",
                synonyms: [
                ...
                ]
            }
        },
        analyzer: {
            title: {
                tokenizer: 'standard',
                filter: ['lowercase', 'asciifolding', "my_synonym_filter"]
            }
        }
    }
```

How can I share this between the two indexes? Should I make a parent index and derive each index from it? If I do this, can I merge the settings together?

**Comment by pyromaniac** [comment]
I was thinking about common repository of index settings, but since it is not implemented we are using simple concerns

**Comment by renatolond** [comment]
I wasn't really sure how to make it with concerns, so I did a parent class with a default_settings static method. Thanks for the idea!
