### ISSUE TITLE
Unable to Query via Console

### ISSUE THREAD

**Issue by joshuamcginnis** [toptal/chewy#243]
I'm having a heck of a hard time executing queries in the `rails console` and getting back results. 

This raw query works (all records are returned) when using a curl or a rest client:

```
GET /_search
{
    "query": {
        "match_all": {}
    }
}
```

However, when I execute the following from the rails console:

``` ruby
CompaniesIndex.filter{ match_all }
```

I get:

``` console
=> #<CompaniesIndex::Query:0x007f98f9aacbe0
 @_collection=nil,
 @_indexes=[CompaniesIndex],
 @_request=nil,
 @_response=nil,
 @_results=nil,
 @_types=[],
 @criteria=
  #<Chewy::Query::Criteria:0x007f98f9aacbb8
   @aggregations={},
   @facets={},
   @fields=[],
   @filters=[{:match_all=>{}}],
   @options={:query_mode=>:must, :filter_mode=>:and, :post_filter_mode=>:and},
   @post_filters=[],
   @queries=[],
   @request_options={},
   @scores=[],
   @script_fields={},
   @sort=[],
   @suggest={},
   @types=[]>,
 @options={}>
```

If I try to call `.to_a` on the result, I get `NoMethodError: undefined method `[]' for nil:NilClass`.

I'm I missing something here? Is there a way to output the raw `json` sent to the ES Client? I tried to hack the gem (`lib/chewy/search.rb:25`), but it seems this line is never called in the console.

Thanks again.

**Comment by joshuamcginnis** [comment]
Another note, querying directly from the client also works:

```ruby
CompaniesIndex.client.search body: { query: { match_all: {} } }
```

**Comment by pyromaniac** [comment]
Actually `.to_a` should do the job. Could you post the whole `NoMethodError` exception stacktrace?

**Comment by joshuamcginnis** [comment]
Yea, there was no stack trace. It was as if something was eating the exception and then just printing the message.

Me and a colleague spent a day figuring this out, hunting through this gem and it's dependencies but weren't able to pin down the issue. Ultimately, everything started working again after a machine restart (I realize how ridiculous that sounds). 

One thing I did notice was that prior to the restart, I had two elasticsearch processes running, which seemed strange. I killed one of them but it didn't have any effect.

Prior to the restart, I tried:
* Deleting / recreating the index
* Optimizing the index
* Restarting the rails server
* Trying the queries via console and via the app
* I tried filters, queries, etc - they all appeared correct, but would throw the `NoMethodError` error

Very strange, but restarting was the only thing I could try to get it working. Tomorrow is a new day so I'll see if it pops up again and try to add more info.

**Comment by pyromaniac** [comment]
Could it be spring, for example? Have you try simple spring stop? About 2 processes: chewy dictates using of 2 different ES servers. One on 9200 post - the usual one which goes with the usual installation (btw is has 2 nodes by default, so there will be 2 processes) and test server on 9250 port used for test and cucumber environments, which is starting with `rake elasticsearch:start` (usually 1-node, this approach came from elasticsearch-ruby gem)

**Comment by ACPK** [comment]
@joshuamcginnis @pyromaniac Did you get this resolved as I'm having the same issue even after stopping Spring.

**Comment by Firfi** [comment]
I have the same error right now doing controller specs, where controller uses chewy

**Comment by pyromaniac** [comment]
Can you simply trace it? Have never face this issue.

**Comment by abartov** [comment]
I'm experiencing this same issue (ES 5.3.0).  A trivial query by a single field works in Kibana, and from the Index class using .client, but not using .query. (it returns an object with no results.)

How can I help debug this?

**Comment by pyromaniac** [comment]
Can you provide your query inspection first of all?

**Comment by abartov** [comment]
Oh, scratch that, it does work.  The returned object confused me with nils, but .count and .each do give me the results I expect.  Thanks for responding, @pyromaniac!

**Comment by pyromaniac** [comment]
You are welcome
