### ISSUE TITLE
How to test connection issues with rspec

### ISSUE THREAD

**Issue by joshuamcginnis** [toptal/chewy#244]
I'm hoping someone can point me in the right direction with regards to testing and handle connection-related exceptions.

I'd like to ensure that if our app loses it's connection to ES or has a connectivity issue, I'm able to catch the exception and handle the exception appropriately. 

There doesn't seem to be an easy way to kill ES without just killing all of the pids. That said, is there a way to force ES to throw a connection-related exception in a test?

**Comment by pyromaniac** [comment]
Well, you probably can use https://github.com/Shopify/toxiproxy or analogues without killing processes

**Comment by joshuamcginnis** [comment]
I took the approach of just overriding the client port in my test to a number that ES isn't listening to in order to simulate a connectivity issue:

```ruby
MyIndex.client.transport.connections.first.host[:port] = 9999
```
Using this approach, I was able to handle these exceptions:
```Faraday::Error::ConnectionFailed, Faraday::Error::TimeoutError```
