### ISSUE TITLE
Multi Search Support

### ISSUE THREAD

**Issue by D1plo1d** [toptal/chewy#245]
Is it possible to do ElasticSearch multi-searches from Chewy? I couldn't find anything in the Chewy docs about this.

https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html

**Comment by pyromaniac** [comment]
Nope, not yet

**Comment by D1plo1d** [comment]
Thanks for the quick reply. Are there any work arounds for parallelizing searches on mruby?

**Comment by pyromaniac** [comment]
Nope as well

**Comment by konalegi** [comment]
Multi Search planning to support? May be  plans?

**Comment by pyromaniac** [comment]
Unfortunately, not yet, It is possible to use elasticsearch-ruby interfaces to do it

**Comment by konalegi** [comment]
Thanks
