### ISSUE TITLE
Setting Logger.new fails

### ISSUE THREAD

**Issue by gmile** [toptal/chewy#248]
As per readme, tried setting the logger from my rails console. Got this:

```
irb(main):011:0> Chewy.logger = Logger.new
ArgumentError: wrong number of arguments (0 for 1..3)
```

**Comment by pyromaniac** [comment]
Are you sure this is not a `Logger.new` exception? it should be at least `Logger.new(STDOUT)`

**Comment by gmile** [comment]
You're right, `Chewy.logger = Logger.new(STDOUT)` works. I will submit an update to Readme, if you don't mind?
