### ISSUE TITLE
Access rake_helper

### ISSUE THREAD

**Issue by eproulx-petalmd** [toptal/chewy#250]
Hi, could you require chewy/rake_helper in chewy.rb ? I would like to use the eager_load_chewy! method for a rake task that will update all indices documents based on a certain date. Looks like the reset_all but I dont want to reset everything juste update some documents.

Thanks

**Comment by pyromaniac** [comment]
well, I actually can, but somewhere in future. For now is it possible to require it directly in application?

**Comment by eproulx-petalmd** [comment]
I tried but can't find file
 require 'chewy/rake_helper'
LoadError: cannot load such file -- chewy/rake_helper

**Comment by pyromaniac** [comment]
Ok, just submit a PR then

**Comment by eproulx-petalmd** [comment]
alright :) thanks
