### ISSUE TITLE
Need example for filtering with ids

### ISSUE THREAD

**Issue by srkgupta** [toptal/chewy#254]
Currently Elasticsearch supports filtering records through ids column. 

https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-ids-filter.html

However when I try to add a filter like any of these, it throws error:
index.filter(ids: ["1","2","4"])
(or)
index.filter({"terms": {"id": ["1", "2","4"]}}
(or)
index.query({filtered: {filter: {ids: {values: ["1","2","4"]}}}})

I went through your examples and couldnt find any example explaining the ids query. Can you please add one example indicating the same.

**Comment by pyromaniac** [comment]
`index.filter({"terms": {"id": ["1", "2","4"]}}` should work actually. But try https://github.com/toptal/chewy/blob/master/lib/chewy/query.rb#L893

**Comment by pyromaniac** [comment]
Ah, the case is: there is only `_id` field, not `id`

**Comment by srkgupta** [comment]
Thanks for the pointer. The find method works like a charm. :+1: 

UsersIndex::User.find(42, 7, 3)
