### ISSUE TITLE
Pass variables in the block version

### ISSUE THREAD

**Issue by Linuus** [toptal/chewy#255]
Hi!
I have some troubles with variables in blocks.

```ruby
@tag_ids = [1,2,3]

# Works
SearchIndex.filter(terms: { "tags.id" => @tag_ids})
SearchIndex.filter { tags.id == [1,2,3] }

# Does not work
SearchIndex.filter { tags.id == @tag_ids }
```

I guess that is because the block is executed later, in another context.

Is there a way around this or do I just have to use this version?
`SearchIndex.filter(terms: { "tags.id" => @tag_ids})`

**Comment by pyromaniac** [comment]
`SearchIndex.filter { tags.id == o{@tag_ids} }`

**Comment by pyromaniac** [comment]
o means outer scope

**Comment by Linuus** [comment]
I see, thanks
