### ISSUE TITLE
How to achieve this query?

### ISSUE THREAD

**Issue by Linuus** [toptal/chewy#258]
Hi!

I'm having some issues to create the query that I need, perhaps someone can help me here.

What I have is `Article` and `BlogPost`. They both have tags indexed (nested).

```
tags: {
    include_in_all: true
    properties: {
        name: {
            include_in_all: true
            index: no
            type: string
            fields: {
                name.original: {
                    type: string
                }
                name.raw: {
                    index: not_analyzed
                    type: string
                }
                name.stemmed: {
                    analyzer: swedish_stemmer
                    type: string
                }
                name.partial: {
                    index_analyzer: partial
                    type: string
                }
            }
        }
```

Now I want to create a query, passing the names of the tags. I want it to return the documents with matching tags first (the more matching tags the higher score). Then it should return not matching documents, ordered by a date.

### Question 1
What is the appropriate way to do this? Can I create two filters, one which matches tag names and one which matches everything or something... and use a `bool` filter mode? Or is there a better way?

#### Question 2

I tried to use a terms filter on the tag names, like this
`MyIndex.filter(terms: { "article.tags.name.raw" => ["Tag1"] })`

But this returns nothing. Why?

When using ids it works:
`MyIndex.filter(terms: { "article.tags.id" => [1] })`

**Comment by Linuus** [comment]
Regarding Question 2:
It seems my index was weird. If I remove the "name." prefix in the field names it works.

```
tags: {
    include_in_all: true
    properties: {
        name: {
            include_in_all: true
            index: no
            type: string
            fields: {
                stemmed: {
                    analyzer: swedish_stemmer
                    type: string
                }
                original: {
                    type: string
                }
                raw: {
                    index: not_analyzed
                    type: string
                }
                partial: {
                    index_analyzer: partial
                    type: string
                }
            }
        }
        id: {
            include_in_all: true
            type: string
        }
    }
```

**Comment by pyromaniac** [comment]
Sorry, didn't answer, but did you find solution? As for the first question, I suppose custom_score would fit your requirements. Also for filters it is better to use `and` and `or` filters instead of `bool` since `bool` is differs slightly.
