### ISSUE TITLE
Indexing a Virtus model

### ISSUE THREAD

**Issue by dnd** [toptal/chewy#260]
I have some data coming from an API that I want to index that are defined as Virtus models. What would I need to do to be able to be able to index this information? Do I need to write my own adapter? If so, what is the minimum amount of functionality that I have to implement in it?

**Comment by pyromaniac** [comment]
Just use object adapter there, nothing else probably

**Comment by dnd** [comment]
How does that work when indexing by id, such as using the resque or sidekiq strategies? Those just send the ids to be imported, and then in the job call `import!` on the index, which calls `import` on the adapter/object, correct? I'm assuming I have to define my own `import` method to first find the object to be imported according to the API format?

**Comment by pyromaniac** [comment]
In case of plain objects strategies sends object itself

**Comment by dnd** [comment]
What would I need to implement to allow Chewy to only send the `id` to a background job, and have it load the object from the api when the job is being worked?

**Comment by pyromaniac** [comment]
Probably this background job only.

**Comment by dnd** [comment]
I'm having a go at writing my own adapter using the changes in master that make it easier to set adapters. Is there a release coming any time soon? It's been 4 months since the last one, and there's a lot of good stuff tied up in master right now.

**Comment by pyromaniac** [comment]
Yep, probably it is going to be soon
