### ISSUE TITLE
What is this warning during index reset? "Scoped order and limit are ignored, it's forced to be batch order and batch size"

### ISSUE THREAD

**Issue by eliduke** [toptal/chewy#261]
Running a full index reset on Heroku, I just started getting this warning output a couple times while it's reseting a couple different indexes.

```
Scoped order and limit are ignored, it's forced to be batch order and batch size
```

Any thoughts? Is it a problem? What does it mean? Is it something that I did?

**Comment by pyromaniac** [comment]
Just ignore it. It seems like you've passed as a default scope for type some scope with limit or order. I have to make this message a little bit more verbose.
