### ISSUE TITLE
Chewy not refreshing dynamic default_scope in production

### ISSUE THREAD

**Issue by Canifex** [toptal/chewy#263]
Chewy does not seem to refresh the (dynamic) default_scope in production before executing imports. This behaviour only occurs in newer versions, in 0.6.x everything works fine. Additionally, this behaviour only occurs in rails production environment, not in development.

Given I have such a model / index: 
```ruby
class Post < ActiveRecord::Base
  default_scope { where(site_id: Site.current_id) }
end


class PostsIndex < Chewy::Index
  define_type Post do
   ...
  end
end
```

Now ``Site.current_id`` is nil at the application start. If I call ``PostsIndex.import``, only the posts with ``site_id=nil`` would be imported. But if I change ``Site.current_id`` to any other value, ``PostsIndex.import`` still only selects posts with ``site_id=nil``. The inner ``@default_scope`` in the adapter (https://github.com/toptal/chewy/blob/master/lib/chewy/type/adapter/orm.rb#L7) never changes, calling ``cleanup_default_scope!`` (https://github.com/toptal/chewy/blob/master/lib/chewy/type/adapter/active_record.rb#L16) doesn't help either.

To repeat, this strange behaviour only occurs in versions > 0.6.x and only in production environment, which makes it very hard to notice.

**Comment by pyromaniac** [comment]
Sorry for not answering for too long, but you probably don't want to index only current site posts, you probably want to do `define_type Post.unscoped do` to index everything at once and then fetch posts for the current site only from index. Don't forget to index `site_id` to be able to do this.
