### ISSUE TITLE
Undefined method when calling Kaminari's page_entries_info on a Chewy query

### ISSUE THREAD

**Issue by aselder** [toptal/chewy#265]
I'm getting

```
undefined method `entry_name' for #<StudiesIndex::Study::Query:0x007fb53d2039e8>
```

when calling Kaminari's page_entries_info helper.

It seems like it would be pretty simple to infer that from the name of the model when creating the type.

I'll give it a shot creating a pull request.

**Comment by pyromaniac** [comment]
Any updates on this?

**Comment by zerosicks** [comment]
In case anyone else runs into this, solution is to explicitly declare the entry name:
```ruby
page_entries_info @users, entry_name: "user"
```
