### ISSUE TITLE
Default request_strategy

### ISSUE THREAD

**Issue by mkcode** [toptal/chewy#268]
Hi @pyromaniac,

Going through the Chewy config in my app, I noticed that I was not using any Async index updates perviously when I thought I was. This is due to Chewy always wrapping requests in the `atomic` strategy. I believe that I want to use an async strategy like `resque` or `active_job` in controllers as well.

Is there any reason why using async strategies in a controller is a bad idea?

If not, I would recommend either documenting `Chewy.request_strategy` in the README or possibly not pushing the `atomic` strategy if the current `Chewy.strategy` already inherits from `Atomic`?

relevent code here: https://github.com/toptal/chewy/blob/8cb6248ae11c5309b73cbdaff2bbb6b8862031e8/lib/chewy/railtie.rb#L16

Thanks for your feeback

**Comment by mkcode** [comment]
Put another way, the README suggests to me that setting `Chewy.strategy` in an initializer will apply to the controller request cycle, when it does not.

**Comment by pyromaniac** [comment]
Using async strategy is not a bad idea, but atomic is default just because it is available always. If you will do a PR with readme fixed - it would be awesome. Thanks.
