### ISSUE TITLE
Perform filter without filtered query

### ISSUE THREAD

**Issue by coatezy** [toptal/chewy#269]
Hey,

I'm trying to perform a filter but also return aggregations what should not be effected by the filter. A good example of what I am trying to archive can be seen in this post which they describe as the LinkedIn way of doing it.

http://substantial.com/blog/2013/01/16/building-faceted-search-with-elasticsearch/ 

```
{
  "query":{"match_all":{}}
  "filter":{
    "term":{"color":"red"}
  },
  "aggregations": {
    "colors": {
      "terms": {"field":"color"}
    }
  }
}
```

Is this possible?

Cheers
Tom

**Comment by pyromaniac** [comment]
Yeah, why not? Just use dsl.

**Comment by coatezy** [comment]
Hey @pyromaniac,

Do you have an example of how to do this? When I use the chewy dsl and apply any filters I seem to get a filtered query. I'm sure I'm doing something wrong :confused:.

**Comment by pyromaniac** [comment]
Ah, I've got the idea, actually this is quite old article, and I'm not quite sure, but this filter usage is deprecated  and you have to use post_filter instead.

**Comment by coatezy** [comment]
Correct. `post_filter` was exactly what I needed. Thanks!

https://github.com/toptal/chewy/blob/ef0fab43cbd302997fcc2b2ae3b400ff97687f4c/lib/chewy/query.rb#L696
