### ISSUE TITLE
How do you turn off debug logging

### ISSUE THREAD

**Issue by Ch4s3** [toptal/chewy#270]
Almost every 2nd line of my stack traces is `DEBUG: Chewy strategies stack:` and I'd like to turn off debug logging, but I can't figure out how.

**Comment by pyromaniac** [comment]
`Chewy.logger.level = Logger::INFO`

**Comment by pyromaniac** [comment]
But probably it will change Rails.logger level as well, so maybe you have to assign another `Chewy.logger` instance

**Comment by Ch4s3** [comment]
Yeah, that did change the Rails logger level as well. It would be nice if Chewy's logging could be set independent of Rails.logger.

**Comment by Ch4s3** [comment]
That said, using the following:
```ruby
Chewy.logger = Logger.new(STDOUT)
Chewy.logger.level = Logger::INFO
```

I'm able to get what I wanted.
