### ISSUE TITLE
Importing to amazon elastic search service

### ISSUE THREAD

**Issue by drnluz** [toptal/chewy#271]
Hello. I'm trying to import a model to the amazon elasticsearch service but I'm getting the following error:

`Elasticsearch::Transport::Transport::Errors::Forbidden: [403] {"message":"When Content-Type:application/x-www-form-urlencoded, URL cannot include query-string parameters (after '?'): '/all/factory/_bulk?refresh=false'"}`

Digging a little I found that amazon ES service does not accept query parameters.
Is there a way to run `MyIndex.reset!` without sending `refresh` as a query parameter?

**Comment by pyromaniac** [comment]
Well, it is quite hardcoded here: https://github.com/toptal/chewy/blob/ef0fab43cbd302997fcc2b2ae3b400ff97687f4c/lib/chewy/type/import.rb#L22
But you may send a patch of de-hardcoding :) Like, in case of `refresh: false` don't add anything.

**Comment by pyromaniac** [comment]
I didn't expect such a behavior, Amazon engineers are strange guys, ES itself doesn't have such a strict rules

**Comment by yurifrl** [comment]
Hy @drnluz , any updates on this issue?

**Comment by feymartynov** [comment]
Had the same issue with AWS. Fixed with explicitly specifying Content-Type header in `chewy.yml`:
```yaml
production:
  host: 'some-host.es.amazonaws.com:80'
  transport_options:
    headers:
      content_type: 'application/json'
```

**Comment by pyromaniac** [comment]
Perfect, thanks for the solution!
