### ISSUE TITLE
Index importing fails with default scope

### ISSUE THREAD

**Issue by levent** [toptal/chewy#273]
This bug affects the latest 0.8.2

When using postgresql and there is an ActiveRecord default scope you get a statement invalid error

```
PG::InvalidColumnReference: ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list LINE 1: ...es" WHERE "items"."user_id" = $1 ORDER BY "item... ^ : SELECT DISTINCT "items"."id" FROM "items" WHERE "items"."user_id" = $1 ORDER BY "items"."created_at" DESC
```

Here are my objects:

```ruby
class User < ActiveRecord::Base
  update_index('app#user') { self }
  update_index('app#item') { items }

  has_many :items
end

class Item < ActiveRecord::Base
  update_index('app#item') { self }

  belongs_to :user
  default_scope { order(created_at: :desc) }
end
```

The exception is being raised here:
https://github.com/toptal/chewy/blob/ef0fab43cbd302997fcc2b2ae3b400ff97687f4c/lib/chewy/type/adapter/active_record.rb#L40

**Comment by pyromaniac** [comment]
Try to use `Item.unscoped` in the type definition. However this is strange, ordering should be cleaned up here: https://github.com/toptal/chewy/blob/ef0fab43cbd302997fcc2b2ae3b400ff97687f4c/lib/chewy/type/adapter/active_record.rb#L22, probably default scopes works somehow different.

**Comment by levent** [comment]
Thanks. This is a workaround, but still doesn't seem like the ideal solution?

```ruby
class User < ActiveRecord::Base
  update_index('app#item') { items.unscoped }
end
```

**Comment by pyromaniac** [comment]
Yeah, I have to investigate this case once. But why don't you use `Item.unscoped` in `define_type` statement? It would propagate on every `update_index` then

**Comment by levent** [comment]
I tried but it didn't work.
I have a couple of models being indexed. I'll call them Item1 and Item2.
I tried the following but had the same error (maybe because of the includes or where clauses?:

```ruby
Item1.unscoped.where(processed: true).includes(:user)
Item2.unscoped.includes(:item1, :user)
```

**Comment by pyromaniac** [comment]
Ok, if workaround works - that's great. I'll try to find a time to prepare a proper fix.

**Comment by levent** [comment]
@pyromaniac just a heads up that this workaround seems to cause other issues. Basically when a record is destroyed (let's assume a User) then it seems to have to do a complete AppIndex.reset! which times out on Heroku for example and is of course very risky with a high traffic site and large index like ours.

**Comment by pyromaniac** [comment]
Oh wow, try to use `Item.reorder(nil)` then in `define_type`

**Comment by levent** [comment]
@pyromaniac was this issue resolved then?

**Comment by pyromaniac** [comment]
Hm, no, but I've decided that it is your setup-related issue. Also did my last proposal work?

**Comment by levent** [comment]
Ok. I'll have to do some further investigation and get back to you.

**Comment by pyromaniac** [comment]
Thanks

**Comment by levent** [comment]
Awesome project by the way!

**Comment by pyromaniac** [comment]
Thanks for using it, let's make it better!

**Comment by jedschneider** [comment]
Hey for big indexes, I think we were able to get this working by unscoping, but then rescoping to the proper context:

```
class BaseLocation < ActiveRecord::Base
  has_many :establishments
  update_index('establishments#establishment') {
    Establishment.unscoped.where(base_location_id: self.id)
  }
end

class Establishment < ActiveRecord::Base
  belongs_to :base_location
  update_index('establishments#establishment') { self }
  default_scope -> { order(:name) }
end
```
