### ISSUE TITLE
delete_if, proc batched_objects

### ISSUE THREAD

**Issue by eproulx-petalmd** [toptal/chewy#274]
Hi,

Is there a way with the delete_if option to receive the batched objects instead of just a single one. In my case, for every objects in the batch, I need to join a view in the database to make sure it still exists.

It created N+1 queries :(

Thanks

**Comment by pyromaniac** [comment]
You may provide `joins` statement to the default `define_type` scope, it should help

**Comment by eproulx-petalmd** [comment]
Unfortunately, I can’t. Since define_type scope is sorted, I can’t join the view. It takes too much time sorting the view everytime :(

**Comment by pyromaniac** [comment]
What do you mean by sorted? Sorting is ignored for define_type scope and even cleaned up, so it doesn't make sense to provide sorting there

**Comment by eproulx-petalmd** [comment]
Sorry my mistake, haven’t expressed myself clearly.

When importing there’s an actual reordering:
def import_scope(scope, batch_size
	scope.reorder(target_id.asc).limit(batch_size)
That’s the sorting or “ordering" I should have said that I was talking about. The reorder affects the join with our view.

Thanks.

**Comment by pyromaniac** [comment]
Are you sure? It is simple ordering by id, it should not affect query too much

**Comment by eproulx-petalmd** [comment]
Our view isn’t sorted by id. If my join was a simple SQL table, there would be no problem, but in my case, it’s a SQL view which a no actual clustered_index for it :(

I like the delete_if option, but its’s not working with the batch only with a single object. The best scenario would be to receive a batch of ids like crutches and the result will be the ids that need to be deleted from the index.

Thanks

**Comment by pyromaniac** [comment]
Hope crutches will help here
