### ISSUE TITLE
script fields not defined for top level index

### ISSUE THREAD

**Issue by mlchai** [toptal/chewy#275]
When I do MyIndex.script_fields it says the method isn't defined. I tried following the example in the README but it doesn't work. When I do MyIndex::Something.script_fields it just returns nil so it's defined there, and when I actually use the script_fields it just doesn't seem to work. Any insight would be greatly appreciated, thanks!

**Comment by pyromaniac** [comment]
Try `MyIndex.all.script_fields` and `MyIndex::Something.all.script_fields` as a workaround, it seems like this method was not defined on index or type level

**Comment by mlchai** [comment]
That seemed to work, thanks!
