### ISSUE TITLE
Rails class method returns nil value inside crutch

### ISSUE THREAD

**Issue by rtcoms** [toptal/chewy#278]
I am using crutch to optimize elasticsearch indexing and having issue with crutch.

crutch is like 

```
crutch :scheme_for_loans do |collection|
    Loan.scheme_mapping_for_milaap_group_by_loan(collection.map(&:id))
end
```

here collection and collection.map(&:id) are getting proper value , but

```
Loan.scheme_mapping_for_milaap_group_by_loan(collection.map(&:id))
```

returns nil. Although same statement returns proper value in rails console

Above method is like , if that helps 

```
def self.scheme_mapping_for_milaap_group_by_loan(loan_ids)
    loan_and_scheme_mapping = {}
    Scheme.running.source_scope_for(Scheme.source_scopes[:source_scope_milaap], nil).each do |s|
      next if !s.applicable_for?(Scheme::SCHEME_SCOPE_LOAN)
      loan_ids_applicable_for_match = s.projects.flat_map(&:loans).map(&:id).uniq
      loan_ids.each do |loan_id|
        loan_and_scheme_mapping[loan_id] = s if loan_ids_applicable_for_match.include?(loan_id)
      end
    end
    loan_and_scheme_mapping
 end
```

**Comment by pyromaniac** [comment]
Wait, if `collection.map(&:id)` returns result correctly and `Loan.scheme_mapping_for_milaap_group_by_loan(collection.map(&:id))` doesn't then problem is in `Loan.scheme_mapping_for_milaap_group_by_loan`. It probably doesn't work correct in the crutch scope, so you have to debug it and take a look what's changed there

**Comment by rtcoms** [comment]
I tried to debug it by putting puts statements inside Loan.scheme_mapping_for_milaap_group_by_loan method . But looks like it's not even entering inside that method and directly returns nil as those puts statements never gets printed

**Comment by pyromaniac** [comment]
What will be printed if:
```ruby
crutch :scheme_for_loans do |collection|
  p Loan.scheme_mapping_for_milaap_group_by_loan(p(collection.map(&:id)))
end
```

**Comment by rtcoms** [comment]
It doesn't print anything . Because it's nil . verified by 

```
crutch :scheme_for_loans do |collection|
     p (Loan.scheme_mapping_for_milaap_group_by_loan(collection.map(&:id))).class
end
```

which prints NilClass

**Comment by pyromaniac** [comment]
you forgot to print `p(collection.map(&:id))`

**Comment by rtcoms** [comment]
Well, there is not issue with collection.map(&:id) . It returns proper array of ids. 

[5, 9294, 9295, 9297......, 10213]

and If take that array and in console

```
Loan.scheme_mapping_for_milaap_group_by_loan(array_of_loan_ids)
```

It gives me a proper hash.  The same statement inside crutch returns nil with same array of ids . 

I can confirm that inside crutch this function is not being called .

**Comment by pyromaniac** [comment]
Wait, if `p (Loan.scheme_mapping_for_milaap_group_by_loan(collection.map(&:id))).class` returns NilClass, then function have been called definitely, but returned nil and something with the function then

**Comment by rtcoms** [comment]
No, otherwise puts statements inside Loan.scheme_mapping_for_milaap_group_by_loan(array_of_loan_ids) would have been printed. 


I tried using another function which is just a scope of active record class 

```
crutch :scheme_for_loans do |collection|
        puts "111111111111111"
        puts Loan.not_fully_funded
        puts "2222222222222"
end
```

the output I get here is 

```
111111111111111

2222222222222
```

In console If I do 

```
Loan.not_fully_funded.count => returns 123
```

**Comment by pyromaniac** [comment]
Maybe you have a tricky code that redefines this function somehow, have no idea frankly. It definitely look like the function was called, but return nil

**Comment by rtcoms** [comment]
I think this is a bug . Even if I put 

```
crutch :scheme_for_loans do |collection|
        puts "111111111111111"
        puts Loan.count
        puts "2222222222222"
end
```

It returns 

```
111111111111111

2222222222222
```

Now Loan.count,  is Active record method , and I'm sure that we have not overridden this method anywhere .

**Comment by rtcoms** [comment]
Interestingly same crutch code works fine in another Index

**Comment by rtcoms** [comment]
Looks like I found a pattern for this issue :

```
class LoansIndex < BaseIndex
  if ActiveRecord::Base.connection.table_exists?('loans') && Loan.count > 0

    define_type Loan.visible.not_fully_funded.limit(2) do
      crutch :test do |collection|
        puts "stories_count: #{MilaapStory.count}"
        puts "loans_count: #{Loan.count}"
        puts "projects_count: #{Project.count}"
    end
end
```

prints 

```
stories_count: 99
loans_count: 
projects_count: 1016
```

and

```
class ProjectsIndex < BaseIndex
  if ActiveRecord::Base.connection.table_exists?('projects') && Project.count > 0
    define_type Project.all do
      crutch :test do |collection|
        puts "stories_count: #{MilaapStory.count}"
        puts "loans_count: #{Loan.count}"
        puts "projects_count: #{Project.count}"
    end
end
```

prints

```
stories_count: 99
loans_count: 9777
projects_count: 
```

Does it mean that we can't use the method from the class for which index is created ?

**Comment by pyromaniac** [comment]
That is because ProjectsIndex::Project exists and you are inside of it, `::Project.count` would work there
