### ISSUE TITLE
Trying to implement nGram filter

### ISSUE THREAD

**Issue by sigoulder** [toptal/chewy#279]
I know it must be possible to do define an nGram type tokenizer within a Chewy index. This is the syntax I'm using, however to no avail:

```
settings analysis: {
        analyzer: {
            name: {
                tokenizer: "ngram_tokenizer",
                filter: ['lowercase', 'ngram_filter']
            }
        },
        tokenizer: {
            name: {
                type: "nGram",
                min_gram: "3",
                max_gram: "8"
            }
        }
    }
```

Can you point me in the right direction please.

Thank you

**Comment by janpieper** [comment]
You've defined a tokenizer named `name` but you are using `ngram_tokenizer` in you analyzer. You need to change the tokenizer name from `name` to `ngram_tokenizer`.

```ruby
  settings analysis: {
      analyzer: {
          name: {
              tokenizer: "ngram_tokenizer",
              filter: ['lowercase', 'ngram_filter']
          }
      },
      tokenizer: {
          ngram_tokenizer: {     # <-----
              type: "nGram",
              min_gram: "3",
              max_gram: "8"
          }
      }
  }
```

To use the analyzer, you need to specify it for each field:

```ruby
define_type ... do
  # ...

  field :name,
    analyzer: "name"

  # ...
end
```

I don't know if `name` is the best name for your analyzer, but this is another thing :smile:
