### ISSUE TITLE
searching on certain fields returns no matches

### ISSUE THREAD

**Issue by mastermike14** [toptal/chewy#283]
I have Chewy setup with very basic search index defined

    class SearchIndex < Chewy::Index

    define_type Post do 
       field :title 
       field :description
       field :rating
       field :published_date 
   end 

Searching by rating I can get matches. Searching on title, even when using exact title I get no matches returned

(term: {title: 'yada..'}) nothing

 (term: {id: '2'}) bam, match!

Search by the record's ID though and I get a match. What am I missing that is causing this issue?

**Comment by pyromaniac** [comment]
Are you using filters for searching or queries? This is about ES knowledge, not chewy actually. Read how do ES works carefully
