### ISSUE TITLE
How to ensure that :resque is running?

### ISSUE THREAD

**Issue by vuhailuyen1991** [toptal/chewy#285]
Hi all, I tried to switch the trategy to :resque. Here is my code in `chewy.rb`:

```
Chewy::Config.instance.request_strategy = :resque
```

How can I ensure that the queue at: https://github.com/toptal/chewy/blob/master/lib/chewy/strategy/resque.rb

is working properly?

**Comment by pyromaniac** [comment]
Better use `Chewy.request_strategy = :resque`

Well, the same way as you are doing for any other job. You can try to do a request and take a look on resque log, there should be a new job executed. Also maybe there will be chewy index entries in the log. After that you can try to search and make sure that changes are applied to the index.

**Comment by vuhailuyen1991** [comment]
Yes, i start the queue: 
QUEUE=chewy bundle exec rake resque:work

and it works, thanks @pyromaniac

**Comment by pyromaniac** [comment]
Awesome :)
