### ISSUE TITLE
Search conflicting with Ransack Gem (used by active_admin)

### ISSUE THREAD

**Issue by ACPK** [toptal/chewy#287]
I'm not able to perform a search due to: https://github.com/elastic/elasticsearch-rails/issues/96

**Comment by pyromaniac** [comment]
but how is it possible? Chewy doesn't use elasticsearch-rails or elasticsearch-model gems at all

**Comment by ACPK** [comment]
@pyromaniac - Hitting the same issue. When I remove active_admin, the error goes away.

**Comment by igorkasyanchuk** [comment]
@ACPK what if you will try to use `User.ransack` for searching instead of `User.search` ?
