### ISSUE TITLE
Slow indexing with Ruby Chewy gem via ActiveRecord

### ISSUE THREAD

**Issue by yang-rifiniti** [toptal/chewy#289]
We use ES for analytics but we seem to have some indexing performance issue, and here are some details

* We have a MySQL database that stores the processed data
* We use a Ruby gem called Chewy (DSL) made by Toptal to interact with ElasticSearch
* We index with the Chewy gem to import data from MySQL to ElasticSearch

The issue we are having here is slow indexing performance. Our current indexing is about 5000 MySQL entries per second and it sounds like we are way behind. At this point we are not 100% sure whether it's the MySQL/ActiveRecord/Chewy or ElasticSearch that is the bottleneck. Some diagnostics and profiling we did include:

* Running iotop to monitor the disk read/write. It's usually 1MB/s read for a few seconds then a burst of 10MB/s disk write. This makes me think that it could be the read stream from MySQL that's slowing things down.
* Separate the read and write stream by connecting Chewy to another MySQL server that is isolated from the ElasticSearch indexing cluster. There is improvement but it was not very significant. It probably went up by 2-3K records/second but still slow.

Since there are many pieces in this indexing process we'd appreciate some help or insights into why the indexing is slow or maybe some pointers about diagnosing the problem. 

Some configs about ElasticSearch:

    bootstrap.mlockall: true
    script.groovy.sandbox.enabled: true
    action.disable_delete_all_indices: true.
    discovery.zen.ping.multicast.enabled: false

    # Heap size defaults to 256m min, 1g max
    # Set ES_HEAP_SIZE to 50% of available RAM, but no more than 31g
    ES_HEAP_SIZE=8g

    # Maximum number of open files
    MAX_OPEN_FILES=65535

    # Maximum amount of locked memory
    MAX_LOCKED_MEMORY=unlimited

    # Maximum number of VMA (Virtual Memory Areas) a process can own
    MAX_MAP_COUNT=262144

Some MySQL configs:

    # This will be passed to all mysql clients
    # It has been reported that passwords should be enclosed with ticks/quotes
    # escpecially if they contain "#" chars...
    # Remember to edit /etc/mysql/debian.cnf when changing the socket location.
    [client]
    port            = 63306
    socket          = /var/run/mysqld/mysqld.sock

    # Here is entries for some specific programs
    # The following values assume you have at least 32M ram

    # This was formally known as [safe_mysqld]. Both versions are currently parsed.
    [mysqld_safe]
    socket          = /var/run/mysqld/mysqld.sock
    nice            = 0

    [mysqld]
    #
    # * Basic Settings
    #
    user            = mysql
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    port            = 63306
    basedir         = /usr
    datadir         = /var/lib/mysql
    tmpdir          = /tmp
    lc-messages-dir = /usr/share/mysql
    skip-external-locking

    # Instead of skip-networking the default is now to listen only on
    # localhost which is more compatible and is not less secure.
    bind-address            = 127.0.0.1
    #
    # * Fine Tuning
    #
    key_buffer              = 128M
    max_allowed_packet      = 128M
    thread_stack            = 1536K
    thread_cache_size       = 64

    # * Query Cache Configuration
    #
    query_cache_limit       = 1M
    query_cache_size        = 16M

    [mysqldump]
    quick
    quote-names
    max_allowed_packet      = 256M

    [mysql]
    #no-auto-rehash # faster start of mysql but no tab completition

    [isamchk]
    key_buffer              = 16M

Environment information:
* 3 nodes in the ES cluster with 16GB RAM 384GB SSD and Quad Core Intel Xeon CPU
* Ubuntu Linux 14.04
* ElasticSearch 1.4.4 (We have some dependency issues so haven't upgraded to 2.0+)
* Ruby 2.2.2, Rails 4.2, latest Chewy gem

Chewy model example:

    define_type ::TypeName.includes(:type_table_from_mysql) do
      field :book_id
      field :entry_time, type: 'date', value: -> { timestamp * 1000 }
      field :in_stock, type: 'boolean', value: -> (o) { ChewyHelper.in_stock?(o) } 
      field :price, type: 'float'
      field :day, type: 'integer', value: -> { Time.at(timestamp).utc.yday }
      field :hour, type: 'integer', value: -> { Time.at(timestamp).utc.hour }
      field :date, type: 'integer', value: -> { timestamp / (24*60*60) }
    end

**Comment by pyromaniac** [comment]
Well, unfortunately I've got no idea what's going on, but on your place I would try to write a simple script witch fetches mysql records in batches, manually forms bulk index request body and pushes it to ES. So you will be able to compare chewy performance with pure ruby stuff. And then continue investigation depending on the results

**Comment by kozze89** [comment]
For anyone interested, I first tried with Chewy's "crutches". Barely any speed increase although it was making batch queries, which makes me think my DB wasn't the bottleneck.
Then tried to just "build" the data myself and pass it to `Chewy.client.bulk` method. This was ~12x faster, than using chewy's `import`. I guess you lose nice stuff like deleting indexes that no longer exist etc, that (I think) Chewy does for you. But doing it manually at least gave me a chance to build it from the ground up real fast and I can now use Chewy to do updates.

Would be nice if import had a better way to parallellize the work. I kept looking at the sidekiq strategy, but that only seems to work for a block of code. Not sure, but it seemed like it would wait until all indexes are built before posting to ES when importing which doesn't seem like a good idea.

**Comment by pyromaniac** [comment]
Interesting, thanks, I'll try to find a time to take a look on import performance. Also take a look on this PR https://github.com/toptal/chewy/pull/321 maybe it will be helpful

**Comment by pyromaniac** [comment]
Hey, could you try to use https://github.com/toptal/chewy/issues/346#issuecomment-198859183 solution? And tell me was it helpful or not.

**Comment by dang-hoang-hieu** [comment]
@kozze89 
Hi, there is the same problem in my import application, I intend to try to write a script to manually build the data, but I am kind of busy now. Could you send me your code of buiding data thanks a lot

**Comment by yl5682** [comment]
I am gonna try @dang-hoang-hieu 's thread and a few other options mentioned above and report back here. Thanks for the updates so far.

**Comment by yang-rifiniti** [comment]
Hi @pyromaniac and @dang-hoang-hieu  thanks for your inputs on this thread. I finally got some time to actually try different strategies out and here are some reports:

I created a profiling environment to test different strategies:
- Always import 30000 records on the BooksIndex::Book
- Every time after an import will delete the entire index.

The machine settings are the same as posted in the very first thread on top.

**First run without WitchCraft and 0.82 version of chewy, no other options:**
```
WifiIndex::Occupancy Import (28896.6ms) {:index=>30000} 
This pass took 28.984829957 seconds
```


**tried witchcraft and 0.8.4 this is like installing a twin turbo to your engine:**

```
WifiIndex::Occupancy Import (16169.6ms) {:index=>30000} 
This pass took 16.313680691 seconds
```

**with replication set to async:**
```
WifiIndex::Occupancy Import (16398.2ms) {:index=>30000} 
This pass took 16.50799948 seconds
```

**with bulk_size set to 10 MB:**
```
WifiIndex::Occupancy Import (18619.4ms) {:index=>30000} 
This pass took 18.719451124 seconds
```

**with bulk_size set to 100 MB:**
```
WifiIndex::Occupancy Import (17861.9ms) {:index=>30000} 
This pass took 17.936323542 seconds
```

**turn bulk_size back off to confirm:**
```
WifiIndex::Occupancy Import (16221.1ms) {:index=>30000} 
This pass took 16.250417875 seconds
```

**with refresh index after import disabled (however I am not sure if we'd still need to do an index refresh; sounds like we need to, but if this could speed up the indexing and flushing out the index all at once doesn't take too much it might be helpful. This is not improving too much so will leave it as is for now)**

```
WifiIndex::Occupancy Import (15457.3ms) {:index=>30000} 
This pass took 15.547787851 seconds
```

**with batch_size set to 30000 (which is the total record I put in the profile):**
```
WifiIndex::Occupancy Import (15928.1ms) {:index=>30000} 
This pass took 16.032695959 seconds
```


**Fun discovery:**

a. the batch read from MySQL seemed to take less than a second initially - seems like all records were very quickly loaded into mem (iotop confirmed read at first and it was a burst, followed by 0 reads) 
b. in the 15 seconds or so, after the MySQL read, there is almost no disk write until by the end there is a burst write of about 15MB/s 
c. a&b makes me think it really is chewy/elasticsearch that is using the CPU and mem to do the indexing. If we'd like to improve anything it should be in this area

**Next try sidekiq and hopefully we can scale horizontally like it should be:**
So scheduled the job with Sidekiq and got this result:

```
2016-03-28T02:29:27.568Z 10579 TID-w57ss Chewy::Strategy::Sidekiq::Worker JID-6b9714c96015715bf04e3c09 INFO: start 
2016-03-28T02:29:42.974Z 10579 TID-w57ss Chewy::Strategy::Sidekiq::Worker JID-6b9714c96015715bf04e3c09 INFO: done: 15.406 sec
```

Not impressive. Looking into more options with sidekiq


**Tried to schedule 6 jobs to run 1..30000, 30001..60000, etc.**

```
2016-03-28T04:10:17.536Z 8143 TID-1jjmcc Chewy::Strategy::Sidekiq::Worker JID-c69ec2284dafc81c906ec968 INFO: done: 94.38 sec 
2016-03-28T04:10:17.571Z 8143 TID-1jjnn0 Chewy::Strategy::Sidekiq::Worker JID-4e01c53e7bfd12fced8fd667 INFO: done: 94.328 sec 
2016-03-28T04:10:19.868Z 8143 TID-1jjllo Chewy::Strategy::Sidekiq::Worker JID-f086687a88034fc57d694164 INFO: done: 96.614 sec 
2016-03-28T04:10:30.972Z 8143 TID-addfo Chewy::Strategy::Sidekiq::Worker JID-8fe04022bcccf118dd97d2e3 INFO: done: 97.144 sec 
2016-03-28T04:10:32.193Z 8143 TID-aeu4c Chewy::Strategy::Sidekiq::Worker JID-e1e1125bac72b42427ef3396 INFO: done: 98.344 sec 
2016-03-28T04:10:36.815Z 8143 TID-1jhf5s Chewy::Strategy::Sidekiq::Worker JID-5dd9dc9aa18ea9da594f8810 INFO: done: 75.69 sec
```
The longest job took 98 seconds so that's 98 / 6 ~= 16 second / job

So that basically means there isn't too much concurrency going on here. :(

**QUESTIONS**
So I wonder if I used sidekiq right:

```
Chewy::Strategy::Sidekiq::Worker.perform_async("BooksIndex::Book", [*1..30000])
```

Second question, what are some of the problems that you guys see can be limiting the indexing performance?

Any input would be greatly appreciated and helpful! Thx!

**Comment by dang-hoang-hieu** [comment]
@yang-rifiniti 
1. You should try other options of batch_size, for me:
```
100 4  7.129461
500 4  2.86017255
1000 4  2.5480937999999997
1500 4  2.144869116666667
2000 4  2.1578910374999998
4000 4  2.113104736111111
10000 4  3.2175962625000003
100 6  7.472030833333334
500 6  2.8385000000000002
1000 6  2.3627573333333336
1500 6  2.1524820222222223
2000 6  2.026925375
4000 6  1.9366167041666666
10000 6  2.0879659150000003
5000 6  2.532585346666667
6000 6  4.464494141666667
7000 6  1.8818611911111112
8000 6  1.841594475
9000 6  1.7835248933333332
10000 6  2.1051081116666666
11000 6  1.9825957444444444
12000 6  2.1013876277777777
```
It turned out that 9k with 6 processes took 1.78 hours 
2. If you try sidekiq, you can use multi-process like with 4 processes, you create 4 new terminal and then run 4 sidekiq instance with thread = 1 (you can see in sidekiq web 4 processes with 4 threads)
3. Or you can spawn process directly from code
I will update code spawning process later :)

**Comment by yang-rifiniti** [comment]
Hey @dang-hoang-hieu thx for the quick response. I figured out the big picture idea of sidekiq but since I am still pretty new to it if you can share w me the code (thx in advance for willing to share the spawning process too!), that'd be very very helpful!

**Comment by dang-hoang-hieu** [comment]
yep
1. for sidekiq, you create a new ternimal tab, run sidekiq instance with thread = 1. Then create another terminal tab, run sidekiq instance with thread = 1, each tab is a process
2. code for spawn, rake task:
```
namespace :reindex do
  task candidate: :environment do
    logger = ActiveSupport::Logger.new("log/reindex.log")
    total_doc = 0
    count = 0
    start = Time.now
    Candidate.find_in_batches(batch_size: ENV["BATCH_SIZE"].to_i) do |candidates|
      pid = fork {
        CandidatesIndex::Candidate.import candidates, suffix: start.to_i
      }
      count += 1
      if count == ENV["POOL_SIZE"].to_i
        Process.waitall
        elapsed = Time.now - start
        total_doc += ENV["POOL_SIZE"].to_i * ENV["BATCH_SIZE"].to_i
        log = "process: #{total_doc} after #{elapsed / 60} minutes"
        logger.info log
        puts log
        count = 0
        break if ENV["TEST"]
      end
    end
    logger.close
  end
end
```
I run
`bundle exec rake reindex:candidate POOL_SIZE=4 BATCH_SIZE=9000`

**Comment by pyromaniac** [comment]
Well, I personally would prefer Chewy::Strategy::Sidekiq::Worker.perform_async("BooksIndex::Book", candidates) instead of forking. But yeah, a kind of :)

**Comment by yang-rifiniti** [comment]
@pyromaniac thanks for your hint. I wonder what the difference is between @dang-hoang-hieu 's approach and the perform_async approach? Is the perform_async a wrapper for the same thing as @dang-hoang-hieu wrote right above?

I tried the perform_async but didn't see indexing improvement (about 2K records/s) but w @dang-hoang-hieu 's method I got a solid 4K records/s which is a bless for me. Could it be when I use the perform_async I didn't set up some threading params right or?

**ES 2.x Support**
@pyromaniac Wonder if the latest chewy gem supports 2.x and if it is not currently supported, is it on the road map? I spoke w ES people in their Chicago office before and they recommended 2.x for stability and added features but not sure if chewy will support. Any thoughts or plans would be helpful.

** data stability **
So in our use case we do a full indexing by doing a BooksIndex.reset! and if everything goes through in one pass the data is usually very solid. However if we delete one period of data (e.g. 2013-2014 data entries), and reindex some other periods of time (2013/05 - 2014/01) then sometimes the queries would fail with random errors (such as parsing error, out of memory, etc.) Wonder what could be causing that if you can offer any pointers. We are still on ES 1.4.4, could that be the problem? Any best practice kind of advice would be greatly appreciated!

**Comment by yang-rifiniti** [comment]
Reporting back some updates here:

With a pretty beefy machine I've got:

POOL_SIZE=4 BATCH_SIZE=9000; 5769 records / s 
POOL_SIZE=9 BATCH_SIZE=9000; 10242 records / s 
POOL_SIZE=13 BATCH_SIZE=9000; 11470 records / s

I think tweaking the numbers can potentially make it even faster as I still occasionally see 50% on all cores CPU time.

**Comment by pyromaniac** [comment]
The difference is that you are putting all the records in one job: `Chewy::Strategy::Sidekiq::Worker.perform_async("BooksIndex::Book", [*1..30000])`, but you should do it like `Chewy::Strategy::Sidekiq::Worker.perform_async("BooksIndex::Book", [*1..1000]); Chewy::Strategy::Sidekiq::Worker.perform_async("BooksIndex::Book", [*1000..2000])`. Only in this case it will work as expected.

Chewy supports 2.0, but still uses deprecated features. I'm going to work on this definitely.

As for data stability would be better to post errors themselves. Also upgrade to 1.7.5.

**Comment by yang-rifiniti** [comment]
@pyromaniac right that makes perfect sense. thx for the quick update!

**Comment by dang-hoang-hieu** [comment]
@yang-rifiniti (y) 
you can try more processes to get the best performance
my server only has 6 cores, it works best at 10 processes :)

**Comment by yang-rifiniti** [comment]
Yep we did a 12 core w 32GB ram and 24 threads; close to 15K records/s never been this happy!
