### ISSUE TITLE
Upgrade to ElasticSearch 2

### ISSUE THREAD

**Issue by RoxasShadow** [toptal/chewy#291]
I upgraded ElasticSearch from 1.7 to 2.1, but now one of my indexes is broken when using `index_analyzer

*index broken by ES v2*
```ruby
Chewy.analyzer :autocomplete,
  type: 'custom',
  tokenizer: 'standard',
  filter: %w(lowercase autocomplete_filter)

Chewy.filter :autocomplete_filter,
  type: 'edge_ngram',
  min_gram: 1,
  max_gram: 20

class CompaniesIndex < Chewy::Index
  settings analysis: {
    analyzer: [:autocomplete]
  }

  define_type Company do
    field :name, index_analyzer: 'autocomplete', search_analyzer: 'standard'
  end
end

```

*ES version*
> $ elasticsearch -version
Version: 2.1.0, Build: 72cd1f1/2015-11-18T22:40:03Z, JVM: 1.8.0_66

*Output*
>     Elasticsearch::Transport::Transport::Errors::BadRequest:
       [400] {"error":{"root_cause":[{"type":"mapper_parsing_exception","reason":"analyzer on field [name] must be set when search_analyzer is set"}],"type":"mapper_parsing_exception","reason":"Failed to parse mapping [company]: analyzer on field [name] must be set when search_analyzer is set","caused_by":{"type":"mapper_parsing_exception","reason":"analyzer on field [name] must be set when search_analyzer is set"}},"status":400}

Since I noticed https://github.com/toptal/chewy/blob/master/.travis.yml#L42, I wonder if newer versions of ElasticSearch are actually supported by you. Thanks.

**Comment by pyromaniac** [comment]
Unfortunately Chewy doesn't support 2.0 yet, there are a lot of incompatible changes.

**Comment by RoxasShadow** [comment]
@pyromaniac I see, so I'm going to downgrade it. I hope it will be supported soon. Thanks!

**Comment by pyromaniac** [comment]
Hope so as well

**Comment by sergeygaychuk** [comment]
@RoxasShadow Can you check it with [that](https://github.com/toptal/chewy/pull/297) PR

**Comment by RoxasShadow** [comment]
@sergeygaychuk just did it, that index still doesn't work. The output message is the same. 

FYI Gemfile
>>># ElasticSearch
gem 'chewy', github: 'sergeygaychuk/chewy', branch: 'v2.x'
gem 'elasticsearch-extensions'

**Comment by pyromaniac** [comment]
oh, got in now, the reason seems to be in `field :name, index_analyzer: 'autocomplete', search_analyzer: 'standard'`, there is no index_analyzer option anymore in ES https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_analyzer_mappings

**Comment by RoxasShadow** [comment]
Oh, I see @pyromaniac. With `field :name, analyzer: 'autocomplete'` it works indeed. I think this should be enough or equivalent to the original line at this point.

Thanks a lot for your help!
