### ISSUE TITLE
Upgrading from 0.6.2 to 0.8.2

### ISSUE THREAD

**Issue by sardaukar** [toptal/chewy#292]
I've upgraded my gem, and added `require 'chewy/rspec'` and `Chewy.strategy(:bypass)` in a `before(:suite)` block to my rails_helper, but I still get errors about unset strategies. Example:

```
Failure/Error: project = create(:project, location: resort)
     Chewy::UndefinedUpdateStrategy:
       Index update strategy is undefined in current context.
       Please wrap your code with `Chewy.strategy(:strategy_name) block.`
```
(I'm using Factory Girl) What am I missing?

**Comment by pyromaniac** [comment]
Are you sure `Chewy.strategy(:bypass)` is executed?

**Comment by sardaukar** [comment]
I'm sure it's in the rails_helper, and that file is being read.

**Comment by pyromaniac** [comment]
Then you probably have to debug this. Really strange stuff. Also there is info output in logs about strategy, maybe it will be helpful

**Comment by PepperTeasdale** [comment]
I don't know what @sardaukar 's resolution was, but I had a similar issue recently and sharing my resolution here for posterity. Our application was setting:
```ruby
Chewy.request_strategy = :sidekiq
```
In an initializer with the bypass in `rails_helper.rb`, but we had a model with something like:

```
def my_association_that_updates_an_chewy_index
  # i actually hate this, not recommending anyone copy it
  super || create_my_association_that_updates_an_chewy_index
end
```

Not sure exactly the why or what, but wrapping the above `create` method in `Chewy.strategy(:sidekiq)` worked.
