### ISSUE TITLE
Latest patch release

### ISSUE THREAD

**Issue by caldwecr** [toptal/chewy#293]
@pyromaniac I am still waiting for a new version of the gem to appear on rubygems with the atomic strategy update. I know you said it would be a while and to run master, but I'm not really comfortable running a version that is not semantically version locked in production. I just wanted to check in and see when you thought the next patch level release would ship?

Kind regards.

**Comment by pyromaniac** [comment]
Noted, will do it soon

**Comment by pyromaniac** [comment]
Done
