### ISSUE TITLE
Need help for update_index

### ISSUE THREAD

**Issue by nyddogghr** [toptal/chewy#295]
Hi,

I'm having a bit of trouble with the updates on index. I have different cases for which I would like to get help.

First one: I have a `Media` model, indexed in my `SearchIndex`. I have added `update_index search#media, :self` in this model. When creating a new media, it is correctly indexed, but nothing happens when it is destroyed.

Second one, linked to globalization: I've looked at another issue you've answered to, and I chose to use this for the name translations:
```
 field :name_translations, type: 'object'
 template 'name_translations.*', type: 'string', index: 'analyzed'
```
How can I update my media when i change the name, as it is in fact not a `media` that is updated, but a `media_translation` ?

Finally, I have participants linked to medias through mediographies. A media can have several participants, and a participants several medias. How can I make the index update for a media when I edit a participant ? And how can I update the mediographies of a media ?

Here are the files (models are shortened) with what I've tried so far:
SearchIndex:
```
class SearchIndex < Chewy::Index

  define_type Media.includes(:mediographies, :containers) do
    field :name_translations, type: 'object'
    template 'name_translations.*', type: 'string', index: 'analyzed'
    field :description_translations, type: 'object'
    template 'description_translations.*', type: 'string', index: 'analyzed'
    field :media_type_id
    field :mediographies, value: ->(media) { media.mediographies.map(&:name) }
    field :containers do
      field :name, :description
    end
  end

  define_type Container.includes(:mediographies, :medias) do
    field :name, :description
    field :mediographies, value: ->(container) { container.mediographies.map(&:name) }
    field :medias do
      field :name_translations, type: 'object'
      template 'name_translations.*', type: 'string', index: 'analyzed'
      field :description_translations, type: 'object'
      template 'description_translations.*', type: 'string', index: 'analyzed'
      field :media_type_id
    end
  end

  define_type Participant.includes(:mediographies) do
    field :name
    field :mediographies do
      field :media do
        field :name_translations, type: 'object'
        template 'name_translations.*', type: 'string', index: 'analyzed'
        field :description_translations, type: 'object'
        template 'description_translations.*', type: 'string', index: 'analyzed'
        field :media_type_id
      end
      field :container do
        field :name, :description
      end
    end
  end

end
```
Media:
```
class Media < ActiveRecord::Base
  translates :name, :description
  Media::Translation.attr_accessible("name", "description", "locale", as: :renderer)
  update_index('search#media', :self)
  update_index('search#container', :medias)
  update_index('search#participants', :mediographies)
  has_many :mediographies, :dependent => :destroy
end
```
Container:
```
class Container < ActiveRecord::Base
  update_index('search#container', :self)
  update_index('search#media', :containers)
  update_index('search#participant', :mediographies)
  has_many :mediographies, :dependent => :destroy
end
```
Mediography:
```
class Mediography < ActiveRecord::Base
  update_index('search#media', :mediographies)
  update_index('search#container', :mediographies)
  update_index('search#participant', :mediographies
  belongs_to :participant
  belongs_to :media
  belongs_to :container
end
```
Participant:
```
class Participant < ActiveRecord::Base
 update_index('search#participant', :self)
 has_many :mediographies, :dependent => :destroy
end
```

Currently, the only solution I could see would be to use `SearchIndex::Model.import id` to reimport the models. But I fear it is to heavy.

If you could help me get the indexes updated for every actions on these models, it would be very kind.
Thanks

**Comment by pyromaniac** [comment]
First one: don't see anything to catch on. It should work since it works in specs and you probably have to debug it.
Second: `Media::Translation.update_index('search#media', :method_which_references_media)`
Third: 
```ruby
class Participant < ActiveRecord::Base
  update_index('search#participant', :self)
  update_index('search#media') { Media.where(id: mediographies.pluck(:media_id)) } # or even more efficient way you can invent
  has_many :mediographies, :dependent => :destroy
end
```

**Comment by nyddogghr** [comment]
Thanks for the quick answer. I try this and come back if I still have issues.

**Comment by nyddogghr** [comment]
It looks like I have finally succeeded with your answer.
For the first one, it was indeed caused by another after_commit in Media. Rails 3 has this bug, that after_commits override the previous ones, so chewy couldn't trigger its after_commit and delete the index.
If you agree with it, I'd like to keep this ticket open for some days. If I have no other issues until tuesday (in 5 days), I will close it.

Thanks a lot for your help and for this gem.

**Comment by pyromaniac** [comment]
Welcome!

**Comment by nyddogghr** [comment]
I have created the rspec for my models. Your rspec helper is really useful for this :)

I can now say it works perfectly and is always updated as it needs.

Thanks again for your help. I can close this issue.
