### ISSUE TITLE
Pass a block to Elasticsearch::Client

### ISSUE THREAD

**Issue by davekaro** [toptal/chewy#296]
I'd like to pass a block to configure the faraday instance of the Elasticsearch::Client. From [elasticsearch-transport readme](https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-transport#transport-implementations):

You can use any standard Faraday middleware and plugins in the configuration block, for example sign the requests for the AWS Elasticsearch service:

```
require 'patron'
require 'faraday_middleware/aws_signers_v4'

client = Elasticsearch::Client.new url: 'https://search-my-cluster-abc123....es.amazonaws.com' do |f|
  f.request :aws_signers_v4,
            credentials: Aws::Credentials.new(ENV['AWS_ACCESS_KEY'], ENV['AWS_SECRET_ACCESS_KEY']),
            service_name: 'es',
            region: 'us-east-1'
end
```

I believe https://github.com/toptal/chewy/blob/master/lib/chewy.rb#L125 is where the client is created, but I'm not sure the best way to pass a block to that. Could I simply override the client myself by setting `Thread.current[:chewy_client]` to whatever I want? Are there multi-threaded concerns I should be aware of if I do that?

**Comment by pyromaniac** [comment]
Well, I would rather redefine the whole method in my application, also I would (if I would be on your place) create a patch since this is a good observation :)
