### ISSUE TITLE
client.indices is nil

### ISSUE THREAD

**Issue by mlchai** [toptal/chewy#299]
One of my index is not working since anytime I try to do anything it seems any code running "client.indices" is returning nil. What could cause this? I've never had this problem with any other index, but this new index is named Client. Not sure if that would clash with anything.

EDIT: Did some debugging, and it seems that instead of returning an ElasticSearch Transport object, the client method for my Client index is returning the index object itself.
EDIT2: Found out exactly why this is happening. It seems that each index creates methods based on type so a ClientsIndex with a type Client would have ClientsIndex.client. Chewy.client is what it wants, but it's just using the simple client method so it's calling the ClientsIndex.client method that's overriding the Chewy.client one.

Example:

```ruby
def ClientsIndex < Chewy::Index
  define_type Client do
  end
end
```

Running rake chewy:reset will give:
NoMethodError: undefined method `get_alias' for nil:NilClass
/Users/mike/Projects/chewy/lib/chewy/index/aliases.rb:8:in `indexes'

Code in Chewy:

```ruby
client.indices.get_alias(name: index_name).keys
```

For any other index, client returns an ElasticSearch transport object because what's really being called is Chewy.client. It seems like it could be

```ruby
Chewy.client.indices.get_alias(name: index_name).keys
```

In the case of ClientsIndex though, ClientsIndex.client is being called so it's actually like this:

```ruby
ClientsIndex.client.indices.get_alias(name: index_name).keys
```

client just returns ClientsIndex::Client in that case, and it returns nil so get_alias is being called on nil.

**Comment by pyromaniac** [comment]
Yeah, that's because on Client type definition `#client` method is defined as well. Maybe it make sense to deprecate index definition. I would recommend to add `singleton_class.delegate :client, to: 'Chewy'` to right after type definition to redefine this method back :)

**Comment by mlchai** [comment]
I'd like to just change those instances to Chewy.client instead of client, would that work? If so, I'll make a PR.

**Comment by pyromaniac** [comment]
Well, no, it is a kind of per-index client redefinition ability. I'm already removing those type methods generation from here: https://github.com/toptal/chewy/blob/master/lib/chewy/index.rb#L83-L87, access via constants will be enough I suppose.

**Comment by pyromaniac** [comment]
btw, latest master should work fine for you
