### ISSUE TITLE
best way to share custom tokenizers/analyzers

### ISSUE THREAD

**Issue by mlchai** [toptal/chewy#300]
At the moment I'm creating a BaseIndex class that inherits from Chewy::Index, and making my other indices inherit from BaseIndex. Inside BaseIndex I only have definitions for custom tokenizers/analyzers that the indices use. However, when I run rake chewy:reset it creates an empty index called "base". I'd like it to not do that, but if it's not possible to disable that how can I share my custom code across indices?

**Comment by pyromaniac** [comment]
Well, good point, I'm using concerns usually for it.

**Comment by mlchai** [comment]
I found something that might be what I want although it wasn't heavily documented. Could I somehow use the Chewy::Index.settings to achieve this? If not, how do you use concerns for it?

**Comment by pyromaniac** [comment]
```ruby
module CommonSettings
  extend ActiveSupport::Concern

  included do
    settings ....
  end
end

class MyIndex < Chewy::Index
  include CommonSettings
end
```

**Comment by mlchai** [comment]
I think this did the job, thanks for all the help!

**Comment by mlchai** [comment]
Just wondering, how do you deal with multiple concerns? Like if you had CommonSettings1 and CommonSettings2, I found that including both and setting up both in the same way only allows one of them to actually be executed, namely the last one included.

**Comment by pyromaniac** [comment]
Well, I didn't face with such a problem yet, but you can patch chewy to do a deep_merge on settings
