### ISSUE TITLE
Callbacks don't appear to work in patched object

### ISSUE THREAD

**Issue by rhulse** [toptal/chewy#305]
I am integrating ES into my app with Chewy and we use Acts As Taggable On like the example app. 

I have tests written around the AATO patch, modified for my models, but for some reason the callbacks registered by update_index are not called (the test is failing). The patch IS being eval'ed. Has the API changed since the example was published? (The test ES server is running on the correct port)

**Comment by pyromaniac** [comment]
As far as I remember - nothing. Try to read this: https://github.com/toptal/chewy/blob/9c104b25b136cbadcdf9dfb7971b310ebb3d8f4c/README.md#rspec-integration

**Comment by rhulse** [comment]
OK, thanks. 

I had missed the line:
```Chewy.use_after_commit_callbacks = !Rails.env.test?``` line. 

All my regular model tests are passing now, but the patched AATO is still failing.

If I pass in a bogus symbol or specify an non existent index it does not throw any exceptions, so I am not sure whats going on.

Here is my patch code:

```
ActsAsTaggableOn::Tag.class_eval do
  has_many :news, through: :taggings, source: :taggable, source_type: 'News'

  update_index 'site#news', :news
end

ActsAsTaggableOn::Tagging.class_eval do
  update_index('site#news') { taggable if taggable_type == 'News' }
end
```

**Comment by pyromaniac** [comment]
The code looks ok, you probably have to debug it further since I've got no any idea right now

**Comment by rhulse** [comment]
No worries. 

I patched ```module ActiveRecordMethods``` to see what was going on. For some reason I've not identified this line in the initializer:

```Chewy.use_after_commit_callbacks = !Rails.env.test?```

does not have any effect on the patched code. I suspect this is a load order thing - the patch gets loaded before ```use_after_commit_callbacks``` is changed.

To fix this I instead added this line:

```Chewy.use_after_commit_callbacks = false```

to ```config/environments/test.rb``` and things are all good now.

Because it is likely people will be applying patches like this, would it be a good idea to change to docs to use this instead?

**Comment by pyromaniac** [comment]
Yeah, you are right, also maybe it would be even better to put this setting even to spec_helper.rb

**Comment by rhulse** [comment]
I tried it in the spec_helper but it didn't work there.

**Comment by pyromaniac** [comment]
That actually happens when models are loaded before this option is set up, normally it doesn't happen, but if you are forcing models loading - it happens then

**Comment by rhulse** [comment]
I wonder if that is related to using Guard?

**Comment by pyromaniac** [comment]
Spring probably, yeah

**Comment by rhulse** [comment]
OK, thanks for your help, and for the great Gem. Cheers.

**Comment by pyromaniac** [comment]
Welcome, thank you!
