### ISSUE TITLE
update index partially

### ISSUE THREAD

**Issue by cubbiu** [toptal/chewy#307]
Sorry, I can't find anywhere, is any way to update index partially with chewy? I need to update only one column for my large collection of indexes. And its very hard to reset it completely.

**Comment by edipofederle** [comment]
+1 here

**Comment by pyromaniac** [comment]
Currently this is not supported unfortunately, it is really tough to implement such a thing in the universal way. I'l think about it, but since index reset is zero-downtime, it will not affect anything even if it runs for a long time

**Comment by cubbiu** [comment]
thnx
