### ISSUE TITLE
Import seems to only use the :urgent strategy

### ISSUE THREAD

**Issue by dnd** [toptal/chewy#310]
I have a lot of data that I need to index and it would go much faster if I could have multiple workers processing it in the background. I tried using `Chewy.strategy(:resque) { MyIndex.import }` but everything just indexes immediately in the console I'm running. How can I get Chewy to batch the import out to my workers?

**Comment by pyromaniac** [comment]
Yeah, this is hot it supposed to be working. It is a low-level method. Strategy counts only on model save, and import is called immediately or from the worker
