### ISSUE TITLE
NameError - uninitialized constant - *index not defined

### ISSUE THREAD

**Issue by 6ewis** [toptal/chewy#312]

**Comment by yahooguntu** [comment]
@6ewis What ended up being the problem? I'm running into the same issue.

**Comment by 6ewis** [comment]
@yahooguntu apologies. I've just seen your message. I really don't remember...if you paste your error I might be able to help

**Comment by BastienL** [comment]
@yahooguntu @6ewis I'm just facing the same issue with a fresh Chewy install and a very simple ActiveRecord < ChewyIndex.

Do you have any fix to share about this? 

Thanks.

**Comment by BastienL** [comment]
Ok just found the fix. Just in case: http://stackoverflow.com/a/39781754/877323
