### ISSUE TITLE
changes is empty - update_index

### ISSUE THREAD

**Issue by edipofederle** [toptal/chewy#313]
Hi,
I don't know if I am doing something wrong or anything else. I have this, on my Client model.
``` 
update_index('client#person_client') { self if client_change? } 

def client_change? 
   puts changes
   true
 end
```
But ``changes`` always return empty hash

The chewy version is the last one.

Thanks in advance.

**Comment by pyromaniac** [comment]
At the moment of indexing model is saved already, so you have to use `previous_changes` method

**Comment by edipofederle** [comment]
Great. Thanks.
