### ISSUE TITLE
Can't enable dynamic scripting

### ISSUE THREAD

**Issue by khoffma4** [toptal/chewy#323]
First off, thanks Toptal for building and open sourcing this gem. Working with it has been great.

I have an issue with getting dynamic scripting to work. I may be missing something, but I can't find any reference to this in the docs. I've also looked at the elasticsearch gem that this wraps, thinking there may be instructions in there.

Here is an example of my query and the error.
```
MyIndex.script_score("_score * doc['rating'].value").load.to_a
{:body=>{:query=>{:function_score=>{:functions=>[{:script_score=>{:script=>"_score * doc['id'].value"}}]}}}, :index=>["my_index"], :type=>[]}
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"script_exception","reason":"scripts of type [inline], operation [search] and lang [groovy] are disabled"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"my_index","node":"Y-znyXOfQRWN1KxbM2PDhQ","reason":{"type":"query_parsing_exception","reason":"script_score the script could not be loaded","index":"my_index","line":1,"col":94,"caused_by":{"type":"script_exception","reason":"scripts of type [inline], operation [search] and lang [groovy] are disabled"}}}]},"status":400}
```

The error message makes me think that scripting is disabled, specifically because it says `"scripts of type [inline], operation [search] and lang [groovy] are disabled"`

I've read through this article and can't determine where to configure the ES settings. (https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html#modules-scriptin) I have tried using the chewy.yml and chewy.rb files.
```
script.inline: on
script.indexed: on
```

I'm running:
chewy 0.8.3
elastic search 2.0.0
rails 3.2.22

If I am doing something incorrectly or these settings are easy to configure, I'm happy to add to the docs to make it clearer to others how to do this.

**Comment by pyromaniac** [comment]
Did you try even google it? The first page of google gives additionally:

```
script.engine.groovy.inline.search: on
script.search: on
script.groovy.sandbox.enabled: true
```

**Comment by khoffma4** [comment]
Yes, I have spent many hours searching for a solution before creating an issue. I'm hoping this really isn't an issue and it's just a case of it not being clear how to set these configurations. If someone can let if I'm setting these configurations correctly, then I would be able to really tell if there is an issue with the gem. If it happens that I'm setting the configurations incorrectly, then I'll submit a PR to add some more instructions to the docs.

I have tried using chewy.yml and chewy.rb and set these configurations. Neither of them have worked for me. I've tried including the configurations that you posted as well. Any help would be much appreciated.

```
# chewy.yml
test:
  host: 'localhost:9250'
  prefix: 'test'
development:
  host: 'localhost:9200'
  script:
    engine:
      groovy:
        inline:
          search: on
    search: on
    groovy:
      sandbox:
        enabled: true
    inline: on
    indexed: on
```

```
# chewy.rb
Chewy.settings = {
  host: 'localhost:9200',
  script: {
    inline: 'on',
    indexed: 'on',
    search: 'on',
    engine: {
      groovy: {
        inline: {
          search: 'on'
        }
      }
    },
    groovy: {
      sandbox: {
        enabled: true
      }
    }
  }
}
```

**Comment by pyromaniac** [comment]
You have to set it up in elasticsearch.yml, this is not per-index configuration

**Comment by khoffma4** [comment]
Ok, thanks
