### ISSUE TITLE
On Save Import creates the index and deletes the index using Mongoid

### ISSUE THREAD

**Issue by phyxavier** [toptal/chewy#325]
GEM LISTS
 
 * elasticsearch (1.0.15)
 * elasticsearch-api (1.0.15)
 * elasticsearch-transport (1.0.15)
 * mongoid (5.0.0)
 * chewy (0.8.3)

`class Contractor
   include Mongoid::Document
   include Mongoid::Timestamps
  
   update_index 'availability#contractor',  :self

end`

On contractor.save! Import creates an index and deletes the index.

Console log:
AvailabilityIndex::Contractor Import (21.8ms) {:index=>1, :delete=>1}

**Comment by pyromaniac** [comment]
Do you mean it create object in index and delete it, right? Could you assign Chewy.transport_logger and Chewy.transport_tracer and put logs here?

**Comment by phyxavier** [comment]
`Started POST "/contractors/sync" for 127.0.0.1 at 2016-02-04 12:28:49 -0500
D, [2016-02-04T12:28:49.489699 #11292] DEBUG -- : DEBUG: Chewy strategies stack: [2] <- atomic @ /Users/phyxavier/.rvm/gems/ruby-2.2.3@rails5/bundler/gems/chewy-ea931285b160/lib/chewy/railtie.rb:16
Processing by ContractorsController#sync as JSON
  Parameters: {"contractor"=>{"www_user_id"=>125175, "firstname"=>"lois", "lastname"=>"macaulay", "availability_feature"=>false, "company_attributes"=>{"name"=>"Lois MacAulay Interior Design", "score"=>-1, "www_company_id"=>192545}, "service_areas_attributes"=>[{"coordinates"=>[-79.3931, 43.6709], "city"=>"Toronto", "zip"=>"M5R1G2", "state_province"=>"Ontario", "state_province_abbr"=>"ON", "country"=>"CANADA"}]}}
Unpermitted parameter: availability_feature
D, [2016-02-04T12:28:49.522816 #11292] DEBUG -- : MONGODB | Adding localhost:27017 to the cluster.
D, [2016-02-04T12:28:49.533411 #11292] DEBUG -- : MONGODB | localhost:27017 | homestars_available_development.find | STARTED | {"find"=>"contractors", "filter"=>{"www_user_id"=>125175}}
D, [2016-02-04T12:28:49.533723 #11292] DEBUG -- : MONGODB | localhost:27017 | homestars_available_development.find | SUCCEEDED | 0.000248s
D, [2016-02-04T12:28:49.566848 #11292] DEBUG -- : MONGODB | localhost:27017 | homestars_available_development.insert | STARTED | {"insert"=>"contractors", "documents"=>[{"_id"=>BSON::ObjectId('56b38a51f5b2192c1c000000'), "score"=>0.0, "total_projects"=>0, "total_reviews"=>0, "www_user_id"=>125175, "updated_at"=>2016-02-04 17:28:49 UTC, "created_at"=>2016-02-04 17:28:49 UTC}], "...
D, [2016-02-04T12:28:49.567479 #11292] DEBUG -- : MONGODB | localhost:27017 | homestars_available_development.insert | SUCCEEDED | 0.0005510000000000001s
Unpermitted parameter: availability_feature
D, [2016-02-04T12:28:49.591664 #11292] DEBUG -- : MONGODB | localhost:27017 | homestars_available_development.update | STARTED | {"update"=>"contractors", "updates"=>[{"q"=>{"_id"=>BSON::ObjectId('56b38a51f5b2192c1c000000')}, "u"=>{"$set"=>{"firstname"=>"lois", "lastname"=>"macaulay", "updated_at"=>2016-02-04 17:28:49 UTC, "company"=>{"_id"=>BSON::ObjectId('56b38a51f5b2192c1c00...
D, [2016-02-04T12:28:49.592223 #11292] DEBUG -- : MONGODB | localhost:27017 | homestars_available_development.update | SUCCEEDED | 0.000488s
Unpermitted parameter: availability_feature
Completed 200 OK in 83ms (Views: 0.9ms | ActiveRecord: 0.0ms)
D, [2016-02-04T12:28:49.594640 #11292] DEBUG -- : DEBUG: Chewy strategies stack: [2] -> atomic @ /Users/phyxavier/.rvm/gems/ruby-2.2.3@rails5/bundler/gems/chewy-ea931285b160/lib/chewy/railtie.rb:16
I, [2016-02-04T12:28:49.597559 #11292]  INFO -- : HEAD http://localhost:9200/availability [status:404, request:0.002s, query:N/A]
D, [2016-02-04T12:28:49.597597 #11292] DEBUG -- : < 
F, [2016-02-04T12:28:49.597619 #11292] FATAL -- : [404] 
I, [2016-02-04T12:28:49.600340 #11292]  INFO -- : GET http://localhost:9200/ [status:200, request:0.002s, query:n/a]
D, [2016-02-04T12:28:49.600396 #11292] DEBUG -- : < {
  "status" : 200,
  "name" : "Betty Ross Banner",
  "cluster_name" : "elasticsearch_phyxavier",
  "version" : {
    "number" : "1.7.2",
    "build_hash" : "e43676b1385b8125d647f593f7202acbd816e8ec",
    "build_timestamp" : "2015-09-14T09:49:53Z",
    "build_snapshot" : false,
    "lucene_version" : "4.10.4"
  },
  "tagline" : "You Know, for Search"
}

I, [2016-02-04T12:28:49.635032 #11292]  INFO -- : PUT http://localhost:9200/availability [status:200, request:0.034s, query:n/a]
D, [2016-02-04T12:28:49.635918 #11292] DEBUG -- : > {"mappings":{"contractor":{"properties":{"firstname":{"type":"string"},"lastname":{"type":"string"},"profile":{"type":"string"},"score":{"type":"float"},"total_reviews":{"type":"integer"},"total_projects":{"type":"integer"},"profession_types":{"type":"string"},"keywords":{"type":"string"},"company_name":{"type":"string"},"company":{"properties":{"score":{"type":"float"},"www_company_id":{"type":"integer"}},"type":"object"},"availability_app":{"properties":{"app_install":{"type":"boolean"},"feature_on":{"type":"boolean"}},"type":"object"},"connection_analytic":{"properties":{"last_connected_at":{"type":"date"},"connection_count":{"type":"integer"},"rolling_todo_count":{"type":"integer"},"rolling_doing_count":{"type":"integer"},"rolling_done_count":{"type":"integer"},"inbound_count":{"type":"integer"}},"type":"object"},"service_areas":{"properties":{"coordinates":{"type":"geo_point"},"city":{"type":"string"},"zip":{"type":"string"},"state_province":{"type":"string"},"country":{"type":"string"},"time_zone":{"type":"string"}},"type":"object"}}}}}
D, [2016-02-04T12:28:49.636000 #11292] DEBUG -- : < {"acknowledged":true}
D, [2016-02-04T12:28:49.637241 #11292] DEBUG -- : MONGODB | localhost:27017 | homestars_available_development.find | STARTED | {"find"=>"contractors", "filter"=>{"_id"=>{"$in"=>[BSON::ObjectId('56b38a51f5b2192c1c000000')]}}, "projection"=>{:_id=>1}, "limit"=>1}
D, [2016-02-04T12:28:49.637678 #11292] DEBUG -- : MONGODB | localhost:27017 | homestars_available_development.find | SUCCEEDED | 0.00036199999999999996s
D, [2016-02-04T12:28:49.638074 #11292] DEBUG -- : MONGODB | localhost:27017 | homestars_available_development.find | STARTED | {"find"=>"contractors", "filter"=>{"_id"=>{"$in"=>[BSON::ObjectId('56b38a51f5b2192c1c000000')]}}}
D, [2016-02-04T12:28:49.638533 #11292] DEBUG -- : MONGODB | localhost:27017 | homestars_available_development.find | SUCCEEDED | 0.00041099999999999996s
D, [2016-02-04T12:28:49.639066 #11292] DEBUG -- : MONGODB | localhost:27017 | homestars_available_development.find | STARTED | {"find"=>"contractors", "filter"=>{"_id"=>{"$in"=>[BSON::ObjectId('56b38a51f5b2192c1c000000')]}}}
D, [2016-02-04T12:28:49.639481 #11292] DEBUG -- : MONGODB | localhost:27017 | homestars_available_development.find | SUCCEEDED | 0.000358s
D, [2016-02-04T12:28:49.640569 #11292] DEBUG -- : MONGODB | localhost:27017 | homestars_available_development.find | STARTED | {"find"=>"profession_types", "filter"=>{"contractor_id"=>BSON::ObjectId('56b38a51f5b2192c1c000000')}}
D, [2016-02-04T12:28:49.640920 #11292] DEBUG -- : MONGODB | localhost:27017 | homestars_available_development.find | SUCCEEDED | 0.00022s
D, [2016-02-04T12:28:49.641818 #11292] DEBUG -- : MONGODB | localhost:27017 | homestars_available_development.find | STARTED | {"find"=>"keywords", "filter"=>{"contractor_id"=>BSON::ObjectId('56b38a51f5b2192c1c000000')}}
D, [2016-02-04T12:28:49.642097 #11292] DEBUG -- : MONGODB | localhost:27017 | homestars_available_development.find | SUCCEEDED | 0.000211s
I, [2016-02-04T12:28:49.649099 #11292]  INFO -- : POST http://localhost:9200/availability/contractor/_bulk [status:200, request:0.005s, query:0.003s]
D, [2016-02-04T12:28:49.649135 #11292] DEBUG -- : > {"index":{"_id":"56b38a51f5b2192c1c000000"}}
{"firstname":"lois","lastname":"macaulay","profile":null,"score":0.0,"total_reviews":0,"total_projects":0,"profession_types":[],"keywords":[],"company_name":"Lois MacAulay Interior Design","company":{"score":-1.0,"www_company_id":192545},"availability_app":null,"connection_analytic":null,"service_areas":[{"coordinates":[-79.3931,43.6709],"city":"Toronto","zip":"M5R1G2","state_province":"Ontario","country":"CANADA","time_zone":"Eastern Time (US \u0026 Canada)"}]}

D, [2016-02-04T12:28:49.649152 #11292] DEBUG -- : < {"took":3,"errors":false,"items":[{"index":{"_index":"availability","_type":"contractor","_id":"56b38a51f5b2192c1c000000","_version":1,"status":201}}]}
I, [2016-02-04T12:28:49.652275 #11292]  INFO -- : POST http://localhost:9200/availability/contractor/_bulk [status:200, request:0.003s, query:0.001s]
D, [2016-02-04T12:28:49.652317 #11292] DEBUG -- : > {"delete":{"_id":"56b38a51f5b2192c1c000000"}}

D, [2016-02-04T12:28:49.652334 #11292] DEBUG -- : < {"took":1,"errors":false,"items":[{"delete":{"_index":"availability","_type":"contractor","_id":"56b38a51f5b2192c1c000000","_version":2,"status":200,"found":true}}]}
D, [2016-02-04T12:28:49.653977 #11292] DEBUG -- :   AvailabilityIndex::Contractor Import (16.2ms) {:index=>1, :delete=>1}`

**Comment by pyromaniac** [comment]
Well, looks like a bug :) Will take a look, but you probably want to debug it since it is reproducible for you to speed up the process

**Comment by phyxavier** [comment]
will do

**Comment by pyromaniac** [comment]
Btw, I've just found out that chewy was not tested against 5.0.0, trying to fix this and will try to reproduce then

**Comment by pyromaniac** [comment]
And it seems to be working as expected according to my specs, do you have any updates on the case?

**Comment by wulffeld** [comment]
I think I might have hit this bug as well. Things work fine from a console but a controller action will cause the delete as described above. I've set the strategy to urgent in an initializer.

Mongoid 5.1.1 (also happened with 5.0.0)
Chewy 0.8.3.

Let me know if I can help.

**Comment by pyromaniac** [comment]
Since I've updated specs to use mongoid 5 and everything is passing - it seems to be some uncovered case, maybe you can try to debug it to understand what exactly causes it, or at least find essential setup for the bug reproducing, it would be really helpful.

**Comment by wulffeld** [comment]
@pyromaniac Sure I will try. Any hunch at all why it would work in console but not in a controller action? BTW what I was doing was using state_machine - for instance @object.publish. So I suspect the bug lies somewhere with state_machine + mongoid. Will dig into it.

**Comment by pyromaniac** [comment]
Perfect, thanks! As for clues - in console `urgent` strategy is used by default, but I don't see how could it affect import

**Comment by wulffeld** [comment]
@pyromaniac Well I've been unsuccessful trying to trace the problem :(

I've now added a simple app here with only mongoid 5.1.1 and chewy 0.8.3 added. https://github.com/wulffeld/chewy_bug

Just bundle install and run rails server. Go to /movies and click the link. Observe the log/elasticsearch.log for the problem.

If I change request_strategy to :urgent it works fine.

**Comment by pyromaniac** [comment]
Wow, it will be really helpful, thanks! Will take a look.

**Comment by pyromaniac** [comment]
Guys, thanks for the report and help, the bug seems to be fixed, I'm sorry I was unable to find it in time.

**Comment by wulffeld** [comment]
Awesome. Thanks.

**Comment by phyxavier** [comment]
@pyromaniac thanks
