### ISSUE TITLE
How to implement deep pagination?

### ISSUE THREAD

**Issue by pfletch1023** [toptal/chewy#327]
Is there an easy solution to Elasticsearch's deep pagination problem with Chewy? Is there a way to implement scroll without interacting with the Elasticsearch client directly?

**Comment by pyromaniac** [comment]
Well, it was not implemented in chewy yet. Chewy itself uses it directly https://github.com/toptal/chewy/blob/master/lib/chewy/type/import.rb#L169-L190, but I believe you can play with `search_type` query method and will be able at least to use chewy queries dsl. Also feel free to submit your PR :)

**Comment by pfletch1023** [comment]
So just to confirm, there isn't currently a way to do something like the following with the chewy DSL?
```
client = Elasticsearch::Client.new
query = client.search index: 'users', scroll: '1m', size: 100
client.scroll scroll_id: query['_scroll_id'], scroll: '1m'
```

**Comment by pyromaniac** [comment]
yep, there is no way right now

**Comment by binarydev** [comment]
@pyromaniac is this on your roadmap/general radar to be implemented in a future release?

**Comment by pyromaniac** [comment]
Well, why not, basically, will create a ticket for it, It makes sense.

**Comment by pyromaniac** [comment]
There is a scroll API implemented in the latest version.
