### ISSUE TITLE
Faraday::TimeoutError: Timeout::Error on Reindex

### ISSUE THREAD

**Issue by edipofederle** [toptal/chewy#328]
Hi,

I am trying to run ``chewy:reset:all`` on about 40K records. But I end with the timeout error (Faraday::TimeoutError: Timeout::Error).

Any suggestion here ? I see something with set the timeout at ``Chewy.settings``. But this error only happen when I try run the rake task.

chewy version: 0.8.1

Thanks in advance

**Comment by pyromaniac** [comment]
Well, we've got even more records indexing, but didn't see such a timeout ever. How big your inserted objects are? Did you try to tune ES config? How many shards and nodes do you have?

**Comment by pyromaniac** [comment]
And it would be great to find the exact operation causes timeout

**Comment by edipofederle** [comment]
Hi @pyromaniac,

Q: How big your inserted objects are??
A:  I don't know exactly how measure that. But, Are small objects, contains only a set of small text attributes. Please, let me know if there is a more exact way to answer that question

Q: Did you try to tune ES config?
A: No. Now I am trying it on my local machine. But the problem happen also em production (DigitalOcean with a droplet of 4GB).

Q: How many shards and nodes do you have?
A: I use the default configuration.  (here the config file: https://gist.github.com/edipofederle/a1d18d86a6133b527c85)

Here also the output when the timeout happen: https://gist.github.com/edipofederle/05365efdac3a40f926e0

Thanks for your help.

**Comment by pyromaniac** [comment]
Can you check cluster status after timeout? Is it green or any other color?

**Comment by edipofederle** [comment]
``curl -GET 'http://localhost:9200/_cluster/health'
{"cluster_name":"elasticsearch_edipo\nES_HEAP_SIZE=2","status":"yellow","timed_out":false,"number_of_nodes":1,"number_of_data_nodes":1,"active_primary_shards":10,"active_shards":10,"relocating_shards":0,"initializing_shards":0,"unassigned_shards":10,"delayed_unassigned_shards":0,"number_of_pending_tasks":0,"number_of_in_flight_fetch":0}%``

**Comment by pyromaniac** [comment]
"status":"yellow" is probably a key. Something makes your cluster yellow, it waits for something, it should be green. Try to do `Chewy.massacre` to remove everything from index, check out status and do reset again. If error will occur again - there is something with your data and/or mappings, try to dig for a cause

**Comment by edipofederle** [comment]
I will try it and let you know soon as possible. 

Thanks

**Comment by edipofederle** [comment]
I can add new node (a second one) if I have only one server ?

**Comment by pyromaniac** [comment]
Sure. I'm not a huge ES expert, you can read ES docs additionally

**Comment by edipofederle** [comment]
Nice. I will try make it green.

**Comment by edipofederle** [comment]
Hi,
I figure out that some of the attributes became indexed is the problem. I just remove it and ``reset`` works fine. Maybe something wrong with the data.
About the yellow status, I read that this happen when you have only a single node....,
Whatever, I will trying figure out what are wrong with specific attribute.

I thank you for you support.
