### ISSUE TITLE
Reset with scope

### ISSUE THREAD

**Issue by edipofederle** [toptal/chewy#329]
Hi,

With ``import`` I can use:

``UsersIndex::User.import User.where('rating > 100')``

Is possible use something like:

``UsersIndex.reset User.where('rating > 100')``

Thanks in advance

**Comment by pyromaniac** [comment]
It doesn't make sense actually. This means that you are going to remove existing index and then index only `User.where('rating > 100')`. If you want to index this users only - set up `User.where('rating > 100')` as a default scope for type: `define_type User.where('rating > 100')`. Af you want something else - then you are able to take a look on reset implementation and cleanup index manually and then import only those you need

**Comment by edipofederle** [comment]
Great.

Make sense now. 

Thank you again.
