### ISSUE TITLE
Chewy DSL - how to do a geo-type filter?

### ISSUE THREAD

**Issue by hiyer** [toptal/chewy#330]
How do I filter for objects within, say, 'x' km of a specific longitude-latitude pair? In JSON I would use something like
`geo_distance: {
        distance: "#{x}km",
        coordinates: {
          lat: "#latitude",
          lon: "#longitude"
        }
      }`
but how do I express this in the Chewy DSL?

**Comment by hiyer** [comment]
Never mind - I figured it out. I can do something like this:
`filter(geo_distance: {distance: "25km", coordinates: {lat: <latitude>, lon:<longitude>}})`

**Comment by pyromaniac** [comment]
Perfect :+1:
