### ISSUE TITLE
update_index problem - UnderivableType error

### ISSUE THREAD

**Issue by hiyer** [toptal/chewy#332]
I have the following index defined in `app/chewy/active_houses_index.rb`.

```
class ActiveHousesIndex < Chewy::Index
  define_type House.published...
```

And the following update_index statement in my House model:
`update_index "active_houses#house", :self`

This is pretty similar to the `Users` example provided in the docs, so I don't know what I'm doing wrong.
Whenever I save a house, I get the following error:
`#<Chewy::UnderivableType: Can not find index named`HouseIndex`>`

As an aside, I got the same error even when I renamed the index to `HousesIndex` (and also renamed the file accordingly). 

Chewy version: chewy-0.8.3
Ruby version: 2.1.5

**Comment by pyromaniac** [comment]
Didn't see this before. Looks like a bug definitely, could you debug it a little bit please? Have no idea how to reproduce it.

**Comment by hiyer** [comment]
@pyromaniac I tried debugging a bit and found the following. In chewy.rb,
the Observe.update_proc method gets called twice on loading (via
update_index). The first time the type_name is passed in correctly as
'active_houses@house'. The second time - weirdly enough - it changes to
'house#houses'. I couldn't figure out why this change happens (or why
update_index gets called twice). If you can provide any pointers I can
debug further.

Thanks,
Hari

**Comment by pyromaniac** [comment]
So have you find the reason?

**Comment by mayank-singh** [comment]
I am also having a similar issue. Were you able to find out the cause @hiyer @pyromaniac

**Comment by MarioDiar** [comment]
Same here, having the same issue on a simple test example I'm trying to do. Anyone found a solution yet?
