### ISSUE TITLE
specifying transport_options => proc give no method found error

### ISSUE THREAD

**Issue by johnnyiller** [toptal/chewy#333]
I was trying to specify a custom Proc in the settings for adding faraday middleware.  Looking at the code here

https://github.com/toptal/chewy/blob/master/lib/chewy.rb#L126

it looks like you should be able to specify this in the settings and the proc will get passed to the client initialization code.  However, when I do this I get an error and I think it's the result of the config option finding it's way into the *configuration* variable.  I could probably produce a fix but i'm not familiar enough with the testing framework and development process to write an entire test case around it...

**Comment by pyromaniac** [comment]
Any success here?
