### ISSUE TITLE
RubyGem version error: faraday(0.9.0 not ~> 0.4.1)  in rails 2 Application

### ISSUE THREAD

**Issue by shiva-prasad-12** [toptal/chewy#343]
If i try to install faraday 0.4.1
its Gives error like

> Error installing faraday:
	addressable requires Ruby version >= 1.9.0

Gem Environment .

`RubyGems Environment:
  - RUBYGEMS VERSION: 1.3.7
  - RUBY VERSION: 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/1.8
  - RUBY EXECUTABLE: /usr/local/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/1.8
     - /root/.gem/ruby/1.8
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :benchmark => false
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - http://rubygems.org/
`

Gem list 

`*** LOCAL GEMS ***

actionmailer (2.3.5)
actionpack (2.3.5)
activerecord (2.3.5)
activeresource (2.3.5)
activesupport (2.3.5)
bundler (1.7.3)
daemon_controller (1.2.0)
declarative_authorization (0.5.1)
faraday (0.9.0)
fastercsv (1.5.5)
git (1.2.8)
httpauth (0.2.1)
i18n (0.4.2)
json (1.8.1)
minitest (5.4.2)
multi_json (1.8.2)
multipart-post (2.0.0)
mysql (2.8.1)
nokogiri (1.5.6)
oauth2 (0.0.10)
passenger (4.0.59)
pdfkit (0.8.2)
populator (1.0.0)
rack (1.5.2, 1.0.1)
rails (2.3.5)
rake (0.8.7)
rjb (1.5.4)
ruby-progressbar (1.6.0)
rubygems-update (1.3.7)
rush (0.6.8)
session (3.2.0)
thread_safe (0.3.5)
tzinfo (1.2.2)
validatable (1.6.7)
vote_fu (0.0.11)
`

Error 

 `Error details saved to: /tmp/passenger-error-xpSVn9.html
  Message from application: RubyGem version error: faraday(0.9.0 not ~> 0.4.1)
 (Gem::LoadError)
  /usr/local/lib/ruby/site_ruby/1.8/rubygems.rb:779:in `report_activate_error'
  /usr/local/lib/ruby/site_ruby/1.8/rubygems.rb:214:in `activate'
  /usr/local/lib/ruby/site_ruby/1.8/rubygems.rb:249:in `activate'
  /usr/local/lib/ruby/site_ruby/1.8/rubygems.rb:248:in `each'
`

**Comment by pyromaniac** [comment]
Well, chewy doesn't support rails 2 anyway, you have to upgrade your application definitely

**Comment by shiva-prasad-12** [comment]
Hi
If i update it my application doesn't run , is there any other way to solve this issue and if possible give me the steps to upgrade .

Thank You
Shiva

**Comment by pyromaniac** [comment]
Chewy doesn't support ruby 2 unfortunately, so there is no way except app upgrade. You have to upgrade and fix all the issues or use another gem for ES

**Comment by shiva-prasad-12** [comment]
Can uninstall rails or ruby and start install it from scratch , can i do this  , please help me because i am not able to fix it from last last week thank you.

**Comment by pyromaniac** [comment]
Sorry, friend, you have to pass this way by yourself. Just read docs and try again and again and you will figure this out, I believe in you!

**Comment by shiva-prasad-12** [comment]
Hi

I finished i re installed rails , its working fine.

**Comment by pyromaniac** [comment]
Glad for you!
