### ISSUE TITLE
Complex search filtering

### ISSUE THREAD

**Issue by sardaukar** [toptal/chewy#347]
I have a `ProjectsIndex` that has a `Project` type (the `is_secret` and `user_ids_allowed` fields are recent and relevant to this issue):

```
define_type Project do
  field :name, analyzer: 'title'
  field :is_secret
  field :user_ids_allowed
end
```

This is how I query it now:

```
def project_search
  ProjectsIndex.query(
    query_string: {
      fields: [
        :name
      ],
      query: wildcardify(query),
      default_operator: "and"
    }
  ).filter(
    terms: { _type: [:project] }
  ) if query
end
```

The newly added fields are a way to introduce projects that are visible on search only to some users. My idea is to have `user_ids_allowed` (a array) on the index for every project, and when one is made secret, to change its content. The `user_ids_allowed` is either null (non-secret) or has an array of numeric User IDs (secret project). 

Is this a good approach? If so, how do I specify the filtering clause?

Thanks!

**Comment by pyromaniac** [comment]
Yep, we are using the same approach in Toptal in a couple of places.
