### ISSUE TITLE
Max Size/Chunking for Importer

### ISSUE THREAD

**Issue by MetricMike** [toptal/chewy#348]
AWS ES won't let you post more than 10MB (or 100MB if you buy the bigger tiers), but I have over 250k documents I'd like to index.

When I initially imported, I used this block
```ruby
(0..2499).each do |i|
  Chewy.strategy(:sidekiq) do
    Event.where(id: 100*i..100*(i+1)).find_each(&:save);
  end
end
```
to import 100-document chunks at a time, which worked great.

But I missed 1000 events somewhere along the way (a couple of them had mapping errors on the initial import).

Calling `EventsIndex::Event.import` isn't an option because the indexing request is FAR larger than 100MB.
Partial indexing isn't an option yet (and even if it were I don't think it would handle this particular case).

Is there a way to pass a `max_size` option to the importer to chunk it's requests?

**Comment by pyromaniac** [comment]
Currently there is no such an option, but this is an option which is quite easy to add to import, so if you can do it - just submit a PR. I'm actually going to implement it, but simply not sure how soon

**Comment by MetricMike** [comment]
I sort of jumped the gun. Digging through the import internals, I found the `batch_size` method which *mostly* does the trick. It doesn't limit by size, but if you can estimate the average size in json of your documents it's good enough.

I also noticed #271 which is/was in a similar boat - if you're using AWS ES, there's a number of options you have to add to make everything work. Would a PR with a new section detailing these on the README be welcome, or is that more appropriate for a wiki page?

**Comment by pyromaniac** [comment]
PR to readme would be just ok, but I was talking about additional `bulk_size` options, so `batch_size` will be responsible for mysql fetches and `bulk_size` for bulk ES import size so they might be configured independently, but if `batch_size` is enough for you now - just use it and wait for appropriate patch :)

**Comment by pyromaniac** [comment]
`bulk_size` option was released, try it out

**Comment by pyromaniac** [comment]
https://github.com/toptal/chewy/#type-default-import-options

**Comment by MetricMike** [comment]
Sorry for the delay, I just tested this out and it's fantastic!
