### ISSUE TITLE
Dynamic field indexer 

### ISSUE THREAD

**Issue by mikeyhogarth** [toptal/chewy#349]
We have a field in one of our indexes that is based on a hash (which is dynamic and can change from item to item) - it is defined like this: 

```ruby
field :foo, type: 'object', value: ->(obj) do                         
  Hash[obj.foo.map {|x| [x.key, x.value]}]
end
```
This is all working fine - it's looking like we might need to put analyzers on these fields though but the interface here doesn't appear to let you (it's just expecting a hash with key / value pairs). 

ideally we would want all of these to be `index: :not_analyzed`

Is this a limitation of ES itself or is there a way to achieve this?

**Comment by mikeyhogarth** [comment]
Managed to fix this using the `template` feature, cheers

**Comment by pyromaniac** [comment]
:+1:
