### ISSUE TITLE
NoMethodError when running spec suite

### ISSUE THREAD

**Issue by dzunk** [toptal/chewy#351]
Hi, I'm having trouble with Chewy specs - I've implemented them as per the `update_index.rb` file, but I'm getting a strange NoMethodError when my spec suite runs. Details below:

**employees_index.rb**
```ruby
class EmployeesIndex < Chewy::Index

  define_type Employee.includes(:company) do
    field :first_name
    field :last_name
    field :full_name
    field :dob
  end

end
```
**employees_index_spec.rb**
```ruby
require 'rails_helper'

RSpec.describe EmployeesIndex, type: :model do

  let(:employee) { build(:employee) }

  # Indexed objects
  it 'indexes employees' do
    expect(employee.save!).to update_index('employees#employee')
  end

end
```

**Partial stack trace**
```
NoMethodError: undefined method `call' for true:TrueClass
/home/matt/.rvm/gems/ruby-2.2.2/gems/chewy-0.8.3/lib/chewy/rspec/update_index.rb:113:in `block (3 levels) in <top (required)>'
/home/matt/.rvm/gems/ruby-2.2.2/gems/chewy-0.8.3/lib/chewy/strategy.rb:60:in `wrap'
/home/matt/.rvm/gems/ruby-2.2.2/gems/chewy-0.8.3/lib/chewy.rb:173:in `strategy'
/home/matt/.rvm/gems/ruby-2.2.2/gems/chewy-0.8.3/lib/chewy/rspec/update_index.rb:113:in `block (2 levels) in <top (required)>'
./spec/models/employees_index_spec.rb:18:in `block (2 levels) in <top (required)>'
-e:1:in `load'
-e:1:in `<main>'
```

Standard specs (e.g. `expect(employee.save!).to be_truthy`) work fine. I'm stumped - anything in particular I should be looking for?

**Comment by pyromaniac** [comment]
`expect { employee.save! }`

**Comment by dzunk** [comment]
Well, that was easy - best kind of problem to have. Thanks very much!

If any other RSpec newbs come across this, [here's a StackOverflow post](http://stackoverflow.com/a/21568225/4668688) explaining the difference between `expect()` and `expect{}`.

**Comment by pyromaniac** [comment]
Always welcome!
