### ISSUE TITLE
How to get proper value of Groovy method in script score?

### ISSUE THREAD

**Issue by knd** [toptal/chewy#352]
I enabled dynamic scripting. 

```
2.3.0 :214 > DiagnosesIndex.script_score("_score").query(match: {name: "cham k"}).map(&:_score)
  DiagnosesIndex Search (28.7ms) {:body=>{:query=>{:function_score=>{:functions=>[{:script_score=>{:script=>"_score"}}], :query=>{:match=>{:name=>"cham k"}}}}}, :index=>["diagnoses"], :type=>[]}
 => [2.5906327, 1.1099176, 1.0467807, 1.0402842, 1.0119661, 0.8601855, 0.6585796, 0.5438596, 0.36430773, 0.36430773] 
```

However, I'm trying to get the integer value of script score using Groovy method:

```
2.3.0 :215 > DiagnosesIndex.script_score("_score.intValue()").query(match: {name: "cham k"}).map(&:_score)
  DiagnosesIndex Search (13.1ms) {:body=>{:query=>{:function_score=>{:functions=>[{:script_score=>{:script=>"_score.intValue()"}}], :query=>{:match=>{:name=>"cham k"}}}}}, :index=>["diagnoses"], :type=>[]}
 => [1.6095443, 1.0535263, 1.023123, 1.0199432, 1.0059652, 0.0, 0.0, 0.0, 0.0, 0.0] 
```
 Values do change but still in double values and not being integers. I'm not sure what causing this or what's really behind this?

**Comment by pyromaniac** [comment]
_score is a float number, not sure what are you trying to do

**Comment by knd** [comment]
@pyromaniac so calling *_score* always yield float values after all even though I'm trying to get integer values like `ceil(_score)`, `floor(_score)`, `abs(_score)`, `_score.intValue()` in script_score? Integer values are what I'm trying to get.

**Comment by pyromaniac** [comment]
I haven't play with function score, so can't help you here, but obviously you are doing something wrong and it is not related to chewy, read ES docs carefully

**Comment by knd** [comment]
Thanks @pyromaniac, I was hoping to understand what's going behind this mystery.

**Comment by pyromaniac** [comment]
I'm sorry I couldn't help you more
