### ISSUE TITLE
Unable to use client side cert and key

### ISSUE THREAD

**Issue by evuolas** [toptal/chewy#357]
We are using client side certificate to authenticate to our Elasticsearch cluster and we are setting the certificate and correspongin keys as follows:

``` ruby
Chewy.settings = {
  transport_options: {
    ssl: {
      ca_file: './config/ca.crt',
      client_cert: OpenSSL::X509::Certificate.new(File.read('./config/client.crt')),
      client_key: OpenSSL::PKey::RSA.new(File.read('./config/client.key'))
    }
  }
}
```

Configurations are duplicated by Chewy in:
https://github.com/toptal/chewy/blob/master/lib/chewy.rb#L127

But `OpenSSL::PKey::RSA` instance can't be duplicated. `OpenSSL::PKey::RSA#dup` returns a new instance, but the actual key is not copied to the new instance. I'm not sure if thats a bug in OpenSSL module or is that intended behaviour.

We have monkey patched `OpenSSL::PKey::RSA` as a workaround in our project, but maybe this should be included to Chewy also to allow use of client side certificates? Or maybe there are better ways to handle this issue?

``` ruby
class OpenSSL::PKey::RSA
  def duplicable?
    false
  end
end
```

**Comment by pyromaniac** [comment]
Well, actually I don't see any reason for configuration duplication. We can simply do `client_configuration .except(:prefix)` instead. If you will send a patch - would be just perfect.
