### ISSUE TITLE
Dead links in README

### ISSUE THREAD

**Issue by ReadmeCritic** [toptal/chewy#358]
Should these be updated/removed

🔴  404 https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-root-object-type.html
🔴  404 https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-geo-point-type.html

Full results https://gist.github.com/96cab3546d58dd6f02b8

**Comment by pyromaniac** [comment]
Oh, thanks, I'll keep this in mind and fix eventually

**Comment by pyromaniac** [comment]
Fixed, thanks again!
