### ISSUE TITLE
Why includes are removed from ActiveRecord scopes at index time ?

### ISSUE THREAD

**Issue by msievers** [toptal/chewy#366]
I had some trouble using ActiveRecord scopes with chewy, till I discovered, the `includes` are removed from `scopes` and that was the cause, why my scopes *do* work on the console as expected, but using them to index the model *fails*.

The code I mean (introduced with `0.8.2`) is located here

https://github.com/toptal/chewy/blob/master/lib/chewy/type/adapter/active_record.rb#L45

I downgraded to version 0.8.1 and everything works fine.

Removing `includes` from scopes makes it a lot more complicated to use some more advanced scopes at index time. Therefore I would like to request to reconsider this decision.

**Comment by pyromaniac** [comment]
Hey, sorry, I've just woke up :)

Can you provide an exact example when includes are required for id fetching?

**Comment by msievers** [comment]
@pyromaniac Sure, it's even quite simple to construct one which fails.

Assume there are albums which may have records. There is a scope which only returns albums which actually have records.

```ruby
class Album < ApplicationRecord
  has_many :records

  scope :with_records, -> { includes(:records).where.not(records: { id: nil }) }
end

class Record < ApplicationRecord
  belongs_to :album
end
```

The corresponding index file should look like this

```ruby
class AlbumsIndex < Chewy::Index
  # this does not work, because the scope uses includes, which are removed
  define_type Album.with_records do
    field :title
  end
end
```

As soon as the `except(:includes)` statements are removed from `lib/chewy/type/adapter/active_record.rb` the scope can be used and `rake chewy:reset` correctly indexes 2 albums.

I created a basic rails app with these two models for you so that you can quickly reproduce this. Have a look at [msievers/chewy-includes-example](https://github.com/msievers/chewy-includes-example)

**Comment by pyromaniac** [comment]
Hm, you are right, will remove it, or you can do it if you want and have some time.

**Comment by msievers** [comment]
Because not removing the includes may have significant performance drawbacks in certain situations, I close this for now. See the attached PR for further informations.
