### ISSUE TITLE
When update index for model, got {:delete=>1}

### ISSUE THREAD

**Issue by hieuns** [toptal/chewy#371]
Hello every body! I'm using Chewy 0.8.4 with Rails 4.2.1. I declare `update_index` in a model and when a record of that model is created, in log of Rails server it said something like:

``` ruby
ModelsIndex::TypeOfModel Import (2.6ms) {:delete=>1}
```

And there is no new document create for that record in Elastic search database. I don't know why it doesn't create new document and instead of `{:index=>1}`, it outputs `{:delete=>1}`. Do you know which case that Chewy/Elastic search doesn't create new document and output `{:delete=>1}` like that? Thank you very much!
(Sorry I can not show detail of the model because it is from a project of my company :bow: )

**Comment by pyromaniac** [comment]
How did you define the type? Which scope did you use? Is the record included in this scope?

**Comment by hieuns** [comment]
Thank you for your quickly response. I'm really sorry but I can's show the detail (I know that it is very uncomfortable when doing something without detail :bow: ). The record is included in the scope I use in `define_type`, I checked that. I set `binding.pry` inside the `define_type`'s block and it goes to there. But after that block and when rails server done response, the server's log show that `{:delete=>1}` line. I just wonder which case that Chewy shows that `{:delete=>1}`, I will try to investigate my code to find out my bug with any clue about that case.
Thanks in advance and sorry for your inconvenience.

**Comment by hieuns** [comment]
I've found the cause of that bug. In my scope, I find record by an array of ids return from a function (those ids are not fixed):
```sql
SELECT * FROM table WHERE id in (1, 2, 3)
```
and for some reasons, the id of new record (4, for instance) is not included in the array when execute the documenting process (when I check with the scope, it does include the new id). And when the function `default_scope_where_ids_in` in `lib/chewy/type/adapter/orm.rb` (line 128) is called in line 108, the query is:
```sql
SELECT * FROM table where id in (1, 2, 3) and id in (4)
```
So the new record is considered to not appear in the scope and it delete the document instead of create (output `{:delete=>1}`).

**Comment by Diasporism** [comment]
I know this was closed forever ago, but my company has been struggling with randomly failing specs for years due to this issue. I was able to track down and confirm we were running into the same bad query issue and I found a workaround:

```ruby
define_type ModelName.unscoped do
...
end
```

Chaining `.unscoped` ensures stale bits of queries don't pollute subsequent imports.
