### ISSUE TITLE
Unable to run `rake elasticsearch:start`

### ISSUE THREAD

**Issue by sevab** [toptal/chewy#377]
I'm trying to start Elastic cluster for tests in development using the recommended in Readme `rake elasticsearch:start`, but for some reason it throws an error:

```
rake aborted!
Don't know how to build task 'elasticsearch:start' (see --tasks)
/Users/.../.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/.../.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
```

Running `rake -T` lists all `rake chewy:*` tasks, but neither `rake elasticsearch:start` nor `rake elasticsearch:stop` are listed.

**Comment by pyromaniac** [comment]
It is provided by elasticsearch-ruby gem, check its description out.
