### ISSUE TITLE
Dynamically adding fields to mapping

### ISSUE THREAD

**Issue by arinhouck** [toptal/chewy#394]
I am trying to find a way to dynamically add fields to my ElasticSearch mapping using Chewy. I have an `attribute` model that corresponds to a field on the mapping and when a user creates a new `attribute` it should be added to the mapping accordingly.

The new field gets added to the mapping by Chewy's `update_index` but Rails will not recognize the updated mapping until the server is restarted. Is this something that is supported?

**Comment by pyromaniac** [comment]
You probably want to play with ES dynamic templates. So it would be better not to change the type fieldset itself, but define `field :attributes` as a usual hash and use dynamic templates to set up additional properties.

**Comment by arinhouck** [comment]
Great suggestion @pyromaniac. We were able to work out a solution with dynamic templates.
