### ISSUE TITLE
Add concerns directory to Rails autoload paths

### ISSUE THREAD

**Issue by nbulaj** [toptal/chewy#397]
Hi. I get the following situation during the work with the `chewy` gem: more then 3 index objects share a common functionality - _full search_, that implemented in the standalone module and is included in the necessary files. I was thinking about to move it to the "_concerns_" directory (as it done for models and controllers):

```
├── app/
│   ├── chewy/
│   │   ├── concerns/
│   │   │   ├── full_search.rb
│   │   ├── user_index.rb
│   │   ├── comment_index.rb
│   │   ├── post_index.rb
...
```

But `chewy` gem [doesn't add "concerns" directory](https://github.com/toptal/chewy/blob/master/lib/chewy/railtie.rb#L75) to the autoload paths. I think that this situation is quite prevalent (common functionality between several indexes), so adding concerns autoloading would be a great solution. 

What do you think about it, @pyromaniac? Thanks.

**Comment by nbulaj** [comment]
@pyromaniac have you seen the issue?

**Comment by pyromaniac** [comment]
Hey, sorry, I've missed it somehow. Well, I believe that everybody is able to add one more line to `application.rb`. But you are free to submit a PR, why not.

**Comment by nbulaj** [comment]
@pyromaniac Rails 5 [fixed the issue](https://github.com/rails/rails/blob/master/railties/lib/rails/engine/configuration.rb#L39) by adding concerns directory for every subdirectory to autoload: 

```ruby
paths.add "app", eager_load: true, glob: "{*,*/concerns}"
```

So in Rails 5 it works perfectly. What we decide to do for older versions of Rails ?

**Comment by pyromaniac** [comment]
As I said - not a big deal. Everyone can add it manually it it is necessary.

**Comment by nbulaj** [comment]
I think your are right.
