### ISSUE TITLE
Fuzzy searches

### ISSUE THREAD

**Issue by ziazek** [toptal/chewy#399]
Is it possible to do [fuzzy searches] (https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-fuzzy-query.html) in Chewy using the _fuzziness_ setting? I've tried looking through the code but could not get any clues how to move forward. 

Any help would be greatly appreciated. Thanks.

**Comment by pyromaniac** [comment]
Yeah, just pass everything to query like: `MyIndex.query(fuzzy: {field: {value: '42', fuzziness: 2}})`

**Comment by ziazek** [comment]
@pyromaniac Thanks for the quick reply! I'll try it out and report back.

**Comment by ziazek** [comment]
Update: it works. For anyone who stumbles on this, I used this in my code: `MyIndex.query(match: {owner: {query: params[:search], fuzziness: 'AUTO'}})` ("owner" is a field of the object)

Thanks @pyromaniac for the help.
