### ISSUE TITLE
Correct usage of #boost_factor?

### ISSUE THREAD

**Issue by ziazek** [toptal/chewy#400]
I tried to use #boost_factor, but I can't figure out the correct usage.

`GeoIndex.query(match: {continental_region: {query: "america"}}).boost_factor(3, filter: {term: {continental_region: 'Latin America'}})`

Thanks!

**Comment by pyromaniac** [comment]
Can you post the result query? Usage seems to be correct.

**Comment by ziazek** [comment]
https://gist.github.com/ziazek/658cfb5fc7c0b6b8bf66d906faacd426

It's no different from the results I get without using #boost_factor.

**Comment by pyromaniac** [comment]
I was asking about the request body. Also, the problem seems to be in ES misusing. Read ES docs carefully.

**Comment by ziazek** [comment]
OK, thanks.
