### ISSUE TITLE
[term] query does not support array of values

### ISSUE THREAD

**Issue by monika-khatri** [toptal/chewy#401]
I want to fire an IN query

I have array of state_ids = [1,2,3]

EventsIndex.query(term: {satate_id: state_ids})

Above query gives me following response

{:body=>{:query=>{:term=>{:state_id=>[12]}}}, :index=>"events", :type=>["event"]}
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"query_parsing_exception","reason":"[term] query does not support array of values","index":"events","line":1,"col":19}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"events","node":"7JgZ0TjbRO2Ix1j4eR8auw","reason":{"type":"query_parsing_exception","reason":"[term] query does not support array of values","index":"events","line":1,"col":19}}]},"status":400}

Please help me to solve this issue.

**Comment by GabKlein** [comment]
You have to use `terms`
```
EventsIndex.query(terms: { satate_id: state_ids })
```

**Comment by monika-khatri** [comment]
Thank you for update.

I am still facing an issue with filter with state_id

Event.where(state_id: [5, 8, 12]) gives me 42 results from database but

EventIndex.query(terms: {state_id: [5, 8, 12]}) gives 0 results.

Can you please help me to find out the issue?

My EventIndex do have field :state_id, type: 'integer' configured.

**Comment by pyromaniac** [comment]
`EventIndex.filter(terms: {state_id: [5, 8, 12]})`

**Comment by GabKlein** [comment]
Try this 
```
field : state_id, type: 'string', index: 'not_analyzed'
```
