### ISSUE TITLE
Modernization - ES2.0, Ruby upgrade, etc.

### ISSUE THREAD

**Issue by robacarp** [toptal/chewy#403]
While working on #396, I notice that several things are starting to fall out of date with Chewy, making it a little risky for us to include it into our business. However, I've not yet found any comparable query / index definition paradigm so I'd like to see the project continue. 

Given that toptal is sponsoring the development, I understand that there can be business or organizational reasons why certain dependencies aren't up to date. For example, perhaps toptal.com is locked into Ruby 2.0.0 (or another aging dependency) for some reason.

Are there any outside constraints helping cause the dependency age in Chewy? If not, is it possible to begin to upgrade the short list of dependencies?

On a related subject, I couldn't find any definitive statement in issues or pulls about Chewy's ElasticSearch 2 compatibility. I understand that there are some breaking API changes which certainly will impact Chewy, but there are also other features we'd like to take advantage of which aren't present in ES1.7, notably the [nested data type](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html) which I also don't see mentioned in the readme here. Broadly speaking, is Chewy ES2 compatible?

Given the apparent willingness of the project to accept pull requests, I'm happy to help contribute to these upgrades as time allows, but I'd like to make sure that there aren't external constraints that will prevent some necessary upgrades from happening. 

Thanks!

**Comment by pyromaniac** [comment]
Hey, thanks for your passion here! So, first of all, Toptal is using mostly a cutting edge of technologies. So we are almost always up to date with ruby and rails.

Chewy is 2.0 compatible as soon as 2.0 didn't remove 1.7 features, just deprecated them. But you are right, for example, queries DSL is requiring some rework to be compatible with the new approach (filters are inside queries) and features. However, you are able to do queries even without chewy DSL, nothing prevents you from it, just use MyIndex.client for it directly.

The most important part of chewy - indexes, model callbacks and strategies is mostly ES-independent.

That nested data type is a new feature, but it should simply work, just try it.

Looking forward to see your proposals and contributions.
