### ISSUE TITLE
Filter by indices

### ISSUE THREAD

**Issue by witliving** [toptal/chewy#404]
Hi,

I'm trying to switch from elasticsearch-rails to chewy, and im struggling with making a similiar query to this.

``` ruby
Elasticsearch::Model.search({
            filter: {
              indices: {
                indices: [Campaign.index_name],
                filter: {
                  not: {
                    filter: {
                      terms: {
                        id: unacessible_ids
                      }
                    }
                  }
                }
              }
            },
            query: {
              query_string: {
                query: params[:query]
              }
            }
          }, 
          [
            SuperCampaign,
            Campaign
          ]
        )
```

Is this even possible with chewy? Thanks

**Comment by pyromaniac** [comment]
So you want to query for several indexes, right?

**Comment by ddxtreme** [comment]
Yes, querying and specifying filters for some of the indexes

**Comment by pyromaniac** [comment]
Well, there are 2 options: you are still able to use elasticsearch-rails or elasticsearch-ruby API using Chewy.client directly, or if you want to use the Chewy DLS - you can initialize `Chewy::Query` directly for the several indexes, check out this: https://github.com/toptal/chewy/blob/master/lib/chewy/query.rb#L26

Btw, I've just realized how to implement multiple indexes support with the chewy DSL, thanks! :) Will do it later.

**Comment by ddxtreme** [comment]
Ok, i've managed to get what i wanted. I will post here for further related searches.

```ruby

query = Chewy::Query CampaignIndex, SuperCampaignIndex

query.filter(
  indices: { 
    indices: ["brand"], 
    filter: {
      not: {
        filter: {
          terms: {
            _id: [44]
          }
        }
      }
    }
  }
 ).query(term: {name: "teste"})
```
