### ISSUE TITLE
Query multiple indices 

### ISSUE THREAD

**Issue by antoniusostermann** [toptal/chewy#405]
We have multiple indices, for example one containing users and one containing the users contributed content. In the fulltext search, we'd like to query all these indices and still have a great order of the returned results. For example, if the user enters "foo", the search should return as well users called "foo" as contents with "foo" in it's title.

These indicies do already exist, and I want to query nearly all of their own respective fields in that search. So I do not want to create a new index just to combine all of my elastic search contents with all of it's attributes in it.

My current idea is to either let elastic search do all of it or let me return the score of each entry and merge the results on my own (as long as it is in any way possible to achieve a reasonable result that way..)

I can't find any hints in the chewy docs how to query multiple indices or how to get the entrys scoring.. Is there any option to achieve my goal? :-)

**Comment by pyromaniac** [comment]
Check out this: https://github.com/toptal/chewy/issues/404#issuecomment-230232963

**Comment by BenEmdon** [comment]
On GitHub Classroom we perform a multi index search like so:
```ruby 
Chewy::Search::Request.new(FirstIndex, SecondIndex, ThirdIndex, ...)
  .query(...) # your query here

# This can also be done through the Query interface like so:
Chewy::Query.new(FirstIndex, SecondIndex, ThirdIndex, ...)
  .query(...) # your query here
```

If you want to see how we did it with pagination take a look at https://github.com/education/classroom/pull/1588
