### ISSUE TITLE
Better instructions on how to setup development environment

### ISSUE THREAD

**Issue by guigs** [toptal/chewy#406]
I had a hard time trying to build elasticsearch in order to run chewy tests.

I've already opened an issue in elasticsearch-ruby project (https://github.com/elastic/elasticsearch-ruby/issues/326).

But after I successfully built elasticsearch, I still needed to set some variables before running the tests:

```
export TEST_CLUSTER_COMMAND=~/elasticsearch-ruby/tmp/builds/elasticsearch-2.1.3-SNAPSHOT/bin/elasticsearch
export BUNDLE_GEMFILE=gemfiles/rails.3.2.activerecord.gemfile
```

Then I can run:

```
bundle exec rake elasticsearch:start
bundle exec rspec
```

Improving docs and linking to instructions on how to install pre-requisites will make it easier to contribute.

**Comment by pyromaniac** [comment]
You probably have to install ES as a system package using brew or apt-get or whatever you have in the system.

**Comment by pyromaniac** [comment]
Sorry for the late answer
