### ISSUE TITLE
Not able to use search query filters

### ISSUE THREAD

**Issue by hashwin** [toptal/chewy#416]
Hi, I just started on the Chewy gem, looks like a great idea, but I'm unable to get it working properly with even a super basic query.

I have indexed my Lead model as LeadsIndex.
Here I have a query that works:

```
irb(main):068:0> LeadsIndex.filter.first
  LeadsIndex Search (8.9ms) {:body=>{}, :index=>["leads"], :type=>[]}
=> #<LeadsIndex::Lead:0x007ff76324cbf8 @attributes={"id"=>"14", "name"=>"Victoria Roob", "_score"=>1.0, "_explanation"=>nil}, @_data={"_index"=>"leads", "_type"=>"lead", "_id"=>"14", "_score"=>1.0, "_source"=>{"name"=>"Victoria Roob"}}>
```

But when I try to search for that very record, it shows no results:

```
irb(main):071:0> LeadsIndex.filter { name == "Victoria Roob" }.first
  LeadsIndex Search (7.4ms) {:body=>{:query=>{:filtered=>{:query=>{:match_all=>{}}, :filter=>{:term=>{"name"=>"Victoria Roob"}}}}}, :index=>["leads"], :type=>[]}
=> nil
```

Am I doing something wrong?

**Comment by pyromaniac** [comment]
Sorry for the late answer.

Yeah, you are probably doing it wrong. Name is an indexed field, so it is not stored as `Victoria Roob` in ES. Read more ES docs about the indexing internals. You have to use either query here or non-indexed field.
