### ISSUE TITLE
Chewy::UndefinedUpdateStrategy: updating indexed model from within background job

### ISSUE THREAD

**Issue by PepperTeasdale** [toptal/chewy#419]
Hello! First off, I love the gem; it's made working with ES super convenient in a few Rails projects I've used. Recently I've had some issues when I try to update an indexed model from within a Sidekiq job. Using Ruby 2.3.1, Rails 4.2.5.2 and Chewy 0.8.2:

In config/initializers/chewy.rb:

``` Ruby
Chewy.request_strategy = :sidekiq
Chewy.logger = Logger.new(STDOUT)
Chewy.logger.level = Logger::INFO
```

and as script that updates our User model (`UsersIndex << Chewy::Index`):

``` Ruby
class SampleWorker
  include Sidekiq::Worker

  def perform(params)
    @params = params

    some_method_that_updates_the_user_model
  end
end
```

I get:

```
Chewy::UndefinedUpdateStrategy
Index update strategy is undefined in current context.
Please wrap your code with `Chewy.strategy(:strategy_name) block.`
```

I have tried following that hint, using `strategy(:atomic)` and `sidekiq`, but keep getting the same error message. If I move the update out of the worker, everything works as expected, however it is important that the code in question is performed in the background. I've not been able to find anything relevant to my problem in the docs, sorry if I'm missing something obvious.

Please advise.

**Comment by pyromaniac** [comment]
well,

```
def perform(params)
  @params = params

  Chewy.strategy(:atomic) { some_method_that_updates_the_user_model }
end
```

should do the trick

**Comment by PepperTeasdale** [comment]
Hey, sorry for taking so long to get back to this -- I got pulled onto a different project and this fell to the wayside. For whatever reason the way I was wrapping the code in the atomic strategy block was not working previously, but now I am doing something similar with a different model, and it works. Thanks for your help!

**Comment by thechrisoshow** [comment]
I solved this by using an around_perform within ApplicationJob:

```ruby
class ApplicationJob < ActiveJob::Base
  around_perform do |job, block|
    Chewy.strategy(:atomic) do
      block.call
    end
  end
end
```
This works because all of my jobs inherit from ApplicationJob.

**Comment by perkins2099** [comment]
Is there a way to set a default strategy for for sidekiq jobs, similar to how you did above?

Each sidekiq job that runs and modifies an index causes this error unfortunately.  Would be nice to have a blanket strategy here.

**Comment by oozzal** [comment]
@perkins2099 Here's how to set a default strategy for sidekiq jobs: https://github.com/education/classroom/pull/378/files
