### ISSUE TITLE
Undefined update strategy inside rake task

### ISSUE THREAD

**Issue by dzunk** [toptal/chewy#424]
Good afternoon, I'm receiving an `Chewy::UndefinedUpdateStrategy` error when creating or updating a Chewy-enabled model - but only when doing so within a rake task.

I've tried wrapping the individual call to the `save` method in a strategy block like so:

``` ruby
# This throws an UndefinedUpdateStrategy error
employees.each do |employee|
  Chewy.strategy(:atomic) do
    employee.save
  end
end
```

I also tried wrapping the entire parse method.

``` ruby
# This also throws an UndefinedUpdateStrategy error
Chewy.strategy(:atomic) do
  parse_employees(file_handle) # this method contains the save call
end
```

Neither had any effect. Interestingly, I was able to drop in a completely new block of code like so:

``` ruby
# This works fine
Chewy.strategy(:atomic) do
  EmployeesIndex.reset!
end
```

^ and that resets the index properly - it's only when calling `save` on individual employees that the error occurs.

Aside from the specific issue, I also don't understand why this error is occurring in the first place. The rake task initializes the Rails environment, so I would have thought that the Chewy configuration should be available from the get-go without needing to be wrapped in a block.

It's worth noting that when I run the same code from the console, it works fine - the error only occurs when it's wrapped in a rake task.

Any thoughts out of the gate? I can provide a sample app to replicate the problem if necessary.

**Comment by dzunk** [comment]
It looks like this may be the same problem as #419 actually.

**Comment by pyromaniac** [comment]
Yeah, right

**Comment by pyromaniac** [comment]
First of all, EmployeesIndex.reset! doesn't need to be wrapped with a strategy, it works as is.

Also, this should work (and is a correct way actually):

```ruby
Chewy.strategy(:atomic) do
  parse_employees(file_handle)
end
```

Are you sure this error comes from the inside of the block? Can you trace it?

**Comment by dzunk** [comment]
So I was trying to replicate the error with our latest importer code and I wasn't able to do so. Wrapping it in the strategy block worked.

The major architecture change was that we originally had an async component (since removed) running with RabbitMQ using the Bunny gem - I'll try tomorrow to provide an example with the older code and see if the asynchronous part was what's causing the error.

As an aside, though, is there a way to have the rake tasks load the regular Chewy defaults to avoid having to wrap our code in the strategy block?

**Comment by pyromaniac** [comment]
I didn't find an acceptable way to do this, unfortunately. Unlike controllers or migrations rake tasks might have different requirements, so it is better to go explicit.

**Comment by lfv89** [comment]
This doesn't only happen with rake tasks but also with background jobs (https://github.com/toptal/chewy/issues/419)

Are we sure there is no way to default wrap the strategy definition for rake tasks and background jobs? I could gladly jump into this if it would be possible to do so.

**Comment by pyromaniac** [comment]
You can do it in your project as you want to.

```ruby
    class DelayedChewy < Delayed::Plugin
      callbacks do |lifecycle|
        lifecycle.around(:invoke_job) do |*args, &block|
          Chewy.strategy(:atomic) do
            block.call(*args)
          end
        end
      end
    end

Delayed::Worker.plugins << DelayedChewy
```

The only problem here is that requirements will be really different, so I would not propose a generic way.

**Comment by ajays1991** [comment]
+1

**Comment by rbq** [comment]
Is there a reasonable way to pick a default for Rake tasks? I'm trying to run the provided Paperclip task to refresh thumbnails and Chewy breaks those.

**Comment by pyromaniac** [comment]
try this: https://stackoverflow.com/questions/15707940/rake-before-task-hook

**Comment by rbq** [comment]
@pyromaniac Thanks! I ended up with something like this to set a default:

```ruby
namespace :chewy_strategies do
  task :bypass do
    Chewy.strategy :bypass
  end

  task :atomic do
    Chewy.strategy :atomic
  end
end

Rake::Task.tasks.each do |task|
  task.enhance do
    Rake::Task['chewy_strategies:bypass'].invoke
  end
end
```

Feels like a dirty hack, but works for now. Btw., re-opening the namespace `:chewy` to add tasks doesn't work, is makes the built-in Chewy task disappear. Oo
