### ISSUE TITLE
Attachment field example

### ISSUE THREAD

**Issue by 3dd13** [toptal/chewy#43]
I am using Carrierwave for the s3 file upload and have elasticsearch-mapper-attachments plugin installed for my elasticsearch

```
# app/chewy/candidate_index.rb
class CandidateIndex < Chewy::Index
  define_type Candidate.includes({:campaign_invitation => :labels}, :campaign_response_details) do
    field :resume, type: 'attachment', value: -> (candidate) {
      if candidate.resume.present?
        Base64.encode64(open(candidate.resume.url) { |doc| doc.read })
      else
        ""
      end
    }
  end
end

# app/models/candidate.rb
class Candidate < ActiveRecord::Base
  mount_uploader :resume, ResumeUploader

  def self.search(options)
    fields = [ 'resume' ]
    CandidateIndex.query(multi_match: { query: options[:keyword], fields: fields })
  end
end
```

**Comment by caherrerapa** [comment]
thnx @3dd13 just what i was looking for

**Comment by icortex** [comment]
Hi @3dd13 I'm following your example but I'm getting an error: 

`Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"query_shard_exception","reason":"Attachment fields are not searchable: [resume]","index_uuid":"6TkSHMMJQSSwcTimqBRgmQ","index":"candidates_1500503250849"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"candidates_1500503250849","node":"wxVUZ0hmSZKbdpZ0_Y1qUA","reason":{"type":"query_shard_exception","reason":"Attachment fields are not searchable: [resume]","index_uuid":"6TkSHMMJQSSwcTimqBRgmQ","index":"candidates_1500503250849"}}]},"status":400}`

I'm using the latest version of Elasticsearch and Chewy with the mapper-attachement plugin.

Any ideas?

**Comment by yortz** [comment]
@icortex I was experiencing the very same kind of error, what I needed to do was to explicitly look for the `content` attribute of the attachment to be able to get back some results, so you can write the query in this way from console:

`CandidateIndex.query(query_string: { query: "lorem", fields: ['attachment.content'] })`

you can also use `multi_match` if you want, I also think that the example in the wiki needs to be updated https://github.com/toptal/chewy/wiki/Using-attachment-mapping-field-in-Chewy haven't been using this with carrierwave but with some simple metal implementation of local file upload with ruby.
