### ISSUE TITLE
Problems with journaling and indexes in modules

### ISSUE THREAD

**Issue by fpbouchard** [toptal/chewy#431]
Hi, we are having issues with `apply_changes_from` with journaling with indexes inside modules.

The way the index is serialized is using `_index_name` which calls `demodulize`. Then, when replaying the journal, `derive_type` is called to infer the index, but it is missing the module. `derive_type` does work with modules using the slash notation: `module/index#type`.

We are wondering if the fix should be in `_index_name` or in the way the index is serialized in the journal.

Any thoughts?
P.S. I did want to create a spec to reproduce the issue, but I can't seem to run the specs on `master`. `bundle` doesn't work: 

You have requested:
  listen ~> 3.0.0

The bundle currently has listen locked at 2.10.0.
Try running `bundle update listen`

If you are updating multiple gems in your Gemfile at once,
try passing them all to `bundle update`

**Comment by pyromaniac** [comment]
Yeah, probably `_index_name` have to be fixed. Actually, there should be even another method used because `_index_name` have a specific meaning.

As for bundler, just try `bundle update`, should help.
