### ISSUE TITLE
[terms] query does not support

### ISSUE THREAD

**Issue by ThomAille** [toptal/chewy#435]
Hi, 

I want to make a filter on multiple terms. But I have an error ElasticSearch

> [400] {"error":{"root_cause":[{"type":"query_parsing_exception","reason":"[terms] query does not support [regions]","index":"recipes","line":1,"col":242}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"recipes","node":"fxYfW4K0QUiUUJMgHB4oHg","reason":{"type":"query_parsing_exception","reason":"[terms] query does not support [regions]","index":"recipes","line":1,"col":242}}]},"status":400}

Here is the configuration of my index : 
define_type Recipe.with_accepted_state.includes(:ingredients,:regions,:steps,:photos,:diets,:healths,:meal_categories,:variants,:bases,:recipe_links, :creator) do
    field :name, type: 'multi_field' do
      field :name, index: 'analyzed', analyzer: 'autocomplete'
      field :sorted, index: 'analyzed', analyzer: 'sorted'
    end
    field :thumbnail, type: 'string', index: 'no', value: ->(recipe) { Base64.encode64(File.open(Rails.root.to_s + "/public" + URI.unescape(recipe.photos.first.file.url(:medium)), "rb").read) if recipe.photos.first && recipe.photos.first.file  }
    field :preparation_time, type: 'integer'
    field :cooking_time, type: 'integer'
    field :utensils, type: 'string'
    field :calories, type: 'integer'
    field :dietary
    field :min_nb_of_servings, type: 'integer'
    field :nutrients
    field :workflow_state, type: 'string'
    field :slug, type: 'string'
    field :break_time
    field :created_at
    field :updated_at
    field :full_name, type: 'string', value: -> { [creator.first_name, creator.last_name].join(' ') }
    field :creator_thumbnail, type: 'string', index: 'no', value: -> (recipe) { Base64.encode64(File.open(Rails.root.to_s + "/public" + URI.unescape(recipe.creator.profile_picture.url(:thumb)), "rb").read) if recipe.creator.profile_picture && recipe.creator.profile_picture  }
    field :meal_categories, index: 'not_analyzed', value: ->{ meal_categories.map(&:name) }
    field :meal_categories_color, index: 'not_analyzed', value: ->{ meal_categories.map(&:color) }
    field :regions, type: 'string', index: 'not_analyzed', value: ->{ regions.map(&:name) }
    field :ingredients do
      field :name, type: 'string', analyzer: 'autocomplete'
      field :quantity, type: 'string'
    end
    field :diets, type: 'string', index: 'not_analyzed', value: ->{ diets.map(&:label) }
    field :healths, type: 'string', index: 'not_analyzed', value: ->{ healths.map(&:label) }
  end

Here is my request sent to the ElasticSearch
> {:body=>{:query=>{:filtered=>{:query=>{:query_string=>{:fields=>[:name], :query=>"courge", :default_operator=>"and"}}, :filter=>{:and=>[{:range=>{:preparation_time=>{:gte=>"2", :lte=>"120"}}}, {:range=>{:cooking_time=>{:gte=>"0", :lte=>"180"}}}, {:terms=>{:regions=>"[\"Andorre\", \"France\"]"}}]}}}, :aggregations=>{:stats_preparation=>{:stats=>{:field=>"preparation_time"}}, :stats_cooking=>{:stats=>{:field=>"cooking_time"}}, :stats_calories=>{:stats=>{:field=>"calories"}}, :terms_categories=>{:terms=>{:field=>"meal_categories"}}, :terms_healths=>{:terms=>{:field=>"healths"}}, :terms_regions=>{:terms=>{:field=>"regions"}}}, :size=>60, :from=>0}, :index=>["recipes"], :type=>[]}

Do you have a solution for my error ?

Best Regards
Thomas

**Comment by ThomAille** [comment]
I just fix my error. 
I used the example of chewy developed by TopCal
I change this line to terms that works : `attribute :meal_categories, mode: :arrayed, type: String, normalize: ->(value) { value.reject(&:blank?) }` for  `attribute :meal_categories, type: Array`

**Comment by pyromaniac** [comment]
Oh, sorry, missed this :) Anyway, kudos!
