### ISSUE TITLE
Completion Suggester: Enable special mapping

### ISSUE THREAD

**Issue by ricardopacheco** [toptal/chewy#442]
"To use this feature, specify a special mapping for this field, which indexes the field values for fast completions." [Documentation](https://www.elastic.co/guide/en/elasticsearch/reference/master/search-suggesters-completion.html#completion-suggester-mapping)

Chewy does this automatically after import the indexes or not? Or the procedure is really manual?

If already, what do i do?

**Comment by pyromaniac** [comment]
Nope, chewy doesn't do it automatically, you literally have to do what's described in the doc. Create mapping, do queries.
