### ISSUE TITLE
Filter feature generating deprecation warning

### ISSUE THREAD

**Issue by aselder** [toptal/chewy#444]
When I use the `filter` function on an index (for example `AccountsIndex::Account.filter{ subscription.plan == "Basic" }.total_count`) , I'm getting the following warning in the logs:

```
The [filtered] query is deprecated, please use a [bool] query instead with a [must] clause for the query part and a [filter] clause for the filter part.
```

With a little debugging, the above query was generating the following JSON being sent to the server:

```
{:query=>{:filtered=>{:query=>{:match_all=>{}}, :filter=>{:term=>{"subscription.plan"=>"Basic"}}}}}
```

**Comment by pyromaniac** [comment]
Yeah, this is simply an outdated Chewy queries code, we are going to update it, but didn't manage yet, sorry

**Comment by aselder** [comment]
@pyromaniac No need to apologize. Chewy is awesome. Just trying to do my little bit to help out.

**Comment by pyromaniac** [comment]
Yeah, we are planning to introduce Query2 to support ES >= 2 properly, so hope it is only a matter of time.

**Comment by jnicklas** [comment]
Just hit this, seems like this has now been completely *removed* not just deprecated. Getting errors like this:

```
     Elasticsearch::Transport::Transport::Errors::BadRequest:
       [400] {"error":{"root_cause":[{"type":"parsing_exception","reason":"no [query] registered for [filtered]","line":1,"col":22}],"type":"parsing_exception","reason":"no [query] registered for [filtered]","line":1,"col":22},"status":400}
```

**Comment by aselder** [comment]
@jnicklas, if you go back to elasticsearch 2.4, you should be OK until the gem gets updated

**Comment by jnicklas** [comment]
@aselder that's what I did to work around this for the time being. Thanks :)

**Comment by rtapali** [comment]
Any updates on fixing this issue ?

**Comment by ralbt** [comment]
Any updates on fixing this issue ?

**Comment by Spazer9** [comment]
Any updates on this? seems like the gem doesn't work ES5 now

**Comment by pyromaniac** [comment]
https://github.com/toptal/chewy/pull/493
