### ISSUE TITLE
Partial word search

### ISSUE THREAD

**Issue by raviada** [toptal/chewy#446]
for example 
This oak grain is of the highest quality, leaving ...

how to implement autocompletion functionality? for example "oa" should return match "oak",,, as we type in the search criteria, how do I setup creating such indexes.

I was following the demo, but it always expects the complete word to match. I am getting empty results when I partially type and send that query string.

any help would be appreciated.

Thanks
Ravi Ada

**Comment by pyromaniac** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters-completion.html
