### ISSUE TITLE
Including query parameters in REST API URL

### ISSUE THREAD

**Issue by sevab** [toptal/chewy#447]
I'm trying to do [response filtering](https://www.elastic.co/guide/en/elasticsearch/reference/current/common-options.html#_response_filtering) to reduce size of the payload returned by elastic and need a `filter_path` param to be included in the REST APIs request, e.g.:

`my_index/_search?filter_path=took,**.total,hits.**._source`

Is there a clean and correct way of doing it via the Chewy APIs?

**Comment by pyromaniac** [comment]
Wow, missed this somehow, sorry. Nope, you can only filter returned fields, like: `.only(:field1, :field2)`
