### ISSUE TITLE
[!] You are using unsupported method [delete_by_query]

### ISSUE THREAD

**Issue by Diasporism** [toptal/chewy#448]
Hello,

I recently made the jump to Elasticsearch 2.4.1 (and bumped Chewy to 0.8.4 from 0.8.3) and started receiving this warning/error in our logs: "You are using unsupported method [delete_by_query]".

I've installed the delete by query plugin for elastic search which didn't seem to help. I've also noticed the error in your own Travis CI logs: https://travis-ci.org/toptal/chewy/jobs/165732960

Any idea what's causing this or if we should be concerned?

**Comment by pyromaniac** [comment]
This this is a warning by `elasticsearch-ruby` gem. Use the plugin and ignore the warning for a while. `delete_all` have to be reimplemented to the version which is not using delete_by_query (like, fetch ids and delete ids then in batches) as soon as we will find a time.

**Comment by Diasporism** [comment]
👍  Thanks for the info!
