### ISSUE TITLE
Can update_index be executed in batches?

### ISSUE THREAD

**Issue by lfv89** [toptal/chewy#450]
Hi,

Let's say that I have a company with 100.00.000 cities. Every time a given company is updated, the `update_index` loops through all of its cities and reindex each one of them. My question is, can this loop be made in batches? If already is, can I configure this batch size? 

Thank you.

**Comment by pyromaniac** [comment]
You can use https://github.com/toptal/chewy#type-default-import-options

**Comment by lfv89** [comment]
I'm already doing that and works fine when I import all the cities.

My problem is (and I might be wrong), when I update a company I'm feeling that this BATCH_SIZE is not respected. That is, when I update a company what I see is that every city of this company is indexed (and consequently loaded by ActiveRecord) at once, and not in batches.

Do you think his is a possible scenario?

**Comment by pyromaniac** [comment]
There are 2 possible cases: cities are in the company index and cities are in the separate index. I can't get which one is yours.

In the first one - import loads companies in batches and then uses standard AR preloading to fetch cities for each company. And then all the structure goes to company index. You can try to optimize it using https://github.com/toptal/chewy#crutches-technology if you feel that preload is not optimal enough.

In the second case everything should be split to batches correctly depending on the configuration. Whenever you are updating the company, all the related cities are indexed in batches.

**Comment by lfv89** [comment]
Understood, thank you @pyromaniac.
