### ISSUE TITLE
update index doesn't work

### ISSUE THREAD

**Issue by bogdan8** [toptal/chewy#451]
I use aasm and after I click to change at State is simply lost record, but when I do rake chewy:reset it record appears again, that it might be?

**Comment by pyromaniac** [comment]
Hm, have no idea, didn't you forget `update_index` for your model?

**Comment by bogdan8** [comment]
I have  update_index('appointments#appointment') {self }
  update_index('car_washes#car_wash') { car_wash }

**Comment by bogdan8** [comment]
```  Appointment.last.update(status: :pending) ```
If you run the console then it works, and if the site through the controller then record disappears from site

**Comment by pyromaniac** [comment]
This is quite strange, you probably have to debug it

**Comment by pyromaniac** [comment]
Hey, did you find the reason?

**Comment by bogdan8** [comment]
yes, so when there is a request with IN
```  
UPDATE "appointments" SET "status" = 'pending' WHERE "appointments"."id" IN (SELECT "appointments"."id" FROM "appointments" WHERE "appointments"."id" = $1  ORDER BY "appointments"."reservation" ASC) 
```
therefore update_index does not work
and if no IN 
````
UPDATE "appointments" SET "status" = $1, "updated_at" = $2 WHERE "appointments"."id" = $3  [["status", "progress"], ["updated_at", "2016-10-24 12:06:08.170870"], ["id", 309]]

```
its work

**Comment by pyromaniac** [comment]
Got it, ok

**Comment by bogdan8** [comment]
but there is some method to be able to apply to many requests?

**Comment by pyromaniac** [comment]
You have to use Import on the same scope after mass-update manually.

```ruby
Model.where(status: 'pending').update_all(something: 42)
ModelIndex::Model.import(Model.where(status: 'pending'))
```

**Comment by bogdan8** [comment]
In documentation is this?
```
However, to make it work, you must load the chewy plugin into Sequel model:

Sequel::Model.plugin :chewy_observe  # for all models, or...
User.plugin :chewy_observe           # just for User
```
