### ISSUE TITLE
update_index in RSpec does not update

### ISSUE THREAD

**Issue by jeansimon** [toptal/chewy#452]
I'm trying to get specs written for some changes made with the Chewy gem and am seriously stumped. 

My Post model contains this line: `update_index('post#post') { self if indexable? && live? }`

My spec currently looks like this: 

```
it "updates the PostIndex on save" do                                               
  post = FactoryGirl.create(:post)
  expect(post.indexable?).to be(true)                                                       
  expect(post.live?).to be(true)                                                            
  expect{post.save!}.to update_index(PostIndex::Post)                                       
end
```

I've ensured that the post in my test is both `indexable` and `live`, however, I keep getting the following error: 
`Expected index `PostIndex::Post` to be updated, but it was not`

My spec helper contains `require 'chewy/rspec'` but I'm not sure what else I'm missing. 

I've tried not using Factory Girl, changing the root_strategy in the spec helper file to `:bypass` and then `:urgent`, and even digging into chewy's update_index.rb file. As far as I can tell, nothing is being passed to the `update_index` method inside the gem.

Thanks for your help!

**Comment by pyromaniac** [comment]
Hey, sorry, I've missed this issue somehow, try to put `indexable? && live?` in the index scope rather than use it in `update_index`
