### ISSUE TITLE
Request spec failure after upgrading to rails 5

### ISSUE THREAD

**Issue by musaffa** [toptal/chewy#453]
Here's a request spec for POST request of an article:

``` Ruby
expect{ post api_articles_path, new_attrs }.to change{Article.count}.by(1)
```

When I run this, I get this error:

``` Bash
     Faraday::ConnectionFailed:
       Failed to open TCP connection to localhost:9250 (Connection refused - connect(2) for "localhost" port 9250)
```

I didn't have this problem in rails 4.2.7.

**Comment by pyromaniac** [comment]
Are you sure ES is started?

**Comment by musaffa** [comment]
I'm 100% sure.

**Comment by musaffa** [comment]
With Rails 4.2.7, the above test passes even if I stop `elasticsearch` daemon.

**Comment by pyromaniac** [comment]
there should be 2 ES - one for dev on 9200 and one on 9250 for test env. https://github.com/elastic/elasticsearch-ruby/tree/master/elasticsearch-extensions#testcluster

**Comment by musaffa** [comment]
@pyromaniac Is there any rake command to start ES at 9250?

**Comment by pyromaniac** [comment]
I've just posted a link, everything is there

**Comment by musaffa** [comment]
For anyone facing the same problem in the future, this is how I've solved this problem:

1. Install `elasticsearch-extensions` gem in the test group of your `Gemfile`.
2. Add this to your `rails_helper.rb`:

```Ruby
require 'elasticsearch/extensions/test/cluster'

RSpec.configure do |config|
  ....
  config.before :suite do
    Chewy.strategy(:bypass)
  end

  config.before :all, elasticsearch: true do
    Elasticsearch::Extensions::Test::Cluster.start(
      port: 9250,
      nodes: 1,
      timeout: 120
    ) unless Elasticsearch::Extensions::Test::Cluster.running?(on: 9250)
  end

  config.after :each do
    Warden.test_reset!
  end

  config.after :suite do
    Elasticsearch::Extensions::Test::Cluster.stop(
      port: 9250,
      nodes: 1
    ) if Elasticsearch::Extensions::Test::Cluster.running?(on: 9250)
  end
  ....
end
```

3. Place `elasticsearch: true` tag to the blocks of specs which require ES service to be present during testing.

**Comment by pyromaniac** [comment]
👍
