### ISSUE TITLE
Update indexes

### ISSUE THREAD

**Issue by elpic** [toptal/chewy#455]
Documents are not being updated after a change made to them. Even if I try to reimport them.

**Comment by pyromaniac** [comment]
Hi. Can you provide more details?

**Comment by elpic** [comment]
```
class InvitationIndex < Chewy::Index

    define_type Invitation.all, delete_if: :used? do
      field :first_name, :last_name
      field :email
      # ... Other attributes
    end

end

class Invitation < ActiveRecord::Base

  update_index('Invitation#invitation') { self }

end
```
Names are changed, but integration works correctly.

```
$> invitation = Invitation.find(1)
$> invitation.first_name = "New name" # Old name was "Old Name"
$> invitation.save! 
# InvitationIndex::Invitation Import (33.0ms) {:delete=>1}
```

Then I try to use the "New name" to find the invitation but the invitation still use the old name. I also checked on elastic search using elastic hq and the invitation document has "Old Name"

Am I doing something wrong?

Could you help me? Thanks

**Comment by pyromaniac** [comment]
`update_index('Invitation#invitation') { self }` - are you sure that `self` here is an invitation? :) I'm not quite.

Also what did it delete? `# InvitationIndex::Invitation Import (33.0ms) {:delete=>1}`
You can try to set up `Chewy.transport_logger = Rails.logger` or so to check it.

**Comment by elpic** [comment]
`# InvitationIndex::Invitation Import (33.0ms) {:delete=>1}` This is what is being output to the console when I updated the invitation 

For the *self* question. I think that the lamda run with an instance_eval so self will be the invitation. I used the same example that is on the README.

**Comment by elpic** [comment]
I will try `Chewy.transport_logger = Rails.logger` and update the ticket with that output.

**Comment by elpic** [comment]
I think it was unrelated with the Chewy code itself it was some conditions on the indexes. Thank you

**Comment by pyromaniac** [comment]
👍
