### ISSUE TITLE
Upgrading, specify specific type fields and filters not working

### ISSUE THREAD

**Issue by Linuus** [toptal/chewy#458]
Hi!

I'm currently on Chewy 0.6 and Elasticsearch 1.4 and trying to update. First I'll do the Chewy 0.6 -> 0.7 and Elasticsearch 2.4 (and then 0.7 -> 0.8) but I have some issues.

1. Fields in different types can't have the same name.
I guess this is purely Elasticsearch fault, I just want to confirm. If I have the type `Article` with a field `:title` then my other type `Discussion` which also has the field `:title` _must_ have the exact same mapping/settings, correct? If I don't want that I need to rename one of them.

2. Before I had a query like this:
```ruby
    index.query(multi_match:
    {
      query: @query,
      fields: ["*.original^4", "*.stemmed", "*.partial", "tag.name.original*30", "tag.name.lowercased^30",
               "department.title", "department_title", "colleague.full_name"],
      cutoff_frequency: 0.001
    })
```
It doesn't seem to work to do `type.field_name` anymore, is that correct? If I search for something which is in the Colleage `full_name` field I get no results. If I change it to `full_name` it works though. The same happens with `tag.name.original` etc.

So, if I want to, like I do above, boost some field of a specific type, how do I do that now?

3. Filters seems to always be executed as "or".
I have tags on my articles, which I index like this:
```ruby
    define_type scope, name: name do
      field :title
      field :tags, value: -> { all_tags }, include_in_all: true do
        field :id
        stemmed_and_partial_field :name do # stemmed_and_partial_field is a helper I've written. Not important here.
          field :lowercased, analyzer: "lowercased"
        end
      end
    end
```

Previously I had a filter like this:
```ruby
    # @tag_ids is an array of ids, [1,2,3]
    index.filter(terms: { "tags.id" => @tag_ids, execution: :and })
```
When I filter by _one_ tag id `[1]` it returns articles tagged with that tag. However, when I pass two ids `[1,2]` it returns articles tagged with _either_ 1 **or** 2.

Has this API changed somehow?

**Comment by Linuus** [comment]
I just realised that Elasticsearch 2.X support was added in Chewy 0.8 so I moved to 0.8 directly now. Same issues though :)

**Comment by pyromaniac** [comment]
Aha, that's what I was going to suggest :)
1. Inside a single index - yeah they can't.

As for other items - I frankly have no idea what have been changed in ES, but there were a lot of changes. So you probably have to read the changelog and docs carefully.

**Comment by Linuus** [comment]
@pyromaniac Ok, thanks :) Yes, there seems to be some major changes there.

I'll start by just updating to ES 1.7 and Chewy 0.8 and take it from there. ES 1.7 works fine for me on 0.6.2 so that's all good :)

I do have some questions about upgrading Chewy though.

1. Previously I used this module in my controllers:

```ruby
module Indexable
  extend ActiveSupport::Concern

  included do
     around_action :update_index, only: [:create, :update, :destroy]
  end

  def update_index
     Chewy.strategy(:atomic) do
       yield
     end
  end
end
```

Can I remove this now? It seems like you wrap all ActionController actions in an `:atomic` by default now.

2. Failing tests.
I have the callbacks for indexing my ActiveRecord models, like this:

```ruby
      update_index("global#tag") { self }
```
When I update it in my interface it works fine but in my tests it fails.

Example:

```ruby
    it "updates global index when updating tag" do
      question = Tag.create!(name: "Something", title: "More Something")
      expect { question.update_attributes(title: "FooBar") }.to update_index("global#tag")
    end
```

It fails, saying it didn't update my index. I have tried to set `Chewy.strategy(:urgent)` in my spec_helper but it doesn't make any difference.

Any suggestions on what I'm missing?

**Comment by pyromaniac** [comment]
1. Yeah, you can remove it.
2. You probably have to debug it. Strategy in your example should be set around the expect block content. Also, set up `Chewy.strategy(:bypass)` in your spec helper.

**Comment by Linuus** [comment]
@pyromaniac Thank you so much for the great support here :)

In my spec_helper I have this:

```ruby
RSpec.configure do |config|
  config.before(:suite) do
    Chewy.strategy(:bypass)
  end
[...]
```

And my test looks like this:

```ruby
    it "updates global index when updating tag" do
      Chewy.strategy(:urgent) do
        question = Tag.create!(name: "Something", title: "More Something")
        expect { question.update_attributes(title: "FooBar") }
          .to update_index("global#tag")
      end
    end
```

This still fails though.

```
  1) GlobalIndex Tags updates global index when updating tag
     Failure/Error:
       expect { question.update_attributes(title: "FooBar") }
         .to update_index("global#tag")
```

If I check the strategy in my test, it looks like this before the `Chewy.strategy(:urgent)`
```
#<Chewy::Strategy:0x007fef5b4f2188 @stack=[#<Chewy::Strategy::Base:0x007fef5b4f1300>, #<Chewy::Strategy::Bypass:0x007fef5b4f0798>]>
```

And inside the block
```
#<Chewy::Strategy:0x007fef5b4f2188 @stack=[#<Chewy::Strategy::Base:0x007fef5b4f1300>, #<Chewy::Strategy::Bypass:0x007fef5b4f0798>, #<Chewy::Strategy::Urgent:0x007fef5a92d988>]>
```

Also, if I stop the test with `binding.pry` and check my elasticsearch indices (using the head plugin) I don't see the test index at all. :-/

I tried to manually run `GlobalIndex.import` and that created the index. However, changing my models does not trigger any update in the index when in the test environment :(

**Comment by pyromaniac** [comment]
Hm, everything seems to be correct, are you sure you have `update_index('global#tag') { tags }` in your `Question` model?

**Comment by Linuus** [comment]
@pyromaniac I just found the issue. I had this in my spec_helper

```ruby
RSpec.configure do |config|
  config.use_transactional_fixtures = true
[...]
```

Having this set to true does not run `after_commit` callbacks... That's annoying.

Is it appropriate to set the `use_after_commit_callbacks` to false in tests only? Or is it a better idea to try not to have `use_transactional_fixtures` set to true?

**Comment by pyromaniac** [comment]
Yeah, `use_after_commit_callbacks ` option was added exactly for this purpose, use it.

**Comment by Linuus** [comment]
Ok, thanks!

Sorry for taking up so much of your time. Great job with Chewy! :+1:

**Comment by pyromaniac** [comment]
Always welcome, sorry that I was almost useless :(
