### ISSUE TITLE
Re-write filtered query as bool query

### ISSUE THREAD

**Issue by Linuus** [toptal/chewy#459]
Hi!

(This is partly a follow-up to https://github.com/toptal/chewy/issues/458)

Previously, on ES 1.7, I had a multi_match query with a filter, like this:
```ruby
  def create_query
    [multi_match_query, tag_ids_filter, tag_aggregation].compact.reduce(:merge)
  end

  def multi_match_query
    return unless @query.present?
    index.query(multi_match:
    {
      query: @query,
      fields: ["*.original^4", "*.stemmed", "*.partial", "tag.name.original^30", "tag.name.lowercased^30",
               "department.title", "department_title", "colleague.full_name"],
      cutoff_frequency: 0.001
    })
  end

  def tag_ids_filter
    return unless @tag_ids.present?
    index.filter(terms: { "tags.id" => @tag_ids, execution: :and })
  end
```

Now, on ES > 2.0 the `execution` option on the terms filter has been removed.
See: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_query_dsl_changes.html#_literal_terms_literal_query_and_filter

The above code generates this query:

(Formatting is a bit weird, sorry about that)
```
{: body =>
  {: query =>
    {: filtered =>
      {: query =>
        {: multi_match =>
          {: query => "Something", : fields => ["*.original^4", "*.stemmed", "*.partial", "tag.name.original^30", "tag.name.lowercased^30", "department.title", "department_title", "colleague.full_name"], : cutoff_frequency => 0.001
          }
        }, : filter =>
        {: terms =>
          {
            "tags.id" => [5, 8], :execution => :and
          }
        }
      }
    }, : aggregations =>
    {: tag_ids =>
      {: terms =>
        {: field => "tags.id"
        }
      }
    }, : _source => ["id"], : from => 0, : size => 10
  }, : index => ["my_index"], : type => []
}
```

The generated query is a "filtered" query with a filter, which is a terms filter with execution `:and`.

According to the above link I have to re-write this to a bool (must?) query, and try to figure out how to filter on _all_ the tag ids.

Can you point me in the right direction on how to re-write it into a bool query?

Also, I guess the above should not be a "filtered" query for future versions of Chewy, but that seems to be tracked here:
https://github.com/toptal/chewy/issues/444

And the code generating the filtered query is here, right?
https://github.com/toptal/chewy/blob/991af1a2529beadcaeb6137d68437548661f2bb3/lib/chewy/query/compose.rb#L6

**Comment by pyromaniac** [comment]
Hm, how about to try post_filter along with query?

**Comment by Linuus** [comment]
@pyromaniac I don't think I can use that because I also have a tag aggregation. It aggregates the tags in my matches. If I do a `post_filter` I think it will break the tag aggregation.  :-/

**Comment by pyromaniac** [comment]
I didn't use ES > 2 yet, so if you will find the exact query which will work for you - I'll try to help you with the Chewy DSL to implement it, ok?

**Comment by Linuus** [comment]
Of course :) Thank you for the help.
