### ISSUE TITLE
Please cut a release including the multibyte error fix

### ISSUE THREAD

**Issue by stephencattaneo** [toptal/chewy#460]
Sadly I can't use 0.8.4 because its missing this commit 40b040860e78d7fd55a854d3ed0e0a7d6507e7da

My environment crashes when loading witchcraft.rb

I assume cutting a release is a bit of effort, but maybe a 0.8.4.1 release (including the above commit)  is lower effort and would allow use by some of us who are hung up by this issue. 

(I'm running ruby 1.9.5 and I assume later versions of ruby don't choke on the same error)

**Comment by pyromaniac** [comment]
Will try to do it over the weekend, but why can't you just go with master? It is quite stable.
