### ISSUE TITLE
Strange nested object import bug

### ISSUE THREAD

**Issue by mkcode** [toptal/chewy#461]
ENV:
  * rails and activerecord 5.0.0.1
  * chewy 0.8.4
  * ruby 2.3.1

I have a standard `has_many` activerecord association:

```ruby
class Country
  has_many :cities
  ...

class City
  belongs_to :country
  ...
```

And I am counting child objects while indexing like so:

```ruby
define_type Country.includes(:cities) do
  field :name
  field :cities do
    field :submitted_count, value: ->(cts) { cts.select { |r| r.state == 'submitted' }.size }
    field :approved_count,  value: ->(cts) { cts.select { |r| r.state == 'approved' }.size }
  end
end
```

Running `rake reset[my_index]` indexes most of the docs and then yields an error like:

```ruby
rake aborted!
NoMethodError: private method `select' called for #<City:0x007fced6c2bcd8>
```

Somehow the first argument being sent to the child `value` proc is an individual element and not an `ActiveRecord::CollectionProxy` like it normally is. I had verified that calling `Country.all.map(&:cities)`  always returns a Cities collection or else an empty collection.

For now, there is an easy workaround of just adding a value proc to the parent object:

```ruby
define_type Country.includes(:cities) do
  field :name
  field :cities, value: -> { } do
    field :submitted_count, value: ->(cts) { cts.select { |r| r.state == 'submitted' }.size }
    field :approved_count,  value: ->(cts) { cts.select { |r| r.state == 'approved' }.size }
  end
end
```

An empty `value` proc works fine.

Is there any behavior that would cause the first argument in a child object mapping to be a single element? Like I said, there is an easy workaround for now, but I thought this is strange behavior and should be documented.

Thanks for your time!

**Comment by pyromaniac** [comment]
Hey. This is actually not a bug but intended behavior. You are just using it in a strange way. Usually, `cities` nested object is used to define a collection of nested objects and their count makes sense to keep on the top level since it is a singular value relatively to the collection of the parent object.
