### ISSUE TITLE
bypass problem with feature specs

### ISSUE THREAD

**Issue by blankenshipz** [toptal/chewy#462]
I'm using Capybara for feature specs and I'm noticing that the `_test` ES index is being updated causing some of my tests to fail depending on the order; I thought that using the `bypass` strategy would prevent updates to the index?

Here's my setup:

```
#Gemfile.lock
...
chewy (0.8.4)
rails (~> 5.0.0)
rspec (3.1.0)
capybara (2.11.0)
...
```

```
# spec/spec_helper.rb
...
  config.before(:suite) do
    Chewy.strategy(:bypass)
  end
...
```

**Comment by wycleffsean** [comment]
try setting the request_strategy

```
# spec/spec_helper.rb
...
  config.before(:suite) do
    Chewy.request_strategy = :bypass
  end
...
```

**Comment by DNNX** [comment]
This should work:

```
...
  config.around do |example|
    Chewy.strategy(:bypass) do
      example.run
    end
  end
...
```

**Comment by blankenshipz** [comment]
@wycleffsean @DNNX I tried the first suggestion and it seems to work, thanks for your help!
