### ISSUE TITLE
Can't get specs with update_index to pass

### ISSUE THREAD

**Issue by jcohenho** [toptal/chewy#464]
I'm following this tutorial to a tee: https://www.toptal.com/ruby-on-rails/elasticsearch-for-ruby-on-rails-an-introduction-to-chewy

But i'm having trouble getting 
```
describe EntertainmentIndex do
  # No need to cleanup Elasticsearch as requests are
  # stubbed in case of `update_index` matcher usage.
  describe 'Tag' do
    # We create several books with the same tag
    let(:books) { create_list :book, 2, tag_list: 'tag1' }

    specify do
      # We expect that after modifying the tag name...
      expect do
        ActsAsTaggableOn::Tag.where(name: 'tag1').update_attributes(name: 'tag2')
      # ... the corresponding type will be updated with previously-created books.
      end.to update_index('entertainment#book').and_reindex(books,
                                                            with: {tags: ['tag2']})
    end
  end
end
```
specs to pass:
```
Expected index `entertainment#book` to be updated, but it was not
       Expected document with id `113` to be reindexed, but it was not
```

in initializers/chewy.rb I have `Chewy.use_after_commit_callbacks = !Rails.env.test?` and in 
spec_helper.rb I am requiring chewy/rspec and have the following: 
``` 
config.before(:suite) do
   Chewy.strategy(:bypass)
end
```

I have the same `ActsAsTaggableOn::Tag/Taggable.class_eval` code in initializers/acts_as_taggable_on.rb, it and successfully updates the index in Rails console but not in my test environment. Anything else I'm missing?

**Comment by jcohenho** [comment]
Note that from the example code, `ActsAsTaggableOn::Tag.where(name: 'tag1').update_attributes(name: 'tag2')` should actually be `ActsAsTaggableOn::Tag.where(name: 'tag1').first.update_attributes(name: 'tag2')`

**Comment by pyromaniac** [comment]
Try to put `Chewy.use_after_commit_callbacks = false` in the spec helper. higher is better. It might occur that models are already initialized by this time.
