### ISSUE TITLE
Disable update_index for development / staging

### ISSUE THREAD

**Issue by silva96** [toptal/chewy#468]
Hi!,

We want to update index for certain environments, we don't want to have our developers to install elasticsearch in their local machines, only in production.

Is there any way to do this?

I tried 

`update_index('users#user') { self if Rails.env.production?}` and didn't work, still tries to update the index in my local machine.

Thanks in advance

**Comment by pyromaniac** [comment]
Hey,

For testing bypass strategy is used normally:

```
RSpec.configure do |config|
  config.before(:suite) do
    Chewy.strategy(:bypass)
  end
end
```

You probably do want to test indexing sometimes.
If you want to disable indexing for development - try to set `Chewy.request_strategy = :bypass`, for the environment you need in the initializer or so, this will disable indexing in controllers.
