### ISSUE TITLE
The chewy:reset task is unable to join Elasticsearch server from a Docker container

### ISSUE THREAD

**Issue by hdl-paris** [toptal/chewy#472]
I get this error when I execute this task in Rails container:

> Faraday::ConnectionFailed: Couldn't connect to server

Here is my log:

> [Faraday::ConnectionFailed] Couldn't connect to server {:host=>"localhost", :port=>9200, :protocol=>"http"}

and my config/initializer/chewy.rb:
`
Chewy.transport_logger = Rails.logger
Chewy.settings = {host: "elasticsearch:9200" }
`
I don't understand why the host is always displayed as 'localhost' in my logs. 'elasticsearch' seems not to be taken account by the rails task.

When I go to console, it  works fine:
Chewy.configuration render:
'{:host=>"elasticsearch:9200", :logger=>#<ActiveSupport::Logger:0x0000000a24aab8 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x0000000a24a9f0 @datetime_format=nil>, @formatter=#<ActiveSupport::Logger::SimpleFormatter:0x0000000b7737a0 @datetime_format=nil, @thread_key="activesupport_tagged_logging_tags:96181200">, @logdev=#<Logger::LogDevice:0x0000000a24a9a0 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<File:/var/www/airkemist_ror/web_container/log/development.log>, @mon_owner=nil, @mon_count=0, @mon_mutex=#<Thread::Mutex:0x0000000a24a900>>, @local_levels=#<Concurrent::Map:0x0000000a24a810 entries=0 default_proc=nil>>}'

We can see the host is correct above. And when I do some queries, I get the results form Elasticsearch.

Then, why the rails command doesn't work in the right way for me ?
Why rails chewy:reset is unable to join the server ?

**Comment by pyromaniac** [comment]
Try to set up host correctly for the production env in chewy.yml

**Comment by hdl-paris** [comment]
I use the container un development environment. Not in production.  The RAILS_ENV is set to development. I have already tried with chewy.yml:

## config/chewy.yml
## separate environment configs
test:
 host: elasticsearch:9250
 prefix: 'test'
development:
 host: elasticsearch:9200

It doesn't work anymore.

**Comment by pyromaniac** [comment]
So strange, you probably have to debug it or so. Have no any idea from the top of my head, sorry.

**Comment by hdl-paris** [comment]
No worry. I'm going to try to debug it.

Thanks for your reply :)

**Comment by hdl-paris** [comment]
I have switched from Puma to Passenger and it works now. I will do a new try with Puma.

**Comment by hdl-paris** [comment]
Finally, I have found the solution.
It's not enough to set the right host in chewy.yml.
In my web containers linked to Elasticsearch container, I havw provides the  ELASTICSEARCH_URL environement variable. Below a snippet of my docker-compose.yml:

```yaml
elasticsearch:
  image: elasticsearch:2.4.6
  ports:
    - 9200:9200
app:
  build: ./
  environment:
    - ELASTICSEARCH_URL=http://elasticsearch:9200
  links:
    -elasticsearch
```
