### ISSUE TITLE
Sidekiq Strategy and batch_size

### ISSUE THREAD

**Issue by junaidatique** [toptal/chewy#473]
I am using sidekiq strategy. My Index setting is 
`default_import_options batch_size: 100, bulk_size: 10.megabytes`
I am using save on individual records,
`Chewy.strategy(:sidekiq) do
        document.save
  end`

But I think this code is not batching 100 items and sending it to elastic search service as I am receiving error that try batching request. 
My question is if I have defined default import option, does chewy batch requests by default or does I have to do it manually.

**Comment by pyromaniac** [comment]
Hey, it definitely should do it in batches. Everything comes to `import` method is handled in batches. As you can see here, https://github.com/toptal/chewy/blob/master/lib/chewy/strategy/sidekiq.rb#L19, we are using `import` method after all the stuff is done. As for queue name, there was an attempt: https://github.com/toptal/chewy/pull/438, but it is not merged yet unfortunately. You can simply try to do `class_eval` on `Chewy::Strategy::Sidekiq::Worker` to modify its options.
