### ISSUE TITLE
[Question] Filters terms

### ISSUE THREAD

**Issue by ThomAille** [toptal/chewy#474]
Hi Guys

I use the filter terms, but the result obtained is not that expected
Today in my elasticsearch I have indexes with several tags
Example : 
Index_1 : tags {'tag1','tag2'}
Index_2 : tags {'tag2','tag3'}
Index_3 : tags {'tag1'}

But when I use this code : 
```
def search
    [query_string, tag_filter, post_aggs].compact.reduce(:merge)
  end

  def query_string
    index.query(query_string: {fields: [:name], query: search_string, default_operator: 'and'}) if search_string?
  end

def tag_filter
    index.filter(terms: {tags: tags}) if tags
  end

def post_aggs
    index.aggregations(terms_tags: {terms: {field: 'tags'}})
  end
```

It returns the results that contain at least one of the tag

example : 
search_1 : {tag1,tag3} : return index_1, index_2 and index_3
search_2 : {tag2, tag3} : return index_1, index_2

But I wish rather that returns to me
search_1 : {tag1,tag3} : return null
search_2 : {tag2, tag3} : return index_2
search_3 : {tag1, tag2} return index_1, index_3

Do I add any additional options?

Best Regards 
Thomas

**Comment by pyromaniac** [comment]
Holy crap sir! Missed this issue somehow, so sorry. Did you solve it?

**Comment by dalthon** [comment]
Closed due to inactivity
