### ISSUE TITLE
How to log the query being made?

### ISSUE THREAD

**Issue by lfv89** [toptal/chewy#477]
If I want to log an active record query, I can do, for instance: `Rails.logger(User.all.to_sql)`

Which could be chewy's "`to_sql`" method that would give me the builded query?

Thanks.

**Comment by pyromaniac** [comment]
`_request` or so :)

**Comment by lfv89** [comment]
Thanks for the fast response.

Wouldn't be more intuitive though to have a `to_search_query` method? If it's interesting I can jump on it.

**Comment by pyromaniac** [comment]
yeah, why not? But we have to think about the name

**Comment by lfv89** [comment]
Yes, `to_query` is already used by ActiveSupport, that's why I suggested `to_search_query`.

Do you have anything better in mind?

**Comment by pyromaniac** [comment]
to_request maybe

**Comment by pyromaniac** [comment]
The `render` method is actually exposed in the new version (new DSL).
