### ISSUE TITLE
How to set "size" for aggregation?

### ISSUE THREAD

**Issue by daneelgiskard** [toptal/chewy#479]
Hi all,

My aggregation looks like this:
`ProductsIndex.filter { match_all }.aggs(key: {terms: {field: "features.key"}}, value: { terms: { field: "features.value"}}).aggs`

However, I always only get back the first 10 results of it, this is also indicated by the field `doc_count_error_upper_bound` which value is 10.

I know that I need to set the size to 0 in my query to get all results. I tried doing this with the limit() method, but I still only get back the first 10 results.

How can I set the size for an aggregation?

Many thanks,
Michael

**Comment by daneelgiskard** [comment]
Hi all,

I got it to work using:
`ProductsIndex.filter { match_all }.aggs(key: {terms: {field: "features.key", "size": 0}}, value: { terms: { field: "features.value"}}).aggs`

This gives me all results, i.e. sets the size to 0.

Many thanks and all the best,
Michael

**Comment by pyromaniac** [comment]
👍
