### ISSUE TITLE
Expecting [] to be implemented on an Index.

### ISSUE THREAD

**Issue by ChrisCPO** [toptal/chewy#480]
since taken from docs `scope.load # => scope is marked to return User instances array`

one would expect 
`scope.load[0] == scope.load.first' however this returns false.

Is there a reason [] was never implemented on the index model?

**Comment by pyromaniac** [comment]
Hey, probably I simply forgot it. And Enumerable module doesn't implement it unfortunately.

**Comment by pyromaniac** [comment]
Implemented in the new DSL
