### ISSUE TITLE
search_after support

### ISSUE THREAD

**Issue by markiz** [toptal/chewy#485]
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html

Hey guys, any objections to support this little feature of elasticsearch 5+?
I think it should be as simple as adding another field to `Query` and can probably even do it myself if no one minds.

**Comment by pyromaniac** [comment]
No objections, we are going to support it definitely

**Comment by pyromaniac** [comment]
Supported in the new DSL
