### ISSUE TITLE
how to store hashes in elasticsearch?

### ISSUE THREAD

**Issue by mlchai** [toptal/chewy#486]
I'm trying to store a hash object in elasticsearch and it seems ES supports this. I can't figure out how to define it in the index, though. I tried specificying type: 'objects' but it didn't work. It looks kinda like this:

field :my_field, value: -> (obj) { obj.hash }, type: 'objects'

**Comment by pyromaniac** [comment]
Well, the type is called `object`, not `objects`. Also, `.hash` afaik is a standard method returning a hash string, not a hash object.

**Comment by mlchai** [comment]
Thanks for the quick reply. I tried both 'objects' and 'object' (I got 'objects' from the github README) and both didn't work. The .hash was just psuedo code for a method that would return an actual hash.

**Comment by pyromaniac** [comment]
Hm, ok, then it looks like it should work, have no clue then.

**Comment by mlchai** [comment]
This was my fault, it turns out I had a nil key so it wasn't saving the hash correctly.

**Comment by pyromaniac** [comment]
👍
