### ISSUE TITLE
Using sidekiq to create/update one ES doc after model is created/updated

### ISSUE THREAD

**Issue by tuanhuydn** [toptal/chewy#490]
Hi! Thanks for the great gem, it's been amazing working with Chewy and Rails for ES! Please pardon the fact that I'm a newbie.

After reading the README and other similar issues regarding sidekiq and chewy, I still can't solve my problem. I've looked at #51 #171 #473 #119 

Let's say I have a model User. When a new User gets created or an old User gets updated, I'd like to fire off a singular sidekiq job to index/re-index this one particular User. How do I accomplish this?

What code (if any) do I need in my UsersController, User model? What would my Sidekiq Worker look like?

Thanks so much in advance for the help!

**Comment by pyromaniac** [comment]
The general approach is:

```ruby
class User < AR::Base
  update_index 'users#user'
end
```

In the model you are specifying only the connection between the model and the target index(es). To update data you are normally using strategies block.

`Chewy.strategy(:sidekiq) { user.save }`

Every model update wrapped with the `sidekiq` strategy will be updated using sidekiq.

Controller is already pre-configured to be wrapped with the strategy (`atomic`) by default, so all you need is to change this preference - `Chewy.request_strategy = :sidekiq`

**Comment by tuanhuydn** [comment]
Great thanks. I think I have it working, but right now I have ```Chewy.root_strategy = :sidekiq``` in the file initializers/chewy.rb. Should I keep it there? Where should I put ```Chewy.request_strategy = :sidekiq```

**Comment by pyromaniac** [comment]
Just keep it there

**Comment by tuanhuydn** [comment]
Thanks, got it working :)

**Comment by pyromaniac** [comment]
Welcome

**Comment by bastoune** [comment]
Hi @pyromaniac 

I did the same by adding 
```Chewy.root_strategy = :sidekiq
Chewy.request_strategy = :sidekiq```
TO
`config/initializers/chewy.rb`

Indexing still works but it doesn't increment sidekiq jobs so I guess it doesn't go async.
How can I ensure it ? Why would it not work ?

**Comment by pyromaniac** [comment]
Have no idea tbh, I'm not using Sidekiq, so you probably have dig into it, sorry.
