### ISSUE TITLE
Is a delete_from_index('index#type') callback interesting?

### ISSUE THREAD

**Issue by lfv89** [toptal/chewy#491]
```ruby
class Comment
  # callback invoked after a comment update
  delete_from_index('comments') { !published? }  
  delete_from_index('posts#post') { !published? }
end
```

The reasoning behind: I never want to import a non published comment to my indices, since it makes no sense to search a comment that is not published.

Because of that, I don't think that makes much sense to index the field `published` and then query only by documents with `published: true`. So, in that scenario, if a comment is not published anymore I would really like to remove it from my indices using a nice chewy DSL.

What do you think @pyromaniac?

**Comment by lfv89** [comment]
The reasoning behind: I never want to import a non published comment to my indices, since it makes no sense to search a comment that is not published.

Because of that, I don't think that makes much sense to index the field `published` and then query only by documents with `published: true`. So, in that scenario, if a comment is not published anymore I would really like to remove it from my indices using a nice chewy DSL.

**Comment by pyromaniac** [comment]
Just define your type with this condition.

```ruby
define_type Comment.published do

end
```

Chewy will automatically remove everything that is not in the scope anymore.

**Comment by lfv89** [comment]
Ah sweet, I thought that this scope was only taken into consideration during a index reset, and not during a model lifecycle... Good to know, thanks.

**Comment by lfv89** [comment]
A last question. In my example, it will automatically remove everything that is not in the scope, both from the `Comments` index **and** the `Posts` index?

**Comment by pyromaniac** [comment]
Scopes are configured per-type, so you have to use tha same scope in both types if you want to have similar behavior

**Comment by lfv89** [comment]
I wasn't clear enough, in my PostsIndex I have something like this:

```ruby
class PostsIndex < Chewy::Index
  define_type Post.published do
    field :comments do
      field :id
    end
  end
end
```

In that scenario, if I unpublish a comment this comment won't be removed from the Posts index, even If I had defined `define_type Comment.published`, right?

**Comment by lfv89** [comment]
Sorry I wasn't clear enough, in my PostsIndex I have something like this:

```ruby
class PostsIndex < Chewy::Index
  define_type Post.published do
    field :comments do
      field :id
    end
  end
end
```

In that scenario, if I unpublish a comment this comment won't be removed from the `PostsIndex`, even If I had defined `define_type Comment.published`, right?

Thats where my proposed DSL could help:

```ruby
class Comment
  # callback invoked after a comment update
  delete_from_index('posts') { !published? }
end
```

What do you think?

**Comment by pyromaniac** [comment]
Just do

```ruby
class Commet
  belongs_to :post
  update_index('posts/post') { post }
end
```

**Comment by lfv89** [comment]
Hummm... If I understand correctly one more thing needs to be done for this to work then:

```ruby
class PostsIndex < Chewy::Index
  define_type Post.published do
    field :comments, value: -> { comments.published } do
      field :id
    end
  end
end
```

**Comment by pyromaniac** [comment]
Well, probably

**Comment by lfv89** [comment]
Got it, thanks @pyromaniac

**Comment by pyromaniac** [comment]
Welcome
