### ISSUE TITLE
Avoiding :urgent strategy in the console?

### ISSUE THREAD

**Issue by aselder** [toptal/chewy#495]
In some of our staging environments we don't have ES hooked up, and it's controlled by an environment variable to set all strategies to `:bypass` in an initializer. However when you fire up a console in that environment, an instance of the `:urgent` strategy gets added to the stack:

```
irb(main):003:0> Chewy.root_strategy
=> :bypass
irb(main):004:0> Chewy.request_strategy
=> :bypass
irb(main):005:0> Chewy.strategy
=> #<Chewy::Strategy:0x00000008545698 @stack=[#<Chewy::Strategy::Base:0x00000008545328>, #<Chewy::Strategy::Bypass:0x00000008544f68>, #<Chewy::Strategy::Urgent:0x0000000b80c658>]>
```

Is there a way to avoid this `:urgent` strategy getting added? 

Also, ideally I'd love to not have to worry about strategies at all when I just need to completely disable Chewy in certain environments. I'd love for there to be a configuration object like `enabled` that could be set to true just to stop everything Chewy related.

**Comment by aselder** [comment]
I know it's a hack, but I put in the following code in our initializer in the ES off block:

```
  Chewy::Railtie.console do
    Chewy.strategy.pop if Chewy.strategy.current.name == :urgent
  end
```

**Comment by pyromaniac** [comment]
Right now use your hack, I'm going to make the console strategy configurable. Also, you can submit a PR by yourself. Here it is set: https://github.com/toptal/chewy/blob/master/lib/chewy/railtie.rb#L49

**Comment by aselder** [comment]
I'll take a look at adding this functionality while I'm digging into it this weekend.
