### ISSUE TITLE
Percentile Ranks

### ISSUE THREAD

**Issue by tuanhuydn** [toptal/chewy#496]
Is it possible to use Chewy / Elastic Search to calculate percentile ranks of a specific field over all documents in an index?

Say I have 10,000 documents in an index that all have a test_score field (integer 0-100). Given one document's score of 85, I'd like to see that document's test_score percentile rank compared to the other 9,999 documents.

Thanks!

**Comment by olleolleolle** [comment]
This usage question could perhaps find a larger audience at the Elasticsearch online discussion forum, which you can find at: https://discuss.elastic.co/ Good luck!

**Comment by pyromaniac** [comment]
I would say, aggregations might work in the case.
