### ISSUE TITLE
Elasticsearch Completion Suggest

### ISSUE THREAD

**Issue by jondavidford** [toptal/chewy#50]
I want to use the elasticsearch completion suggest feature to implement autocomplete. when I do something like this:

index.suggest(mysuggest: { text: 'roy', completion: { field: 'suggest' }})

it sends this request to the elasticsearch server:

GET /console/job,table,column/_search  [{"suggest":{"mysuggest":{"text":"roy","completion":{"field":"suggest"}}}}]

Since the search endpoint is used and there is no query given, I think elasticsearch just assumes a blank query (so it returns all objects in db). It also has this in the result (when I submit the query with a curl command)

{...
"suggest":{"mysuggest":[{"text":"roy","offset":0,"length":3,"options":[{"text":"Roy Lane","score":1.0}]}]}}

I want to be able to get those suggestion results, but I can't figure out any way to do it. I tried looking into the Chewy code, but I'm new to Ruby and I don't really understand what is going on. 

Is there currently any way to retrieve suggestion results? If not, can someone point me to the right places in the code to do this? I think a better way to implement suggest would just be to use the _suggest endpoint of the elasticsearch server so that you are not doing a query if all you want are suggestion results.

Something like this would be good:

GET /console/job,table,column/_suggest  [{"mysuggest":{"text":"roy","completion":{"field":"suggest"}}}]

**Comment by ricardopacheco** [comment]
Not work for me!

**Comment by suryapandian** [comment]
@jondavidford While using Chewy how are you able to get the ElasticSearch requests? Can we enable logs or something so that we would be able to see the requests? It will be extremely helpful, please help.

**Comment by jondavidford** [comment]
@suryapandian sorry, but it's been 5 years since I looked at any of this stuff. I don't remember very well how I got it to work in the end.
