### ISSUE TITLE
Can i write a Sidekiq job updating the index async?

### ISSUE THREAD

**Issue by danielkummer** [toptal/chewy#51]
Hi there

I'm just getting started with your chewy gem because it looks great and I'd like to try it.
A question. Is it possible to hook into the update_index action and perform the updating inside an async sidekiq job?

Example: 
````
class User <  ActiveRecord::Base
  after_save    { Indexer.perform_async(:index, self.class.name,  self.id) }
  ......
end    
````
And a Sidekiq worker named "Indexer":
````
class Indexer
  include Sidekiq::Worker

  def perform(operation, model_name, record_id)
    #update elasticsearch index here...
  end
end
````

**Comment by baothi** [comment]
when i do again bin/spring stop it run `TacosIndex but when i run TacosIndex::Taco.import(Taco.all)`
it error `Faraday::ConnectionFailed: Connection refused - connect(2) for "localhost" port 9200 `

**Comment by pyromaniac** [comment]
You have to install and run elasticsearch: `brew install elasticsearch` on OS X

**Comment by baothi** [comment]
yes thanks pyromaniac ^^

**Comment by averell23** [comment]
@pyromaniac If you have a generic way of implementing indexing strategies, I'll be happy to fold my code in. The reason I wrote the gem was that the async update was very different to the way chewy handles updates.

Also, what specifically isn't up to date? Even though it's scratchy-ware, we do use the gem in production. So it will get eventually updated when we update chewy and/or Rails. If that's not fast enough for you guys, patches are welcome ;-)

**Comment by pyromaniac** [comment]
Hey @averell23! By not-up-to-date I meant current master for sure. And also https://github.com/toptal/chewy/pull/119 here is the PR you could check out and even try to cooperate :)

**Comment by dapi** [comment]
BTW Use `after_commit` instead of `after_save`. Becase worker can catch job BEFORE database close transaction or transaction can be rollbacked.

**Comment by pyromaniac** [comment]
I've added this change a couple of days ago
