### ISSUE TITLE
notation support for parent child relationship

### ISSUE THREAD

**Issue by ajays1991** [toptal/chewy#518]
i was looking for parent-child relationship support with chewy.

i referred [this](https://github.com/toptal/chewy/issues/56) and [this](https://github.com/toptal/chewy/pull/58) .

With the following index type definition 
```

define_type EventSet.status_event.includes(:lead) do
    root parent: 'lead', parent_id: ->{ status_event.lead_id } do
      template 'metadata.*', 'date', type: 'date', index: 'no'
      template 'metadata.*', 'long', type: 'integer', index: 'no'
      template 'metadata.*', 'string', type: 'text', analyzer: 'index_analyzer_v1', fields: { keyword: { type: 'keyword' } }
      field :metadata, type: 'object'
      #field :_type, value: ->(status_event) { status_event.elastic_type } 
      field :account_id, type: 'integer', index: 'not_analyzed'
      field :user_id, type: 'integer', index: 'not_analyzed'
      field :created_at, type: 'date'
      #field :parent, value: ->(status_event) { status_event.lead_id }
    end
  end
```

I the get the following exception message
```

Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":[{"type":"parsing_exception","reason":"Unknown key for a START_OBJECT in [filter].","line":1,"col":11}],"type":"parsing_exception","reason":"Unknown key for a START_OBJECT in [filter].","line":1,"col":11},"status":400}
/home/ajay/.rvm/gems/ruby-2.4.1/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:202:in `__raise_transport_error'
/home/ajay/.rvm/gems/ruby-2.4.1/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/base.rb:319:in `perform_request'
/home/ajay/.rvm/gems/ruby-2.4.1/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/transport/http/faraday.rb:20:in `perform_request'
/home/ajay/.rvm/gems/ruby-2.4.1/gems/elasticsearch-transport-5.0.4/lib/elasticsearch/transport/client.rb:131:in `perform_request'
/home/ajay/.rvm/gems/ruby-2.4.1/gems/elasticsearch-api-5.0.4/lib/elasticsearch/api/actions/search.rb:183:in `search'
/home/ajay/.rvm/gems/ruby-2.4.1/gems/chewy-0.9.0/lib/chewy/type/import.rb:220:in `fetch_indexed_objects'
```

I also took a look at [root.rb](https://github.com/toptal/chewy/blob/master/lib/chewy/fields/root.rb) and found out i am passing parent values using correct procs inside the type context.

can someone help me picking correct working code for parent child relationship

**Comment by pyromaniac** [comment]
Hey, are you using ES5? Are you using the latest Chewy master?

**Comment by ajays1991** [comment]
i am using chewy 0.9

**Comment by ajays1991** [comment]
i am also looking at your this [commit](https://github.com/toptal/chewy/pull/58/commits/34151f29f7895b03a77a122a7d0f4a62cfff9732) for parent child support added to root.rb and following the notation from the spec file to build parent child relationship for my event_set type to lead type

Thanks

**Comment by pyromaniac** [comment]
Did it help? Ok, can you provide some additional notes, please, if everything works? I would like to use your experience as a foundation for docs I'm going to add there.

**Comment by ajays1991** [comment]
sure i can priced additonal notes and setting is did with chewy. i also worked with dynamic templates with chewy and yes i must say documentation need additions. also for minitest support.

Anyway this code commit along with test usecase did't help. Its still throwing transport exception.

Can you share a working example for parent_child if you are running one.

**Comment by pyromaniac** [comment]
Unfortunately, I don't run any. That's the issue. 
Anyway, which ES're you running? Because it looks like it is ES5 you have, but the support is implemented now in master only.

**Comment by ajays1991** [comment]
ok i will  try with master es build. 

Thanks

**Comment by pyromaniac** [comment]
Not ES, Chewy master

**Comment by ajays1991** [comment]
Thanks this worked. 
You can close the issue now.

**Comment by pyromaniac** [comment]
ok, great!
