### ISSUE TITLE
How to filter to matching tags, then rank by an already-defined "likeness" attribute of matching tags

### ISSUE THREAD

**Issue by TrevorHinesley** [toptal/chewy#519]
As the title suggests, my app has songs with "ranked" tags. Tags are specified a "likeness" rank (lower = better), so that tags that are most-like the song are ranked as such. For instance, a heavy metal song may have these tags:

Metal - 1
Angry - 2
Loud - 3

Where "Metal" is the most-like the song. So what I'd like to accomplish:

If I search for "metal":
1st - Filter songs to only songs that have at LEAST the Metal tag (but can have other tags as well).
2nd - Rank the filtered songs such that those with lower "ranks" on their "Metal" tag are ranked first. So songs with a "Metal" tag of rank "1" will be the first songs shown.

I know I could make a "tags" index that just collects tag IDs or names or whatever, but how do I tie the ranks to these tags? If a song has 10 tags, but I search for "loud metal", I would only want it to be sorted by the rank of its "Loud" and "Metal" tags, not the ranks of its other 8 tags since I don't care about those in this search.

**Comment by pyromaniac** [comment]
Well, to be honest, this is not a Chewy question, but the ES one. Unfortunately, it doesn't seem like I have enough experience to answer it.

**Comment by TrevorHinesley** [comment]
No sweat! I just asked over on the discuss forum, so we'll see what happens. Thanks!
