### ISSUE TITLE
has_many as a nested object example?

### ISSUE THREAD

**Issue by TrevorHinesley** [toptal/chewy#520]
https://www.elastic.co/blog/managing-relations-inside-elasticsearch <-- the nested object example here. How would that be implemented in a Chewy index?

i.e.

```
{
  "name" : "Zach",
  "car" : [
    {
      "make" : "Saturn",
      "model" : "SL"
    },
    {
      "make" : "Subaru",
      "model" : "Imprezza"
    }
  ]
}
```

Which is mapped in ES like so:

```
{
  "person":{
    "properties":{
      "name" : {
        "type" : "string"
      },
      "car":{
        "type" : "nested"
      }
    }
  }
}
```

**Comment by TrevorHinesley** [comment]
Is it something like this? https://github.com/toptal/chewy/blob/master/lib/chewy/type/mapping.rb#L94

**Comment by pyromaniac** [comment]
Hey, try this: https://github.com/toptal/chewy/#multi-nested-and-object-field-types

**Comment by TrevorHinesley** [comment]
Thanks!
