### ISSUE TITLE
Requirement: Add feature support for reindex

### ISSUE THREAD

**Issue by ajays1991** [toptal/chewy#525]
i was looking at `rake chewy:update` source code and found out it actually imports the data for indexes with mappings change.

Following [this](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-reindex.html), i think `rake chewy:reindex` would be more helpful for updating the indexes without bothering the primary data-store or maybe the primary database cease to exist in some cases. like in mine.

I dig deep in src for reset, update, deploy. They all in the end rely on import for importing the data after updating/creating index to cluster.

Followings are the reasons why i am looking for this feature.

1) For us we save additional metadata for each model record in elastic and we want to have this metadata in elastic only instead on postgress. This metadata is purely for analytics purposes. We compute this metadata only once and currently there is now way we can update our index settings without loosing metadata and relying on our main postgress database.

2) I posted [this](https://github.com/toptal/chewy/issues/476) sometime back where i was looking to maintain indenpendent models class for elastic index as mentioned in to-do list. With independent models elastic will be the original source of truth and having reindex option would be necessary. This can become analogous to postgress or mysql `db:migrate`

I have started work on this on a forked version. Maybe i will give you a PR with minimum implementation to review by weekend and then we can discuss more on that.

**Comment by pyromaniac** [comment]
Wait, how does it change mapping? It actually doesn't

**Comment by pyromaniac** [comment]
Reindex as far as I got, simply copies data from one index to another and created exactly for the purpose of the mapping change. The same is achieved in Chewy with index reset

**Comment by ajays1991** [comment]
it will copy the data from the one index to another and thats exactly what i want `reindex` to do. Currently reset or update doesn't copy from previous index but fetches the data from the Activerecord database.

**Comment by pyromaniac** [comment]
Yeah, that's the point. If you want reindex - you can use elasticsearch-api client directly, it will be a single-line code. I don't think is worth to be duplicated in chewy.

**Comment by ajays1991** [comment]
yes make sense, not replicating, adding a rake task support for automations. Rake task can call elasticsearch api directly as this will need the code to get the latest live index_name for reindexing and new  schema changes.

**Comment by ajays1991** [comment]
work in progress https://github.com/toptal/chewy/pull/530

**Comment by dalthon** [comment]
Closed due to inactivity

**Comment by mmyoji** [comment]
@dalthon maybe you forgot to close this issue?
