### ISSUE TITLE
Get result as ActiveRecord::Relation

### ISSUE THREAD

**Issue by travisofthenorth** [toptal/chewy#528]
Is there a way to get a query result as an AR relation rather than as an array of AR objects? All I seem to be able to do is `ThingIndex.query(...).load.to_a`. My strategy to get a relation has been to do something like:
```
ids = ThingIndex.query(...).only(:id).map(&:id)
Thing.where(id: ids)
```

Forgive me if I'm missing something in the documentation/code. I'm new to this gem and I've been struggling to find an answer.

**Comment by pyromaniac** [comment]
I was thinking about this, bu unfortunately since it is possible o query multiple types, it will not be working in all the cases. New DSL has pluck BTW, get the latest master, it should be stable enough.
