### ISSUE TITLE
Dynamic query

### ISSUE THREAD

**Issue by reyntjensw** [toptal/chewy#546]
Hi

We would like to create dynamic queries, this is our working base:

`VcenterDbIndex::Asset.query(bool:{must:{bool:{should: [**{match: {parent_host_name: "host1"}},{match: {parent_host_name: "host2"}},{match: {parent_host_name: "host3"}}**]}}, filter:{bool:{must: [{term:{run_version: "#{run_version}"}},{term:{power_state: "poweredOn"}}]}}}).limit(100).aggs({ sum_cpu: { sum: { field: "cpu" } } }).aggs({ sum_memory: { sum: { field: "memory" } } })`

We would like to generate the part in bold using an each loop so we can add or remove hosts as we'd like.

When we change the part in bold with a variable:

`VcenterDbIndex::Asset.query(bool:{must:{bool:{should: ["#{search_string}"]}}, filter:{bool:{must: [{term:{run_version: "#{run_version}"}},{term:{power_state: "poweredOn"}}]}}}).limit(100).aggs({ sum_cpu: { sum: { field: "cpu" } } }).aggs({ sum_memory: { sum: { field: "memory" } } })`

We keep getting escaped characters in the query:

`  VcenterDbIndex::Asset Search (3.9ms) {:body=>{:query=>{:bool=>{:must=>{:bool=>{:should=>["{match:{parent_host_name: \"host1\"}},{match: {parent_host_name: \"host2\"}},{match: {parent_host_name: \"host3\"}}"]}}, :filter=>{:bool=>{:must=>[{:term=>{:run_version=>"AV0dTFrgBx1hF1te2uzE"}}, {:term=>{:power_state=>"poweredOn"}}]}}}}, :aggregations=>{:sum_cpu=>{:sum=>{:field=>"cpu"}}, :sum_memory=>{:sum=>{:field=>"memory"}}}, :size=>100}, :index=>["vcenter_db"], :type=>["asset"]}`

The variable looks like this :
`search_string= '{match:{parent_host_name: "host1"}},{match: {parent_host_name: "host2"}},{match: {parent_host_name: "host3"}}'
`
Once this is working we can generate the content using our each loop.

Any thoughts how we can solve this?

**Comment by zerosicks** [comment]
[Check out this article](https://www.toptal.com/ruby-on-rails/elasticsearch-for-ruby-on-rails-an-introduction-to-chewy#searching). You can build a 'search object' that's form friendly and that you can define custom methods on to build your search query with whatever conditions/loops you happen to need.
