### ISSUE TITLE
Using `value` at index root no longer works

### ISSUE THREAD

**Issue by chrisandreae** [toptal/chewy#549]
In certain cases we use a `value` proc to manually calculate an Index's root object rather than using the `Chewy::Type::Mapping` DSL. For example, something like 
```ruby
Class FooIndex < Chewy::Index
  define_type Foo do
    root type: 'object', value: -> (model, crutches) { FooSerializer.serialize(model) }
  end
end
```
This can be useful (in combination with overriding `mappings_hash`) to reduce code duplication in cases where the relevant hash serialization and ElasticSearch mapping are already defined elsewhere in the application.

This worked until recently, but was broken in https://github.com/toptal/chewy/commit/167d7fc9b33321e0abbdc20fef3a08a7842ad419, as the new implementation of `Chewy::Fields::Root#compose` no longer delegates to `Chewy::Fields::Base#compose`.

**Comment by pyromaniac** [comment]
Hm, right, I didn't realize somebody is using it. Make sense. Unfortunately, I need to find a time to fix it. Maybe you can submit the patch?
