### ISSUE TITLE
Specifying `value` as a :symbol does not work, despite code documentation

### ISSUE THREAD

**Issue by tlrdstd** [toptal/chewy#550]
https://github.com/toptal/chewy/blob/master/lib/chewy/type/mapping.rb#L59-L70 states: 

```
# :value might be a proc or indexed object method name:
field :full_name, type: 'string', value: :user_full_name
```

However, the code at https://github.com/toptal/chewy/blob/master/lib/chewy/fields/base.rb#L34-L54 does not support this. Specifically, if `value` is not a `Proc`, then the code calls `object.send(name)`, when I would have expected it to call `object.send(value)` if `value` is a `Symbol`.

https://github.com/toptal/chewy/blob/master/lib/chewy/fields/base.rb#L53

Possibly related to #549, though I have not examined the diff in depth.

**Comment by pyromaniac** [comment]
Oh, you are right, will fix it, thanks for the report!
