### ISSUE TITLE
If WillPaginate is present, calling `load.objects` without `paginate` fails

### ISSUE THREAD

**Issue by tlrdstd** [toptal/chewy#551]
https://github.com/toptal/chewy/blob/master/README.md#loading-objects states that this works:

`PlacesIndex.load(scope: -> { active }).objects`

However, if `WillPaginate` is present, then https://github.com/toptal/chewy/blob/master/lib/chewy/search/response.rb#L86-L87 forces the result of `objects` through `@paginator`. Because `@paginator` has not been initialized via https://github.com/toptal/chewy/blob/master/lib/chewy/search/pagination/will_paginate.rb#L18-L25, the call to `.objects` fails with:

```ruby
TypeError: can't convert nil into Integer
```

This call will succeed:

`PlacesIndex.load(scope: -> { active }).paginate.objects`

The error message does not effectively communicate what is going on. It would be best if pagination was handled more gracefully.

**Comment by pyromaniac** [comment]
Thanks for the report, will take a look.
