### ISSUE TITLE
undefined method `debug` 

### ISSUE THREAD

**Issue by niels-s** [toptal/chewy#552]
With the latest version 0.10.0 I got a undefined method `debug` when booting my rails app.

The issue is introduced by this PR I believe: https://github.com/toptal/chewy/pull/543
I think we have a race condition here, since the `Chewy.logger` has been initialised yet because ActiveRecord isn't load. Because ActiveRecord `on_load` is used on [lib/chewy/railtie.rb#55](https://github.com/toptal/chewy/blob/master/lib/chewy/railtie.rb#L55), the time when the RequestStrategy is initialised, the Chewy.logger is still nil in my case.

Using Rails 5.1.3 on ruby 2.4.0

**Comment by pyromaniac** [comment]
Oh, okay, thanks for the report
