### ISSUE TITLE
`Type.import` drops `includes()` for ActiveRecord types

### ISSUE THREAD

**Issue by tlrdstd** [toptal/chewy#561]
I have a type defined like:

```ruby
class AttachmentIndex < Chewy::Index
  define_type Attachment.includes({document: [:topics], binary: [], thumbnail: []}
end
```

These includes are vital for drastically speeding up my imports. However, when I call `AttachmentIndex.import(batch_size: 100)`, https://github.com/toptal/chewy/blob/master/lib/chewy/type/adapter/active_record.rb#L29 drops the passed-in `scope` in favor of `Attachment.default_scope`.

The results that come back from `import_scope` are the correct results, but Rails has not eager-loaded the associations for my results. Thus the import operation takes much, much longer due to many `n+1` queries.

The simplest fix seems to be:

```diff
-default_scope_where_ids_in(ids)
+scope_where_ids_in(scope, ids)
```

This correctly loads my objects with ActiveRecord `includes`.

**Comment by pyromaniac** [comment]
Hey, you are mixing something, `default_scope` in this context is exactly the scope with all the includes. And we are using this functionality and includes are not ignored.

Are you sure this is the case? Can you check twice, please?

**Comment by tlrdstd** [comment]
Ah. On further inspection, I over-simplified my example above. You are correct that, if my type actually looked like that, it would behave correctly.

My type really looks like this:

```ruby
class AttachmentIndex < Chewy::Index
  define_type Attachment
end
```

And then I call:

```ruby
AttachmentIndex.import(attachment: Attachment.includes({document: [:topics], binary: [], thumbnail: []}))
```

This is when the passed-in `scope` is replaced by `default_scope`.

For my purposes, I realize now that I can probably just switch to actually specifying my `includes()` in the `define_type` call. It still seems surprising that I can pass in a scope with includes and have those includes ignored. However, I would understand if you just wanted to close this issue!

**Comment by pyromaniac** [comment]
Yeah, this thing is intended, if is better to use includes in `define_type`. Good luck!
