### ISSUE TITLE
`Index.import` does not respect `Chewy.strategy`

### ISSUE THREAD

**Issue by tlrdstd** [toptal/chewy#562]
I would like to be able to import my types in the background via something like `Chewy.strategy(:active_job)`. However, `Index.import` does not respect the value of `Chewy.strategy`.

I would expect something like this to work:

```ruby
Chewy.strategy(:active_job) do
  AttachmentIndex.import!(batch_size: 100)
end
```

Ideally, this would queue one `ActiveJob` record for each batch of 100 `Attachment` records. Instead, the `strategy` has no effect.

I've not actually tried to modify Chewy to support this, but a hack-and-slash attempt would, I believe, lead me to https://github.com/toptal/chewy/blob/master/lib/chewy/type/import.rb#L142. That line, specifically, is what I want to execute in the background.

For now, I'm rolling my own external code that batches my objects-to-be-imported and creates an `ActiveJob` record that will later call `AttachmentIndex.import(batch)`. But it would be neat if this were supported natively!

**Comment by pyromaniac** [comment]
You actually did it right, let's don't mix the concepts. Strategies are for the stuff you can't control, like how saved objects should be indexed. If you have a direct access - then the implementation is on your own. I don't think I want to make import unpredictable so much. Too much responsibility for a single method.

**Comment by tlrdstd** [comment]
Okay. I appreciate your work on this. I'm fairly happy with the implementation I've built up for this, so I'll move ahead with that.

**Comment by pyromaniac** [comment]
Cool, thanks! Feel free to ask any further questions.
