### ISSUE TITLE
Configure Chewy Stash index?

### ISSUE THREAD

**Issue by zerosicks** [toptal/chewy#563]
I'm trying to figure out the correct configuration to use for my local/staging/production environments, but I'm noticing some strange behaviour with the shards/indexes being created in various places.

My app has 2 indexes for user, and assignment. When inspecting the shards:
- On my local environment (linux, local elasticsearch)
 I had 5 primary shards, and 5 unassigned replicas for the user, assignment, and chewy_stash indexes.
- On my staging environment (heroku, bonsai elasticsearch) 
 I have 1 primary and 1 replica for each index. This is what I expect.
- On my production environment (heroku, bonsai elasticsearch)
 I have 1 primary and 1 replica for user and chewy_stash, but my assignments index has 2 primary and 2 replicas.

I'd like them all to match, so I know how many shards will be used and can remain within my desired usage bracket.

On my local machine, I edited `config/chewy.yml` to set:
  `number_of_shards: 1` and `number_of_replicas: 0`

I ran a `chewy:reset` and now when I inspect the shards I get:
```
chewy_stash              1 p STARTED      1  3.6kb 127.0.0.1 Psycho-Man
chewy_stash              1 r UNASSIGNED
chewy_stash              3 p STARTED      0   159b 127.0.0.1 Psycho-Man
chewy_stash              3 r UNASSIGNED
chewy_stash              2 p STARTED      1  3.6kb 127.0.0.1 Psycho-Man
chewy_stash              2 r UNASSIGNED
chewy_stash              4 p STARTED      0   159b 127.0.0.1 Psycho-Man
chewy_stash              4 r UNASSIGNED
chewy_stash              0 p STARTED      0   159b 127.0.0.1 Psycho-Man
chewy_stash              0 r UNASSIGNED
user_1502472837118       0 p STARTED    111  170kb 127.0.0.1 Psycho-Man
assignment_1502472836282 0 p STARTED      7 26.4kb 127.0.0.1 Psycho-Man
```
The configuration change affected my indexes, but the chewy_stash index is still behaving as it was when I started. Is there a way to apply the configuration file to the chewy_stash index too?

**Comment by pyromaniac** [comment]
Hm, this looks like a bug. Are you sure you did `Chewy.massacre` before the config change? If the stash is not affected by config changes even after massacre - then it is a bug, but you can use a workaround:

```ruby
Chewy::Stash.class_eval do
  settings ....
end
```

**Comment by zerosicks** [comment]
`Chewy.massacre` did the trick! But am I correct in the understanding there's no zero-downtime option for this?

**Comment by pyromaniac** [comment]
If you want to update the stash options only - just do `Chewy::Stash.delete!` It will be kinda zero-downtime. I mean, it will not affect other indexes almost.
