### ISSUE TITLE
Elastic search rest client for https calls

### ISSUE THREAD

**Issue by ManasaSM** [toptal/chewy#566]
I am using the restclient to connect to Elasticsearch from Java sprint boot..I have one cluster where i can access with 9200 port which is http.. But i have a new cluster which is https where it requires username and apssword encoded in base 64.. 

I tried below
1)Adding username and password using CredentialsProvider with encoded username and password
2)tried with out  encoded username and password
3)Tried adding the authorization header where the value is encode for username:password

All off these fails and get an error unknownhost exception.

Can anyone please help how to use elastic search rest client for https calls

**Comment by pyromaniac** [comment]
Did you solve it? Because I can't help unfortunately.
