### ISSUE TITLE
Querying an index within an index definition

### ISSUE THREAD

**Issue by thechrisoshow** [toptal/chewy#569]
My index definition makes use of another index else where, like so:

```ruby
class DataWarehouse::UserIndex < Chewy::Index
  define_type User.order(:created_at) do
    field :total_value, value: ->(user) {
      transactions = DataWarehouse::TransactionIndex.query(match: {user_id: user.id})
      transactions.collect(&:price).sum
    }
  end
end
```

However, I get a failure, because the internal query uses the wrong index for the query (i.e. it runs the query on TransactionIndex rather than UserIndex).

One workaround is to replace with query a Chewy::Search::Request like this:
```ruby
request = Chewy::Search::Request.new(Datawarehouse::TransactionIndex)
transactions = request.query({match: {user_id: user.id})
```
But the standard approach should really work I think?

**Comment by pyromaniac** [comment]
Hey, take a look here please: https://github.com/toptal/chewy/pull/572/files. Is it similar to what you are doing? It is green.

**Comment by thechrisoshow** [comment]
Dang - it **is** similar to what I'm doing. 

I wonder if the stubbing of the index is hiding the problem. I'll investigate further and find out.

**Comment by pyromaniac** [comment]
Would be great, thanks. At least, can you provide a minimal failing example? Can you try to require the inner index class implicitly? Try to prepend `::` before it.

**Comment by pyromaniac** [comment]
Hey, any news here?
