### ISSUE TITLE
Chewy.massacre does not work on Elasticsearch 5.4.0

### ISSUE THREAD

**Issue by tlrdstd** [toptal/chewy#575]
On Elasticsearch 5.4.0, calling `Chewy.massacre` returns:

```ruby
# output manually wrapped for Markdown display
Elasticsearch::Transport::Transport::Errors::BadRequest: [400]
{"error":{"root_cause":[{"type":"illegal_argument_exception",
"reason":"Wildcard expressions or all indices are not allowed"}],
"type":"illegal_argument_exception",
"reason":"Wildcard expressions or all indices are not allowed"},"status":400}
```

**Comment by pyromaniac** [comment]
This is bad, mkay?

**Comment by pyromaniac** [comment]
But seriously, thanks for the report. Can't do anything with it at the moment, use something else for now.

**Comment by tlrdstd** [comment]
Not a problem. I'm using `index.delete` in my specs for now. Was hoping for a general-purpose cleanup via `Chewy.massacre`, but it's certainly not blocking me in any way.

**Comment by pyromaniac** [comment]
Btw, did you use `action.destructive_requires_name`? https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-delete-index.html

**Comment by tlrdstd** [comment]
If so, it wasn't something I configured manually. It must be the current default in ES. I'm no longer working with ES, unfortunately, so I can't go check the configs on that project.

**Comment by pyromaniac** [comment]
ok, will check it

**Comment by pyromaniac** [comment]
I don't see any other reason except `action.destructive_requires_name`, closing this for now.
