### ISSUE TITLE
#<NoMethodError: undefined method `info' for nil:NilClass>

### ISSUE THREAD

**Issue by vishalsingh123** [toptal/chewy#578]
I am using Rails api app .. when we add gem 'chewy' in Gemfile getting this error on any get request...

#<NoMethodError: undefined method `info' for nil:NilClass>
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/chewy-0.10.1/lib/chewy/railtie.rb:17:in `call'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/rack/logger.rb:36:in `call_app'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/rack/logger.rb:24:in `block in call'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:69:in `block in tagged'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/tagged_logging.rb:69:in `tagged'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/rack/logger.rb:24:in `call'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/request_id.rb:25:in `call'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/runtime.rb:22:in `call'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.4/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/executor.rb:12:in `call'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/actionpack-5.1.4/lib/action_dispatch/middleware/static.rb:125:in `call'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-2.0.3/lib/rack/sendfile.rb:111:in `call'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/railties-5.1.4/lib/rails/engine.rb:522:in `call'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.10.0/lib/puma/configuration.rb:225:in `call'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.10.0/lib/puma/server.rb:605:in `handle_request'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.10.0/lib/puma/server.rb:437:in `process_client'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.10.0/lib/puma/server.rb:301:in `block in run'
/home/vishal_singh/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/puma-3.10.0/lib/puma/thread_pool.rb:120:in `block in spawn_thread'

**Comment by pyromaniac** [comment]
Just do `Chewy.logger = Logger.new('dev/null')` somewhere

**Comment by vishalsingh123** [comment]
ok thanks pyromaniac... 
i have installed version 0.9.0 and it is working fine ... I will also try your solution
