### ISSUE TITLE
undefined method `info' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by maxwxzheng** [toptal/chewy#581]
I upgraded to chewy 0.10.1 and cannot boost my rails app anymore. It's failing at this line.
https://github.com/toptal/chewy/blob/4a21b57fd67d32aef5c2856e626f50fda176a1e3/lib/chewy/railtie.rb#L53

It seems the code sets the Chewy.logger to ActiveRecord::Base.logger a few lines above. However in my case ActiveRecord::Base.logger is nil. Is there any setting that I need to do? Or is this something Chewy code should handle?

**Comment by pyromaniac** [comment]
Oh, this is a bug, just assign ` Chewy.logger` somewhere in an initializer, it should help

**Comment by maxwxzheng** [comment]
It doesn't work because Chewy.logger will be reset by this line 
https://github.com/toptal/chewy/blob/4a21b57fd67d32aef5c2856e626f50fda176a1e3/lib/chewy/railtie.rb#L46

I'm not sure how to set ActiveRecord::Base.logger

**Comment by maxwxzheng** [comment]
Found a temporary workaround. I added an initializer file with these two lines of code:
`require "active_record"`
`ActiveRecord::Base.logger = Rails.logger`

**Comment by maxwxzheng** [comment]
Here is a better fix. Instead of using initializer file, initialize ActiveRecord::Base.logger in the environment file.

**Comment by pyromaniac** [comment]
Should be good in the latest master now
