### ISSUE TITLE
'filtered' not supported by ES5

### ISSUE THREAD

**Issue by maxwxzheng** [toptal/chewy#582]
Does the following code work for ES5 which doesn't support 'filtered'?
https://github.com/toptal/chewy/blob/c203ba7ebe28874480bb80de43f3d63ffcd5623d/lib/chewy/query/criteria.rb#L112

I'm doing a migration from ES1.7 to ES5.6 for my company and our .filter() queries are failing because of this.

**Comment by pyromaniac** [comment]
Hey, you have to use the new DSL from the latest Chewy version.

**Comment by ruvzi** [comment]
https://gist.github.com/ruvzi/4ba1ee8ded4480c441d58add3fd7fac9

**Comment by ruvzi** [comment]
and fix by use random_score
`  def index_query_string(_q, _fields)
    { query_string: { query: "*#{_q}*", fields: _fields, use_dis_max: true } }
  end

  def index_search(_filters, _sorting, _query_string = match_all, _score = nil)
    _filters = [_filters].flatten.compact.presence
    body = { bool: { must: [_query_string, _filters].compact } }
    body = { function_score: { query: body }.merge!(_score)} if _score.present?
    index.query(body).order(_sorting)
  end

  def random_item(filters = nil, query_string = nil)
    index_search(filters, {}, query_string, random_score)
  end

  protected

  def match_all
    { match_all: {} }
  end

  def random_score
    { random_score: { seed: Time.current.to_i } }
  end`

**Comment by mattzollinhofer** [comment]
@maxwxzheng is this still an issue for you?

**Comment by dalthon** [comment]
Closed due inactivity
