### ISSUE TITLE
request_cache calls do not work

### ISSUE THREAD

**Issue by tlrdstd** [toptal/chewy#586]
Calling `UsersIndex.request_cache(true).render` returns:

```
{index=>['users'], :type=>['user'], :body=>{:request_cache=>true}}
```

However, the [Elasticsearch docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/shard-request-cache.html#_enabling_and_disabling_caching_per_request) say that the `request_cache` parameter needs to be passed as a "query-string parameter", not as a parameter in the body. Indeed, calling `UsersIndex.request_cache(true).total` returns:

```
Elasticsearch::Transport::Transport::Errors::BadRequest: [400] {"error":{"root_cause":
[{"type":"parsing_exception","reason":"Unknown key for a VALUE_BOOLEAN in [request_cache].",
"line:":1,"col":18}],"type":"parsing_exception","reason":"Unknown key for a VALUE_BOOLEAN in 
[request_cache].","line":1,"col":18,"status":400}
```

**Comment by pyromaniac** [comment]
Hm, I was under the impression that `elasticsearch-ruby` supposed to handle this. This looks to me like a bug on their side. https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-api/lib/elasticsearch/api/actions/search.rb#L93

Try to upgrade the `elasticsearch-ruby` version.

**Comment by tlrdstd** [comment]
Looks like `elasticsearch-ruby` was last updated in 2012. The link you provided seems to point into `elasticsearch-api`, which is currently on 5.0.4. That's the version I'm using, and the issue is still occurring.

**Comment by pyromaniac** [comment]
Hey, did you find a solution?

**Comment by tlrdstd** [comment]
'Fraid not. Haven't had a chance to touch this since. I've actually moved off to a different team, where I'm not working with Elasticsearch anymore, so I'm afraid I won't be any further help.

**Comment by margonaut** [comment]
Curious as to whether there's been any movement on this issue. I'm running into the exact same problem here and have had no luck finding a way around it.
