### ISSUE TITLE
Chewy Only method is not working on current version 

### ISSUE THREAD

**Issue by vi-huynh** [toptal/chewy#592]
I got exception  `NameError - uninitialized constant Chewy::Search::Parameters::Name:`

```ruby 
     ChewyIndex.query(...).only(:name)
```
For  gem version  0.9.0,  it's good.

**Comment by pyromaniac** [comment]
Yeah, read this please: https://github.com/toptal/chewy#legacy-dsl-incompatibilities

**Comment by vi-huynh** [comment]
@pyromaniac  thank you
