### ISSUE TITLE
_reindex implementation

### ISSUE THREAD

**Issue by benone** [toptal/chewy#594]
[_reindex](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/docs-reindex.html) is much faster than standard import.

I think It can be implemented like that:
`client.perform_request('POST', "_reindex", {}, {
      source: {
        index: general_name
      },
      dest: {
        index: suffixed_name
      }
})`

Here:
https://github.com/toptal/chewy/blob/master/lib/chewy/index/actions.rb#L180

**Comment by pyromaniac** [comment]
Yeah, sure, can you prepare a PR please?
