### ISSUE TITLE
Flaky Tests in CI

### ISSUE THREAD

**Issue by yahooguntu** [toptal/chewy#600]
Looks like we've got a couple of tests that fail intermittently in CI. For example, here are two runs of the same branch, with no changes in between:

Run 1 (fail): https://travis-ci.org/toptal/chewy/jobs/295977868
Run 2 (pass): https://travis-ci.org/toptal/chewy/builds/295995414

The tests in question are:

```
  1) Chewy::Index::Actions.reset! applying journal with journal application
     Failure/Error:
       client.indices.update_aliases body: {actions: [
         *indexes.map do |index|
           {remove: {index: index, alias: general_name}}
         end,
         {add: {index: suffixed_name, alias: general_name}}
       ]}
     
     Elasticsearch::Transport::Transport::Errors::BadRequest:
       [400] {"error":{"root_cause":[{"type":"invalid_alias_name_exception","reason":"Invalid alias name [cities], an index exists with the same name as the alias","index":"cities_suffix"}],"type":"invalid_alias_name_exception","reason":"Invalid alias name [cities], an index exists with the same name as the alias","index":"cities_suffix"},"status":400}
```
```
  1) Chewy::Index::Actions.reset! applying journal with journal application
     Failure/Error: expect(CitiesIndex::City.pluck(:_id, :name)).to contain_exactly(%w[1 NewName1], %w[2 Name2], %w[3 NewName3])
     
       expected collection contained:  [["1", "NewName1"], ["2", "Name2"], ["3", "NewName3"]]
       actual collection contained:    [["1", "Name1"], ["2", "Name2"], ["3", "Name3"]]
       the missing elements were:      [["1", "NewName1"], ["3", "NewName3"]]
       the extra elements were:        [["1", "Name1"], ["3", "Name3"]]
```

It doesn't seem like they fail with any particular combination of Ruby/Elasticsearch/Rails, but I didn't check too thoroughly.

---

So far we've seen the following failures:

Count | Ruby | ES
--|------|----
2 | 2.3.5 | 5.6.2
1 | 2.2.8 | 2.4.4

**Comment by pyromaniac** [comment]
Yeah, I'm aware of them, thanks for the report

**Comment by mainameiz** [comment]
In my project's specs I perform `_flush` (https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-flush.html) after all changes in indexes (PUT and DELETE) to make changes visible in search. May be it will resolve the issue?

**Comment by pyromaniac** [comment]
Great point, I'll check it out. Eventually :)

**Comment by yahooguntu** [comment]
Also seen in #625 : https://travis-ci.org/toptal/chewy/jobs/329079131

**Comment by dalthon** [comment]
They are working now

**Comment by mainameiz** [comment]
@dalthon Could you please provide an issue/commit that fixes the issue?

**Comment by dalthon** [comment]
I just assumed that it was ok since it is 3 years old and I didn't had to retry any CI job in the last PRs that I merged.

@mainameiz should I reopen it? It is still failing for you?

**Comment by mainameiz** [comment]
@dalthon thanks

> should I reopen it? It is still failing for you?

No, I just supposed that the chewy gem handles this issue somehow for now (for example by making [flush](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-flush.html) or [refresh](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-refresh.html) after index updates while running in test environment) so I can remove workarounds I made in my project.

I have some code that handles this issue. It looks like this:

```ruby
# spec/support/chewy.rb
def wait_for_index(index)
  index.client.perform_request(:post, "#{index.index_name}/_flush")
end

# spec/controllers/admin2/subject_codes_controller_spec.rb
RSpec.describe Admin2::SubjectCodesController do
  ...
  
  describe '#autocomplete' do
    before do
      CodesIndex.reset!
      wait_for_index(CodesIndex)
    end
```

**Comment by mainameiz** [comment]
It can be too tricky to reproduce the issue.
We run ours tests in parallel (12 threads) agains the same ES instance (indexes from different test-threads have different prefix) so it can produce a "large" workload on ES instance and in rare cases ES can't update search-data so fast.
