### ISSUE TITLE
Keep definitions DRY

### ISSUE THREAD

**Issue by Strnadj** [toptal/chewy#604]
I am facing a problem with chewy and I am pretty sure there is a problem, but not sure if I am able to fix it:

```
define_type Issue do
  field :subject
  field :project do
    field :name
    field :identifier
  end
end

define_type Wiki do
  field :subject
  field :content
  field :project do
    field :name
    field :identifier
  end
end
```

It's quite clear when I change `project` statement in one I have to do that in the second one too. So, what I can do:

```
project_definition = Proc.new {
  field :name
  field :identifier
}

define_type Issue do
  field :subject
  field :project, &project_definition
end

define_type Wiki do
  field :subject
  field :content
  field :project, &project_definition
end
```

That's probably the best solution, but it's better than nothing. Unfortunately, It won't work. In `lib/chewy/mapping.rb` is method called `expose_nested`. This method `yield` accepted the block, this is a problem because blocks are some kind of closures. I am able to modify this to:

```
def expand_nested(field, &block)
  @_current_field ||= root

  if @_current_field
    field.parent = @_current_field
    @_current_field.children.push(field)
  end

  return unless block_given?

  previous_field = @_current_field
  @_current_field = field
  instance_eval(&block)
  @_current_field = previous_field
end
```

This does not fail, bud it does not work either. (Projects and nested fields are not present after import)

**Comment by pyromaniac** [comment]
Did you try to use lambda instead of proc?

**Comment by mattzollinhofer** [comment]
@strnadj is this still an issue for you? Were you able to try using a lambda instead of a proc as suggested?

**Comment by dalthon** [comment]
Closed due to inactivity
