### ISSUE TITLE
`limit` not working?

### ISSUE THREAD

**Issue by sodapopcan** [toptal/chewy#610]
I'm using ES 5.6 with rails 4.2.

When I do:

```ruby
MyIndex
  .query(query)
  .limit(100)
  .page(1)
  .per(25)
```

I still get back tens of thousands of hits (total, pagination works).  Is this not how limit is intended to be used?  If not, how would I set the `size` or `terminate_after` options?  I've tried a bunch of stuff and having a hrad time here.

**Comment by pyromaniac** [comment]
Limit sets `size`. Pagination also modifies `size`. It should return a limited number of hits. Why are you using limit with pagination at all?

**Comment by sodapopcan** [comment]
Because I clearly don't understand enough about how chewy is working :)  But yes, that makes a lot of sense that it would manipulate `size`.  I'm looking to limit the entire result set then paginate that--assumingly with `terminate_after`.  I've tried adding it in a few places but always get a query error.

Thanks for the response!

**Comment by pyromaniac** [comment]
Size should reduce the returned hits number well enough. With`terminate_after` pagination will not work properly because the total number will be unknown. You probably don't want it.

**Comment by sodapopcan** [comment]
I guess this is not the right place to ask, but I'm just looking to reduce the maximum possible number of possible results and then paginate that, but I can take to SO.  Thank you!

**Comment by zerosicks** [comment]
@sodapopcan did you ever get limit/size working? I'm having the same issue. ES 5.6.4, rails 5.1.4
```
SearchIndex.limit(5).count
=> 527
```
