### ISSUE TITLE
Inconsistent settings/mappings when creating index with suffix vs importing doc directly with suffix

### ISSUE THREAD

**Issue by asabourin** [toptal/chewy#614]
Hi guys, we use monthly indices with a global alias, so we've got `content_201710`, `content_201711` etc. all under the `content` alias.
When running `ContentIndex.create('201712')` the index `content_201712` is created with the settings and mappings as defined in our `ContentIndex.rb` definition as expected. However, if importing directly a document with a suffix when the monthly index doesn't exist yet, such as `ContentIndex::Document.import(a_document, :suffix => a_document.month_suffix)`, the index `content_201712` is created but with the default ES setting, and the mapping is dynamically generated by ES following the document attributes.
Right now we work around it by creating the index ahead of time with a cron task so not a major issue, but just wanted to check if that's the expected behavior.
Using Chewy 0.10.1 on ES 5.5/5.6

**Comment by Able1991** [comment]
How do you do the search? Forcibly specify indices with a suffix?

**Comment by dalthon** [comment]
I believe this was recently fixed by this change:
https://github.com/toptal/chewy/blame/47ad295222212547e67683a0d762bd4f2b64e6b8/lib/chewy/type/import/routine.rb#L69
