### ISSUE TITLE
rspec need to be able to parse response, actually not working with default index import

### ISSUE THREAD

**Issue by yortz** [toptal/chewy#616]
Hi, I am actually trying to spec the response from the following controller action (please note that the very same piece of code renders a correctly formatted array of results if called from console)

```ruby
render json: LaboratoryIndex.query(query_string: { fields: [:title, :content],
                                                            query: params[:q],
                                                            default_operator: 'or' })
                                                .filter(term: {user_id: current_user.id})
                                                .load.to_a, each_serializer: SearchesSerializer
```

in my rails_helper I have added the following (so that each time that the example runs elasticsearch is available on port 9250)

```ruby
# spec/rails_helper.rb

require 'elasticsearch/extensions/test/cluster'
...
Rspec.configure do |config|
...
  config.before :suite do
    Chewy.strategy(:bypass)
    Chewy.logger = Logger.new('log/chewy_debug.log')
  end

  config.before :all, elasticsearch: true do
    Elasticsearch::Extensions::Test::Cluster.start(
      port: 9250,
      nodes: 1,
      timeout: 120
    ) unless Elasticsearch::Extensions::Test::Cluster.running?(on: 9250)
  end

  config.after :suite do
    Elasticsearch::Extensions::Test::Cluster.stop(
      port: 9250,
      nodes: 1
    ) if Elasticsearch::Extensions::Test::Cluster.running?(on: 9250)
  end
...
end
```
in my spec:

```ruby
#spec/acceptance/searches/index.rb

resource "Searches" do

  let(:current_user) { create(:user) }
  let(:other_user)   { create(:user) }

  get "api/searches" do

    before do
      LaboratoryIndex.purge!
    end

    context "Experiment", elasticsearch: true do
      let!(:current_user_notebook)   { create(:notebook, users: [current_user]) }
      let!(:other_user_notebook)     { create(:notebook, users: [other_user]) }
      let!(:current_user_experiment) { create(:experiment, title: "Some Title", content: "bla bla bla land", notebook: current_user_notebook) }
      let!(:other_user_experiment)   { create(:experiment, title: "Other Title", content: "bla", notebook: other_user_notebook) }

      it "searches through title and content of the experiment for the current user" do
        LaboratoryIndex::Experiment.import! Experiment.all
        p LaboratoryIndex.count
        do_request(q: 'Title')
        ap JSON.parse(response_body)
      end
    end

  end
end

```
as a result the response is always an empty arrray? Tried to debug several times to see if the index got updated, but currently event if it seems so, the response is always empty, is there anything that I am missing, or need to configure? Thx in advance.

**Comment by pyromaniac** [comment]
Hey, doesn't seem like you missed anything. I would only do `LaboratoryIndex::Experiment.import!` without any arguments. Can you show the index definition btw?

**Comment by yortz** [comment]
thanks for your prompt feedback on this, actually that's what I am thinking: everything is there, also because as I said if I run that very same piece of code from console it gives me back an array of results, I think that the issue here is with specific elasticsearch/chewy/rspec configuration options, pretty lost and stuck on this, I also tried to sleep to give elasticsearch time to reindex but no matter what I always got an empty array, tried with the following `LaboratoryIndex::Experiment.import!` as you suggested with no luck, still an empty array for the response 🤔 anyway here is my index

```ruby
class LaboratoryIndex < Chewy::Index

  define_type Notebook.includes(:users) do
    field :title
    field :user_id, type: 'integer', value: -> { users.map(&:id) }
  end

  define_type Experiment.includes(:user) do
    field :title, :content
    field :user_id, type: 'integer', value: -> { user.id }
  end

  define_type Inventory.includes(:users) do
    field :title
    field :user_id, type: 'integer', value: -> { users.map(&:id) }
  end

end
```

Also, another thing that I noticed is that everytime that example runs elasticsearch starts 2 nodes and not 1 as defined in the rails_helper, and it seems that it defaults the port to 9251 instead of 9250, could that be the issue? see below the output for the running example

```
rspec spec/acceptance/searches/index_spec.rb:21
WARNING: Skipping key "RAILS_ENV". Already set in ENV.
Run options: include {:locations=>{"./spec/acceptance/searches/index_spec.rb"=>[21]}}

Randomized with seed 25880
Starting 2 Elasticsearch nodes.........

--------------------------------------------------------------------------------
Cluster:            elasticsearch-test-elslabm-156575.science.regn.net
Status:             green
Nodes:              2
                    - node-1 | version: 5.6.4, pid: 10114, address: ["[fe80::1]:9250", "[::1]:9250", "127.0.0.1:9250"]
                    * node-2 | version: 5.6.4, pid: 10133, address: ["[fe80::1]:9251", "[::1]:9251", "127.0.0.1:9251"]
2
{
    "data" => []
}
.Stopping Elasticsearch nodes... Stopped PID 10114. Stopped PID 10133.


Top 1 slowest examples (23.82 seconds, 86.1% of total time):
  Searches GET api/searches Experiment searches through title and content of the experiment for the current user
    23.82 seconds ./spec/acceptance/searches/index_spec.rb:21

Finished in 27.66 seconds (files took 19.5 seconds to load)
1 example, 0 failures

Randomized with seed 25880
```

**Comment by pyromaniac** [comment]
wait, what does `LaboratoryIndex.count` return there?

**Comment by yortz** [comment]
It actually equals to 4 (2 notebooks and 2 experiments) added another example for that into the spec

```ruby
      it "Adds items to the index" do
        LaboratoryIndex.import!
        expect(LaboratoryIndex.count).to eq(4)
      end
```

Also I was thinking to query for something that wasn't there, but I am actually creating those factories

```ruby
      let!(:current_user_experiment) { create(:experiment, title: "Some Title", content: "bla bla bla land", notebook: current_user_notebook) }
      let!(:other_user_experiment)   { create(:experiment, title: "Other Title", content: "bla", notebook: other_user_notebook) }
```

and query for "Title"

```ruby
do_request(q: 'Title')
```

don't understand why it is always an empty array for chewy???

**Comment by pyromaniac** [comment]
The query seems to be wrong. There is nothing to do about chewy, please read the ES docs and compose the query you need.

**Comment by yortz** [comment]
how can the query be wrong if run from console it exactly prints out the array of results that I need?

**Comment by yortz** [comment]
or at least can you explain exactly what is wrong with this query? thx

**Comment by pyromaniac** [comment]
Are you running it from a console in the development mode? When was it reindexed? Can you do chewy:reset and run it in the console again? Maybe the index mapping was changed somehow. Also, which data do you have in the console? Is it the same as in tests?

**Comment by yortz** [comment]
All fixed, do not know why, all is working as it should also while running tests

**Comment by pyromaniac** [comment]
Awesome!
