### ISSUE TITLE
how to query hstore column

### ISSUE THREAD

**Issue by yortz** [toptal/chewy#618]
Hi, actually referencing this closed issue,

https://github.com/toptal/chewy/issues/74

I was wondering how and if it would be possible to query an hstore type of column for the following working query

```ruby
LaboratoryIndex.query(query_string: { fields: [:contents, :title, :content, :name, :url, :price, :unit_size, :location], query: "what to put in here?", default_operator: "or" }).load.to_a
```
tried to pass in the value of the stored keys values pairs in the column but it doesn't seem to be working.

Below here is my index

```ruby
class LaboratoryIndex < Chewy::Index
  define_type Experiment.includes(:user) do
    field :title, :content
    field :user_id, type: "integer", value: -> { user.id }
  end

  define_type Protocol.includes(:user) do
    field :title, :content
    field :user_id, type: "integer", value: -> { user.id }
  end

  define_type Reagent.includes(:inventory) do
    field :title, :price, :unit_size, :location
    field :user_id, type: "integer", value: -> { inventory.users.map(&:id) }
  end

  define_type Experiments::File.includes(:experiment), name: "experiments_file" do
    field :name, :url
    field :user_id, type: "integer", value: -> { experiment.user_id }
  end

  define_type Note.includes(:reagent) do
    template 'contents.*'
    field :contents, type: 'object'
    field :user_id, type: "integer", value: -> { reagent.inventory.users.map(&:id) }
  end
end
```
Probably this should be considered pretty trivial but it seems to not be documented anywhere in the readme. Thanks in advance for any support on this.

In my acceptance spec I am just adding some key value into the hstore column

```ruby
create(:note, contents: { key: "value" }, reagent: current_user_reagent) 
```

**Comment by yortz** [comment]
not sure if this is the right way to do it, but I changed my index this way

```ruby
  define_type Note.includes(:reagent) do
    field :keys, type: 'string', value: -> { contents.keys }
    field :values, type: 'string', value: -> { contents.values }
    field :user_id, type: "integer", value: -> { reagent.inventory.users.map(&:id) }
  **end**
```

and I am actually able to search as usual, at this point doesn't make sense to define that as a type of object, and most of all I do not understand how to query as stated in the closed issue ???

**Comment by pyromaniac** [comment]
Hey! This is not about how Chewy works, but about how ES works. You have to read the ES docs to get it. I personally didn't have such a case, so can't help you here. Try to google it, try to take a look at the nested fields query. Your approach can also do the trick, it really depends on your requirement which I have no idea about :)

**Comment by dalthon** [comment]
As far as I understaood your problem, it is not a Chewy issue, you could handle hstore serialization at ActiveRecord and then everything should work as a normal nested field.

If I got it worng we could reopne this issue
