### ISSUE TITLE
Rails model named Patron

### ISSUE THREAD

**Issue by dandlezzz** [toptal/chewy#619]
I'm not sure if this is a chewy problem or one of it's dependencies. But I have an ApplicationRecord/ActiveRecord model in my app called Patron. It is trouncing the namespace of something in faraday.
I get this error
```/Users/danielamiller/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.11.0/lib/faraday/adapter/patron.rb:39: warning: constant ::TimeoutError is deprecated
/Users/danielamiller/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.11.0/lib/faraday/adapter/patron.rb:39: warning: toplevel constant TimeoutError referenced by Patron::TimeoutError
NameError: uninitialized constant Patron::Error
from /Users/danielamiller/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/faraday-0.11.0/lib/faraday/adapter/patron.rb:45:in `rescue in call' 
```

Renaming the model does fix it. Unfortunately that would be a pretty substantital change on the app side so I'd like to find an alternative solution. I'm a little bit at a loss of what to do? 

Maybe the faraday maintainers could help?

**Comment by nattfodd** [comment]
There should not be any collisions - Faraday's Patron class belongs to `Faraday::Adapter` namespace, while your model's namespace is different.

**Comment by dalthon** [comment]
Looks like this is a bug at elasticsearch-transport gem, I could trace it back to here: https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-transport/lib/elasticsearch/transport/client.rb#L259
