### ISSUE TITLE
Setting root_strategy to :atomic does not update index

### ISSUE THREAD

**Issue by artinboghosian** [toptal/chewy#621]
In our chewy.rb initializer we set the root_strategy to :atomic. We noticed that any models saved through controllers would successfully cause the index to update but any saves that occurred in background jobs did not. Looking through the code it seems that you can only use :atomic with block syntax: `Chewy.strategy(:atomic) { }`. If this is the case, it is not clear in the documentation that you should not use :atomic as a value for root_strategy. Can you confirm that our premise is correct regarding only being able to use :atomic with block syntax? And if so, the documentation should be updated to reflect that.

**Comment by pyromaniac** [comment]
Yeah, atomic is being used with the block only. Otherwise, it is not clear when to flush the cache

**Comment by artinboghosian** [comment]
@pyromaniac what is recommendation for setting root_strategy in Rails. When we remove setting Chewy.root_strategy from initializer we are getting Chewy::UndefinedUpdateStrategy error (I'm assuming this is because root_strategy is defaulting to Base)?

**Comment by pyromaniac** [comment]
https://github.com/toptal/chewy#rails-application-strategies-integration - read this carefully please

**Comment by artinboghosian** [comment]
@pyromaniac thanks for your help

**Comment by artinboghosian** [comment]
It's still not clear in documentation that if you set root_strategy to :atomic or any strategy that requires a block to execute properly, it will swallow the updates since `#leave` method will never be called. This has been a bug that we have been tracking down since we implemented ElasticSearch. It might be useful to update docs to inform users of this. Or raise an exception if setting root_strategy to one that will only work when using a block. Let me know if you want me to make a pull request with any of those options.

**Comment by pyromaniac** [comment]
If you can submit such a PR - please do it. I really like the idea of the exception raising.
