### ISSUE TITLE
Dynamic index name from attribute

### ISSUE THREAD

**Issue by Gargron** [toptal/chewy#631]
Looking at <https://www.elastic.co/guide/en/elasticsearch/guide/current/one-lang-docs.html>, it seems that to support documents in different languages, you need to have a separate index for each language. Is it possible to define these dynamically, if the database record contains a `language` attribute?

**Comment by pyromaniac** [comment]
I'm pretty sure it is. Something like:

[:en, :de].each do |lang|
  Class.new("#{lang}Index", Chewy::Index) do 
    define_type ...
  end
end

**Comment by Gargron** [comment]
I don't think that answer helped me, but I also gave up on the idea altogether so I don't need this issue to remain open.
