### ISSUE TITLE
[Question] pass value to define_type to dynamically set a value

### ISSUE THREAD

**Issue by aarmel-sw** [toptal/chewy#633]
We are using sidekiq which has shared global state, but I have setup resque for now to do re-indexing of items. We are using ActiveModel::Serializer to generate json.

Example of our index:

class ArticleIndex < Chewy::Index

define_type Article, delete_if: -> (article) { ArticleSerializer.new(article, site: $site_id).excluded } do
  field A, type: 'keyword'
   ...etc...

  field :featured, type: 'boolean', value -> { ArticleSerializer.new(self, site: $site_id).featured }
end

Question
Can I somehow pass a value instead of $site_id global? It can't be a constant because I don't know what it will be. My understanding at the moment is that 

ArticleIndex::Article.import [id]

Loads the item from the db. I thought maybe I could modify Article to contain it and pass an actual instance of Article, but it just used the id to work out what to load.

E.g
article_instance = Article.find(1)
article_instance.site_id = 1
ArticleIndex::Article.import(article_instance)

**Comment by pyromaniac** [comment]
What's the problem with global wars? I've thought this is basically the way, to have scoped global variables like here: https://github.com/steveklabnik/request_store

**Comment by aarmel-sw** [comment]
I tried request_store-sidekiq, still get the same issue. Perhaps I'm missing some kind of magic setting. I will have another look into it. 

Using resque its fine, sidekiq breaks. I Tried RequestStore.store[:site_id] as per below.

The job class 'perform' method, so when running lots of jobs, "site_id" value is being changed for some jobs on the import phase and get removed from the index.

  def perform(article_id, site_id, site_name)
      RequestStore.store[:site_id] = site_id
      ArticleIndex.index_name(site_name + '_articles')
      ArticleIndex::Article.import [article_id]
  end

**Comment by dalthon** [comment]
Did you manage to solve this?

 I am closing this issue since it already has a little bit more than 3 years. If you think that that you still need some help on it, we could reopen it
