### ISSUE TITLE
How load object with attributes instead of ids

### ISSUE THREAD

**Issue by morron** [toptal/chewy#634]
How can I load plain Ruby objects with attributes instead of ids like it was 0.9.0 ?

```ruby
  class Geoname
    def self.load_all(wrappers, options)
      if options[:additional_data]
        wrappers.map do |wrapper|
          FancyGeoAPI.point_by_name(wrapper.name)
        end
      else
        wrappers
      end
    end
  end
```

**Comment by pyromaniac** [comment]
Try to read this: https://github.com/toptal/chewy#legacy-dsl-incompatibilities

> preload method is no more, the collection returned by scope doesn't depend on loading options, scope always returns Chewy::Type wrappers. To get ORM/ODM objects, use #objects method.

Hope it helps
