### ISSUE TITLE
Chewy not refreshing dynamic default_scope in production

### ISSUE THREAD

**Issue by RichardWatkins1** [toptal/chewy#640]
We are now running into this issue also https://github.com/toptal/chewy/issues/263.

It is also possible to recreate this behaviour in the test environment if you preload the chewy index files in a `before(:suite)` block.

In our application we are applying multi-tenancy and have a default scope on particular models `default_scopes { where(account_reference: current_tenant) }`. When the application  starts the tenant is nil, as it is in the test environment if you preload chewy indexes. 

It is worth mentioning that our application uses a monkey patch for multi tenant indexes that is discussed in this PR https://github.com/toptal/chewy/issues/225#issuecomment-131891526

Are there any plans to be able to apply scopes to a model that will be scoped to the multi-tenanted index? Or is it a case of adding another monkey patch.

**Comment by dalthon** [comment]
Sorry about late response, but what do you mean about being able to "apply scopes to a model that will be scoped to the multi-tenanted index"?

I mean, the multi tenancy logic will depend on how you implement it. You could simply add an extra field to relate to which tenant (that would be the simpler case, I would guess).

On the other way, if you want o create a distinct index for each tenant, we would need to worry about how to index that, and that would be very troublesome and would require a lot of changes. So I don't believe we would support something for now on that direction.

Could you clarify what exactly you want? (If still want)
