### ISSUE TITLE
Chewy support for eager global ordinals?

### ISSUE THREAD

**Issue by maxshortzp** [toptal/chewy#649]
I'd like to use "eager global ordinals" [as documented here for ElasticSearch 5](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/fielddata.html) (see section "Global ordinals" halfway down the page).

Does Chewy support this? I can't find anything in the docs and/or source code.

**Comment by pyromaniac** [comment]
Hey, can you provide a usage example in pure ES requests?

**Comment by maxshortzp** [comment]
@pyromaniac - It should just be the `eager_global_ordinals` property on `keyword` fields.

Example:

```
curl -X PUT "localhost:9200/my_existing_index/_mapping/my_existing_type" -H 'Content-Type: application/json' -d'
{
    "properties": {
        "test_field_2018_09_24": {
          "type":  "keyword",
          "eager_global_ordinals": true
        }
      }
    }
  }
}
'
```

**Comment by pyromaniac** [comment]
So did you try to add it to a field definition? Like, `field :test, type: 'keyword', eager_global_ordinals: true`

**Comment by maxshortzp** [comment]
Yes, that works. I did not know that chewy took arbitrary options.

Thanks for your help.
