### ISSUE TITLE
NameError: uninitialized constant -  module namespace conflicting with model name

### ISSUE THREAD

**Issue by baronworks** [toptal/chewy#65]
Given the following index and definitions:

``` ruby
class AwardsIndex < Chewy::Index
  define_type Award
  define_type Award::Category
end
```

when trying AwardsIndex.import will get error

```
NameError: uninitialized constant AwardsIndex::Award::Category
```

everything will work fine if just defining Award or Award::Category without the other, but get the error when defining both.

**Comment by baothi** [comment]
https://gist.github.com/baothi/72c63fbb9b8b4675188e
please help me chewy
