### ISSUE TITLE
NameError: uninitialized constant for namespace

### ISSUE THREAD

**Issue by surajit** [toptal/chewy#650]
I've namespace in model and I want to do the index of the attributes, when I'm trying to do this 
`module Library`
      `class BooksIndex < Chewy::Index`
     ` define_type Library::Book do`
       ` field :name`
        `field :product_name`
        `field :season`
       ` field :fit`
        `field :created_at, type: 'date', value: ->{ created_at }` 
    `end`
  `end`
`end`

its showing NameError: uninitialized constant Library::BooksIndex
How to do index of the namespace models?

**Comment by pyromaniac** [comment]
Can you post the full backtrace, please?

**Comment by mattzollinhofer** [comment]
Have you tried:
  define_type ::Library::Book

**Comment by dalthon** [comment]
Closed due to inactivity
