### ISSUE TITLE
Stubbing / mocking search with minitest

### ISSUE THREAD

**Issue by yourtallness** [toptal/chewy#654]
I tried to find an existing thread on this or a Google Group for the current gem, but couldn't find one.

I'd like to be able to stub / mock searches without having to use webmock.

The current minitest test helper is only for testing index changes, but not mocking searches.
I'd ideally also like the ability to test that a search was **not** done.

Any recommendations on how to handle this? Thank you in advance.

**Comment by pyromaniac** [comment]
Well, it is a good idea but not implemented yet, unfortunately. You may try to hack into `Chewy::Search::Request`
