### ISSUE TITLE
AWS Invalid host header warning

### ISSUE THREAD

**Issue by nikhild-tech** [toptal/chewy#663]
Hi there,

I am using chewy gem vesion(0.10.1) in my rails application vesion (4.2.10) and ruby version(2.4.3).

I am using AWS's ElasticSearch using and following the setting mentioned in your gem
`Chewy.settings = {
    host: 'http://my-es-instance-on-aws.us-east-1.es.amazonaws.com:80',
    transport_options: {
      headers: { content_type: 'application/json' },
      proc: -> (f) do
          f.request :aws_signers_v4,
                    service_name: 'es',
                    region: 'us-east-1',
                    credentials: Aws::Credentials.new(
                      ENV['AWS_ACCESS_KEY'],
                      ENV['AWS_SECRET_ACCESS_KEY'])
      end
    }
  } `

When I am requesting to access AWS's ElasticSearch instance for some request AWS is giving me an invalid host header warning. AWS instructed me that if you will not fix this issue then they will not entertain the request which invalid host header.
 
I have also tried to pass host value without https in the header but did not get any success.

For example: headers: { content_type: 'application/json', host: 'my-es-instance-on-aws.us-east-1.es.amazonaws.com:80' }

Below is the reference link

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-handling-errors.html#aes-troubleshooting-host-header
https://prnt.sc/lxau3o

Do you have any idea on this how can I resolve this issue?

**Comment by dalthon** [comment]
It seems that you were using http:// at config when it should not be present
