### ISSUE TITLE
Safe and fast import for bulk number of records

### ISSUE THREAD

**Issue by userrails** [toptal/chewy#665]
> I am migrating my Postgresql data to ES indexes to improve my server's performance.

I have a OrderIndex, which is also indexing associated records in it. When I do `Order.count` in rails console, it gives me around 750K records. So, now I have to import all of those to ES in production server.

I moved `OrderIndex.import` in sidekiq worker, and after running it for around 12 hours, it only imported 100K records in my staging server and the worker is interrupted.

How to speed up import using chewy?

**Comment by pyromaniac** [comment]
Your overall index might be slow. Try to optimize it: use crutches and witchcraft. The biggest issue usually in preloaded associations which are way faster to handle with crutches

**Comment by userrails** [comment]
@pyromaniac Thank you, will try them

But for now, I found below code in one of the ticket conversation:

```ruby
Order.find_in_batches do |orders|
	Chewy::Strategy::Sidekiq::Worker.perform_async('OrdersIndex', orders.map(&:id))
end
```

I have hobby heroku dyno, and it is adding 5 workers to the queue, I can configure it to run more than 5, but this is working like a charm. In production server now I can configure more workers just for these imports and it will be way faster. And if worker get any exception, with single worker, it was too difficult to import again and again, but now I know ids in which worker are causing the problem, fix them and retry that worker safely.

Hope this will be helpful for someone.

Thanks
