### ISSUE TITLE
Could I pass the parallel option when using the sidekiq strategy?

### ISSUE THREAD

**Issue by vadus1** [toptal/chewy#668]
For my sidekiq workers who are doing something with the `Lead` model, I use the sidekiq strategy.

and I discovered weird behavior after I updated strategy for my worker.

```ruby
module Sidekiq
  class ChewyMiddleware
    def initialize(strategy = :atomic)
      @strategy = strategy
    end

    def call(_, _, _)
      Chewy.strategy(@strategy) do
        yield
      end
    end
  end
end
```

I began to receive quite often an error.

**Elasticsearch::Transport::Transport::ServerErrorChewy::Strategy::Sidekiq::Worker@chewy**
`[429] {"code":429,"message":"Concurrent request limit exceeded. Please consider batching your requests, or contact support@bonsai.io for help."}`

I can not understand why, I use the sidekiq strategy.

```ruby
Sidekiq.configure_server do |config|
  config.server_middleware do |chain|
    # Add chewy middleware from lib/sidekiq/chewy_middleware.rb
    chain.add Sidekiq::ChewyMiddleware, :sidekiq
  end
end
```

apparently the queue should accumulate and run in accordance with the Concurrent limit I have `concurrency = 5` for sidekiq. 
And have `10` for ES.

How can I establish concurrency for this?

**Comment by dalthon** [comment]
That seems very weird...

Are you sure that you really had only 5 Sidekiq concurrent jobs? I mean, you could have many workers with many thread each.

It seems unlikely a bug, so I'll close it but I'll reopen if needed
