### ISSUE TITLE
Tests fail on sqlite3 wrong version for ActiveRecord

### ISSUE THREAD

**Issue by olleolleolle** [toptal/chewy#671]
The test suite currently fails with a complaint about sqlite3 exact version not matching expectations in ActiveRecord:

```
# Gem::LoadError:
#   can't activate sqlite3 (~> 1.3.6), already activated sqlite3-1.4.0. Make sure all dependencies are added to Gemfile.
#   /home/travis/.rvm/gems/ruby-2.2.9/gems/bundler-1.17.3/lib/bundler/rubygems_integration.rb:408:in `block (2 levels) in replace_gem'
```

Explanation: [This SO answer explains well](https://stackoverflow.com/a/54729071)

**Comment by dalthon** [comment]
It is not supposed to be an issue, since it was an Active Record issue, and its already fixed there since Rails 5.2.3
