### ISSUE TITLE
How we can Access Proc value

### ISSUE THREAD

**Issue by jaypandya73** [toptal/chewy#675]
Here is the example what I'm trying to do. 
I need current record's attribute to add it as a dynamic field

```ruby
define_type City do
  field: code, type: 'integer', value: ->(city) { city.formatted_code }
  field: metadata, type: 'object' do
   #  name = # need name here of city
   name = ->(city) {city.name}.call(?)
    field: "city_#{name}", type: 'keyword', value: ->(city) { calling some method }
  end
end
```

Here I want to access city's name from lambda or any other attribute from it. as we get those value from `value` attribute it fetches from lambda (`value: ->(city) { city.formatted_code }`) I'm trying to do the same but not for `value` attribute. So can I call lambda to access it's value?

name = ->(city) {city.name}.call(?) -> Here I've tried to pass self but it's not working.
It's expecting current record(here city) on which we're making loop but how we can access it ? so then I can pass it to lambda function

**Comment by jaypandya73** [comment]
@pyromaniac - Any help would be appreciated

**Comment by pyromaniac** [comment]
It would not work this way. The mapping passed to ES should be static and can't be generated in runtime. But you can use ES dynamic templates instead.

**Comment by jaypandya73** [comment]
@pyromaniac - Thanks for the response and where I can find an example of this dynamic templates?

**Comment by pyromaniac** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/6.2/dynamic-templates.html for example. Chewy usage - probably nowhere. There was something in the readme and look at the code, should be fairly simple

**Comment by jaypandya73** [comment]
@pyromaniac - Okay I see what do you mean by dynamic templates and I see it's available here in code:
https://github.com/toptal/chewy/blob/f9c02dddbcc4fc836f73330d8db331145c1ff012/lib/chewy/type/mapping.rb#L156

but still, I'm confused about how I can use it in my example? Can you point that out in my example? Sorry I'm new to this ES and still exploring it.

**Comment by pyromaniac** [comment]
So it looks like you need to do something like

```
template 'metadata.city_*', type: 'keyword'
field: metadata, type: 'object' do |city|
   {"city_#{city.name}" => calling some method}
end
```

**Comment by jaypandya73** [comment]
@pyromaniac - Really appreciate your help on this. I've solved this issue by making changes in DB schema relations and now treating rank as nested fields.
