### ISSUE TITLE
Clear cache

### ISSUE THREAD

**Issue by ngouy** [toptal/chewy#679]
Hello 

Is there a provided tool / func / rake whatever to perform this kind of operation : 
https://www.elastic.co/guide/en/elasticsearch/reference/current//indices-clearcache.html
(clear search cache for exemple)

I search for it without success.

If yes I will be delighted to know what is it and maybe if it's ok for you I would submit a PR to update some guides / readme(s)

---

This need coms from a issue in my specs.
When testing search + order by many stuff (including SCORE)
depending on what tests ran before, scores are not always the same for the same query, so are results order

**Comment by dalthon** [comment]
Right now we don't have this operation implemented and you could invoke this directly on elasticsearch-api client with this:
https://www.rubydoc.info/gems/elasticsearch-api/Elasticsearch/API/Indices/Actions#clear_cache-instance_method

It would be nice to add this feature, surely a PR would be welcome
