### ISSUE TITLE
How to find the corresponding ES query for a Chewy query?

### ISSUE THREAD

**Issue by suryapandian** [toptal/chewy#688]
I use use `chewy` in my rails app to query ElasticSearch.

`Autocomplete` is my ElasticSearch Index. 

    AutocompleteIndex.suggest(
          suggest: {
            text: cleanup_query('query'),
            completion: {
              field: 'search_suggest',
              size: 10,
              contexts: {
                entity: @contexts
              },
              fuzzy: { fuzziness: 'AUTO' }
            }
          }
        ).suggest

 this is the chewy query I use to query `Autocomplete` data.
This, in turn, queries like this, 

    {:body=>{:suggest=>{:suggest=>{:text=>["9"], :completion=>{:field=>"search_suggest", :size=>10, :contexts=>{:entity=>[{:context=>"All"}]}, :fuzzy=>{:fuzziness=>"AUTO"}}}}}, :index=>["autocomplete"], :type=>[]}

How can I get the corresponding ElasticSearch Query for the above?

**Comment by jonatas** [comment]
Enable logs and watch it:

```ruby
Chewy.logger.level = :debug
```

You can also watch your server requests enabling logs in your ES server.

**Comment by suryapandian** [comment]
In initializers, chewy.rb this is my configuration
```
Chewy.root_strategy = :urgent if Sidekiq.server?
Chewy.settings = { host: ENV['ELASTICSEARCH_HOST'] }
Chewy.logger.level = :debug
```

**Still, I could see no logs, what is the default log level if we don't set any value?**

**Comment by jonatas** [comment]
Depends on case by case. Check all log usage: https://github.com/toptal/chewy/search?q=logger&unscoped_q=logger

You'll see that you'll need to provide the logger:

https://github.com/toptal/chewy/#client-settings

**Comment by suryapandian** [comment]
Looks like this `{:body=>{:suggest=>{:suggest=>{:text=>["9"], :completion=>{:field=>"search_suggest", :size=>10, :contexts=>{:entity=>[{:context=>"All"}]}, :fuzzy=>{:fuzziness=>"AUTO"}}}}}, :index=>["autocomplete"], :type=>[]}` is the log.

THanks
