### ISSUE TITLE
How to add new field to existed index?

### ISSUE THREAD

**Issue by darkleaf** [toptal/chewy#692]
I have an existed index and I want to add a new field into it without reindex.
Elasticsearch has the [put mapping api](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html).

**Comment by jonatas** [comment]
I think we don't have such an option on chewy.

What you can do is try to update the index definition with our DSL and reindex the entire index. Or you can create a new one asynchronous and drop the old in favor of the new one when it's ready.

**Comment by 5andi5** [comment]
@darkleaf this hack might help:
```
ok = Chewy.client.indices.put_mapping(
  index: MyChewyIndex.index_name,
  type: MyChewyIndex.type_hash.keys.first,
  body: { properties: { my_new_field: { type: :text } } }
)['acknowledged']
```
https://github.com/elastic/elasticsearch-ruby/blob/master/elasticsearch-api/lib/elasticsearch/api/actions/indices/put_mapping.rb


And then to initialize new field value:
```
Chewy.client.update_by_query(...)
```

But field definition must be specified manually in elasticsearch syntax as close as possible to ones created by Chewy.
Elasticsearch does not allow to change field type. Therefore mistakes are not allowed.

**Comment by darkleaf** [comment]
We use this rake task

```ruby
task :put_mapping => :environment do
  Dir["#{Rails.root}/app/chewy/**/*.rb"].each { |file| require_dependency file }

  Chewy::Type.descendants.each do |type|
    Chewy.client.indices.put_mapping index: type.index_name,
                                     type: type.type_name,
                                     body: type.mappings_hash
  end
end
```
