### ISSUE TITLE
Please set the dependency of chewy to ES 7.0.0

### ISSUE THREAD

**Issue by gaurav-balodi** [toptal/chewy#693]
I was upgrading rails from 5.1.6 to rails 5.2.3 because of the chewy dependency at https://github.com/toptal/chewy/blob/master/chewy.gemspec#L36 line the latest ES 7.3.0 was fetched and my chewy searching got suspend.

After I downgraded the elasticsearch to 7.0.0 that is when chewy search started working.

Could you please set the elasticsearch dependency upto 7.0.0 or put in the README file a note regarding this would be great. 

Thanks

**Comment by rabotyaga** [comment]
I believe this is not actual anymore.
