### ISSUE TITLE
Limit doesn't affect count

### ISSUE THREAD

**Issue by Linuus** [toptal/chewy#697]
Is this the correct behaviour?

```
[59] pry(main)> EventsIndex::Event.all.limit(10).count
=> 15
[60] pry(main)> EventsIndex::Event.all.limit(10).to_a.length
  EventsIndex::Event Search (15.1ms) {:index=>["events"], :type=>["event"], :body=>{:size=>10}}
=> 10
```

I thought `total_count` would return the total number of records and `count` would return the number of records in the current query?

**Comment by dalthon** [comment]
I would not say correct or wrong behavior, but unexpected behavior.

`count` is meant to use [Count API](https://www.elastic.co/guide/en/elasticsearch/reference/7.11/search-count.html) which do not have support to from and size parameters, so `limit` is ignored.

On the other way, when you call `to_a` over a query, we use the search API to retrieve data, and then we are able to fetch results accordingly to limit and then value should match (or be smaller than if there isn't that many records at ES).

I agree that this result seems uncanny, but also I don't see use for such use case, so I'll close this issue unless you can give me some other opinion about it, then I'll reopen it.

Thanks
