### ISSUE TITLE
Catch exception on update_index 

### ISSUE THREAD

**Issue by orion122** [toptal/chewy#702]
What is the best way to catch an exception (eq Chewy::ImportFailed) on `update_index 'some_index'` ?

**Comment by maxnorth** [comment]
@orion122 Did you get an answer to this question? I'm trying to figure out what happens if an exception gets thrown in a resolver. I'm wondering if this is a good way to tell the indexer to skip that record.

**Comment by orion122** [comment]
@maxnorth sorry, I don't remember. I haven't worked for ruby for a long time :)

**Comment by ausangshukla** [comment]
This is an important issue, 

1. if my ES goes down, then update_index fails and the user gets an error
2. I would like to be able to recover, as search is not my main use case, and I would like to update the Elastic Search index on a best effort basis

How should I trap this Exception and handle it globally ?

Thanks
