### ISSUE TITLE
Concurrent Queries

### ISSUE THREAD

**Issue by JensRavens** [toptal/chewy#706]
Hey, thanks for this awesome gem. We're along for the ride with a project for some years already and it was always great working with this library.

Our elasticsearch cluster is growing, queries become slower over time and now there's an interesting question that came up in internal discussions: For some endpoints (e.g. autocompletion over multiple indexes) we need to do multiple requests to ES. Due to the nature of Ruby/Rails they happen after each other inside of the controller. If there would be a possibility to do multiple queries in parallel, we could reduce the response time of those endpoints a lot. Our current code (simplified) looks something like this:
```ruby
@search = Search.new @term, user: current_user
@artists = @search.artists.per(@preview_limit).page(1) # performs a query
@albums = @search.albums.per(@preview_limit).page(1) # performs a query
@labels = @search.labels.per(@preview_limit).page(1) # performs a query
@genres = @search.genres.per(@preview_limit).page(1) # performs a query
```

So - is there a simple way to execute multiple queries against ES via Chewy concurrently? It looks like Faraday supports something like this, I'm just not quite sure where to start on this.

**Comment by pyromaniac** [comment]
Hey, I think you might want to take a look at https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html
