### ISSUE TITLE
ElasticSearch instance details - Version and disk usage

### ISSUE THREAD

**Issue by shleeable** [toptal/chewy#709]
I read the documentation, but couldn't find the way to pull this stuff out.

I want to pull the current verison of ES I'm connected to similar to `redis_info['redis_version']`
and maybe even the memory/disk usage.

similar to       
`@database_size         = ActiveRecord::Base.connection.execute('SELECT pg_database_size(current_database())').first['pg_database_size']`
or
`@redis_size            = redis_info['used_memory']`.

**Comment by dalthon** [comment]
Since Chewy uses Elasticsearch client, you can access client object at `Chewy.client` and then you can find those info by `Chewy.client.info` and `Chewy.client.cat.allocation`

**Comment by rabotyaga** [comment]
Also, you can use `Chewy::Runtime.version`

**Comment by rabotyaga** [comment]
Also,  take a look at `Chewy.client.cluster.health`, ` Chewy.client.cat.allocation(v: true)` and [elasticsearch-api documentation](https://rubydoc.info/gems/elasticsearch-api/Elasticsearch/API/Cat/Actions#shards-instance_method) in general.
