### ISSUE TITLE
script_score

### ISSUE THREAD

**Issue by Bukenco** [toptal/chewy#717]
``  def some_search_query
    {
            function_score: {
                query: {
                    bool: {
                        must_not: [
                            "term":
                                {
                                    "price": 0
                                }
                        ],
                        should: [
                            {
                                multi_match: {
                                    query: @search_params[:input_text] || "",
                                    type: "cross_fields",
                                    analyzer: "standard",
                                    fields: some_search_fields,
                                    operator: "and",
                                    _name:"product"
                                }
                            },
                            {
                                multi_match:
                                    { query: @search_params[:input_text] || "",
                                      type: "best_fields",
                                      analyzer: "standard",
                                      fields: similar_product_search_fields,
                                      tie_breaker: 0.3,
                                      _name:"similar_products"
                                    }
                            }
                        ]
                    }
                },
                script_score: {
                    script: {
                        source: doc['priority_score'] + score,
                        params: {
                            score: 2
                        }
                    }
            }
      }
    }
  end
SomeProductsIndex.query(some_search_query)
``
Problem is that it didn't knows what is doc, but if  i put "doc['priority_score'] + score" like this, than it's not working too, because elastic did not knows what is doc in " ".

**Comment by jonatas** [comment]
@Bukenco have you checked the [ES documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-function-score-query.html)?

Because the API is just a wrapper for the ES calls.

You can send the `doc` as a parameter of the `some_search_query` if you're supposed to inject the value. If you want to use the `priority_score` your param should be a **string** not a ruby calculus:
```ruby

def some_search_query 
  { function_score: 
    { query: { bool: { must_not: [ "term": { "price": 0 } ], 
        should: [ { multi_match: { query: @search_params[:input_text] || "", type: "cross_fields", analyzer: "standard", fields: some_search_fields, operator: "and", _name:"product" } }, 
   { multi_match: { 
       query: @search_params[:input_text] || "", type: "best_fields", analyzer: "standard", 
     fields: similar_product_search_fields, tie_breaker: 0.3, _name:"similar_products" } } ] } }, 
    script_score: { script: { source: "doc['priority_score'] + score", params: { score: 2 } } } } }
end

SomeProductsIndex.query(some_search_query)
```

**Comment by dalthon** [comment]
Closed due to inactivity
