### ISSUE TITLE
Sidekiq stash doesn't process inside sidekiq

### ISSUE THREAD

**Issue by travisofthenorth** [toptal/chewy#719]
Hello. I may be misunderstanding how this is supposed to work. My entire app is using the sidekiq strategy (including inside the sidekiq process). I would assume that when a job is finished processing, any ES updates would get sent to the `chewy` queue.

However, the chewy jobs don't seem to be running when an update happens to one of my models inside a sidekiq job. After doing some debugging, it seems like the `stash` inside the sidekiq strategy fills up, but `leave` is never called so the chewy jobs never get enqueued. Maybe this happens when the process shuts down? In any case, I would expect it to happen when the job finishes. Can you clarify how this should work?

**Comment by abraham-chan** [comment]
I'm not a maintainer but I'm guessing if you don't use the block notation you need to manually pop the strategy as suggested in the readme i.e. `Chewy.strategy.pop`
https://github.com/toptal/chewy#non-block-notation

**Comment by dalthon** [comment]
I guess that you are using request_strategy config to create jobs on web app, but at sidekiq it is not granted, so I suggest you to wrap your operations with `Chewy.strategy` block if you want to use sidekiq strategy inside sidekiq.
