### ISSUE TITLE
Nested mapping type issues

### ISSUE THREAD

**Issue by tuanhuydn** [toptal/chewy#721]
Hi everyone,

Apologies in advance if this is an obtuse question and I overlooked a simple solution. I'm having some issues with field type mappings. I think the issue may stem from non-suffixed vs. suffixed indexes, but I'm hoping someone more knowledgeable may know what is causing the problem. I haven't been able to find a solution on the internet so far.

This is how the field is defined in our chewy index file:
```
field :gender_percentages, value: -> { stats.gender_percentages }, type: 'nested'
```
<br/>

This is what the method stats.gender_ percentages returns:
```
[{"name"=>"female", "value"=>0.6524896265560166},{"name"=>"male", "value"=>0.3475103734439834}]
```
<br/>

Below is how the **non-suffixed** index mapping looks. This is the expected and desired outcome.
```
"gender_percentages":{"type":"nested"}
```
<br/>

Below is how the **suffixed** index mapping looks. This is unexpected. For some reason, The type:nested was mapped to other field types. My custom analyzer also doesn't show up in this mapping.
```
"gender_percentages":{
    "properties":{
        "name":{"type":"text","fields":{"keyword":{"type":"keyword","ignore_above":256}}},
        "value":{"type":"float"}
    }
}
```
<br/>

So the error I receive is:
```
"caused_by":{"type":"illegal_state_exception","reason":"[nested] nested object under path [gender_percentages] is not of nested type"}
```
<br/>

Any help greatly appreciated.
Thx!

**Comment by dalthon** [comment]
Did you tried to use the nested interface described here?
https://github.com/toptal/chewy#multi-nested-and-object-field-types

That may solve your problem
