### ISSUE TITLE
Chewy compatible with ES 7 or above

### ISSUE THREAD

**Issue by ajays1991** [toptal/chewy#727]
This is not an issue and more of the question as i am unable to find compatibility matrix for chewy to elasticsearch.

Is chewy compatible with ES 7 and above?

**Comment by mmyoji** [comment]
Current latest version doesn't support ES7, so we have to use [this patch](https://gist.github.com/reneklacan/5ed4bd08b0ad43cd81cab38530ae0889) by @reneklacan.

Found from:
* https://github.com/toptal/chewy/issues/708#issuecomment-673747704 
* https://github.com/toptal/chewy/pull/712

**Comment by bbatsov** [comment]
We've just released Chewy 6 that supports ES 6 (https://github.com/toptal/chewy/releases/tag/v6.0.0) and we're switching our focus on adding ES 7 support. Stay tuned for Chewy 7. :-)

**Comment by reneklacan** [comment]
@bbatsov glad to hear that there's some progress being done on this, thanks a lot!

**Comment by rabotyaga** [comment]
Please take a look at [Chewy 7.0.0 release](https://github.com/toptal/chewy/releases/tag/v7.0.0). Stay tuned for the 7.1 release, with dropped support for ES6.8 and removed deprecation warnings.
Also, take a look at [Elasticsearch compatibility matrix](https://github.com/toptal/chewy#elasticsearch-compatibility-matrix).
