### ISSUE TITLE
Ruby 3 compatibility

### ISSUE THREAD

**Issue by rbq** [toptal/chewy#730]
With the release of Ruby 3, the 2.7 deprecations reported in #700 are now fatal errors that prevent apps from running. Could you please, please release the existing patch?

**Comment by bbatsov** [comment]
We'll look into this soon.

**Comment by bbatsov** [comment]
I think the current `master` branch should work on Ruby 3.

**Comment by AlfonsoUceda** [comment]
Hi @rbq we are going to release a version supporting Ruby 3 :)
