### ISSUE TITLE
Are there any concerns using Chewy with GCP Elastic Cloud Managed Service?

### ISSUE THREAD

**Issue by aabhushan** [toptal/chewy#762]
Are there any concerns using Chewy with GCP Elastic Cloud Managed Service?

I didn't see an example for that and wanted to make sure there is support for that.

Also is this: https://github.com/toptal/chewy/issues/190 the preferred way of authenticating?

**Comment by rabotyaga** [comment]
Version 6.8 is available and the official ruby client is supported - that means that it should work with chewy 6. However, I personally didn't have any experience in such setups and haven't heard of them. You can try (they have 14 days trial) and then share your experience here.

**Comment by aabhushan** [comment]
Sure will do, thanks!
