### ISSUE TITLE
When i delete product with  destroy_fully! then  update_index method not working 

### ISSUE THREAD

**Issue by Sajidalirordevloper** [toptal/chewy#772]
When i delete product in product table then productIndex not update.

`My Query:`
Product.friendly.where(slug: params[:id]).first.destroy_fully!

`Model:`
class Product < ApplicationRecord
  acts_as_paranoid #for soft Delete
  extend FriendlyId #slug
  friendly_id :name, use: :slugged
 update_index('products#product') { self }
end

`Chewy library:`
define_type Product.includes(:brand, product_images_attachments: :blob) do
    field :id
    field :name
      field :name
      field :slug
    end
  end

`GemFile `

gem 'activeadmin'
gem 'acts_as_paranoid'
# gem 'email_validator'
gem 'friendly_id', '~> 5.4.0'
gem 'chewy', git: 'https://github.com/abdullah5514/chewy.git'
gem 'active_model_serializers'

**Comment by rabotyaga** [comment]
Hey @Sajidalirordevloper 👋 !

This is an issue with the `acts_as_paranoid` gem.
As you can see from the `destroy_fully!` method [implementation](https://github.com/ActsAsParanoid/acts_as_paranoid/blob/f35e37a6b06df1d2e00ecc4e15461a75c733608e/lib/acts_as_paranoid/core.rb#L132-L150)
```ruby
    def destroy_fully!
      with_transaction_returning_status do
        run_callbacks :destroy do
          destroy_dependent_associations!

          if persisted?
            # Handle composite keys, otherwise we would just use
            # `self.class.primary_key.to_sym => self.id`.
            self.class
              .delete_all!([Array(self.class.primary_key), Array(id)].transpose.to_h)
            decrement_counters_on_associations
          end

          stale_paranoid_value
          @destroyed = true
          freeze
        end
      end
    end
```
it manually runs `:destroy` callbacks and then uses ActiveRecord's `delete_all!` method, which skips all callbacks.
That means, that `after_commit` callbacks never get called.
By default Chewy uses `after_commit` callbacks, but this is configurable:
https://github.com/toptal/chewy/blob/891472d0266e6c5b6bc53108d4bdd0f06765e799/lib/chewy/config.rb#L16-L21
You can add this into your chewy initializer, i.e. `config/initializers/chewy.rb`:
```ruby
Chewy.use_after_commit_callbacks = false
```

**Comment by Sajidalirordevloper** [comment]
@rabotyaga Now, its working good.
@rabotyaga  Thanks a lot
