### ISSUE TITLE
Nested field string_query not working

### ISSUE THREAD

**Issue by Sajidalirordevloper** [toptal/chewy#777]
Nested fields string_query not working

`My Query:`

 products = ProductsIndex.query(query_string: {fields: [:name, :shoe, :title, :short_description, :description, brand: :name ], query: "#{search_params[:query]}*", default_operator: 'and'})

`result` not found when we search brand name or slug. other field  working good please help how can i apply query on brand fields.

`My Chewy Index`
 class ProductsIndex < Chewy::Index
  define_type Product.includes(:brands, product_images_attachments: :blob) do
    field :id
    field :brand_id
    field :name
    field :slug
    field :colorway
    field :brands  , type: 'string ' do 
          field :name
          field :slug
    end
  end
end

gem 'chewy', git: 'https://github.com/abdullah5514/chewy.git'

* Ruby version
2.7.2
* Rails version
6.0.1.3

**Comment by rabotyaga** [comment]
Hey @Sajidalirordevloper 👋 !
It's not very clear what exactly happens and why, could you please provide a testing example to reproduce the situation?
By the way, in the lines provided I see, that in the index definition you have a field, called `brands` (mind the `s`), and in the query you use `brand: :name`.

**Comment by Sajidalirordevloper** [comment]
@rabotyaga  its not working , I have tried.  Thank you

that query working:
ProductsIndex.query(query_string:  {query: "#{search_params[:query]}*"}).filter{ "brand.name" "name" "shoe" "title" "short_description" "description"}
