### ISSUE TITLE
logstash geo_point error elk latitude must be a number

### ISSUE THREAD

**Issue by comit-master** [toptal/chewy#791]
I have created my index pattern to map my csv file(geoLocation in geo_point)

```
  PUT _template/geotemplate
  {
  "index_patterns": [
        "flightgeolocation"
      ],
  "settings" : {},
      "mappings": {
        "properties": {
          "geolocation" : {
            "type" : "geo_point"
          }
        }
      },
  "aliases": {}
  }
```

I updated my config file and I have made latitude and longitude in float type and put them as a new field (geLocation)
    input { stdin{} }
    
    
    filter {
        csv {
        separator => ","
        columns => 
        ["Airport_ID","Name","City","Country","IATA",
        "ICAO","Latitude","Longitude","Altitude","Timezone","DST",
        "database_time_zone","Type","Source"]
```
     
    }
   mutate {convert => ["Airport_ID", "string"] }
   mutate {convert => ["Name", "string"] }
   mutate {convert => ["City", "string"] }
   mutate {convert => ["Country", "string"] }
   mutate {convert => ["IATA", "string"] }
   mutate {convert => ["ICAO", "string"] }
   mutate {convert => ["Latitude", "float"] }
   mutate {convert => ["Longitude", "float"] }
   mutate {convert => ["Altitude", "string"] }
   mutate {convert => ["Timezone", "string"] }
   mutate {convert => ["DST", "string"] }
   mutate {convert => ["database_time_zone", "string"] }
   mutate {convert => ["Type", "string"] }
   mutate {convert => ["Source", "string"] }
   mutate {
       add_field => {
          "geoLocation" => "%{Latitude},%{Longitude}"
      }
  }
  }

  output {
     elasticsearch {
      hosts => "localhost:9200"
      index => "flight"
     }
     
     stdout { codec => rubydebug }
  }

```
But I always have the same error :

  `Guinea,GKA,AYGA,6.081689834590001,145.391998291,5282,10,U,PacificPort_Moresby,airport,OurAirports[2021-05-02T19:45:35,275][WARN ][logstash.outputs.elasticsearch][main][6f6097aabf7327a68ae97015b3ece31fcdcae152465b7ff4d6cd4d72dc9e602d] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"flight", :routing=>nil, :_type=>"_doc"}, #<LogStash::Event:0x6001a384>], :response=>{"index"=>{"_index"=>"flight", "_type"=>"_doc", "_id"=>"qWovLnkBE-V7VJ24f7oA", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", **"reason"=>"failed to parse field [geoLocation] of type [geo_point]", "caused_by"=>{"type"=>"parse_exception", "reason"=>"latitude must be a number"}**}}}}
`
That say that latitude must be a number but that's a number.

**Comment by rabotyaga** [comment]
Hey @comit-master 👋 !

How is that related to chewy?

**Comment by comit-master** [comment]
Hi rabotyaga, It's the same type error.
It's not in response to chewy problem.
I just make new issue to find someone to help me.
Do I remove ?

**Comment by rabotyaga** [comment]
It seems you're missing the first 3 fields in the CSV string you've shared: "Airport_ID", "Name" and "City". If it's not the copy-paste error here but the real CSV entry is missing those fields, of course.

**Comment by comit-master** [comment]
Hi rabotyaga,
Thank you for your response.
This is what I put in entry : 

for the colomn in my file.conf:

```
"Airport_ID","Name","City","Country","IATA"
,"Latitude","Longitude","Altitude","Timezone","DST",
"database_time_zone","Type","Source"

```

what I copy-past : 


```
1,Goroka Airport,Goroka,Papua New Guinea,GKA,
,6.081689834590001,145.391998291,5282,10,U,
PacificPort_Moresby,airport,OurAirports

```

I just copy-paste this field, i didn't mentionned it !
This is the same error, 1 juste delete one field "ICAO":
the error : 
`Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"flight", :routing=>nil, :_type=>"_doc"}, #<LogStash::Event:0x23b2bbf2>], :response=>{"index"=>{"_index"=>"flight", "_type"=>"_doc", "_id"=>"srzQMHkBlHhPT54mAMu6", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [geoLocation] of type [geo_point]", "caused_by"=>{"type"=>"parse_exception", "reason"=>"latitude must be a number"}}}}}`

the display :

```
{
           "Name" => "Goroka Airport",
           "host" => "DESKTOP-NGIFVCV",
        "message" => "1,Goroka Airport,Goroka,Papua New Guinea,GKA,\r",
           "City" => "Goroka",
     "@timestamp" => 2021-05-03T06:00:08.078Z,
    "geoLocation" => "%{Latitude},%{Longitude}",
     "Airport_ID" => "1",
       "@version" => "1",
        "Country" => "Papua New Guinea",
           "IATA" => "GKA",
       "Latitude" => nil
}
{
           "Name" => "6.081689834590001",
           "host" => "DESKTOP-NGIFVCV",
        "message" => ",6.081689834590001,145.391998291,5282,10,U,\r",
           "City" => "145.391998291",
     "@timestamp" => 2021-05-03T06:00:08.094Z,
    "geoLocation" => "0.0,%{Longitude}",
     "Airport_ID" => nil,
       "@version" => "1",
        "Country" => "5282",
      "Longitude" => nil,
           "IATA" => "10",
       "Latitude" => 0.0
}
```

**Comment by rabotyaga** [comment]
Looks like you shouldn't use `\n` inside one entry

**Comment by comit-master** [comment]
That's it ! Yes !
Thank you very much rabotyaga !
