### ISSUE TITLE
cannot have more than 1 script sorting

### ISSUE THREAD

**Issue by jiajiawang** [toptal/chewy#795]
In elasticsearch, you can have as many script sorting as you want.
For example, there is a test index with two keyword fields "region" and "country", to sort by region and country alphabetically, by using script sorting you can do 
```
{
  "sort": [
    {
      "_script": {
        "type": "string",
        "script": {
          "inline": "doc['region'].value"
        },
        "order": "desc"
      }
    },
    {
      "_script": {
        "type": "string",
        "script": {
          "inline": "doc['country'].value"
        },
        "order": "desc"
      }
    }
  ]
}
```
(In real world, you can simply do `{ "sort": ["region", "country"] }`,  this example is just to explain the issue)
However, when I use the order method of chewy I can't add more than 1 script sorting
```
TestsIndex.order([
    {
      "_script": {
        "type": "string",
        "script": {
          "inline": "doc['region'].value"
        },
        "order": "desc"
      }
    },
    {
      "_script": {
        "type": "string",
        "script": {
          "inline": "doc['country'].value"
        },
        "order": "desc"
      }
    }
  ])
```
it returns
```
<TestsIndex::Query {:index=>["tests"], :type=>["user"], :body=>{:sort=>[{"_script"=>{:type=>"string", :script=>{:inline=>"doc['country'].value"}, :order=>"desc"}}]}}>
```
The region script sorting part is gone.

--------

## Expected behavior

Expect query to be like
```
<TestsIndex::Query {:index=>["tests"], :type=>["user"], :body=>{:sort=>[{"_script"=>{:type=>"string", :script=>{:inline=>"doc['region'].value"}, :order=>"desc"}}, {"_script"=>{:type=>"string", :script=>{:inline=>"doc['country'].value"}, :order=>"desc"}}]}}>
```
## Actual behavior
Actual query is 
```
<TestsIndex::Query {:index=>["tests"], :type=>["user"], :body=>{:sort=>[{"_script"=>{:type=>"string", :script=>{:inline=>"doc['country'].value"}, :order=>"desc"}}]}}>
```
## Steps to reproduce the problem

Define index
```
class TestsIndex < Chewy::Index
  define_type User do
    field :region, type: :keyword
    field :country, type: :keyword
  end
end
```
Then in console do
```
TestsIndex.order([
    {
      "_script": {
        "type": "string",
        "script": {
          "inline": "doc['region'].value"
        },
        "order": "desc"
      }
    },
    {
      "_script": {
        "type": "string",
        "script": {
          "inline": "doc['country'].value"
        },
        "order": "desc"
      }
    }
  ])
```

## Version Information
Chewy 5.0.0 and 6.0.0 and 7.0.0
Elasticsearch 6.4
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
Rails 5.1.7

--------
By looking into the source code, I found that the value of Chewy::Search::Parameters::Order is a hash and the issue is because the key of script sorting must always be "_script".
```
=> #<Chewy::Search::Parameters:0x00007fa76fb3c950
 @storages=
  {:order=>#<Chewy::Search::Parameters::Order:0x00007fa76fb3c6a8 @value={"_script"=>{:type=>"string", :script=>{:inline=>"doc['country'].value"}, :order=>"desc"}}>,
   :types=>#<Chewy::Search::Parameters::Types:0x00007fa76fb4f438 @value=[]>,
   :none=>#<Chewy::Search::Parameters::None:0x00007fa76fb4ea60 @value=false>,
   :filter=>#<Chewy::Search::Parameters::Filter:0x00007fa76fb4ea38 @value=#<Chewy::Search::Parameters::QueryStorage::Bool:0x00007fa76fb4e7e0 @minimum_should_match=nil, @must=[], @must_not=[], @should=[]>>,
   :query=>#<Chewy::Search::Parameters::Query:0x00007fa76fb4e3d0 @value=#<Chewy::Search::Parameters::QueryStorage::Bool:0x00007fa76fb4e1c8 @minimum_should_match=nil, @must=[], @must_not=[], @should=[]>>}>
```

**Comment by rabotyaga** [comment]
Hey @jiajiawang 👋 !
Thanks for the report. Are you interested in submitting a PR with a fix?

**Comment by jiajiawang** [comment]
> Hey @jiajiawang 👋 !
> Thanks for the report. Are you interested in submitting a PR with a fix?

Hey @rabotyaga, Yes, I'm interested in it.
Not sure how hard it would be, but I'm happy to give a try.
In term of the fix, I assume we'll have to change to use array as the storage of Order param.
Would love to hear your thoughts and ideas on it first.

**Comment by rabotyaga** [comment]
Hey @jiajiawang 👋 !

> Hey @rabotyaga, Yes, I'm interested in it.

Great! And thanks!

> Not sure how hard it would be, but I'm happy to give a try.
> In term of the fix, I assume we'll have to change to use array as the storage of Order param.
> Would love to hear your thoughts and ideas on it first.

Yep, I believe we should change the `Chewy::Search::Parameters::Order` implementation to use Array under the hood.
