### ISSUE TITLE
Partials / Fragments

### ISSUE THREAD

**Issue by thedanielhanke** [toptal/chewy#799]
Entities with common fields currently require the developer to re-define those fields in each Index class - and maintain them for each as well.  

Example: Addresses . People, Buildings, Companies etc. 

In order to dry out the code i`d love to use shared "fieldsets"

Grape/Entity for example allows you to define a field analog to chewy, but also to specify a representable model-class which will handle the value exposure etc. in chewy-code this could look like this:

```ruby
  field :address, using: Partials::AddressIndex, value.....
```

For now i just quickly hacked this method, which works for now:

```ruby
module MergeIndex
  def merge_index(fname, klass)
    field fname

    target_field =
      root
        .children
        .detect { |f| f.name == fname }

    klass.root.children.each do |c|
      field = c.dup
      field.parent = target_field
      target_field.children << field
    end
  end
end

Chewy::Index.extend MergeIndex

class FoosIndex < Chewy::Index
  merge_index :bar, BarsIndex
end

```

Questions:

- as i don`t use any private methods and keep a quite simple schema, can i expect this to remain working for a a while while updating this gem? 
- is there be a feature like this planned?
- if desirable i`d contribute

**Comment by rabotyaga** [comment]
Hey @thedanielhanke 👋 !

Why wouldn't you just use ActiveSupport concerns?
Something like
```ruby
module SomeSharedFields
  extend ActiveSupport::Concern

  included do
    field :shared_field_one, type: 'keyword'
    field :shared_field_two
  end
end
```

And then you can just `include SomeSharedFields` in any index class you want.
That way you're getting flat fields structure too.

**Comment by thedanielhanke** [comment]
Too easy. I am quite `Concern`d about not thinking about this solution :D 

Thank you @rabotyaga 

Nevermind.. ;)
