### ISSUE TITLE
Getting both ActiveRecord objects together with highlights for a query

### ISSUE THREAD

**Issue by gczh** [toptal/chewy#809]
## Is your feature request related to a problem? Please describe.

I'm currently trying to use Chewy to do the following with a query:

1. Get the resulting ActiveRecord objects
2. Get the highlights as well

However, it seems i can only do one or the either. Is there any way I can do both at the same time?

**PS:** It'll also be nice to be able to paginate this. Maybe there's a way to use the Search function for this?

## Describe the solution you'd like

I'd like to be able to do something like the following:

```ruby
BooksIndex.query(
  query_string: {
    fields: [:name, :description],
    query: query,
    default_operator: "or"
  }
).highlight(
  fields: { "*": { force_source: true } }
)
.objects_with_highlights # take note of this
```

And get back ActiveRecord objects of the matching records along with a highlight attribute loaded into the object perhaps? Or any other way that might be more efficient.

## Describe alternatives you've considered

Currently, what I'm doing is to index all the attributes of the model and using "_source" to access them. However, as more attributes get added, I would have to re-index the entire dataset every time I want it to be accessible in my search payload. This would become unfeasible once we have too much data.

## Additional context

None but happy to provide more information to paint a clearer picture.

PS: I'd be happy to work on a PR too if someone could guide me 😁

**Comment by rabotyaga** [comment]
Hi @gczh 👋 !

Did you try using [`object_hash`](https://github.com/toptal/chewy#loading-objects)?

> In case when it is necessary to iterate through both of the wrappers and objects simultaneously, object_hash method helps a lot:

```ruby
scope = CitiesIndex.load(scope: -> { active })
scope.each do |wrapper|
  scope.object_hash[wrapper]
end
```

**Comment by rabotyaga** [comment]
Closing this for now, feel free to re-open the issue if you have any questions.
