### ISSUE TITLE
Error when using `Chewy.transport_logger=` method with elasticsearch 7.14

### ISSUE THREAD

**Issue by aglushkov** [toptal/chewy#815]
`Chewy.transport_logger=` raises error when used with elasticsearch 7.14. 

But It woks with elasticsearch 7.13 

## Steps to reproduce the problem

```ruby
require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"
  git_source(:github) { |repo| "https://github.com/#{repo}.git" }
  gem 'chewy', '~> 7.2'
  gem 'elasticsearch', '~> 7.14'
end

Chewy.transport_logger = nil

#  => /.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/chewy-7.2.2/lib/chewy/config.rb:67:in `transport_logger=': undefined method `logger=' for #<Elasticsearch::Transport::Client:0x00007f4a301c70b0> (NoMethodError)
```

## Version Information

* Chewy version 7.2.2
* Elasticsearch version 7.14.1
* Ruby version 2.7
* Rails version 6.0

**Comment by rabotyaga** [comment]
Please don't use `elasticsearch` >= 7.14.0: https://github.com/toptal/chewy/pull/811
