### ISSUE TITLE
Support for OpenSearch

### ISSUE THREAD

**Issue by jdejong** [toptal/chewy#828]
## Is your feature request related to a problem? Please describe.

Today chewy supports ElasticSearch. While that is great, there is a huge community that utilize managed services to host their ElasticSearch that will be forced in the coming months to migrate to OpenSearch. While the version of Chewy that is based on the pre-fork version of ElasticSearch's gem will work, as both ElasticSearch and OpenSearch innovate this will leave OpenSearch users stuck on an older version of the ElasticSearch gem, as well as an older version of Chewy.

## Describe the solution you'd like

We can use the paradigm introduced in many other gems that support multiple similar or different adapter gems in the past, adding an adapter specific gem (chewy-eleasticearch and chewy-opensearch) which for now would just load the relevant adapter gems and override the client method in chewy.rb. Additionally, the elasticsearch requirement would be removed from chewy and instead would ensure that a separate blackened was included and then can be required.

As both elasticsearch and opensearch mature, we could see divergence or different implementations of the same features. This approach would allow customizing the implementation of any specific feature (or no-oping anything not supported) without having to comingle the requirements and code of the specific background.

## Additional context

We are willing to help with the development of this feature and the creation of these new gems, but before we start working on this we wanted to be sure this PR (and additional gems) would be something the maintainers would be willing to approve. 

Not supporting opensearch means not supporting anyone running on a public cloud's elasticsearch service that is transitioning to opensearch (like AWS) or a Database hosting provider (like Aiven or Bonsai). This also paves the way for potentially supporting alternative search services in the future that are feature-rich like Elastic/OpenSarch, but provide a syntactically different DSL's.

We look forward to discussing this potential feature.

**Comment by rabotyaga** [comment]
Hey @jdejong 👋 !
Good idea, let's return to this when there are actually some differences in APIs we'd like to handle.

**Comment by jdejong** [comment]
Hi @rabotyaga 

I think that is the issue, unless this support is added OpenSearch users are stuck on a version of ElasticSearch less than version 7.14 and the opensearch-ruby gem does have some security and bug fixes that exist in 7.14 and above. There is also some new search functionality in 7.16, that would not be available to current Chewy OpenSearch users without this update. I would also recommend having the CI test both backends, which should help identify if drift happens, instead of relying on humans to manage when the dependencies break.

As I said, we are willing to put in the effort to do the initial work and can also try and help with future updates, but want to be sure before we do the work and double down on using Chewy with OpenSearch that this development is going to be supported by the maintainers.

Best,

Jonathan

**Comment by rabotyaga** [comment]
@jdejong Could you please point me to these security and bug fixes and the search functionality? I'm not sure I'm fully getting what you mean.

**Comment by bbatsov** [comment]
Just to be clear - is anyone besides AWS using OpenSearch right now? [This page](https://www.elastic.co/what-is/opensearch) seems to indicate no other major vendor has backed Amazon's efforts so far. 

In general, as @rabotyaga mentioned, it'd be great to get a clear picture of the current situation before committing to any plan of action.

**Comment by jdejong** [comment]
Hi @bbatsov,

Anyone who is offering cloud hosted ElasticSearch will have to move to OpenSearch or lock at 7.10 forever. 

Elastic is of course going to characterize this as not a big deal, but I would instead suggest looking at those who are involved in building and maintaining OpenSearch https://opensearch.org/partners/ (outside of AWS). For example, we use Aiven.io for our database hosting and they are a supporter of the project and we will be moving to OpenSearch shortly to ensure we meet our security and reliability compliance tenets. 

I am trying to avoid forking Chewy to create a OpenSearch version since they should have close in feature parity for the time being.

Jonathan

**Comment by rabotyaga** [comment]
@jdejong Could you please specify what features/bug fixes/security fixes we're talking about right now?
https://github.com/toptal/chewy/issues/828#issuecomment-1000520828

**Comment by keithslater** [comment]
From what I can tell, it's impossible to use Chewy with Rails >6 now if you are using OpenSearch/ElasticSearch 7.10.1. Upgrading to rails 6 provides this error https://github.com/toptal/chewy/issues/832:

```
LoadError: cannot load such file -- i18n/core_ext/hash
```

However, I can't update chewy to 7.2.4 where this is fixed because it requires elasticsearch >= 7.12.0

```
In Gemfile:
    elasticsearch (= 7.10.1)

    chewy (~> 7.2.4) was resolved to 7.2.5, which depends on
      elasticsearch (>= 7.12.0, < 7.14.0)```

**Comment by jdejong** [comment]
Hi @keithslater 

We have a fork we are working on to address the OS/ES issue which can be viewed here --> https://github.com/HelloGLOBO/chewy

However, We are currently running Rails 6.0.4.7 w/ ES 7.13.3 and Chewy 7.2.2 without any issues in one of our projects.

We had another project take the focus off of this fork, but our hope is to finish it soon and talk with the maintainers of Chewy about mainstreaming this change. 

-J

**Comment by rabotyaga** [comment]
Hey @keithslater :wave: !
Why do you need to pin elasticsearch gem version to 7.10, why can't you use 7.12?

**Comment by keithslater** [comment]
As far as I know, AWS hosted elasticsearch and Opensearch only goes to 7.10 (7.10.2 I think).

**Comment by rabotyaga** [comment]
> As far as I know, AWS hosted elasticsearch and Opensearch only goes to 7.10 (7.10.2 I think).

@keithslater Do you mean, it doesn't work with gem version 7.12? I mean, it's absolutely valid to use gem version 7.12 with ES node version 7.10, for example.

**Comment by keithslater** [comment]
Good to know, I will give that a try.

**Comment by rapito** [comment]
> @jdejong Could you please point me to these security and bug fixes and the search functionality? I'm not sure I'm fully getting what you mean.

Hi @rabotyaga, to try and clarify things a bit, what Jonathan meant was that people who uses Chewy and cannot move away from ES version 7.13.3 (because they are hosted on AWS) won't be able to obtain any security patches to the ES gem or even Chewy, including fixed version dependencies of the gem. 

The list of features and patches would simply be everything that's in the changelogs after ES gem version 7.13.3.
This also extends to any dependencies that require any security patches or updates of the gem. i.e Faraday.

**Comment by danpolyuha** [comment]
Hey @jdejong ,
Can you let us know what was your solution in the end? Did you end up simply using opensearch_ruby gem?
