### ISSUE TITLE
support to elasticsearch 7.16.0

### ISSUE THREAD

**Issue by fanxy1** [toptal/chewy#829]
## Is your feature request related to a problem? Please describe.

 I want to chewy support elasticsearch 7.16.0

## Additional context
https://threatpost.com/third-log4j-bug-dos-apache-patch/177159/
log4j bug solution with es 7.16.0，so I want to support 7.16.0, thinks

**Comment by rabotyaga** [comment]
Chewy supports Elasticsearch 7.16.2.
Please let me know if you have any specific difficulties.

**Comment by rabotyaga** [comment]
Also, please take a look at https://xeraa.net/blog/2021_mitigate-log4j2-log4shell-elasticsearch/
