### ISSUE TITLE
Execute multiple queries on one index in one request

### ISSUE THREAD

**Issue by Linuus** [toptal/chewy#90]
Hi!

I have an index with multiple types in it. Now I want to make a search where I get results for each type.
At first I was thinking about using aggregations but that does not work I think, since it is bound to the result of the query.

To clarify, let's say I have three types in my index, `Foo`, `Bar` and `Baz`.
I mean, if I search for "Lorem Ipsum" with a limit of 10 it will fetch the top 10 results and then group these by type in my aggregations. Maybe the top 5 results are of type `Foo` and then 4 are `Bar` and only one `Baz` which is not what I want...

What I really want is 10 hits of each type. So, the most relevant `Foo` the most relevant `Bar` and the most relevant `Baz`.

Sure, I could do one request per type to get the desired result but it would be cool if it could be done in one request (using something like `msearch` I guess, https://github.com/elasticsearch/elasticsearch-ruby/blob/5dc6bc61b85cb681b2453e4b9a6afb9a35e1be98/elasticsearch-api/lib/elasticsearch/api/actions/msearch.rb).

Does Chewy support something like this?

**Comment by prikha** [comment]
With ES5 support API changed and it seems that we should use `Chewy::Search::Request`  for multiple indexes.

**Comment by pyromaniac** [comment]
Chewy::Query also supports multiple indexes, but doesn't support ES5, yeah. Also, it will be removed later, use new new cool API
