### ISSUE TITLE
"#<Chewy::UndefinedUpdateStrategy:   Index update strategy is undefined for current context.\n  Please wrap your code with `Chewy.strategy(:strategy_name) block.`\n>"}

### ISSUE THREAD

**Issue by Bhumika2015** [toptal/chewy#910]
"#<Chewy::UndefinedUpdateStrategy:   Index update strategy is undefined for current context.\n  Please wrap your code with `Chewy.strategy(:strategy_name) block.`\n>"

I'm getting this while bulk importing.

**Comment by konalegi** [comment]
could you please elaborate a bit? What exactly you do?

**Comment by smarquezs** [comment]
We recently updated to the latest Rails version (7.1.2) and encountered the same issue with Chewy::Strategy::ActiveJob::Worker. We resolved it by adding `Chewy.root_strategy = :active_job`. Note that we use DelayedJob for background jobs. You can review the documentation to find the strategy that best fits your requirements.

https://github.com/toptal/chewy#index-update-strategies

**Comment by Bhumika2015** [comment]
It's working fine for me. As I used Chewy.strategy(:urgent) in my code.

**Comment by Bhumika2015** [comment]
It's working fine for me. As I used Chewy.strategy(:urgent) in my code.
