### ISSUE TITLE
Easier creation of mappings

### ISSUE THREAD

**Issue by Linuus** [toptal/chewy#96]
Hi

I have a lot of fields that I want to index as `multi_field` with two different analyzers.

``` ruby
field :title, type: :multi_field do
  field "title.stemmed", analyzer: :swedish_stemmer
  field "title.partial", index_analyzer: :partial
end
```

I have a bunch of these fields and it is quite annoying to have to write this everywhere, so I want to dry it up.

I tried to create a small helper method in my index file so I could do something like this:

``` ruby
def stemmed_field(field_name)
  field "#{field_name}.stemmed", analyzer: :swedish_stemmer
  field "#{field_name}.partial", index_analyzer: :partial
end

# Mapping
[...]
field :title, type: :multi_field, &:stemmed_field
field :body, type: :multi_field, &:stemmed_field
[...]
```

But this does not work of course. The `stemmed_field` method does not know what the field name is.

Any idea how I may implement something like this?

**Comment by danielkummer** [comment]
Did you get this to work? If yes, could you please provide the solution :)

**Comment by Linuus** [comment]
@danielkummer I did as @pyromaniac said :)

More specific, like this:
```ruby
  Chewy::Type.class_eval do
    def self.stemmed_and_partial_field(field_name, options = {})
      field field_name, type: :multi_field do
        field "#{field_name}.stemmed", { analyzer: :swedish_stemmer }.merge(options)
        field "#{field_name}.partial", { index_analyzer: :partial }.merge(options)
        field "#{field_name}.original"
      end
    end
  end
```

I don't know if there is a better way to do it now though.
